import type { DesignProfile } from '../../schemas/knowledge/design-profile.schema.js';

export const HEALTHCARE_CLEAN: DesignProfile = {
  id: 'design.healthcare.clean',
  version: '2.1.0',
  status: 'active',
  createdAt: '2025-01-01T00:00:00+00:00',
  updatedAt: '2025-01-01T00:00:00+00:00',
  evidenceRefs: [],
  kind: 'DesignProfile',
  name: 'Healthcare: Clean Trust',
  description: 'Clean, trustworthy design for healthcare applications with calming blues and high accessibility',
  typography: {
    displayFamily: 'Inter',
    bodyFamily: 'Inter',
    monoFamily: 'JetBrains Mono',
    scale: {
      display: { size: '3rem', lineHeight: '1.1', weight: '700' },
      h1: { size: '2.25rem', lineHeight: '1.2', weight: '700' },
      h2: { size: '1.75rem', lineHeight: '1.3', weight: '600' },
      h3: { size: '1.375rem', lineHeight: '1.4', weight: '600' },
      h4: { size: '1.125rem', lineHeight: '1.4', weight: '500' },
      bodyLg: { size: '1.125rem', lineHeight: '1.7', weight: '400' },
      body: { size: '1rem', lineHeight: '1.7', weight: '400' },
      bodySm: { size: '0.875rem', lineHeight: '1.6', weight: '400' },
      caption: { size: '0.75rem', lineHeight: '1.5', weight: '500' },
      overline: { size: '0.75rem', lineHeight: '1.5', weight: '600', tracking: '0.1em' },
    },
  },
  colorPsychology: {
    primary: '#0077B6',
    secondary: '#00B4D8',
    accent: '#48CAE4',
    background: '#FFFFFF',
    foreground: '#1A1A2E',
    muted: '#6B7280',
    destructive: '#DC2626',
    success: '#059669',
    warning: '#D97706',
    info: '#0077B6',
    psychology: {
      primary: 'Blue conveys trust, calm, and professionalism in healthcare',
      background: 'Clean white creates a sense of hygiene and clarity',
      accent: 'Light blue adds warmth without being playful',
    },
    gradients: {
      hero: 'linear-gradient(135deg, #F0F7FF 0%, #E0F2FE 100%)',
      card: 'linear-gradient(145deg, #FFFFFF 0%, #F0F7FF 100%)',
    },
  },
  spacing: {
    xs: '0.25rem',
    sm: '0.5rem',
    md: '1rem',
    lg: '1.5rem',
    xl: '2rem',
    '2xl': '3rem',
    '3xl': '4rem',
    '4xl': '6rem',
  },
  grid: {
    columns: 12,
    gutter: '1.5rem',
    margin: '2rem',
    breakpoints: {
      sm: '640px',
      md: '768px',
      lg: '1024px',
      xl: '1280px',
      '2xl': '1536px',
    },
  },
  motion: {
    duration: { fast: '150ms', normal: '250ms', slow: '400ms' },
    easing: {
      default: 'ease-out',
      enter: 'ease-out',
      exit: 'ease-in',
      spring: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
    },
    reducedMotion: 'simplify',
  },
  accessibility: {
    contrastRatio: 4.5,
    focusVisible: true,
    keyboardNav: true,
    ariaLabels: true,
    reducedMotion: true,
    screenReader: true,
  },
  iconography: {
    library: 'lucide',
    style: 'outline',
    size: { sm: '16px', md: '20px', lg: '24px' },
  },
  illustration: { style: 'flat' },
  photography: { style: 'lifestyle', mood: ['calm', 'professional', 'caring'], aspectRatio: '16/9' },
  componentsStyling: {
    button: { borderRadius: '0.5rem', fontWeight: '500' },
    card: { borderRadius: '0.75rem', shadow: '0 1px 3px rgba(0,0,0,0.1)' },
    input: { borderRadius: '0.5rem', borderColor: '#D1D5DB' },
    badge: { borderRadius: '9999px' },
    avatar: { borderRadius: '50%' },
    dialog: { borderRadius: '1rem' },
    table: { borderRadius: '0.5rem' },
    form: { gap: '1rem' },
    chart: {},
  },
  brandPersonality: ['trustworthy', 'calm', 'professional', 'caring', 'accessible'],
  microInteractions: [
    { trigger: 'hover', animation: 'scale(1.02)', duration: '150ms' },
    { trigger: 'click', animation: 'scale(0.98)', duration: '100ms' },
    { trigger: 'focus', animation: 'ring(2px)', duration: '150ms' },
  ],
};

export const ECOMMERCE_MODERN: DesignProfile = {
  id: 'design.ecommerce.modern',
  version: '2.1.0',
  status: 'active',
  createdAt: '2025-01-01T00:00:00+00:00',
  updatedAt: '2025-01-01T00:00:00+00:00',
  evidenceRefs: [],
  kind: 'DesignProfile',
  name: 'E-Commerce: Modern Marketplace',
  description: 'Clean, conversion-optimized design for e-commerce with product-focused layouts',
  typography: {
    displayFamily: 'Plus Jakarta Sans',
    bodyFamily: 'Inter',
    monoFamily: 'JetBrains Mono',
    scale: {
      display: { size: '3.5rem', lineHeight: '1.1', weight: '700', tracking: '-0.02em' },
      h1: { size: '2.5rem', lineHeight: '1.2', weight: '700' },
      h2: { size: '2rem', lineHeight: '1.3', weight: '600' },
      h3: { size: '1.5rem', lineHeight: '1.4', weight: '600' },
      h4: { size: '1.25rem', lineHeight: '1.4', weight: '500' },
      bodyLg: { size: '1.125rem', lineHeight: '1.7', weight: '400' },
      body: { size: '1rem', lineHeight: '1.7', weight: '400' },
      bodySm: { size: '0.875rem', lineHeight: '1.6', weight: '400' },
      caption: { size: '0.75rem', lineHeight: '1.5', weight: '500' },
      overline: { size: '0.75rem', lineHeight: '1.5', weight: '600', tracking: '0.1em' },
    },
  },
  colorPsychology: {
    primary: '#111827',
    secondary: '#6366F1',
    accent: '#8B5CF6',
    background: '#FFFFFF',
    foreground: '#111827',
    muted: '#9CA3AF',
    destructive: '#DC2626',
    success: '#059669',
    warning: '#D97706',
    info: '#6366F1',
    psychology: {
      primary: 'Dark primary creates authority and trust for product purchases',
      secondary: 'Indigo adds modern tech feel',
      accent: 'Violet draws attention to CTAs',
    },
    gradients: {
      hero: 'linear-gradient(135deg, #F9FAFB 0%, #EEF2FF 100%)',
      card: 'linear-gradient(145deg, #FFFFFF 0%, #F9FAFB 100%)',
      button: 'linear-gradient(135deg, #6366F1 0%, #8B5CF6 100%)',
    },
  },
  spacing: {
    xs: '0.25rem',
    sm: '0.5rem',
    md: '1rem',
    lg: '1.5rem',
    xl: '2rem',
    '2xl': '3rem',
    '3xl': '4rem',
    '4xl': '6rem',
  },
  grid: {
    columns: 12,
    gutter: '1.5rem',
    margin: '2rem',
    breakpoints: {
      sm: '640px',
      md: '768px',
      lg: '1024px',
      xl: '1280px',
      '2xl': '1536px',
    },
  },
  motion: {
    duration: { fast: '150ms', normal: '200ms', slow: '350ms' },
    easing: {
      default: 'cubic-bezier(0.4, 0, 0.2, 1)',
      enter: 'cubic-bezier(0, 0, 0.2, 1)',
      exit: 'cubic-bezier(0.4, 0, 1, 1)',
      spring: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
    },
    reducedMotion: 'simplify',
  },
  accessibility: {
    contrastRatio: 4.5,
    focusVisible: true,
    keyboardNav: true,
    ariaLabels: true,
    reducedMotion: true,
    screenReader: true,
  },
  iconography: {
    library: 'lucide',
    style: 'outline',
    size: { sm: '16px', md: '20px', lg: '24px' },
  },
  illustration: { style: 'flat' },
  photography: { style: 'product', mood: ['premium', 'clean', 'lifestyle'], aspectRatio: '1:1' },
  componentsStyling: {
    button: { borderRadius: '0.5rem', fontWeight: '600' },
    card: { borderRadius: '0.75rem', shadow: '0 1px 3px rgba(0,0,0,0.08)' },
    input: { borderRadius: '0.5rem' },
    badge: { borderRadius: '9999px' },
    avatar: { borderRadius: '50%' },
    dialog: { borderRadius: '1rem' },
    table: { borderRadius: '0.5rem' },
    form: { gap: '1rem' },
    chart: {},
  },
  brandPersonality: ['modern', 'clean', 'conversion-focused', 'product-centric', 'trustworthy'],
  microInteractions: [
    { trigger: 'hover', animation: 'translateY(-2px)', duration: '150ms' },
    { trigger: 'click', animation: 'scale(0.98)', duration: '100ms' },
    { trigger: 'focus', animation: 'ring(2px)', duration: '150ms' },
  ],
};
