import type { DesignProfile } from '../../schemas/knowledge/design-profile.schema.js';

export const RESTAURANT_WARM: DesignProfile = {
  id: 'design.restaurant.warm',
  version: '2.1.0', status: 'active', createdAt: '2025-01-01T00:00:00+00:00', updatedAt: '2025-01-01T00:00:00+00:00',
  evidenceRefs: [], kind: 'DesignProfile',
  name: 'Restaurant: Warm Appetizing',
  description: 'Warm, appetizing design for restaurants with food-forward layouts and rich textures',
  typography: { displayFamily: 'Playfair Display', bodyFamily: 'Inter', monoFamily: 'JetBrains Mono', scale: { display: { size: '3.5rem', lineHeight: '1.1', weight: '700', tracking: '-0.02em' }, h1: { size: '2.5rem', lineHeight: '1.2', weight: '700' }, h2: { size: '2rem', lineHeight: '1.3', weight: '600' }, h3: { size: '1.5rem', lineHeight: '1.4', weight: '600' }, h4: { size: '1.25rem', lineHeight: '1.4', weight: '500' }, bodyLg: { size: '1.125rem', lineHeight: '1.7', weight: '400' }, body: { size: '1rem', lineHeight: '1.7', weight: '400' }, bodySm: { size: '0.875rem', lineHeight: '1.6', weight: '400' }, caption: { size: '0.75rem', lineHeight: '1.5', weight: '500' }, overline: { size: '0.75rem', lineHeight: '1.5', weight: '600', tracking: '0.1em' } } },
  colorPsychology: { primary: '#B91C1C', secondary: '#D97706', accent: '#F59E0B', background: '#FFF7ED', foreground: '#1C1917', muted: '#78716C', destructive: '#DC2626', success: '#059669', warning: '#D97706', info: '#B91C1C', psychology: { primary: 'Rich red stimulates appetite and conveys passion', background: 'Warm cream creates cozy atmosphere', accent: 'Amber adds warmth and highlights CTAs' }, gradients: { hero: 'linear-gradient(135deg, #FFF7ED 0%, #FFEDD5 100%)', card: 'linear-gradient(145deg, #FFFFFF 0%, #FFF7ED 100%)', button: 'linear-gradient(135deg, #B91C1C 0%, #DC2626 100%)' } },
  spacing: { xs: '0.25rem', sm: '0.5rem', md: '1rem', lg: '1.5rem', xl: '2rem', '2xl': '3rem', '3xl': '4rem', '4xl': '6rem' },
  grid: { columns: 12, gutter: '1.5rem', margin: '2rem', breakpoints: { sm: '640px', md: '768px', lg: '1024px', xl: '1280px', '2xl': '1536px' } },
  motion: { duration: { fast: '150ms', normal: '250ms', slow: '400ms' }, easing: { default: 'ease-out', enter: 'ease-out', exit: 'ease-in', spring: 'cubic-bezier(0.34, 1.56, 0.64, 1)' }, reducedMotion: 'simplify' },
  accessibility: { contrastRatio: 4.5, focusVisible: true, keyboardNav: true, ariaLabels: true, reducedMotion: true, screenReader: true },
  iconography: { library: 'lucide', style: 'outline', size: { sm: '16px', md: '20px', lg: '24px' } },
  illustration: { style: 'flat' }, photography: { style: 'lifestyle', mood: ['warm', 'appetizing', 'lifestyle'], aspectRatio: '4/3' },
  componentsStyling: { button: { borderRadius: '0.75rem', fontWeight: '600' }, card: { borderRadius: '1rem', shadow: '0 4px 6px rgba(0,0,0,0.05)' }, input: { borderRadius: '0.75rem' }, badge: { borderRadius: '9999px' }, avatar: { borderRadius: '50%' }, dialog: { borderRadius: '1rem' }, table: { borderRadius: '0.5rem' }, form: { gap: '1rem' }, chart: {} },
  brandPersonality: ['warm', 'inviting', 'passionate', 'hospitable', 'authentic'],
  microInteractions: [{ trigger: 'hover', animation: 'translateY(-2px)', duration: '150ms' }, { trigger: 'click', animation: 'scale(0.98)', duration: '100ms' }, { trigger: 'focus', animation: 'ring(2px)', duration: '150ms' }],
};

export const FITNESS_ENERGETIC: DesignProfile = {
  id: 'design.fitness.energetic',
  version: '2.1.0', status: 'active', createdAt: '2025-01-01T00:00:00+00:00', updatedAt: '2025-01-01T00:00:00+00:00',
  evidenceRefs: [], kind: 'DesignProfile',
  name: 'Fitness: Energetic Bold',
  description: 'High-energy design for fitness brands with bold typography and vibrant accent colors',
  typography: { displayFamily: 'Bebas Neue', bodyFamily: 'Inter', monoFamily: 'JetBrains Mono', scale: { display: { size: '4rem', lineHeight: '1', weight: '700', tracking: '-0.02em' }, h1: { size: '3rem', lineHeight: '1.1', weight: '700' }, h2: { size: '2.25rem', lineHeight: '1.2', weight: '700' }, h3: { size: '1.75rem', lineHeight: '1.3', weight: '600' }, h4: { size: '1.25rem', lineHeight: '1.4', weight: '600' }, bodyLg: { size: '1.125rem', lineHeight: '1.7', weight: '400' }, body: { size: '1rem', lineHeight: '1.7', weight: '400' }, bodySm: { size: '0.875rem', lineHeight: '1.6', weight: '400' }, caption: { size: '0.75rem', lineHeight: '1.5', weight: '500' }, overline: { size: '0.75rem', lineHeight: '1.5', weight: '700', tracking: '0.15em' } } },
  colorPsychology: { primary: '#DC2626', secondary: '#EA580C', accent: '#F97316', background: '#09090B', foreground: '#FAFAFA', muted: '#27272A', destructive: '#EF4444', success: '#22C55E', warning: '#EAB308', info: '#3B82F6', psychology: { primary: 'Red conveys energy, intensity, and passion', background: 'Dark background creates drama and focus', accent: 'Orange adds heat and urgency' }, gradients: { hero: 'linear-gradient(135deg, #09090B 0%, #1A0000 100%)', card: 'linear-gradient(145deg, #18181B 0%, #09090B 100%)', button: 'linear-gradient(135deg, #DC2626 0%, #EA580C 100%)' } },
  spacing: { xs: '0.25rem', sm: '0.5rem', md: '1rem', lg: '1.5rem', xl: '2rem', '2xl': '3rem', '3xl': '4rem', '4xl': '6rem' },
  grid: { columns: 12, gutter: '1rem', margin: '1.5rem', breakpoints: { sm: '640px', md: '768px', lg: '1024px', xl: '1280px', '2xl': '1536px' } },
  motion: { duration: { fast: '100ms', normal: '200ms', slow: '300ms' }, easing: { default: 'cubic-bezier(0.4, 0, 0.2, 1)', enter: 'cubic-bezier(0, 0, 0.2, 1)', exit: 'cubic-bezier(0.4, 0, 1, 1)', spring: 'cubic-bezier(0.34, 1.56, 0.64, 1)' }, reducedMotion: 'simplify' },
  accessibility: { contrastRatio: 4.5, focusVisible: true, keyboardNav: true, ariaLabels: true, reducedMotion: true, screenReader: true },
  iconography: { library: 'lucide', style: 'filled', size: { sm: '16px', md: '20px', lg: '24px' } },
  illustration: { style: 'abstract' }, photography: { style: 'candid', mood: ['energetic', 'powerful', 'motivational'], aspectRatio: '16/9' },
  componentsStyling: { button: { borderRadius: '0.5rem', fontWeight: '700' }, card: { borderRadius: '0.75rem', shadow: '0 4px 6px rgba(0,0,0,0.3)' }, input: { borderRadius: '0.5rem' }, badge: { borderRadius: '0.25rem' }, avatar: { borderRadius: '50%' }, dialog: { borderRadius: '0.75rem' }, table: { borderRadius: '0.5rem' }, form: { gap: '1rem' }, chart: {} },
  brandPersonality: ['energetic', 'bold', 'motivational', 'intense', 'modern'],
  microInteractions: [{ trigger: 'hover', animation: 'scale(1.05)', duration: '100ms' }, { trigger: 'click', animation: 'scale(0.95)', duration: '75ms' }, { trigger: 'focus', animation: 'ring(2px)', duration: '100ms' }],
};

export const EDUCATION_FRIENDLY: DesignProfile = {
  id: 'design.education.friendly',
  version: '2.1.0', status: 'active', createdAt: '2025-01-01T00:00:00+00:00', updatedAt: '2025-01-01T00:00:00+00:00',
  evidenceRefs: [], kind: 'DesignProfile',
  name: 'Education: Friendly Approachable',
  description: 'Warm, approachable design for education platforms with clean typography and encouraging colors',
  typography: { displayFamily: 'DM Sans', bodyFamily: 'Inter', monoFamily: 'JetBrains Mono', scale: { display: { size: '3rem', lineHeight: '1.1', weight: '700', tracking: '-0.02em' }, h1: { size: '2.25rem', lineHeight: '1.2', weight: '700' }, h2: { size: '1.75rem', lineHeight: '1.3', weight: '600' }, h3: { size: '1.375rem', lineHeight: '1.4', weight: '600' }, h4: { size: '1.125rem', lineHeight: '1.4', weight: '500' }, bodyLg: { size: '1.125rem', lineHeight: '1.7', weight: '400' }, body: { size: '1rem', lineHeight: '1.7', weight: '400' }, bodySm: { size: '0.875rem', lineHeight: '1.6', weight: '400' }, caption: { size: '0.75rem', lineHeight: '1.5', weight: '500' }, overline: { size: '0.75rem', lineHeight: '1.5', weight: '600', tracking: '0.1em' } } },
  colorPsychology: { primary: '#6366F1', secondary: '#4F46E5', accent: '#818CF8', background: '#FFFFFF', foreground: '#1E1B4B', muted: '#6B7280', destructive: '#DC2626', success: '#059669', warning: '#D97706', info: '#6366F1', psychology: { primary: 'Indigo conveys intelligence and trust', background: 'Clean white keeps content readable', accent: 'Light indigo adds friendly energy' }, gradients: { hero: 'linear-gradient(135deg, #EEF2FF 0%, #E0E7FF 100%)', card: 'linear-gradient(145deg, #FFFFFF 0%, #F8FAFC 100%)', button: 'linear-gradient(135deg, #6366F1 0%, #4F46E5 100%)' } },
  spacing: { xs: '0.25rem', sm: '0.5rem', md: '1rem', lg: '1.5rem', xl: '2rem', '2xl': '3rem', '3xl': '4rem', '4xl': '6rem' },
  grid: { columns: 12, gutter: '1.5rem', margin: '2rem', breakpoints: { sm: '640px', md: '768px', lg: '1024px', xl: '1280px', '2xl': '1536px' } },
  motion: { duration: { fast: '150ms', normal: '250ms', slow: '400ms' }, easing: { default: 'ease-out', enter: 'ease-out', exit: 'ease-in', spring: 'cubic-bezier(0.34, 1.56, 0.64, 1)' }, reducedMotion: 'simplify' },
  accessibility: { contrastRatio: 4.5, focusVisible: true, keyboardNav: true, ariaLabels: true, reducedMotion: true, screenReader: true },
  iconography: { library: 'lucide', style: 'outline', size: { sm: '16px', md: '20px', lg: '24px' } },
  illustration: { style: 'flat' }, photography: { style: 'lifestyle', mood: ['friendly', 'inclusive', 'inspiring'], aspectRatio: '16/9' },
  componentsStyling: { button: { borderRadius: '0.75rem', fontWeight: '600' }, card: { borderRadius: '1rem', shadow: '0 2px 4px rgba(0,0,0,0.06)' }, input: { borderRadius: '0.75rem' }, badge: { borderRadius: '9999px' }, avatar: { borderRadius: '50%' }, dialog: { borderRadius: '1rem' }, table: { borderRadius: '0.5rem' }, form: { gap: '1rem' }, chart: {} },
  brandPersonality: ['friendly', 'approachable', 'trustworthy', 'inspiring', 'inclusive'],
  microInteractions: [{ trigger: 'hover', animation: 'translateY(-2px)', duration: '150ms' }, { trigger: 'click', animation: 'scale(0.98)', duration: '100ms' }, { trigger: 'focus', animation: 'ring(2px)', duration: '150ms' }],
};

export const REALESTATE_PREMIUM: DesignProfile = {
  id: 'design.realestate.premium',
  version: '2.1.0', status: 'active', createdAt: '2025-01-01T00:00:00+00:00', updatedAt: '2025-01-01T00:00:00+00:00',
  evidenceRefs: [], kind: 'DesignProfile',
  name: 'Real Estate: Premium Trust',
  description: 'Premium design for real estate with clean typography, warm tones, and property-focused imagery',
  typography: { displayFamily: 'Cormorant Garamond', bodyFamily: 'Inter', monoFamily: 'JetBrains Mono', scale: { display: { size: '3.5rem', lineHeight: '1.1', weight: '600', tracking: '-0.02em' }, h1: { size: '2.5rem', lineHeight: '1.2', weight: '600' }, h2: { size: '2rem', lineHeight: '1.3', weight: '600' }, h3: { size: '1.5rem', lineHeight: '1.4', weight: '500' }, h4: { size: '1.25rem', lineHeight: '1.4', weight: '500' }, bodyLg: { size: '1.125rem', lineHeight: '1.7', weight: '400' }, body: { size: '1rem', lineHeight: '1.7', weight: '400' }, bodySm: { size: '0.875rem', lineHeight: '1.6', weight: '400' }, caption: { size: '0.75rem', lineHeight: '1.5', weight: '500' }, overline: { size: '0.75rem', lineHeight: '1.5', weight: '600', tracking: '0.1em' } } },
  colorPsychology: { primary: '#1E3A5F', secondary: '#C4956A', accent: '#D4A574', background: '#FAFAFA', foreground: '#1E293B', muted: '#94A3B8', destructive: '#DC2626', success: '#059669', warning: '#D97706', info: '#1E3A5F', psychology: { primary: 'Navy conveys stability, trust, and premium quality', secondary: 'Gold adds warmth and luxury feel', background: 'Light gray keeps focus on property images' }, gradients: { hero: 'linear-gradient(135deg, #0F172A 0%, #1E3A5F 100%)', card: 'linear-gradient(145deg, #FFFFFF 0%, #FAFAFA 100%)', button: 'linear-gradient(135deg, #1E3A5F 0%, #2D5A87 100%)' } },
  spacing: { xs: '0.25rem', sm: '0.5rem', md: '1rem', lg: '1.5rem', xl: '2rem', '2xl': '3rem', '3xl': '4rem', '4xl': '6rem' },
  grid: { columns: 12, gutter: '1.5rem', margin: '2rem', breakpoints: { sm: '640px', md: '768px', lg: '1024px', xl: '1280px', '2xl': '1536px' } },
  motion: { duration: { fast: '150ms', normal: '300ms', slow: '500ms' }, easing: { default: 'ease-out', enter: 'ease-out', exit: 'ease-in', spring: 'cubic-bezier(0.34, 1.56, 0.64, 1)' }, reducedMotion: 'simplify' },
  accessibility: { contrastRatio: 4.5, focusVisible: true, keyboardNav: true, ariaLabels: true, reducedMotion: true, screenReader: true },
  iconography: { library: 'lucide', style: 'outline', size: { sm: '16px', md: '20px', lg: '24px' } },
  illustration: { style: 'flat' }, photography: { style: 'editorial', mood: ['premium', 'bright', 'spacious'], aspectRatio: '16/9' },
  componentsStyling: { button: { borderRadius: '0.5rem', fontWeight: '500' }, card: { borderRadius: '0.75rem', shadow: '0 2px 8px rgba(0,0,0,0.08)' }, input: { borderRadius: '0.5rem' }, badge: { borderRadius: '0.25rem' }, avatar: { borderRadius: '50%' }, dialog: { borderRadius: '0.75rem' }, table: { borderRadius: '0.5rem' }, form: { gap: '1rem' }, chart: {} },
  brandPersonality: ['premium', 'trustworthy', 'professional', 'sophisticated', 'reliable'],
  microInteractions: [{ trigger: 'hover', animation: 'translateY(-4px)', duration: '200ms' }, { trigger: 'click', animation: 'scale(0.98)', duration: '100ms' }, { trigger: 'focus', animation: 'ring(2px)', duration: '150ms' }],
};

export const FINTECH_SECURE: DesignProfile = {
  id: 'design.fintech.secure',
  version: '2.1.0', status: 'active', createdAt: '2025-01-01T00:00:00+00:00', updatedAt: '2025-01-01T00:00:00+00:00',
  evidenceRefs: [], kind: 'DesignProfile',
  name: 'Fintech: Secure Professional',
  description: 'Secure, professional design for fintech applications with data-dense layouts and trust signals',
  typography: { displayFamily: 'Inter', bodyFamily: 'Inter', monoFamily: 'JetBrains Mono', scale: { display: { size: '2.75rem', lineHeight: '1.1', weight: '700', tracking: '-0.02em' }, h1: { size: '2rem', lineHeight: '1.2', weight: '700' }, h2: { size: '1.5rem', lineHeight: '1.3', weight: '600' }, h3: { size: '1.25rem', lineHeight: '1.4', weight: '600' }, h4: { size: '1.125rem', lineHeight: '1.4', weight: '500' }, bodyLg: { size: '1rem', lineHeight: '1.6', weight: '400' }, body: { size: '0.875rem', lineHeight: '1.6', weight: '400' }, bodySm: { size: '0.75rem', lineHeight: '1.5', weight: '400' }, caption: { size: '0.75rem', lineHeight: '1.5', weight: '500' }, overline: { size: '0.75rem', lineHeight: '1.5', weight: '600', tracking: '0.1em' } } },
  colorPsychology: { primary: '#0F766E', secondary: '#14B8A6', accent: '#2DD4BF', background: '#F8FAFC', foreground: '#0F172A', muted: '#64748B', destructive: '#DC2626', success: '#059669', warning: '#D97706', info: '#0284C7', psychology: { primary: 'Teal conveys stability, growth, and financial trust', background: 'Light slate keeps data readable', accent: 'Light teal adds modern fintech feel' }, gradients: { hero: 'linear-gradient(135deg, #0F172A 0%, #134E4A 100%)', card: 'linear-gradient(145deg, #FFFFFF 0%, #F8FAFC 100%)', button: 'linear-gradient(135deg, #0F766E 0%, #0D9488 100%)' } },
  spacing: { xs: '0.25rem', sm: '0.5rem', md: '1rem', lg: '1.5rem', xl: '2rem', '2xl': '3rem', '3xl': '4rem', '4xl': '6rem' },
  grid: { columns: 12, gutter: '1rem', margin: '1.5rem', breakpoints: { sm: '640px', md: '768px', lg: '1024px', xl: '1280px', '2xl': '1536px' } },
  motion: { duration: { fast: '100ms', normal: '200ms', slow: '300ms' }, easing: { default: 'ease-out', enter: 'ease-out', exit: 'ease-in', spring: 'cubic-bezier(0.34, 1.56, 0.64, 1)' }, reducedMotion: 'simplify' },
  accessibility: { contrastRatio: 4.5, focusVisible: true, keyboardNav: true, ariaLabels: true, reducedMotion: true, screenReader: true },
  iconography: { library: 'lucide', style: 'outline', size: { sm: '14px', md: '18px', lg: '22px' } },
  illustration: { style: 'flat' }, photography: { style: 'editorial', mood: ['professional', 'secure', 'modern'], aspectRatio: '16/9' },
  componentsStyling: { button: { borderRadius: '0.5rem', fontWeight: '600' }, card: { borderRadius: '0.75rem', shadow: '0 1px 3px rgba(0,0,0,0.1)' }, input: { borderRadius: '0.5rem' }, badge: { borderRadius: '0.25rem' }, avatar: { borderRadius: '50%' }, dialog: { borderRadius: '0.75rem' }, table: { borderRadius: '0.375rem' }, form: { gap: '0.75rem' }, chart: {} },
  brandPersonality: ['secure', 'professional', 'reliable', 'modern', 'data-driven'],
  microInteractions: [{ trigger: 'hover', animation: 'translateY(-1px)', duration: '150ms' }, { trigger: 'click', animation: 'scale(0.98)', duration: '100ms' }, { trigger: 'focus', animation: 'ring(2px)', duration: '150ms' }],
};

export const ENTERPRISE_CLEAN: DesignProfile = {
  id: 'design.enterprise.clean',
  version: '2.1.0', status: 'active', createdAt: '2025-01-01T00:00:00+00:00', updatedAt: '2025-01-01T00:00:00+00:00',
  evidenceRefs: [], kind: 'DesignProfile',
  name: 'Enterprise: Clean Professional',
  description: 'Clean, data-dense design for enterprise B2B software with maximum information density',
  typography: { displayFamily: 'Inter', bodyFamily: 'Inter', monoFamily: 'JetBrains Mono', scale: { display: { size: '2.5rem', lineHeight: '1.1', weight: '700', tracking: '-0.02em' }, h1: { size: '1.75rem', lineHeight: '1.2', weight: '700' }, h2: { size: '1.375rem', lineHeight: '1.3', weight: '600' }, h3: { size: '1.125rem', lineHeight: '1.4', weight: '600' }, h4: { size: '1rem', lineHeight: '1.4', weight: '500' }, bodyLg: { size: '1rem', lineHeight: '1.6', weight: '400' }, body: { size: '0.875rem', lineHeight: '1.6', weight: '400' }, bodySm: { size: '0.75rem', lineHeight: '1.5', weight: '400' }, caption: { size: '0.75rem', lineHeight: '1.5', weight: '500' }, overline: { size: '0.75rem', lineHeight: '1.5', weight: '600', tracking: '0.1em' } } },
  colorPsychology: { primary: '#2563EB', secondary: '#0F172A', accent: '#3B82F6', background: '#FFFFFF', foreground: '#0F172A', muted: '#64748B', destructive: '#DC2626', success: '#059669', warning: '#D97706', info: '#2563EB', psychology: { primary: 'Blue conveys enterprise reliability and professionalism', secondary: 'Dark navy for authoritative headers', accent: 'Light blue for interactive elements' }, gradients: { hero: 'linear-gradient(135deg, #0F172A 0%, #1E293B 100%)', card: 'linear-gradient(145deg, #FFFFFF 0%, #F8FAFC 100%)', button: 'linear-gradient(135deg, #2563EB 0%, #1D4ED8 100%)' } },
  spacing: { xs: '0.25rem', sm: '0.5rem', md: '0.75rem', lg: '1.25rem', xl: '1.75rem', '2xl': '2.5rem', '3xl': '3.5rem', '4xl': '5rem' },
  grid: { columns: 12, gutter: '1rem', margin: '1.5rem', breakpoints: { sm: '640px', md: '768px', lg: '1024px', xl: '1280px', '2xl': '1536px' } },
  motion: { duration: { fast: '100ms', normal: '200ms', slow: '300ms' }, easing: { default: 'ease-out', enter: 'ease-out', exit: 'ease-in', spring: 'cubic-bezier(0.34, 1.56, 0.64, 1)' }, reducedMotion: 'simplify' },
  accessibility: { contrastRatio: 4.5, focusVisible: true, keyboardNav: true, ariaLabels: true, reducedMotion: true, screenReader: true },
  iconography: { library: 'lucide', style: 'outline', size: { sm: '14px', md: '18px', lg: '22px' } },
  illustration: { style: 'flat' }, photography: { style: 'editorial', mood: ['professional', 'clean', 'efficient'], aspectRatio: '16/9' },
  componentsStyling: { button: { borderRadius: '0.375rem', fontWeight: '500' }, card: { borderRadius: '0.5rem', shadow: '0 1px 2px rgba(0,0,0,0.05)' }, input: { borderRadius: '0.375rem' }, badge: { borderRadius: '0.25rem' }, avatar: { borderRadius: '50%' }, dialog: { borderRadius: '0.5rem' }, table: { borderRadius: '0.375rem' }, form: { gap: '0.75rem' }, chart: {} },
  brandPersonality: ['professional', 'efficient', 'reliable', 'data-driven', 'authoritative'],
  microInteractions: [{ trigger: 'hover', animation: 'translateY(-1px)', duration: '150ms' }, { trigger: 'click', animation: 'scale(0.98)', duration: '100ms' }, { trigger: 'focus', animation: 'ring(2px)', duration: '150ms' }],
};

export const NONPROFIT_WARM: DesignProfile = {
  id: 'design.nonprofit.warm',
  version: '2.1.0', status: 'active', createdAt: '2025-01-01T00:00:00+00:00', updatedAt: '2025-01-01T00:00:00+00:00',
  evidenceRefs: [], kind: 'DesignProfile',
  name: 'Nonprofit: Warm Compassionate',
  description: 'Warm, compassionate design for nonprofit organizations with impact-focused storytelling',
  typography: { displayFamily: 'Source Serif 4', bodyFamily: 'Inter', monoFamily: 'JetBrains Mono', scale: { display: { size: '3.25rem', lineHeight: '1.1', weight: '700', tracking: '-0.01em' }, h1: { size: '2.5rem', lineHeight: '1.2', weight: '700' }, h2: { size: '1.75rem', lineHeight: '1.3', weight: '600' }, h3: { size: '1.375rem', lineHeight: '1.4', weight: '600' }, h4: { size: '1.125rem', lineHeight: '1.4', weight: '500' }, bodyLg: { size: '1.125rem', lineHeight: '1.8', weight: '400' }, body: { size: '1rem', lineHeight: '1.7', weight: '400' }, bodySm: { size: '0.875rem', lineHeight: '1.6', weight: '400' }, caption: { size: '0.75rem', lineHeight: '1.5', weight: '500' }, overline: { size: '0.75rem', lineHeight: '1.5', weight: '600', tracking: '0.1em' } } },
  colorPsychology: { primary: '#059669', secondary: '#10B981', accent: '#34D399', background: '#F0FDF4', foreground: '#022C22', muted: '#6B7280', destructive: '#DC2626', success: '#059669', warning: '#D97706', info: '#0284C7', psychology: { primary: 'Green conveys growth, hope, and positive impact', background: 'Light green creates caring atmosphere', accent: 'Bright green draws attention to CTAs' }, gradients: { hero: 'linear-gradient(135deg, #F0FDF4 0%, #DCFCE7 100%)', card: 'linear-gradient(145deg, #FFFFFF 0%, #F0FDF4 100%)', button: 'linear-gradient(135deg, #059669 0%, #047857 100%)' } },
  spacing: { xs: '0.25rem', sm: '0.5rem', md: '1rem', lg: '1.5rem', xl: '2rem', '2xl': '3rem', '3xl': '4rem', '4xl': '6rem' },
  grid: { columns: 12, gutter: '1.5rem', margin: '2rem', breakpoints: { sm: '640px', md: '768px', lg: '1024px', xl: '1280px', '2xl': '1536px' } },
  motion: { duration: { fast: '150ms', normal: '300ms', slow: '500ms' }, easing: { default: 'ease-out', enter: 'ease-out', exit: 'ease-in', spring: 'cubic-bezier(0.34, 1.56, 0.64, 1)' }, reducedMotion: 'simplify' },
  accessibility: { contrastRatio: 4.5, focusVisible: true, keyboardNav: true, ariaLabels: true, reducedMotion: true, screenReader: true },
  iconography: { library: 'lucide', style: 'outline', size: { sm: '16px', md: '20px', lg: '24px' } },
  illustration: { style: 'flat' }, photography: { style: 'candid', mood: ['hopeful', 'impactful', 'authentic'], aspectRatio: '4/3' },
  componentsStyling: { button: { borderRadius: '9999px', fontWeight: '600' }, card: { borderRadius: '1rem', shadow: '0 2px 4px rgba(0,0,0,0.06)' }, input: { borderRadius: '0.75rem' }, badge: { borderRadius: '9999px' }, avatar: { borderRadius: '50%' }, dialog: { borderRadius: '1rem' }, table: { borderRadius: '0.5rem' }, form: { gap: '1rem' }, chart: {} },
  brandPersonality: ['compassionate', 'hopeful', 'authentic', 'warm', 'transparent'],
  microInteractions: [{ trigger: 'hover', animation: 'translateY(-2px)', duration: '150ms' }, { trigger: 'click', animation: 'scale(0.98)', duration: '100ms' }, { trigger: 'focus', animation: 'ring(2px)', duration: '150ms' }],
};

export const MEDIA_CONTENT: DesignProfile = {
  id: 'design.media.content',
  version: '2.1.0', status: 'active', createdAt: '2025-01-01T00:00:00+00:00', updatedAt: '2025-01-01T00:00:00+00:00',
  evidenceRefs: [], kind: 'DesignProfile',
  name: 'Media: Content-First',
  description: 'Content-first design for media and publishing with focus on readability and typography',
  typography: { displayFamily: 'Merriweather', bodyFamily: 'Source Serif 4', monoFamily: 'JetBrains Mono', scale: { display: { size: '3.5rem', lineHeight: '1.1', weight: '800', tracking: '-0.02em' }, h1: { size: '2.5rem', lineHeight: '1.2', weight: '700' }, h2: { size: '1.75rem', lineHeight: '1.3', weight: '700' }, h3: { size: '1.375rem', lineHeight: '1.4', weight: '600' }, h4: { size: '1.125rem', lineHeight: '1.4', weight: '600' }, bodyLg: { size: '1.25rem', lineHeight: '1.8', weight: '400' }, body: { size: '1.125rem', lineHeight: '1.8', weight: '400' }, bodySm: { size: '0.875rem', lineHeight: '1.6', weight: '400' }, caption: { size: '0.75rem', lineHeight: '1.5', weight: '500' }, overline: { size: '0.75rem', lineHeight: '1.5', weight: '700', tracking: '0.1em' } } },
  colorPsychology: { primary: '#111827', secondary: '#3B82F6', accent: '#2563EB', background: '#FFFFFF', foreground: '#111827', muted: '#6B7280', destructive: '#DC2626', success: '#059669', warning: '#D97706', info: '#3B82F6', psychology: { primary: 'Black text maximizes readability on white', background: 'Clean white for print-like reading experience', accent: 'Blue for hyperlinks and interactive elements' }, gradients: { hero: 'linear-gradient(135deg, #F8FAFC 0%, #E2E8F0 100%)', card: 'linear-gradient(145deg, #FFFFFF 0%, #F8FAFC 100%)', button: 'linear-gradient(135deg, #111827 0%, #374151 100%)' } },
  spacing: { xs: '0.25rem', sm: '0.5rem', md: '1rem', lg: '1.5rem', xl: '2rem', '2xl': '3rem', '3xl': '4rem', '4xl': '6rem' },
  grid: { columns: 12, gutter: '2rem', margin: '2rem', breakpoints: { sm: '640px', md: '768px', lg: '1024px', xl: '1280px', '2xl': '1536px' } },
  motion: { duration: { fast: '150ms', normal: '250ms', slow: '400ms' }, easing: { default: 'ease-out', enter: 'ease-out', exit: 'ease-in', spring: 'cubic-bezier(0.34, 1.56, 0.64, 1)' }, reducedMotion: 'simplify' },
  accessibility: { contrastRatio: 4.5, focusVisible: true, keyboardNav: true, ariaLabels: true, reducedMotion: true, screenReader: true },
  iconography: { library: 'lucide', style: 'outline', size: { sm: '16px', md: '20px', lg: '24px' } },
  illustration: { style: 'abstract' }, photography: { style: 'editorial', mood: ['journalistic', 'clean', 'authentic'], aspectRatio: '16/9' },
  componentsStyling: { button: { borderRadius: '0.375rem', fontWeight: '500' }, card: { borderRadius: '0.5rem', shadow: '0 1px 2px rgba(0,0,0,0.05)' }, input: { borderRadius: '0.375rem' }, badge: { borderRadius: '0.25rem' }, avatar: { borderRadius: '50%' }, dialog: { borderRadius: '0.5rem' }, table: { borderRadius: '0.375rem' }, form: { gap: '1rem' }, chart: {} },
  brandPersonality: ['authoritative', 'trustworthy', 'editorial', 'clean', 'sophisticated'],
  microInteractions: [{ trigger: 'hover', animation: 'underline', duration: '150ms' }, { trigger: 'click', animation: 'opacity(0.8)', duration: '100ms' }, { trigger: 'focus', animation: 'ring(2px)', duration: '150ms' }],
};

export const TRAVEL_VIBRANT: DesignProfile = {
  id: 'design.travel.vibrant',
  version: '2.1.0', status: 'active', createdAt: '2025-01-01T00:00:00+00:00', updatedAt: '2025-01-01T00:00:00+00:00',
  evidenceRefs: [], kind: 'DesignProfile',
  name: 'Travel: Vibrant Adventurous',
  description: 'Vibrant, adventurous design for travel brands with immersive destination imagery',
  typography: { displayFamily: 'Poppins', bodyFamily: 'Inter', monoFamily: 'JetBrains Mono', scale: { display: { size: '3.75rem', lineHeight: '1', weight: '700', tracking: '-0.02em' }, h1: { size: '2.75rem', lineHeight: '1.1', weight: '700' }, h2: { size: '2rem', lineHeight: '1.2', weight: '600' }, h3: { size: '1.5rem', lineHeight: '1.3', weight: '600' }, h4: { size: '1.25rem', lineHeight: '1.4', weight: '500' }, bodyLg: { size: '1.125rem', lineHeight: '1.7', weight: '400' }, body: { size: '1rem', lineHeight: '1.7', weight: '400' }, bodySm: { size: '0.875rem', lineHeight: '1.6', weight: '400' }, caption: { size: '0.75rem', lineHeight: '1.5', weight: '500' }, overline: { size: '0.75rem', lineHeight: '1.5', weight: '700', tracking: '0.15em' } } },
  colorPsychology: { primary: '#0891B2', secondary: '#06B6D4', accent: '#22D3EE', background: '#FFFFFF', foreground: '#164E63', muted: '#64748B', destructive: '#DC2626', success: '#059669', warning: '#D97706', info: '#0891B2', psychology: { primary: 'Cyan conveys travel, freedom, and open skies', background: 'Clean white keeps destination photos prominent', accent: 'Bright cyan adds excitement and energy' }, gradients: { hero: 'linear-gradient(135deg, #ECFEFF 0%, #CFFAFE 100%)', card: 'linear-gradient(145deg, #FFFFFF 0%, #F0FDFA 100%)', button: 'linear-gradient(135deg, #0891B2 0%, #06B6D4 100%)' } },
  spacing: { xs: '0.25rem', sm: '0.5rem', md: '1rem', lg: '1.5rem', xl: '2rem', '2xl': '3rem', '3xl': '4rem', '4xl': '6rem' },
  grid: { columns: 12, gutter: '1.5rem', margin: '2rem', breakpoints: { sm: '640px', md: '768px', lg: '1024px', xl: '1280px', '2xl': '1536px' } },
  motion: { duration: { fast: '200ms', normal: '350ms', slow: '600ms' }, easing: { default: 'cubic-bezier(0.4, 0, 0.2, 1)', enter: 'cubic-bezier(0, 0, 0.2, 1)', exit: 'cubic-bezier(0.4, 0, 1, 1)', spring: 'cubic-bezier(0.34, 1.56, 0.64, 1)' }, reducedMotion: 'simplify' },
  accessibility: { contrastRatio: 4.5, focusVisible: true, keyboardNav: true, ariaLabels: true, reducedMotion: true, screenReader: true },
  iconography: { library: 'lucide', style: 'outline', size: { sm: '16px', md: '20px', lg: '24px' } },
  illustration: { style: 'flat' }, photography: { style: 'lifestyle', mood: ['vibrant', 'adventurous', 'inspiring'], aspectRatio: '16/9' },
  componentsStyling: { button: { borderRadius: '9999px', fontWeight: '600' }, card: { borderRadius: '1rem', shadow: '0 4px 6px rgba(0,0,0,0.08)' }, input: { borderRadius: '9999px' }, badge: { borderRadius: '9999px' }, avatar: { borderRadius: '50%' }, dialog: { borderRadius: '1rem' }, table: { borderRadius: '0.5rem' }, form: { gap: '1rem' }, chart: {} },
  brandPersonality: ['adventurous', 'vibrant', 'inspiring', 'welcoming', 'energetic'],
  microInteractions: [{ trigger: 'hover', animation: 'scale(1.03)', duration: '200ms' }, { trigger: 'click', animation: 'scale(0.97)', duration: '100ms' }, { trigger: 'focus', animation: 'ring(2px)', duration: '150ms' }],
};

export const LEGAL_TRUST: DesignProfile = {
  id: 'design.legal.trust',
  version: '2.1.0', status: 'active', createdAt: '2025-01-01T00:00:00+00:00', updatedAt: '2025-01-01T00:00:00+00:00',
  evidenceRefs: [], kind: 'DesignProfile',
  name: 'Legal: Trustworthy Traditional',
  description: 'Trustworthy, professional design for legal firms with classic typography and formal layouts',
  typography: { displayFamily: 'Libre Baskerville', bodyFamily: 'Inter', monoFamily: 'JetBrains Mono', scale: { display: { size: '3rem', lineHeight: '1.1', weight: '700' }, h1: { size: '2.25rem', lineHeight: '1.2', weight: '700' }, h2: { size: '1.75rem', lineHeight: '1.3', weight: '600' }, h3: { size: '1.375rem', lineHeight: '1.4', weight: '600' }, h4: { size: '1.125rem', lineHeight: '1.4', weight: '500' }, bodyLg: { size: '1.125rem', lineHeight: '1.8', weight: '400' }, body: { size: '1rem', lineHeight: '1.7', weight: '400' }, bodySm: { size: '0.875rem', lineHeight: '1.6', weight: '400' }, caption: { size: '0.75rem', lineHeight: '1.5', weight: '500' }, overline: { size: '0.75rem', lineHeight: '1.5', weight: '700', tracking: '0.08em' } } },
  colorPsychology: { primary: '#1E3A5F', secondary: '#B8860B', accent: '#C4956A', background: '#FAFAF8', foreground: '#1C1917', muted: '#78716C', destructive: '#991B1B', success: '#065F46', warning: '#92400E', info: '#1E3A5F', psychology: { primary: 'Navy blue conveys tradition, authority, and trustworthiness', secondary: 'Gold accents add prestige and heritage', background: 'Warm off-white creates a distinguished feel' }, gradients: { hero: 'linear-gradient(135deg, #1E3A5F 0%, #2D5A87 100%)', card: 'linear-gradient(145deg, #FFFFFF 0%, #FAFAF8 100%)', button: 'linear-gradient(135deg, #1E3A5F 0%, #B8860B 100%)' } },
  spacing: { xs: '0.25rem', sm: '0.5rem', md: '1rem', lg: '1.5rem', xl: '2rem', '2xl': '3rem', '3xl': '4rem', '4xl': '6rem' },
  grid: { columns: 12, gutter: '2rem', margin: '2rem', breakpoints: { sm: '640px', md: '768px', lg: '1024px', xl: '1280px', '2xl': '1536px' } },
  motion: { duration: { fast: '200ms', normal: '300ms', slow: '500ms' }, easing: { default: 'ease-out', enter: 'ease-out', exit: 'ease-in', spring: 'cubic-bezier(0.34, 1.56, 0.64, 1)' }, reducedMotion: 'simplify' },
  accessibility: { contrastRatio: 4.5, focusVisible: true, keyboardNav: true, ariaLabels: true, reducedMotion: true, screenReader: true },
  iconography: { library: 'lucide', style: 'outline', size: { sm: '16px', md: '20px', lg: '24px' } },
  illustration: { style: 'flat' }, photography: { style: 'studio', mood: ['professional', 'serious', 'trustworthy'], aspectRatio: '16/9' },
  componentsStyling: { button: { borderRadius: '0.375rem', fontWeight: '500' }, card: { borderRadius: '0.5rem', shadow: '0 1px 3px rgba(0,0,0,0.08)' }, input: { borderRadius: '0.375rem' }, badge: { borderRadius: '0.25rem' }, avatar: { borderRadius: '50%' }, dialog: { borderRadius: '0.5rem' }, table: { borderRadius: '0.375rem' }, form: { gap: '1rem' }, chart: {} },
  brandPersonality: ['trustworthy', 'authoritative', 'traditional', 'professional', 'dignified'],
  microInteractions: [{ trigger: 'hover', animation: 'opacity(0.9)', duration: '200ms' }, { trigger: 'click', animation: 'opacity(0.8)', duration: '100ms' }, { trigger: 'focus', animation: 'ring(2px)', duration: '150ms' }],
};

export const AGENCY_BOLD: DesignProfile = {
  id: 'design.agency.bold',
  version: '2.1.0', status: 'active', createdAt: '2025-01-01T00:00:00+00:00', updatedAt: '2025-01-01T00:00:00+00:00',
  evidenceRefs: [], kind: 'DesignProfile',
  name: 'Agency: Bold Creative',
  description: 'Bold, creative design for agencies with striking visuals, large typography, and portfolio showcases',
  typography: { displayFamily: 'Space Grotesk', bodyFamily: 'Inter', monoFamily: 'JetBrains Mono', scale: { display: { size: '5rem', lineHeight: '1', weight: '700', tracking: '-0.03em' }, h1: { size: '3.5rem', lineHeight: '1.1', weight: '700' }, h2: { size: '2.5rem', lineHeight: '1.2', weight: '600' }, h3: { size: '1.75rem', lineHeight: '1.3', weight: '600' }, h4: { size: '1.25rem', lineHeight: '1.4', weight: '500' }, bodyLg: { size: '1.125rem', lineHeight: '1.7', weight: '400' }, body: { size: '1rem', lineHeight: '1.7', weight: '400' }, bodySm: { size: '0.875rem', lineHeight: '1.6', weight: '400' }, caption: { size: '0.75rem', lineHeight: '1.5', weight: '500' }, overline: { size: '0.75rem', lineHeight: '1.5', weight: '700', tracking: '0.1em' } } },
  colorPsychology: { primary: '#6D28D9', secondary: '#EC4899', accent: '#F472B6', background: '#09090B', foreground: '#FAFAFA', muted: '#27272A', destructive: '#DC2626', success: '#10B981', warning: '#F59E0B', info: '#8B5CF6', psychology: { primary: 'Purple conveys creativity, originality, and premium service', secondary: 'Pink adds energy and modern edge', background: 'Dark backdrop makes portfolio work pop' }, gradients: { hero: 'linear-gradient(135deg, #09090B 0%, #1F0933 100%)', card: 'linear-gradient(145deg, #18181B 0%, #09090B 100%)', button: 'linear-gradient(135deg, #6D28D9 0%, #EC4899 100%)' } },
  spacing: { xs: '0.25rem', sm: '0.5rem', md: '1rem', lg: '1.5rem', xl: '2rem', '2xl': '3rem', '3xl': '5rem', '4xl': '8rem' },
  grid: { columns: 12, gutter: '1rem', margin: '1.5rem', breakpoints: { sm: '640px', md: '768px', lg: '1024px', xl: '1280px', '2xl': '1536px' } },
  motion: { duration: { fast: '200ms', normal: '400ms', slow: '700ms' }, easing: { default: 'cubic-bezier(0.4, 0, 0.2, 1)', enter: 'cubic-bezier(0, 0, 0.2, 1)', exit: 'cubic-bezier(0.4, 0, 1, 1)', spring: 'cubic-bezier(0.34, 1.56, 0.64, 1)' }, reducedMotion: 'simplify' },
  accessibility: { contrastRatio: 4.5, focusVisible: true, keyboardNav: true, ariaLabels: true, reducedMotion: true, screenReader: true },
  iconography: { library: 'lucide', style: 'filled', size: { sm: '16px', md: '20px', lg: '24px' } },
  illustration: { style: 'abstract' }, photography: { style: 'editorial', mood: ['creative', 'bold', 'inspiring'], aspectRatio: '4/3' },
  componentsStyling: { button: { borderRadius: '0.5rem', fontWeight: '700' }, card: { borderRadius: '0.75rem', shadow: '0 8px 16px rgba(0,0,0,0.3)' }, input: { borderRadius: '0.5rem' }, badge: { borderRadius: '0.25rem' }, avatar: { borderRadius: '50%' }, dialog: { borderRadius: '0.75rem' }, table: { borderRadius: '0.5rem' }, form: { gap: '1rem' }, chart: {} },
  brandPersonality: ['creative', 'bold', 'innovative', 'confident', 'premium'],
  microInteractions: [{ trigger: 'hover', animation: 'scale(1.05)', duration: '200ms' }, { trigger: 'click', animation: 'scale(0.95)', duration: '100ms' }, { trigger: 'focus', animation: 'ring(3px)', duration: '150ms' }],
};

export const LOGISTICS_RELIABLE: DesignProfile = {
  id: 'design.logistics.reliable',
  version: '2.1.0', status: 'active', createdAt: '2025-01-01T00:00:00+00:00', updatedAt: '2025-01-01T00:00:00+00:00',
  evidenceRefs: [], kind: 'DesignProfile',
  name: 'Logistics: Reliable Efficient',
  description: 'Clean, data-dense design for logistics with real-time tracking, maps, and operational dashboards',
  typography: { displayFamily: 'Inter', bodyFamily: 'Inter', monoFamily: 'JetBrains Mono', scale: { display: { size: '2.5rem', lineHeight: '1.1', weight: '700', tracking: '-0.02em' }, h1: { size: '1.75rem', lineHeight: '1.2', weight: '700' }, h2: { size: '1.375rem', lineHeight: '1.3', weight: '600' }, h3: { size: '1.125rem', lineHeight: '1.4', weight: '600' }, h4: { size: '1rem', lineHeight: '1.4', weight: '500' }, bodyLg: { size: '1rem', lineHeight: '1.6', weight: '400' }, body: { size: '0.875rem', lineHeight: '1.6', weight: '400' }, bodySm: { size: '0.75rem', lineHeight: '1.5', weight: '400' }, caption: { size: '0.75rem', lineHeight: '1.5', weight: '500' }, overline: { size: '0.75rem', lineHeight: '1.5', weight: '600', tracking: '0.1em' } } },
  colorPsychology: { primary: '#0F766E', secondary: '#0284C7', accent: '#0EA5E9', background: '#F8FAFC', foreground: '#0F172A', muted: '#64748B', destructive: '#DC2626', success: '#059669', warning: '#D97706', info: '#0284C7', psychology: { primary: 'Teal conveys reliability efficiency and professionalism', secondary: 'Blue adds technological capability', background: 'Light slate keeps operational data readable' }, gradients: { hero: 'linear-gradient(135deg, #0F172A 0%, #134E4A 100%)', card: 'linear-gradient(145deg, #FFFFFF 0%, #F8FAFC 100%)', button: 'linear-gradient(135deg, #0F766E 0%, #0284C7 100%)' } },
  spacing: { xs: '0.25rem', sm: '0.5rem', md: '0.75rem', lg: '1.25rem', xl: '1.75rem', '2xl': '2.5rem', '3xl': '3.5rem', '4xl': '5rem' },
  grid: { columns: 12, gutter: '1rem', margin: '1.5rem', breakpoints: { sm: '640px', md: '768px', lg: '1024px', xl: '1280px', '2xl': '1536px' } },
  motion: { duration: { fast: '100ms', normal: '200ms', slow: '300ms' }, easing: { default: 'ease-out', enter: 'ease-out', exit: 'ease-in', spring: 'cubic-bezier(0.34, 1.56, 0.64, 1)' }, reducedMotion: 'simplify' },
  accessibility: { contrastRatio: 4.5, focusVisible: true, keyboardNav: true, ariaLabels: true, reducedMotion: true, screenReader: true },
  iconography: { library: 'lucide', style: 'outline', size: { sm: '14px', md: '18px', lg: '22px' } },
  illustration: { style: 'flat' }, photography: { style: 'editorial', mood: ['operational', 'efficient', 'professional'], aspectRatio: '16/9' },
  componentsStyling: { button: { borderRadius: '0.375rem', fontWeight: '600' }, card: { borderRadius: '0.5rem', shadow: '0 1px 2px rgba(0,0,0,0.05)' }, input: { borderRadius: '0.375rem' }, badge: { borderRadius: '0.25rem' }, avatar: { borderRadius: '50%' }, dialog: { borderRadius: '0.5rem' }, table: { borderRadius: '0.375rem' }, form: { gap: '0.75rem' }, chart: {} },
  brandPersonality: ['reliable', 'efficient', 'professional', 'data-driven', 'punctual'],
  microInteractions: [{ trigger: 'hover', animation: 'translateY(-1px)', duration: '150ms' }, { trigger: 'click', animation: 'scale(0.98)', duration: '100ms' }, { trigger: 'focus', animation: 'ring(2px)', duration: '150ms' }],
};
