import type { DesignProfile } from '../../schemas/knowledge/design-profile.schema.js';

export const SAAS_MODERN: DesignProfile = {
  id: 'design.saas.modern',
  version: '2.1.0',
  status: 'active',
  createdAt: '2025-01-01T00:00:00+00:00',
  updatedAt: '2025-01-01T00:00:00+00:00',
  evidenceRefs: [],
  kind: 'DesignProfile',
  name: 'SaaS: Modern Clean',
  description: 'Clean, professional SaaS design with violet accents',
  typography: {
    displayFamily: 'Inter',
    bodyFamily: 'Inter',
    monoFamily: 'JetBrains Mono',
    scale: {
      display: { size: '3rem', lineHeight: '1.1', weight: '800', tracking: '-0.02em' },
      h1: { size: '2.25rem', lineHeight: '1.2', weight: '700', tracking: '-0.01em' },
      h2: { size: '1.75rem', lineHeight: '1.3', weight: '600' },
      h3: { size: '1.375rem', lineHeight: '1.4', weight: '600' },
      h4: { size: '1.125rem', lineHeight: '1.4', weight: '500' },
      bodyLg: { size: '1.125rem', lineHeight: '1.7', weight: '400' },
      body: { size: '1rem', lineHeight: '1.7', weight: '400' },
      bodySm: { size: '0.875rem', lineHeight: '1.6', weight: '400' },
      caption: { size: '0.75rem', lineHeight: '1.5', weight: '500' },
      overline: { size: '0.75rem', lineHeight: '1.5', weight: '600', tracking: '0.05em' },
    },
  },
  colorPsychology: {
    primary: '#7C3AED',
    secondary: '#3B82F6',
    accent: '#8B5CF6',
    background: '#09090B',
    foreground: '#FAFAFA',
    muted: '#27272A',
    destructive: '#EF4444',
    success: '#22C55E',
    warning: '#F59E0B',
    info: '#3B82F6',
    psychology: {
      primary: 'Violet conveys innovation, creativity, and premium tech',
      background: 'Near-black creates focus and professionalism',
      accent: 'Light violet adds energy without overwhelming',
    },
    gradients: {
      hero: 'linear-gradient(135deg, #09090B 0%, #18181B 100%)',
      card: 'linear-gradient(145deg, #18181B 0%, #09090B 100%)',
      button: 'linear-gradient(135deg, #7C3AED 0%, #6D28D9 100%)',
      subtle: 'linear-gradient(180deg, transparent 0%, rgba(124,58,237,0.05) 100%)',
    },
  },
  spacing: {
    xs: '0.25rem',
    sm: '0.5rem',
    md: '1rem',
    lg: '1.5rem',
    xl: '2rem',
    '2xl': '3rem',
    '3xl': '4rem',
    '4xl': '6rem',
  },
  grid: {
    columns: 12,
    gutter: '1.5rem',
    margin: '1.5rem',
    breakpoints: {
      sm: '640px',
      md: '768px',
      lg: '1024px',
      xl: '1280px',
    },
  },
  motion: {
    duration: {
      fast: '150ms',
      normal: '300ms',
      slow: '500ms',
    },
    easing: {
      default: 'cubic-bezier(0.4, 0, 0.2, 1)',
      enter: 'cubic-bezier(0, 0, 0.2, 1)',
      exit: 'cubic-bezier(0.4, 0, 1, 1)',
      spring: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
    },
    reducedMotion: 'simplify',
  },
  accessibility: {
    contrastRatio: 4.5,
    focusVisible: true,
    keyboardNav: true,
    ariaLabels: true,
    reducedMotion: true,
    screenReader: true,
  },
  iconography: {
    library: 'lucide',
    style: 'outline',
    size: {
      sm: '16px',
      md: '20px',
      lg: '24px',
    },
  },
  illustration: { style: 'none' },
  photography: { style: 'none', mood: [], aspectRatio: '16/9' },
  componentsStyling: {
    button: {
      primary: 'bg-violet-600 hover:bg-violet-700 text-white font-semibold px-6 py-3 rounded-xl transition-all',
      secondary: 'border border-zinc-700 hover:border-zinc-500 text-white font-semibold px-6 py-3 rounded-xl transition-all',
    },
    card: {
      default: 'bg-zinc-900 border border-zinc-800 rounded-2xl p-6',
      hover: 'bg-zinc-900 border border-zinc-800 rounded-2xl p-6 hover:border-zinc-700 transition cursor-pointer',
    },
    input: {
      default: 'bg-zinc-900 border border-zinc-800 rounded-xl px-4 py-3 text-white focus:border-violet-500 transition-colors',
    },
    badge: {
      default: 'bg-violet-600/10 text-violet-400 border border-violet-600/20 px-3 py-1 text-xs font-medium rounded-full',
    },
    avatar: { default: 'rounded-full border border-zinc-800' },
    dialog: { default: 'bg-zinc-900 border border-zinc-800 rounded-2xl' },
    table: { default: 'bg-zinc-900 border border-zinc-800 rounded-xl' },
    form: { default: 'space-y-4' },
    chart: { default: 'bg-zinc-900 border border-zinc-800 rounded-2xl p-6' },
  },
  brandPersonality: ['modern', 'professional', 'innovative', 'trustworthy'],
  microInteractions: [
    { trigger: 'hover', animation: 'translateY(-2px)', duration: '300ms' },
    { trigger: 'click', animation: 'scale(0.98)', duration: '150ms' },
  ],
};
