import type { DesignProfile } from '../../schemas/knowledge/design-profile.schema.js';

export const SUPPLEMENT_MARKETPLACE: DesignProfile = {
  id: 'design.supplement.marketplace',
  version: '1.0.0',
  status: 'active',
  createdAt: '2026-07-01T00:00:00+00:00',
  updatedAt: '2026-07-01T00:00:00+00:00',
  evidenceRefs: [],
  kind: 'DesignProfile',
  name: 'Supplement Marketplace',
  description: 'Health-focused ecommerce design for supplement marketplaces with trust signals, ingredient details, and FSSAI compliance badges',
  typography: {
    displayFamily: 'Plus Jakarta Sans',
    bodyFamily: 'Inter',
    monoFamily: 'JetBrains Mono',
    scale: {
      display: { size: '3rem', lineHeight: '1.1', weight: '700' },
      h1: { size: '2.25rem', lineHeight: '1.2', weight: '700' },
      h2: { size: '1.75rem', lineHeight: '1.3', weight: '600' },
      h3: { size: '1.375rem', lineHeight: '1.4', weight: '600' },
      h4: { size: '1.125rem', lineHeight: '1.4', weight: '500' },
      bodyLg: { size: '1.125rem', lineHeight: '1.7', weight: '400' },
      body: { size: '1rem', lineHeight: '1.7', weight: '400' },
      bodySm: { size: '0.875rem', lineHeight: '1.6', weight: '400' },
      caption: { size: '0.75rem', lineHeight: '1.5', weight: '500' },
      overline: { size: '0.75rem', lineHeight: '1.5', weight: '600', tracking: '0.1em' },
    },
  },
  colorPsychology: {
    primary: '#059669',    // Green — health, vitality, nature
    secondary: '#D97706',  // Amber — energy, warmth, trust
    accent: '#10B981',     // Emerald — freshness, growth
    background: '#FFFFFF',
    foreground: '#1F2937',
    muted: '#6B7280',
    destructive: '#DC2626',
    success: '#059669',
    warning: '#D97706',
    info: '#2563EB',
    psychology: {
      primary: 'Green conveys health, vitality, and natural ingredients',
      secondary: 'Amber signals energy, warmth, and premium quality',
      accent: 'Emerald reinforces freshness and growth',
    },
    gradients: {
      hero: 'linear-gradient(135deg, #ECFDF5 0%, #FEF3C7 100%)',
      card: 'linear-gradient(145deg, #FFFFFF 0%, #ECFDF5 100%)',
      button: 'linear-gradient(135deg, #059669 0%, #10B981 100%)',
    },
  },
  spacing: {
    xs: '0.25rem',
    sm: '0.5rem',
    md: '1rem',
    lg: '1.5rem',
    xl: '2rem',
    '2xl': '3rem',
    '3xl': '4rem',
    '4xl': '6rem',
  },
  grid: {
    columns: 12,
    gutter: '1.5rem',
    margin: '2rem',
    breakpoints: {
      sm: '640px',
      md: '768px',
      lg: '1024px',
      xl: '1280px',
      '2xl': '1536px',
    },
  },
  motion: {
    duration: { fast: '150ms', normal: '250ms', slow: '400ms' },
    easing: {
      default: 'ease-out',
      enter: 'ease-out',
      exit: 'ease-in',
      spring: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
    },
    reducedMotion: 'simplify',
  },
  accessibility: {
    contrastRatio: 4.5,
    focusVisible: true,
    keyboardNav: true,
    ariaLabels: true,
    reducedMotion: true,
    screenReader: true,
  },
  iconography: {
    library: 'lucide',
    style: 'outline',
    size: { sm: '16px', md: '20px', lg: '24px' },
  },
  illustration: { style: 'flat' },
  photography: { style: 'product', mood: ['health', 'vitality', 'natural', 'energetic'], aspectRatio: '1:1' },
  componentsStyling: {
    button: { borderRadius: '0.5rem', fontWeight: '600' },
    card: { borderRadius: '0.75rem', shadow: '0 1px 3px rgba(0,0,0,0.08)' },
    input: { borderRadius: '0.5rem' },
    badge: { borderRadius: '9999px' },
    avatar: { borderRadius: '50%' },
    dialog: { borderRadius: '1rem' },
    table: { borderRadius: '0.5rem' },
    form: { gap: '1rem' },
    chart: {},
  },
  brandPersonality: ['healthy', 'vital', 'trustworthy', 'natural', 'energetic', 'clean', 'professional'],
  microInteractions: [
    { trigger: 'hover', animation: 'translateY(-2px)', duration: '150ms' },
    { trigger: 'click', animation: 'scale(0.98)', duration: '100ms' },
    { trigger: 'focus', animation: 'ring(2px)', duration: '150ms' },
  ],
};
