import type { BusinessIntelligenceProfile } from '../../schemas/knowledge/business-intelligence.schema.js';

export const AGENCY_BI: BusinessIntelligenceProfile = {
  id: 'bi.agency.creative',
  version: '1.0.0',
  name: 'Creative/Digital Agency',
  description: 'How an agency makes money: lead → proposal → pitch → contract → project delivery → invoicing → retainer',
  revenueCycle: {
    name: 'Lead → Proposal → Contract → Delivery → Retainer',
    description: 'Prospect finds agency → discovery call → proposal sent → contract signed → project delivered → retainer/upsell',
    steps: [
      { name: 'Lead generation', action: 'Prospect finds agency via referral/portfolio/ad', conversionRate: 0.05, avgTimeToNext: '1-14 days', revenueImpact: 'high' },
      { name: 'Discovery call', action: 'Initial call to understand prospect needs', conversionRate: 0.40, avgTimeToNext: '1-7 days', revenueImpact: 'critical' },
      { name: 'Proposal sent', action: 'Custom proposal with scope and pricing', conversionRate: 0.35, avgTimeToNext: '3-10 days', revenueImpact: 'high' },
      { name: 'Contract signed', action: 'Prospect signs contract and pays deposit', conversionRate: 0.50, avgTimeToNext: '1-14 days', revenueImpact: 'critical' },
      { name: 'Project delivered', action: 'All deliverables completed and approved', conversionRate: 0.90, avgTimeToNext: '14-120 days', revenueImpact: 'high' },
      { name: 'Final payment', action: 'Client pays final invoice', conversionRate: 0.95, avgTimeToNext: '7-30 days', revenueImpact: 'critical' },
      { name: 'Retainer/upsell', action: 'Client signs retainer or new project', conversionRate: 0.25, avgTimeToNext: '30-90 days', revenueImpact: 'medium' },
    ],
    avgCycleLength: '30-120 days',
    avgRevenuePerCustomer: '$5,000-50,000 per project',
  },
  conversionFunnel: {
    name: 'Lead → Proposal → Contract → Delivery',
    stages: ['Website Visit', 'Contact', 'Discovery Call', 'Proposal', 'Contract', 'Project', 'Payment', 'Retainer'],
    overallConversionRate: '1-3% of website visitors become clients',
    biggestDropOff: 'Proposal → Contract (50% don\'t sign)',
  },
  churnSignals: [
    { name: 'Project delay', detection: 'Project past deadline by 2+ weeks', window: '14 days', severity: 'high' },
    { name: 'Scope dispute', detection: 'Client disputes scope or pricing', window: '7 days', severity: 'critical' },
    { name: 'Communication gap', detection: 'No client response for 7+ days', window: '7 days', severity: 'medium' },
    { name: 'Late payment', detection: 'Invoice unpaid for 30+ days', window: '30 days', severity: 'high' },
    { name: 'No repeat business', detection: 'Client hasn\'t engaged in 6+ months', window: '180 days', severity: 'medium' },
  ],
  retentionAutomations: [
    { name: 'Monthly check-in', trigger: 'Monthly during active project', action: 'Send progress report + next steps', expectedImpact: 'Improves client satisfaction by 25%' },
    { name: 'Post-project follow-up', trigger: '30 days after project completion', action: 'Request testimonial + discuss next needs', expectedImpact: 'Generates 20% repeat business' },
    { name: 'Quarterly review', trigger: 'Every 3 months for retainer clients', action: 'Review metrics + propose new initiatives', expectedImpact: 'Increases retainer value by 15%' },
    { name: 'Referral incentive', trigger: 'After successful project', action: 'Offer referral discount on next project', expectedImpact: 'Generates 15% new leads from referrals' },
  ],
  kpis: [
    { name: 'Revenue', label: 'Revenue', formula: 'Total billings', benchmark: '$20K-200K/month', unit: '$', category: 'revenue' },
    { name: 'Utilization Rate', label: 'Utilization', formula: 'Billable hours / Available hours × 100', benchmark: '65-80%', unit: '%', category: 'operations' },
    { name: 'Average Project Value', label: 'Avg Project', formula: 'Total revenue / Total projects', benchmark: '$5,000-30,000', unit: '$', category: 'revenue' },
    { name: 'Client Retention Rate', label: 'Retention', formula: 'Returning clients / Total clients × 100', benchmark: '50-70%', unit: '%', category: 'retention' },
    { name: 'Proposal Win Rate', label: 'Win Rate', formula: 'Contracts signed / Proposals sent × 100', benchmark: '25-40%', unit: '%', category: 'growth' },
    { name: 'Revenue per Employee', label: 'Rev/Employee', formula: 'Total revenue / Total employees', benchmark: '$80K-150K/year', unit: '$', category: 'operations' },
    { name: 'Average Days to Payment', label: 'Payment Days', formula: 'Average days from invoice to payment', benchmark: '15-30 days', unit: 'days', category: 'operations' },
    { name: 'Client Satisfaction', label: 'NPS', formula: 'Net Promoter Score', benchmark: '50-70', unit: 'score', category: 'engagement' },
  ],
  dashboardWidgets: [
    { name: 'Revenue Dashboard', type: 'chart', description: 'Billing and revenue trends', kpis: ['Revenue', 'Average Project Value'], priority: 'primary' },
    { name: 'Project Pipeline', type: 'table', description: 'Active projects with status and budget', kpis: ['Utilization Rate', 'Proposal Win Rate'], priority: 'primary' },
    { name: 'Client Metrics', type: 'stat-card', description: 'Retention, satisfaction, and pipeline', kpis: ['Client Retention Rate', 'Client Satisfaction'], priority: 'secondary' },
    { name: 'Team Utilization', type: 'chart', description: 'Team utilization by department', kpis: ['Revenue per Employee'], priority: 'secondary' },
  ],
  leadCaptureMechanisms: [
    { name: 'Project Inquiry', headline: 'Let\'s Build Something Great', fields: ['name', 'email', 'company', 'project_type', 'budget'], nextStep: 'Discovery call within 24 hours', conversionRate: '8-12% of visitors' },
    { name: 'Portfolio Review', headline: 'See Our Work', fields: ['name', 'email', 'interest'], nextStep: 'Case study email + follow-up', conversionRate: '15-20% of visitors' },
    { name: 'Newsletter', headline: 'Agency Insights & Case Studies', fields: ['email'], nextStep: 'Nurture sequence', conversionRate: '25-35% of visitors' },
  ],
  morningCheck: {
    primaryMetrics: ['Active projects', 'Utilization rate', 'Pending invoices', 'Pipeline value'],
    secondaryMetrics: ['Team capacity', 'Project deadlines', 'Client communications', 'New leads'],
    alertConditions: ['Utilization <60%', 'Project overdue', 'Invoice >30 days', 'Client dissatisfaction'],
  },
  revenueModels: [
    { name: 'Project-Based', description: 'Fixed-fee project engagements', percentage: 55 },
    { name: 'Retainer', description: 'Monthly retainer agreements', percentage: 25 },
    { name: 'Hourly Consulting', description: 'Hourly consulting fees', percentage: 15 },
    { name: 'Commission/Revenue Share', description: 'Performance-based fees', percentage: 5 },
  ],
  vocabulary: {
    'customer': 'client',
    'product': 'deliverable',
    'buy': 'engage',
    'store': 'agency',
    'cart': 'scope',
    'checkout': 'contract',
    'price': 'budget',
    'order': 'project',
  },
};
