import type { BusinessIntelligenceProfile } from '../../schemas/knowledge/business-intelligence.schema.js';

export const AUTOMOTIVE_BI: BusinessIntelligenceProfile = {
  id: 'bi.automotive.dealer',
  version: '1.0.0',
  name: 'Automotive Dealership',
  description: 'How a dealership makes money: traffic → showroom → test drive → negotiation → financing → delivery → service',
  revenueCycle: {
    name: 'Traffic → Showroom → Test Drive → Financing → Delivery',
    description: 'Buyer discovers inventory → visits showroom → test drives → negotiates → finances → takes delivery → returns for service',
    steps: [
      { name: 'Inventory discovery', action: 'Buyer finds vehicle online or via ad', conversionRate: 0.05, avgTimeToNext: '1-14 days', revenueImpact: 'high' },
      { name: 'Showroom visit', action: 'Buyer visits dealership', conversionRate: 0.30, avgTimeToNext: '1-7 days', revenueImpact: 'critical' },
      { name: 'Test drive', action: 'Buyer test drives vehicle', conversionRate: 0.50, avgTimeToNext: '0-3 days', revenueImpact: 'high' },
      { name: 'Negotiation', action: 'Buyer negotiates price and terms', conversionRate: 0.60, avgTimeToNext: '0-7 days', revenueImpact: 'critical' },
      { name: 'Financing', action: 'Buyer secures financing', conversionRate: 0.70, avgTimeToNext: '1-7 days', revenueImpact: 'high' },
      { name: 'Delivery', action: 'Vehicle delivered to buyer', conversionRate: 0.95, avgTimeToNext: '1-14 days', revenueImpact: 'critical' },
      { name: 'Service return', action: 'Buyer returns for maintenance/repair', conversionRate: 0.60, avgTimeToNext: '90-365 days', revenueImpact: 'medium' },
    ],
    avgCycleLength: '14-60 days',
    avgRevenuePerCustomer: '$5,000-15,000 profit per vehicle',
  },
  conversionFunnel: {
    name: 'Traffic → Showroom → Test Drive → Sale',
    stages: ['Website/Ad', 'Inventory View', 'Showroom Visit', 'Test Drive', 'Negotiation', 'Financing', 'Delivery'],
    overallConversionRate: '3-5% of leads become buyers',
    biggestDropOff: 'Showroom visit → Test drive (50% don\'t test drive)',
  },
  churnSignals: [
    { name: 'Lost to competitor', detection: 'Buyer purchased elsewhere', window: '30 days', severity: 'critical' },
    { name: 'Financing fall-through', detection: 'Buyer couldn\'t secure financing', window: '7 days', severity: 'high' },
    { name: 'Extended negotiation', detection: 'Negotiation ongoing for 7+ days', window: '7 days', severity: 'medium' },
    { name: 'No show at appointment', detection: 'Buyer missed scheduled visit', window: '0 days', severity: 'high' },
    { name: 'Service defection', detection: 'Buyer service elsewhere', window: '90 days', severity: 'medium' },
  ],
  retentionAutomations: [
    { name: 'Test drive follow-up', trigger: '24 hours after test drive', action: 'Send thank you + special offer', expectedImpact: 'Increases conversion by 15%' },
    { name: 'Service reminder', trigger: '6 months or 5K miles after purchase', action: 'Send service reminder', expectedImpact: 'Recalls 40% of service customers' },
    { name: 'Trade-in offer', trigger: '3 years after purchase', action: 'Send trade-in valuation offer', expectedImpact: 'Generates 20% repeat sales' },
    { name: 'Referral bonus', trigger: 'After successful purchase', action: 'Offer referral incentive', expectedImpact: 'Generates 10% new leads' },
  ],
  kpis: [
    { name: 'Revenue', label: 'Revenue', formula: 'Total vehicle + F&I + service revenue', benchmark: '$500K-5M/month', unit: '$', category: 'revenue' },
    { name: 'Units Sold', label: 'Units', formula: 'Vehicles sold this month', benchmark: '50-200/month', unit: 'count', category: 'revenue' },
    { name: 'Gross Profit per Unit', label: 'Gross/Unit', formula: 'Total gross profit / Units sold', benchmark: '$3,000-8,000', unit: '$', category: 'revenue' },
    { name: 'Lead-to-Sale Rate', label: 'Close Rate', formula: 'Sales / Total leads × 100', benchmark: '8-15%', unit: '%', category: 'growth' },
    { name: 'Average Days to Sell', label: 'Days to Sell', formula: 'Average days from intake to sale', benchmark: '30-60 days', unit: 'days', category: 'operations' },
    { name: 'F&I Penetration', label: 'F&I', formula: 'F&I products sold / Vehicles sold × 100', benchmark: '50-80%', unit: '%', category: 'revenue' },
    { name: 'Service Retention Rate', label: 'Service Ret', formula: 'Buyers who service here / Total buyers × 100', benchmark: '40-60%', unit: '%', category: 'retention' },
    { name: 'Customer Satisfaction', label: 'CSI', formula: 'Customer Satisfaction Index score', benchmark: '85-95', unit: 'score', category: 'engagement' },
  ],
  dashboardWidgets: [
    { name: 'Sales Dashboard', type: 'chart', description: 'Unit sales and revenue trends', kpis: ['Revenue', 'Units Sold'], priority: 'primary' },
    { name: 'Inventory Status', type: 'table', description: 'Current inventory with aging and pricing', kpis: ['Average Days to Sell', 'Gross Profit per Unit'], priority: 'primary' },
    { name: 'Lead Pipeline', type: 'chart', description: 'Lead-to-sale conversion funnel', kpis: ['Lead-to-Sale Rate', 'Customer Satisfaction'], priority: 'secondary' },
    { name: 'F&I Performance', type: 'stat-card', description: 'Finance and insurance product metrics', kpis: ['F&I Penetration', 'Service Retention Rate'], priority: 'secondary' },
  ],
  leadCaptureMechanisms: [
    { name: 'Test Drive Booking', headline: 'Book a Test Drive', fields: ['name', 'phone', 'email', 'vehicle_interest', 'preferred_date'], nextStep: 'Sales team confirmation call', conversionRate: '10-15% of visitors' },
    { name: 'Finance Calculator', headline: 'Estimate Your Monthly Payment', fields: ['name', 'email', 'vehicle', 'down_payment'], nextStep: 'Finance team pre-qualification', conversionRate: '15-20% of visitors' },
    { name: 'Trade-In Valuation', headline: 'Get Your Trade-In Value', fields: ['name', 'email', 'vehicle_year', 'vehicle_make', 'mileage'], nextStep: 'Valuation report + dealer contact', conversionRate: '20-25% of visitors' },
  ],
  morningCheck: {
    primaryMetrics: ['Today\'s appointments', 'Inventory aging', 'Pending deals', 'Service appointments'],
    secondaryMetrics: ['Lead response time', 'Staff utilization', 'Marketing ROI', 'Parts inventory'],
    alertConditions: ['Inventory aging >60 days', 'Lead response >1 hour', 'Deal pending >7 days', 'CSI below target'],
  },
  revenueModels: [
    { name: 'New Vehicle Sales', description: 'New vehicle front-end gross', percentage: 40 },
    { name: 'Used Vehicle Sales', description: 'Pre-owned vehicle gross', percentage: 25 },
    { name: 'F&I Products', description: 'Finance and insurance products', percentage: 20 },
    { name: 'Service & Parts', description: 'Service department revenue', percentage: 15 },
  ],
  vocabulary: {
    'customer': 'buyer',
    'product': 'vehicle',
    'buy': 'purchase',
    'store': 'dealership',
    'cart': 'shortlist',
    'checkout': 'delivery',
    'price': 'MSRP',
    'order': 'order',
  },
};
