import type { BusinessIntelligenceProfile } from '../../schemas/knowledge/business-intelligence.schema.js';

export const ECOMMERCE_BI: BusinessIntelligenceProfile = {
  id: 'bi.ecommerce.retail',
  version: '1.0.0',
  name: 'E-Commerce Store',
  description: 'How an e-commerce store makes money: traffic → product view → add to cart → checkout → repeat purchase → referral',
  revenueCycle: {
    name: 'Traffic → Cart → Checkout → Repeat Purchase',
    description: 'Customer discovers product via search/ad → views product → adds to cart → completes checkout → returns for repeat purchase',
    steps: [
      { name: 'Product discovery', action: 'Customer finds product via search/ad/social', conversionRate: 0.10, avgTimeToNext: '0-3 days', revenueImpact: 'high' },
      { name: 'Product view', action: 'Customer views product detail page', conversionRate: 0.35, avgTimeToNext: '0-1 days', revenueImpact: 'high' },
      { name: 'Add to cart', action: 'Customer adds product to cart', conversionRate: 0.12, avgTimeToNext: '0-1 days', revenueImpact: 'critical' },
      { name: 'Checkout started', action: 'Customer begins checkout process', conversionRate: 0.60, avgTimeToNext: '0-1 days', revenueImpact: 'high' },
      { name: 'Order completed', action: 'Payment successful, order placed', conversionRate: 0.65, avgTimeToNext: '0-1 days', revenueImpact: 'critical' },
      { name: 'Repeat purchase', action: 'Customer returns for second order within 90 days', conversionRate: 0.25, avgTimeToNext: '30-90 days', revenueImpact: 'high' },
    ],
    avgCycleLength: '1-3 days',
    avgRevenuePerCustomer: '$50-200 per order',
  },
  conversionFunnel: {
    name: 'Browse → Cart → Purchase → Repeat',
    stages: ['Site Visit', 'Product View', 'Add to Cart', 'Checkout Started', 'Payment Complete', 'Repeat Purchase'],
    overallConversionRate: '1-3% of visitors purchase',
    biggestDropOff: 'Product view → Add to cart (88% bounce)',
  },
  churnSignals: [
    { name: 'No purchase in 60 days', detection: 'Customer hasn\'t ordered in 60 days', window: '60 days', severity: 'medium' },
    { name: 'Cart abandonment', detection: 'Cart left with items for 24+ hours', window: '24 hours', severity: 'high' },
    { name: 'Negative review', detection: 'Customer leaves 1-2 star review', window: '7 days', severity: 'critical' },
    { name: 'Return request', detection: 'Customer initiates return', window: '0 days', severity: 'high' },
    { name: 'Unsubscribe', detection: 'Customer unsubscribes from email list', window: '7 days', severity: 'medium' },
  ],
  retentionAutomations: [
    { name: 'Cart recovery email', trigger: 'Cart abandoned for 4 hours', action: 'Send reminder with product image + 10% off', expectedImpact: 'Recovers 15% of abandoned carts' },
    { name: 'Post-purchase follow-up', trigger: '3 days after delivery', action: 'Request review + recommend related products', expectedImpact: 'Increases repeat rate by 20%' },
    { name: 'Win-back campaign', trigger: 'No purchase in 45 days', action: 'Send personalized product recommendations', expectedImpact: 'Recovers 10% of lapsed customers' },
    { name: 'VIP rewards', trigger: '5+ orders or $500+ spent', action: 'Unlock free shipping + exclusive discounts', expectedImpact: 'Increases LTV by 35%' },
  ],
  kpis: [
    { name: 'Revenue', label: 'Revenue', formula: 'Total sales revenue', benchmark: '$10K-100K/month', unit: '$', category: 'revenue' },
    { name: 'Conversion Rate', label: 'Conv. Rate', formula: 'Orders / Sessions × 100', benchmark: '1-3%', unit: '%', category: 'growth' },
    { name: 'Average Order Value', label: 'AOV', formula: 'Revenue / Orders', benchmark: '$50-150', unit: '$', category: 'revenue' },
    { name: 'Cart Abandonment Rate', label: 'Cart Abandon', formula: 'Abandoned carts / Started checkouts × 100', benchmark: '60-75%', unit: '%', category: 'operations' },
    { name: 'Customer Lifetime Value', label: 'LTV', formula: 'AOV × Purchase frequency × Lifespan', benchmark: '$200-800', unit: '$', category: 'revenue' },
    { name: 'Repeat Purchase Rate', label: 'Repeat', formula: 'Repeat customers / Total customers × 100', benchmark: '20-35%', unit: '%', category: 'retention' },
    { name: 'Return Rate', label: 'Returns', formula: 'Returns / Orders × 100', benchmark: '5-15%', unit: '%', category: 'operations' },
    { name: 'Customer Acquisition Cost', label: 'CAC', formula: 'Marketing spend / New customers', benchmark: '$10-50', unit: '$', category: 'growth' },
  ],
  dashboardWidgets: [
    { name: 'Revenue Dashboard', type: 'chart', description: 'Revenue trend with daily/weekly/monthly views', kpis: ['Revenue'], priority: 'primary' },
    { name: 'Conversion Funnel', type: 'chart', description: 'Browse → Cart → Checkout → Purchase funnel', kpis: ['Conversion Rate', 'Cart Abandonment Rate'], priority: 'primary' },
    { name: 'Top Products', type: 'table', description: 'Best-selling products by revenue and quantity', kpis: ['Revenue', 'Average Order Value'], priority: 'secondary' },
    { name: 'Customer Metrics', type: 'stat-card', description: 'LTV, CAC, and repeat purchase rates', kpis: ['Customer Lifetime Value', 'Customer Acquisition Cost'], priority: 'secondary' },
    { name: 'Inventory Status', type: 'table', description: 'Stock levels and low inventory alerts', kpis: ['Return Rate'], priority: 'secondary' },
  ],
  leadCaptureMechanisms: [
    { name: 'First Purchase Offer', headline: 'Get 15% Off Your First Order', fields: ['email'], nextStep: 'Welcome email with discount code', conversionRate: '10-20% of visitors' },
    { name: 'Newsletter Signup', headline: 'Stay in the Loop', fields: ['email'], nextStep: 'Nurture sequence with product highlights', conversionRate: '15-25% of visitors' },
    { name: 'Abandoned Cart Recovery', headline: 'Complete Your Order', fields: [], nextStep: 'Cart reminder email sequence', conversionRate: '30-40% of abandoners' },
  ],
  morningCheck: {
    primaryMetrics: ['Revenue today', 'Orders today', 'Conversion rate', 'Cart abandonment rate'],
    secondaryMetrics: ['Top selling products', 'Inventory alerts', 'Customer reviews', 'Marketing ROI'],
    alertConditions: ['Revenue dropped >20% vs yesterday', 'Conversion rate <0.5%', 'Low stock alerts', 'Negative review posted'],
  },
  revenueModels: [
    { name: 'Direct Sales', description: 'Product sales revenue', percentage: 75 },
    { name: 'Shipping Fees', description: 'Shipping and handling charges', percentage: 10 },
    { name: 'Affiliate Commissions', description: 'Revenue from affiliate referrals', percentage: 8 },
    { name: 'Gift Cards', description: 'Gift card sales and redemption', percentage: 7 },
  ],
  vocabulary: {
    'customer': 'shopper',
    'product': 'item',
    'buy': 'purchase',
    'store': 'shop',
    'cart': 'cart',
    'checkout': 'checkout',
    'price': 'price',
    'order': 'order',
  },
};
