import type { BusinessIntelligenceProfile } from '../../schemas/knowledge/business-intelligence.schema.js';

export const ENTERPRISE_SOFTWARE_BI: BusinessIntelligenceProfile = {
  id: 'bi.enterprise.software',
  version: '1.0.0',
  name: 'Enterprise Software (ERP/CRM/HRM)',
  description: 'How enterprise software makes money: lead → demo → pilot → procurement → implementation → adoption → expansion',
  revenueCycle: {
    name: 'Lead → Demo → Pilot → Procurement → Implementation → Expansion',
    description: 'Prospect finds solution → requests demo → runs pilot → procurement approves → implementation → user adoption → license expansion',
    steps: [
      { name: 'Lead generation', action: 'Prospect finds solution via search/referral/ad', conversionRate: 0.03, avgTimeToNext: '1-30 days', revenueImpact: 'high' },
      { name: 'Demo requested', action: 'Prospect requests product demonstration', conversionRate: 0.25, avgTimeToNext: '1-7 days', revenueImpact: 'critical' },
      { name: 'Pilot started', action: 'Prospect begins free pilot/trial', conversionRate: 0.40, avgTimeToNext: '7-14 days', revenueImpact: 'high' },
      { name: 'Procurement approved', action: 'Budget and procurement approved', conversionRate: 0.30, avgTimeToNext: '14-60 days', revenueImpact: 'critical' },
      { name: 'Implementation complete', action: 'Software deployed and configured', conversionRate: 0.85, avgTimeToNext: '30-90 days', revenueImpact: 'high' },
      { name: 'User adoption', action: '70%+ of target users active', conversionRate: 0.70, avgTimeToNext: '30-60 days', revenueImpact: 'critical' },
      { name: 'License expansion', action: 'Customer adds modules/users', conversionRate: 0.20, avgTimeToNext: '90-365 days', revenueImpact: 'high' },
    ],
    avgCycleLength: '60-180 days',
    avgRevenuePerCustomer: '$10,000-100,000/year',
  },
  conversionFunnel: {
    name: 'Lead → Demo → Pilot → Purchase → Expansion',
    stages: ['Website Visit', 'Demo Request', 'Pilot Start', 'Procurement', 'Implementation', 'Adoption', 'Expansion'],
    overallConversionRate: '1-3% of leads become customers',
    biggestDropOff: 'Pilot → Procurement (70% don\'t purchase)',
  },
  churnSignals: [
    { name: 'Low user adoption', detection: '<30% of licensed users active after 90 days', window: '90 days', severity: 'critical' },
    { name: 'Support ticket spike', detection: '5+ critical support tickets in 30 days', window: '30 days', severity: 'high' },
    { name: 'Contract non-renewal', detection: 'Customer doesn\'t renew at contract end', window: '90 days', severity: 'critical' },
    { name: 'Feature request gap', detection: 'Customer requests features not in roadmap', window: '30 days', severity: 'medium' },
    { name: 'Budget cuts', detection: 'Customer mentions budget reductions', window: '30 days', severity: 'high' },
  ],
  retentionAutomations: [
    { name: 'Onboarding check-in', trigger: 'Weekly during first 3 months', action: 'CSM check-in with usage metrics', expectedImpact: 'Increases adoption by 25%' },
    { name: 'Feature adoption nudge', trigger: 'User hasn\'t tried key feature', action: 'In-app tutorial + email', expectedImpact: 'Increases feature usage by 20%' },
    { name: 'Quarterly business review', trigger: 'Every 3 months', action: 'Review ROI and expansion opportunities', expectedImpact: 'Generates 30% expansion revenue' },
    { name: 'Renewal prep', trigger: '90 days before renewal', action: 'CSM renewal conversation + ROI report', expectedImpact: 'Increases renewal rate by 15%' },
  ],
  kpis: [
    { name: 'Revenue', label: 'ARR', formula: 'Annual recurring revenue', benchmark: '$1M-50M', unit: '$', category: 'revenue' },
    { name: 'Customers', label: 'Customers', formula: 'Total active customers', benchmark: '100-1,000', unit: 'count', category: 'growth' },
    { name: 'Net Revenue Retention', label: 'NRR', formula: '(Starting ARR + Expansion - Contraction - Churn) / Starting ARR', benchmark: '100-130%', unit: '%', category: 'revenue' },
    { name: 'User Adoption Rate', label: 'Adoption', formula: 'Active users / Licensed users × 100', benchmark: '60-80%', unit: '%', category: 'engagement' },
    { name: 'Customer Acquisition Cost', label: 'CAC', formula: 'Sales + Marketing spend / New customers', benchmark: '$5,000-30,000', unit: '$', category: 'growth' },
    { name: 'CAC Payback Period', label: 'CAC Payback', formula: 'CAC / (ARR per customer / 12)', benchmark: '12-18 months', unit: 'months', category: 'growth' },
    { name: 'Gross Margin', label: 'Gross Margin', formula: '(Revenue - COGS) / Revenue × 100', benchmark: '70-85%', unit: '%', category: 'operations' },
    { name: 'Implementation Time', label: 'Impl. Time', formula: 'Average days from contract to go-live', benchmark: '30-90 days', unit: 'days', category: 'operations' },
  ],
  dashboardWidgets: [
    { name: 'ARR Dashboard', type: 'chart', description: 'ARR growth with churn and expansion breakdown', kpis: ['Revenue', 'Net Revenue Retention'], priority: 'primary' },
    { name: 'Customer Health', type: 'table', description: 'Customer adoption and health scores', kpis: ['User Adoption Rate', 'Customers'], priority: 'primary' },
    { name: 'Sales Pipeline', type: 'chart', description: 'Lead-to-close conversion funnel', kpis: ['Customer Acquisition Cost', 'CAC Payback Period'], priority: 'secondary' },
    { name: 'Operations Metrics', type: 'stat-card', description: 'Implementation and support metrics', kpis: ['Implementation Time', 'Gross Margin'], priority: 'secondary' },
  ],
  leadCaptureMechanisms: [
    { name: 'Request Demo', headline: 'See [Product] in Action', fields: ['name', 'email', 'company', 'role', 'team_size'], nextStep: 'Sales demo scheduling', conversionRate: '5-10% of visitors' },
    { name: 'Free Trial', headline: 'Start Free Pilot', fields: ['name', 'email', 'company'], nextStep: 'Self-service trial setup', conversionRate: '8-12% of visitors' },
    { name: 'Case Study', headline: 'See How [Customer] Succeeded', fields: ['name', 'email', 'company'], nextStep: 'Case study delivery + follow-up', conversionRate: '15-20% of visitors' },
  ],
  morningCheck: {
    primaryMetrics: ['ARR', 'Pipeline value', 'Customer health scores', 'Support tickets'],
    secondaryMetrics: ['User adoption rates', 'Churn risk accounts', 'Implementation progress', 'Feature usage'],
    alertConditions: ['Churn risk account detected', 'Implementation overdue', 'Support SLA breach', 'Pipeline slippage'],
  },
  revenueModels: [
    { name: 'Subscription Licenses', description: 'Annual/monthly subscription fees', percentage: 70 },
    { name: 'Implementation', description: 'Setup and configuration services', percentage: 15 },
    { name: 'Professional Services', description: 'Custom development and consulting', percentage: 10 },
    { name: 'Training', description: 'User training and certification', percentage: 5 },
  ],
  vocabulary: {
    'customer': 'enterprise',
    'product': 'platform',
    'buy': 'deploy',
    'store': 'solution',
    'cart': 'procurement',
    'checkout': 'contract',
    'price': 'license',
    'order': 'purchase order',
  },
};
