import type { BusinessIntelligenceProfile } from '../../schemas/knowledge/business-intelligence.schema.js';

export const EVENT_BI: BusinessIntelligenceProfile = {
  id: 'bi.event.venue',
  version: '1.0.0',
  name: 'Event Venue / Organizer',
  description: 'How an event business makes money: discovery → inquiry → booking → event → feedback → rebooking → referral',
  revenueCycle: {
    name: 'Discovery → Inquiry → Booking → Event → Rebooking',
    description: 'Host discovers venue → sends inquiry → books venue → hosts event → gets feedback → rebooks or refers',
    steps: [
      { name: 'Discovery', action: 'Host finds venue via search/social/referral', conversionRate: 0.05, avgTimeToNext: '1-30 days', revenueImpact: 'high' },
      { name: 'Inquiry', action: 'Host sends inquiry or tours venue', conversionRate: 0.25, avgTimeToNext: '1-7 days', revenueImpact: 'critical' },
      { name: 'Booking', action: 'Host signs contract and pays deposit', conversionRate: 0.40, avgTimeToNext: '3-14 days', revenueImpact: 'critical' },
      { name: 'Event held', action: 'Event takes place successfully', conversionRate: 0.95, avgTimeToNext: '30-180 days', revenueImpact: 'high' },
      { name: 'Final payment', action: 'Host pays final balance', conversionRate: 0.90, avgTimeToNext: '7-30 days', revenueImpact: 'critical' },
      { name: 'Rebooking', action: 'Host books another event', conversionRate: 0.20, avgTimeToNext: '90-365 days', revenueImpact: 'high' },
      { name: 'Referral', action: 'Host refers other event planners', conversionRate: 0.25, avgTimeToNext: '30-365 days', revenueImpact: 'medium' },
    ],
    avgCycleLength: '30-180 days',
    avgRevenuePerCustomer: '$2,000-20,000 per event',
  },
  conversionFunnel: {
    name: 'Discovery → Inquiry → Booking → Event',
    stages: ['Website Visit', 'Venue View', 'Inquiry', 'Tour', 'Proposal', 'Booking', 'Event', 'Referral'],
    overallConversionRate: '3-5% of visitors book',
    biggestDropOff: 'Inquiry → Booking (60% don\'t book)',
  },
  churnSignals: [
    { name: 'Inquiry not converted', detection: 'Inquiry received but no booking in 30 days', window: '30 days', severity: 'high' },
    { name: 'Event cancelled', detection: 'Host cancels booking', window: '0 days', severity: 'critical' },
    { name: 'No rebooking', detection: 'Client hasn\'t booked in 2+ years', window: '730 days', severity: 'medium' },
    { name: 'Negative feedback', detection: 'Host leaves negative review', window: '7 days', severity: 'critical' },
    { name: 'Price sensitivity', detection: 'Host requests significant discount', window: '7 days', severity: 'medium' },
  ],
  retentionAutomations: [
    { name: 'Post-event follow-up', trigger: '7 days after event', action: 'Send thank you + feedback survey', expectedImpact: 'Increases referrals by 30%' },
    { name: 'Anniversary reminder', trigger: '1 year since event', action: 'Send anniversary message + rebooking offer', expectedImpact: 'Generates 15% rebookings' },
    { name: 'Seasonal promotion', trigger: 'Off-peak season', action: 'Send early booking discounts', expectedImpact: 'Increases off-peak bookings by 20%' },
    { name: 'Referral incentive', trigger: 'After successful event', action: 'Offer referral credit', expectedImpact: 'Generates 20% new leads from referrals' },
  ],
  kpis: [
    { name: 'Revenue', label: 'Revenue', formula: 'Total event bookings revenue', benchmark: '$20K-200K/month', unit: '$', category: 'revenue' },
    { name: 'Events Booked', label: 'Events', formula: 'Total events booked this month', benchmark: '10-40/month', unit: 'count', category: 'revenue' },
    { name: 'Average Event Value', label: 'Avg Event', formula: 'Total revenue / Total events', benchmark: '$3,000-15,000', unit: '$', category: 'revenue' },
    { name: 'Inquiry-to-Booking Rate', label: 'Close Rate', formula: 'Bookings / Inquiries × 100', benchmark: '25-40%', unit: '%', category: 'growth' },
    { name: 'Client Retention Rate', label: 'Retention', formula: 'Returning clients / Total clients × 100', benchmark: '20-35%', unit: '%', category: 'retention' },
    { name: 'Venue Utilization', label: 'Utilization', formula: 'Booked days / Available days × 100', benchmark: '40-60%', unit: '%', category: 'operations' },
    { name: 'Client Satisfaction', label: 'NPS', formula: 'Net Promoter Score', benchmark: '60-80', unit: 'score', category: 'engagement' },
    { name: 'Referral Rate', label: 'Referrals', formula: 'Referral bookings / Total bookings × 100', benchmark: '15-30%', unit: '%', category: 'growth' },
  ],
  dashboardWidgets: [
    { name: 'Revenue Dashboard', type: 'chart', description: 'Booking revenue and seasonal trends', kpis: ['Revenue', 'Average Event Value'], priority: 'primary' },
    { name: 'Booking Calendar', type: 'table', description: 'Upcoming events with details and status', kpis: ['Events Booked', 'Venue Utilization'], priority: 'primary' },
    { name: 'Lead Pipeline', type: 'chart', description: 'Inquiry-to-booking conversion funnel', kpis: ['Inquiry-to-Booking Rate', 'Client Satisfaction'], priority: 'secondary' },
    { name: 'Client Metrics', type: 'stat-card', description: 'Retention and referral rates', kpis: ['Client Retention Rate', 'Referral Rate'], priority: 'secondary' },
  ],
  leadCaptureMechanisms: [
    { name: 'Venue Tour Request', headline: 'Schedule a Tour', fields: ['name', 'email', 'phone', 'event_type', 'event_date'], nextStep: 'Tour scheduling + follow-up', conversionRate: '10-15% of visitors' },
    { name: 'Event Inquiry', headline: 'Plan Your Event', fields: ['name', 'email', 'phone', 'event_type', 'guest_count', 'budget'], nextStep: 'Custom proposal', conversionRate: '8-12% of visitors' },
    { name: 'Newsletter', headline: 'Event Planning Tips', fields: ['email'], nextStep: 'Nurture sequence', conversionRate: '15-25% of visitors' },
  ],
  morningCheck: {
    primaryMetrics: ['Upcoming events', 'Pending inquiries', 'Revenue this month', 'Venue availability'],
    secondaryMetrics: ['Staff assignments', 'Catering orders', 'Equipment status', 'Client communications'],
    alertConditions: ['Event in 48 hours + issue', 'Inquiry >7 days old', 'Venue double-booked', 'Client complaint'],
  },
  revenueModels: [
    { name: 'Venue Rental', description: 'Venue hire fees', percentage: 50 },
    { name: 'Catering', description: 'Food and beverage services', percentage: 25 },
    { name: 'Add-ons', description: 'AV, decor, coordination services', percentage: 15 },
    { name: 'Packages', description: 'All-inclusive event packages', percentage: 10 },
  ],
  vocabulary: {
    'customer': 'host',
    'product': 'event',
    'buy': 'book',
    'store': 'venue',
    'cart': 'proposal',
    'checkout': 'contract',
    'price': 'quote',
    'order': 'booking',
  },
};
