import type { BusinessIntelligenceProfile } from '../../schemas/knowledge/business-intelligence.schema.js';

export const FINTECH_BI: BusinessIntelligenceProfile = {
  id: 'bi.fintech.neobank',
  version: '1.0.0',
  name: 'Fintech / Neobank',
  description: 'How a fintech business makes money: signup → KYC → account funded → transactions → interchange fees → premium upgrades',
  revenueCycle: {
    name: 'Signup → KYC → Funded Account → Transactions → Premium',
    description: 'User downloads app → completes KYC → funds account → starts transacting → hits limits → upgrades to premium',
    steps: [
      { name: 'App download', action: 'User downloads app from store', conversionRate: 0.15, avgTimeToNext: '0-1 days', revenueImpact: 'high' },
      { name: 'KYC completed', action: 'User completes identity verification', conversionRate: 0.60, avgTimeToNext: '0-2 days', revenueImpact: 'critical' },
      { name: 'Account funded', action: 'User adds money to account', conversionRate: 0.50, avgTimeToNext: '1-3 days', revenueImpact: 'critical' },
      { name: 'First transaction', action: 'User makes first card payment', conversionRate: 0.70, avgTimeToNext: '1-7 days', revenueImpact: 'high' },
      { name: 'Regular usage', action: 'User transacts 5+ times per month', conversionRate: 0.40, avgTimeToNext: '14-30 days', revenueImpact: 'high' },
      { name: 'Premium upgrade', action: 'User upgrades to premium plan', conversionRate: 0.08, avgTimeToNext: '30-90 days', revenueImpact: 'medium' },
    ],
    avgCycleLength: '7-30 days',
    avgRevenuePerCustomer: '$5-50/month',
  },
  conversionFunnel: {
    name: 'Download → KYC → Funded → Active → Premium',
    stages: ['App Download', 'KYC Started', 'KYC Complete', 'Account Funded', 'First Transaction', 'Regular Usage', 'Premium Upgrade'],
    overallConversionRate: '15-25% of downloads become active users',
    biggestDropOff: 'KYC started → KYC complete (40% abandon)',
  },
  churnSignals: [
    { name: 'Account dormant', detection: 'No transactions in 30+ days', window: '30 days', severity: 'high' },
    { name: 'Low balance', detection: 'Account balance <minimum for 14 days', window: '14 days', severity: 'medium' },
    { name: 'Card not activated', detection: 'Card issued but not activated in 14 days', window: '14 days', severity: 'high' },
    { name: 'Negative balance', detection: 'Account goes negative', window: '0 days', severity: 'critical' },
    { name: 'Support complaint', detection: 'User files support ticket about issues', window: '7 days', severity: 'medium' },
  ],
  retentionAutomations: [
    { name: 'KYC completion nudge', trigger: 'KYC started but not completed in 48 hours', action: 'Send SMS reminder + support link', expectedImpact: 'Recovers 30% of abandoned KYC' },
    { name: 'Funding reminder', trigger: 'Account created but not funded in 7 days', action: 'Send push notification with funding incentives', expectedImpact: 'Increases funding rate by 20%' },
    { name: 'Usage milestone', trigger: '10th transaction completed', action: 'Congratulate + introduce premium features', expectedImpact: 'Increases premium conversion by 15%' },
    { name: 'Win-back offer', trigger: 'No transactions for 21 days', action: 'Send cashback offer for next 5 transactions', expectedImpact: 'Recovers 25% of dormant users' },
  ],
  kpis: [
    { name: 'Revenue', label: 'Revenue', formula: 'Total interchange + subscription fees', benchmark: '$50K-500K/month', unit: '$', category: 'revenue' },
    { name: 'Active Users', label: 'Active', formula: 'Users with 1+ transactions this month', benchmark: '50K-500K', unit: 'count', category: 'engagement' },
    { name: 'KYC Completion Rate', label: 'KYC Rate', formula: 'KYC completed / KYC started × 100', benchmark: '50-70%', unit: '%', category: 'operations' },
    { name: 'Funding Rate', label: 'Funding', formula: 'Funded accounts / Total accounts × 100', benchmark: '40-60%', unit: '%', category: 'growth' },
    { name: 'Monthly Transactions', label: 'Txns', formula: 'Total transactions this month', benchmark: '100K-1M', unit: 'count', category: 'engagement' },
    { name: 'Average Revenue Per User', label: 'ARPU', formula: 'Total revenue / Active users', benchmark: '$2-15/month', unit: '$', category: 'revenue' },
    { name: 'Customer Acquisition Cost', label: 'CAC', formula: 'Marketing spend / New users', benchmark: '$5-30', unit: '$', category: 'growth' },
    { name: 'Premium Conversion Rate', label: 'Premium', formula: 'Premium users / Total users × 100', benchmark: '5-15%', unit: '%', category: 'revenue' },
  ],
  dashboardWidgets: [
    { name: 'Revenue Dashboard', type: 'chart', description: 'Interchange and subscription revenue trends', kpis: ['Revenue', 'Average Revenue Per User'], priority: 'primary' },
    { name: 'User Funnel', type: 'chart', description: 'Download → KYC → Funded → Active funnel', kpis: ['KYC Completion Rate', 'Funding Rate'], priority: 'primary' },
    { name: 'Transaction Metrics', type: 'stat-card', description: 'Daily/monthly transaction volumes', kpis: ['Monthly Transactions', 'Active Users'], priority: 'secondary' },
    { name: 'Growth Metrics', type: 'chart', description: 'User acquisition and premium conversion', kpis: ['Customer Acquisition Cost', 'Premium Conversion Rate'], priority: 'secondary' },
  ],
  leadCaptureMechanisms: [
    { name: 'App Download', headline: 'Download the App', fields: ['phone number'], nextStep: 'App download link via SMS', conversionRate: '15-25% of visitors' },
    { name: 'Referral Program', headline: 'Refer & Earn $10', fields: ['name', 'email', 'phone'], nextStep: 'Referral code generation', conversionRate: '10-15% of visitors' },
    { name: 'Newsletter', headline: 'Financial Tips & Updates', fields: ['email'], nextStep: 'Nurture sequence', conversionRate: '20-30% of visitors' },
  ],
  morningCheck: {
    primaryMetrics: ['Transaction volume', 'Active users', 'KYC completions', 'Revenue so far'],
    secondaryMetrics: ['Fraud alerts', 'Support tickets', 'App crashes', 'Partner integrations'],
    alertConditions: ['Transaction volume drop >20%', 'Fraud spike', 'App downtime', 'KYC backlog >100'],
  },
  revenueModels: [
    { name: 'Interchange Fees', description: 'Transaction interchange revenue', percentage: 55 },
    { name: 'Subscription Fees', description: 'Premium plan monthly fees', percentage: 20 },
    { name: 'ATM Fees', description: 'Out-of-network ATM fees', percentage: 10 },
    { name: 'Late Fees', description: 'Overdraft and late payment fees', percentage: 10 },
    { name: 'Interest Income', description: 'Interest on float/balances', percentage: 5 },
  ],
  vocabulary: {
    'customer': 'user',
    'product': 'account',
    'buy': 'transact',
    'store': 'app',
    'cart': 'wallet',
    'checkout': 'payment',
    'price': 'fee',
    'order': 'transaction',
  },
};
