import type { BusinessIntelligenceProfile } from '../../schemas/knowledge/business-intelligence.schema.js';

export const LEGAL_BI: BusinessIntelligenceProfile = {
  id: 'bi.legal.lawfirm',
  version: '1.0.0',
  name: 'Law Firm',
  description: 'How a law firm makes money: lead → consultation → case acceptance → billable hours → case resolution → referral',
  revenueCycle: {
    name: 'Lead → Consultation → Case → Billable Hours → Resolution',
    description: 'Prospective client finds firm → books consultation → accepts engagement → attorney bills hours → case resolved → referral',
    steps: [
      { name: 'Lead generation', action: 'Prospect finds firm via referral/search/ad', conversionRate: 0.08, avgTimeToNext: '1-7 days', revenueImpact: 'high' },
      { name: 'Consultation booked', action: 'Prospect schedules initial consultation', conversionRate: 0.25, avgTimeToNext: '1-5 days', revenueImpact: 'critical' },
      { name: 'Case accepted', action: 'Client signs engagement letter', conversionRate: 0.55, avgTimeToNext: '1-7 days', revenueImpact: 'critical' },
      { name: 'Billable hours logged', action: 'Attorney completes billable work', conversionRate: 0.90, avgTimeToNext: '1-90 days', revenueImpact: 'high' },
      { name: 'Invoice sent', action: 'Monthly invoice sent to client', conversionRate: 0.85, avgTimeToNext: '30 days', revenueImpact: 'high' },
      { name: 'Payment received', action: 'Client pays invoice within terms', conversionRate: 0.90, avgTimeToNext: '30-60 days', revenueImpact: 'critical' },
      { name: 'Referral made', action: 'Client refers another prospect', conversionRate: 0.12, avgTimeToNext: '30-365 days', revenueImpact: 'medium' },
    ],
    avgCycleLength: '30-180 days',
    avgRevenuePerCustomer: '$2,000-20,000 per case',
  },
  conversionFunnel: {
    name: 'Lead → Consultation → Engagement → Resolution',
    stages: ['Website Visit', 'Contact Form', 'Consultation', 'Engagement Letter', 'Active Case', 'Invoice Paid', 'Referral'],
    overallConversionRate: '3-5% of website visitors become clients',
    biggestDropOff: 'Consultation → Engagement (45% don\'t sign)',
  },
  churnSignals: [
    { name: 'Slow invoice payment', detection: 'Invoice unpaid for 60+ days', window: '60 days', severity: 'high' },
    { name: 'Client dissatisfaction', detection: 'Negative feedback during check-in', window: '14 days', severity: 'critical' },
    { name: 'Scope creep complaint', detection: 'Client questions billing for additional work', window: '7 days', severity: 'medium' },
    { name: 'Case resolution delay', detection: 'Case taking longer than estimated', window: '30 days', severity: 'medium' },
    { name: 'Competitor switch', detection: 'Client mentions alternative firms', window: '30 days', severity: 'high' },
  ],
  retentionAutomations: [
    { name: 'Case status update', trigger: 'Bi-weekly during active case', action: 'Send case status update email', expectedImpact: 'Improves client satisfaction by 30%' },
    { name: 'Invoice reminder', trigger: '7 days before payment due', action: 'Send payment reminder', expectedImpact: 'Reduces late payments by 25%' },
    { name: 'Anniversary check-in', trigger: '1 year since case resolution', action: 'Send check-in + offer for new matters', expectedImpact: 'Generates 15% repeat business' },
    { name: 'Referral request', trigger: 'After successful case resolution', action: 'Ask for referral + testimonial', expectedImpact: 'Generates 20% new leads from referrals' },
  ],
  kpis: [
    { name: 'Revenue', label: 'Revenue', formula: 'Total billings', benchmark: '$50K-500K/month', unit: '$', category: 'revenue' },
    { name: 'Billable Hours', label: 'Bill Hours', formula: 'Hours billed this month', benchmark: '120-180/month/attorney', unit: 'hours', category: 'operations' },
    { name: 'Utilization Rate', label: 'Utilization', formula: 'Billable hours / Available hours × 100', benchmark: '65-80%', unit: '%', category: 'operations' },
    { name: 'Realization Rate', label: 'Realization', formula: 'Collected / Billed × 100', benchmark: '85-95%', unit: '%', category: 'revenue' },
    { name: 'Client Acquisition Cost', label: 'CAC', formula: 'Marketing spend / New clients', benchmark: '$500-2,000', unit: '$', category: 'growth' },
    { name: 'Client Retention Rate', label: 'Retention', formula: 'Returning clients / Total clients × 100', benchmark: '60-80%', unit: '%', category: 'retention' },
    { name: 'Avg Revenue per Client', label: 'Rev/Client', formula: 'Total revenue / Total clients', benchmark: '$3,000-15,000', unit: '$', category: 'revenue' },
    { name: 'Matter Pipeline Value', label: 'Pipeline', formula: 'Sum of potential case values', benchmark: '3-6 months revenue', unit: '$', category: 'growth' },
  ],
  dashboardWidgets: [
    { name: 'Revenue Dashboard', type: 'chart', description: 'Billing and collection trends', kpis: ['Revenue', 'Realization Rate'], priority: 'primary' },
    { name: 'Active Matters', type: 'table', description: 'Active cases with status and billing', kpis: ['Billable Hours', 'Utilization Rate'], priority: 'primary' },
    { name: 'Client Metrics', type: 'stat-card', description: 'Retention, acquisition, and pipeline', kpis: ['Client Retention Rate', 'Matter Pipeline Value'], priority: 'secondary' },
    { name: 'AR Aging', type: 'chart', description: 'Accounts receivable aging report', kpis: ['Realization Rate'], priority: 'secondary' },
  ],
  leadCaptureMechanisms: [
    { name: 'Free Consultation', headline: 'Free Case Evaluation', fields: ['name', 'phone', 'email', 'case_type'], nextStep: 'Attorney callback within 24 hours', conversionRate: '10-15% of visitors' },
    { name: 'Contact Form', headline: 'Schedule a Consultation', fields: ['name', 'email', 'phone', 'description'], nextStep: 'Intake team contact', conversionRate: '8-12% of visitors' },
    { name: 'Newsletter', headline: 'Legal Insights & Updates', fields: ['email'], nextStep: 'Nurture sequence', conversionRate: '20-30% of visitors' },
  ],
  morningCheck: {
    primaryMetrics: ['Today\'s billable hours', 'Pending invoices', 'Active matters', 'Upcoming deadlines'],
    secondaryMetrics: ['Client communications', 'Court appearances', 'Document deadlines', 'Trust account balance'],
    alertConditions: ['Billable hours below target', 'AR >60 days', 'Deadline missed', 'Trust account discrepancy'],
  },
  revenueModels: [
    { name: 'Hourly Billing', description: 'Hourly attorney fees', percentage: 55 },
    { name: 'Flat Fee', description: 'Fixed-fee engagements', percentage: 25 },
    { name: 'Contingency', description: 'Percentage of settlement/award', percentage: 15 },
    { name: 'Retainer', description: 'Monthly retainer agreements', percentage: 5 },
  ],
  vocabulary: {
    'customer': 'client',
    'product': 'service',
    'buy': 'engage',
    'store': 'firm',
    'cart': 'engagement letter',
    'checkout': 'retainer',
    'price': 'fee',
    'order': 'matter',
  },
};
