import type { BusinessIntelligenceProfile } from '../../schemas/knowledge/business-intelligence.schema.js';

export const LOGISTICS_BI: BusinessIntelligenceProfile = {
  id: 'bi.logistics.shipping',
  version: '1.0.0',
  name: 'Logistics / Shipping',
  description: 'How a logistics business makes money: inquiry → quote → booking → pickup → transit → delivery → invoicing',
  revenueCycle: {
    name: 'Inquiry → Quote → Booking → Transit → Delivery → Invoice',
    description: 'Shipper inquires → receives quote → books shipment → pickup → transit → delivery → invoice paid',
    steps: [
      { name: 'Inquiry', action: 'Shipper requests shipping quote', conversionRate: 0.15, avgTimeToNext: '0-1 days', revenueImpact: 'high' },
      { name: 'Quote sent', action: 'Logistics company sends quote', conversionRate: 0.60, avgTimeToNext: '0-1 days', revenueImpact: 'critical' },
      { name: 'Booking confirmed', action: 'Shipper confirms and books', conversionRate: 0.55, avgTimeToNext: '0-3 days', revenueImpact: 'high' },
      { name: 'Pickup completed', action: 'Cargo picked up from origin', conversionRate: 0.95, avgTimeToNext: '1-3 days', revenueImpact: 'critical' },
      { name: 'Delivery completed', action: 'Cargo delivered to destination', conversionRate: 0.98, avgTimeToNext: '1-30 days', revenueImpact: 'high' },
      { name: 'Invoice paid', action: 'Shipper pays invoice', conversionRate: 0.85, avgTimeToNext: '30-60 days', revenueImpact: 'critical' },
      { name: 'Repeat booking', action: 'Shipper books another shipment', conversionRate: 0.35, avgTimeToNext: '30-180 days', revenueImpact: 'high' },
    ],
    avgCycleLength: '1-30 days',
    avgRevenuePerCustomer: '$200-5,000 per shipment',
  },
  conversionFunnel: {
    name: 'Inquiry → Quote → Booking → Delivery',
    stages: ['Website Visit', 'Quote Request', 'Quote Sent', 'Booking', 'Pickup', 'Delivery', 'Payment'],
    overallConversionRate: '10-20% of inquiries become bookings',
    biggestDropOff: 'Quote sent → Booking (45% don\'t book)',
  },
  churnSignals: [
    { name: 'Quote not accepted', detection: 'Quote sent but no booking in 7 days', window: '7 days', severity: 'high' },
    { name: 'Delivery issue', detection: 'Delivery delay or damage reported', window: '0 days', severity: 'critical' },
    { name: 'Invoice dispute', detection: 'Shipper disputes invoice amount', window: '7 days', severity: 'high' },
    { name: 'No repeat booking', detection: 'Shipper hasn\'t booked in 6 months', window: '180 days', severity: 'medium' },
    { name: 'Price complaint', detection: 'Shipper says rates too high', window: '7 days', severity: 'medium' },
  ],
  retentionAutomations: [
    { name: 'Quote follow-up', trigger: '24 hours after quote sent', action: 'Follow up on quote status', expectedImpact: 'Increases conversion by 15%' },
    { name: 'Delivery confirmation', trigger: '24 hours after delivery', action: 'Send delivery confirmation + invoice', expectedImpact: 'Reduces payment delays by 20%' },
    { name: 'Reorder reminder', trigger: '30 days since last shipment', action: 'Send shipping needs reminder', expectedImpact: 'Generates 15% repeat bookings' },
    { name: 'Volume discount offer', trigger: '10+ shipments per month', action: 'Offer volume discount', expectedImpact: 'Increases volume by 25%' },
  ],
  kpis: [
    { name: 'Revenue', label: 'Revenue', formula: 'Total shipping revenue', benchmark: '$50K-500K/month', unit: '$', category: 'revenue' },
    { name: 'Shipments', label: 'Shipments', formula: 'Total shipments this month', benchmark: '500-5,000/month', unit: 'count', category: 'operations' },
    { name: 'On-Time Delivery Rate', label: 'OTD', formula: 'On-time deliveries / Total deliveries × 100', benchmark: '95-99%', unit: '%', category: 'operations' },
    { name: 'Quote-to-Booking Rate', label: 'Close Rate', formula: 'Bookings / Quotes sent × 100', benchmark: '30-50%', unit: '%', category: 'growth' },
    { name: 'Revenue per Shipment', label: 'Rev/Ship', formula: 'Total revenue / Total shipments', benchmark: '$100-500', unit: '$', category: 'revenue' },
    { name: 'Damage Rate', label: 'Damage', formula: 'Damaged shipments / Total shipments × 100', benchmark: '<1%', unit: '%', category: 'operations' },
    { name: 'Customer Retention Rate', label: 'Retention', formula: 'Returning shippers / Total shippers × 100', benchmark: '50-70%', unit: '%', category: 'retention' },
    { name: 'Fleet Utilization', label: 'Fleet Util.', formula: 'Active vehicles / Total fleet × 100', benchmark: '75-90%', unit: '%', category: 'operations' },
  ],
  dashboardWidgets: [
    { name: 'Revenue Dashboard', type: 'chart', description: 'Shipping revenue and volume trends', kpis: ['Revenue', 'Shipments'], priority: 'primary' },
    { name: 'Shipment Tracker', type: 'table', description: 'Active shipments with real-time status', kpis: ['On-Time Delivery Rate', 'Fleet Utilization'], priority: 'primary' },
    { name: 'Performance Metrics', type: 'stat-card', description: 'Delivery and quality metrics', kpis: ['Damage Rate', 'Revenue per Shipment'], priority: 'secondary' },
    { name: 'Customer Pipeline', type: 'chart', description: 'Quote-to-booking conversion funnel', kpis: ['Quote-to-Booking Rate', 'Customer Retention Rate'], priority: 'secondary' },
  ],
  leadCaptureMechanisms: [
    { name: 'Get a Quote', headline: 'Get Instant Shipping Quote', fields: ['origin', 'destination', 'weight', 'dimensions', 'email'], nextStep: 'Instant quote + follow-up', conversionRate: '15-20% of visitors' },
    { name: 'Account Setup', headline: 'Open a Shipping Account', fields: ['company', 'name', 'email', 'phone', 'monthly_volume'], nextStep: 'Account setup + onboarding', conversionRate: '8-12% of visitors' },
    { name: 'Track Shipment', headline: 'Track Your Shipment', fields: ['tracking_number'], nextStep: 'Shipment status display', conversionRate: '20-30% of visitors' },
  ],
  morningCheck: {
    primaryMetrics: ['Shipments in transit', 'Today\'s pickups/deliveries', 'Pending quotes', 'Revenue so far'],
    secondaryMetrics: ['Fleet status', 'Driver availability', 'Customs clearance', 'Weather delays'],
    alertConditions: ['Delivery delay', 'Vehicle breakdown', 'Customs hold', 'Customer complaint'],
  },
  revenueModels: [
    { name: 'Freight Charges', description: 'Core shipping fees', percentage: 70 },
    { name: 'Warehousing', description: 'Storage and fulfillment', percentage: 15 },
    { name: 'Value-Added Services', description: 'Packaging, labeling, customs', percentage: 10 },
    { name: 'Insurance', description: 'Cargo insurance fees', percentage: 5 },
  ],
  vocabulary: {
    'customer': 'shipper',
    'product': 'cargo',
    'buy': 'ship',
    'store': 'warehouse',
    'cart': 'shipment',
    'checkout': 'delivery',
    'price': 'rate',
    'order': 'booking',
  },
};
