import type { BusinessIntelligenceProfile } from '../../schemas/knowledge/business-intelligence.schema.js';

export const LUXURY_RETAIL_BI: BusinessIntelligenceProfile = {
  id: 'bi.luxury.retail',
  version: '1.0.0',
  name: 'Luxury Retail Brand',
  description: 'How a luxury brand makes money: aspiration → discovery → consideration → purchase → ownership → loyalty → advocacy',
  revenueCycle: {
    name: 'Aspiration → Discovery → Consideration → Purchase → Advocacy',
    description: 'Customer aspires → discovers brand → considers purchase → acquires piece → becomes loyal advocate → refers others',
    steps: [
      { name: 'Brand aspiration', action: 'Customer sees brand in media/influencer', conversionRate: 0.02, avgTimeToNext: '30-180 days', revenueImpact: 'high' },
      { name: 'Brand discovery', action: 'Customer explores brand website/store', conversionRate: 0.10, avgTimeToNext: '1-30 days', revenueImpact: 'high' },
      { name: 'Consideration', action: 'Customer considers specific piece', conversionRate: 0.20, avgTimeToNext: '7-60 days', revenueImpact: 'critical' },
      { name: 'Purchase', action: 'Customer acquires piece', conversionRate: 0.15, avgTimeToNext: '1-30 days', revenueImpact: 'critical' },
      { name: 'Ownership experience', action: 'Customer enjoys product + brand experience', conversionRate: 0.90, avgTimeToNext: '30-365 days', revenueImpact: 'high' },
      { name: 'Repeat purchase', action: 'Customer acquires additional pieces', conversionRate: 0.25, avgTimeToNext: '90-730 days', revenueImpact: 'high' },
      { name: 'Advocacy', action: 'Customer recommends brand to others', conversionRate: 0.10, avgTimeToNext: '30-365 days', revenueImpact: 'medium' },
    ],
    avgCycleLength: '30-365 days',
    avgRevenuePerCustomer: '$500-50,000 per purchase',
  },
  conversionFunnel: {
    name: 'Aspiration → Discovery → Consideration → Purchase',
    stages: ['Brand Awareness', 'Website Visit', 'Product View', 'Store Visit', 'Purchase', 'Repeat', 'Advocacy'],
    overallConversionRate: '0.5-2% of visitors purchase',
    biggestDropOff: 'Website visit → Store visit (90% don\'t visit)',
  },
  churnSignals: [
    { name: 'No purchase in 18 months', detection: 'Customer hasn\'t purchased in 18+ months', window: '540 days', severity: 'high' },
    { name: 'Negative brand experience', detection: 'Customer had poor in-store/online experience', window: '7 days', severity: 'critical' },
    { name: 'Competitor engagement', detection: 'Customer seen with competitor products', window: '30 days', severity: 'medium' },
    { name: 'Price sensitivity', detection: 'Customer asks about discounts/sales', window: '7 days', severity: 'medium' },
    { name: 'VIP downgrade', detection: 'VIP customer engagement dropped', window: '90 days', severity: 'high' },
  ],
  retentionAutomations: [
    { name: 'VIP appreciation', trigger: 'After significant purchase', action: 'Send personalized thank you + exclusive preview', expectedImpact: 'Increases loyalty by 30%' },
    { name: 'New collection preview', trigger: 'New collection launch', action: 'Invite VIP customers to exclusive preview', expectedImpact: 'Generates 20% early sales' },
    { name: 'Birthday gift', trigger: 'Customer birthday', action: 'Send luxury gift + handwritten note', expectedImpact: 'Increases emotional connection' },
    { name: 'Anniversary celebration', trigger: '1 year since first purchase', action: 'Send anniversary gift + exclusive offer', expectedImpact: 'Increases repeat rate by 15%' },
  ],
  kpis: [
    { name: 'Revenue', label: 'Revenue', formula: 'Total sales revenue', benchmark: '$100K-2M/month', unit: '$', category: 'revenue' },
    { name: 'Units Sold', label: 'Units', formula: 'Total pieces sold', benchmark: '100-1,000/month', unit: 'count', category: 'revenue' },
    { name: 'Average Transaction Value', label: 'ATV', formula: 'Total revenue / Total transactions', benchmark: '$500-3,000', unit: '$', category: 'revenue' },
    { name: 'VIP Customer Ratio', label: 'VIP', formula: 'VIP customers / Total customers × 100', benchmark: '5-15%', unit: '%', category: 'engagement' },
    { name: 'Repeat Purchase Rate', label: 'Repeat', formula: 'Repeat buyers / Total buyers × 100', benchmark: '15-30%', unit: '%', category: 'retention' },
    { name: 'Customer Lifetime Value', label: 'LTV', formula: 'Average spend × Purchase frequency × Lifespan', benchmark: '$2,000-20,000', unit: '$', category: 'revenue' },
    { name: 'Brand Sentiment', label: 'Sentiment', formula: 'Positive mentions / Total mentions × 100', benchmark: '80-95%', unit: '%', category: 'engagement' },
    { name: 'Referral Rate', label: 'Referrals', formula: 'Referral customers / Total customers × 100', benchmark: '10-20%', unit: '%', category: 'growth' },
  ],
  dashboardWidgets: [
    { name: 'Revenue Dashboard', type: 'chart', description: 'Sales revenue and category trends', kpis: ['Revenue', 'Average Transaction Value'], priority: 'primary' },
    { name: 'VIP Dashboard', type: 'table', description: 'VIP customer activity and spending', kpis: ['VIP Customer Ratio', 'Customer Lifetime Value'], priority: 'primary' },
    { name: 'Brand Metrics', type: 'stat-card', description: 'Sentiment, referrals, and loyalty', kpis: ['Brand Sentiment', 'Referral Rate'], priority: 'secondary' },
    { name: 'Inventory Status', type: 'table', description: 'Product availability and exclusivity', kpis: ['Repeat Purchase Rate', 'Units Sold'], priority: 'secondary' },
  ],
  leadCaptureMechanisms: [
    { name: 'Private Appointment', headline: 'Book a Private Viewing', fields: ['name', 'email', 'phone', 'interest'], nextStep: 'Personal stylist contact', conversionRate: '5-10% of visitors' },
    { name: 'VIP Registration', headline: 'Join Our VIP Circle', fields: ['name', 'email', 'phone'], nextStep: 'VIP welcome package', conversionRate: '8-12% of visitors' },
    { name: 'Newsletter', headline: 'Exclusive Updates', fields: ['email'], nextStep: 'Luxury content + previews', conversionRate: '10-15% of visitors' },
  ],
  morningCheck: {
    primaryMetrics: ['Sales today', 'VIP appointments', 'New VIP registrations', 'Inventory status'],
    secondaryMetrics: ['Social media mentions', 'Influencer collaborations', 'Store traffic', 'Online orders'],
    alertConditions: ['VIP customer complaint', 'Low stock on key item', 'Negative press', 'Competitor launch'],
  },
  revenueModels: [
    { name: 'Direct Retail', description: 'In-store and online sales', percentage: 65 },
    { name: 'E-Commerce', description: 'Online direct-to-consumer', percentage: 20 },
    { name: 'Wholesale', description: 'Department store and multi-brand', percentage: 10 },
    { name: 'Accessories/Small Leather', description: 'Entry-level accessories', percentage: 5 },
  ],
  vocabulary: {
    'customer': 'client',
    'product': 'piece',
    'buy': 'acquire',
    'store': 'maison',
    'cart': 'selection',
    'checkout': 'acquisition',
    'price': 'investment',
    'order': 'commission',
  },
};
