import type { BusinessIntelligenceProfile } from '../../schemas/knowledge/business-intelligence.schema.js';

export const MANUFACTURING_BI: BusinessIntelligenceProfile = {
  id: 'bi.manufacturing.industrial',
  version: '1.0.0',
  name: 'Manufacturing',
  description: 'How a manufacturer makes money: inquiry → quote → sample → order → production → delivery → repeat order',
  revenueCycle: {
    name: 'Inquiry → Quote → Sample → Order → Delivery → Repeat',
    description: 'Buyer inquires → receives quote → approves sample → places order → production → delivery → repeat orders',
    steps: [
      { name: 'Inquiry', action: 'Buyer inquires about product/capability', conversionRate: 0.10, avgTimeToNext: '1-7 days', revenueImpact: 'high' },
      { name: 'Quote sent', action: 'Manufacturer sends detailed quote', conversionRate: 0.50, avgTimeToNext: '3-10 days', revenueImpact: 'critical' },
      { name: 'Sample approved', action: 'Buyer approves product sample', conversionRate: 0.60, avgTimeToNext: '7-30 days', revenueImpact: 'high' },
      { name: 'Order placed', action: 'Buyer places purchase order', conversionRate: 0.70, avgTimeToNext: '1-14 days', revenueImpact: 'critical' },
      { name: 'Production complete', action: 'Order manufactured and QC passed', conversionRate: 0.95, avgTimeToNext: '14-60 days', revenueImpact: 'high' },
      { name: 'Delivery accepted', action: 'Buyer receives and inspects goods', conversionRate: 0.90, avgTimeToNext: '7-14 days', revenueImpact: 'critical' },
      { name: 'Repeat order', action: 'Buyer places reorder', conversionRate: 0.30, avgTimeToNext: '30-365 days', revenueImpact: 'high' },
    ],
    avgCycleLength: '30-120 days',
    avgRevenuePerCustomer: '$5,000-100,000 per order',
  },
  conversionFunnel: {
    name: 'Inquiry → Quote → Order → Delivery',
    stages: ['Website Visit', 'Product Inquiry', 'Quote Sent', 'Sample Approved', 'Order Placed', 'Delivered', 'Reorder'],
    overallConversionRate: '5-10% of inquiries become orders',
    biggestDropOff: 'Quote sent → Sample approval (40% don\'t approve)',
  },
  churnSignals: [
    { name: 'Quote not accepted', detection: 'Quote sent but no response in 14 days', window: '14 days', severity: 'high' },
    { name: 'Sample rejected', detection: 'Buyer rejects product sample', window: '7 days', severity: 'critical' },
    { name: 'Quality issue', detection: 'Buyer reports quality defect', window: '0 days', severity: 'critical' },
    { name: 'Delivery delay', detection: 'Order delivered late', window: '0 days', severity: 'high' },
    { name: 'No reorder', detection: 'Buyer hasn\'t reordered in 12 months', window: '365 days', severity: 'medium' },
  ],
  retentionAutomations: [
    { name: 'Quote follow-up', trigger: '7 days after quote sent', action: 'Follow up on quote status', expectedImpact: 'Increases conversion by 15%' },
    { name: 'Production update', trigger: 'Weekly during production', action: 'Send production progress update', expectedImpact: 'Improves buyer satisfaction by 25%' },
    { name: 'Reorder reminder', trigger: '30 days before estimated reorder date', action: 'Send reorder reminder', expectedImpact: 'Generates 20% repeat orders' },
    { name: 'New product alert', trigger: 'New product launched', action: 'Email relevant buyers about new capabilities', expectedImpact: 'Generates 10% new orders from existing customers' },
  ],
  kpis: [
    { name: 'Revenue', label: 'Revenue', formula: 'Total order revenue', benchmark: '$100K-1M/month', unit: '$', category: 'revenue' },
    { name: 'Orders', label: 'Orders', formula: 'Total orders this month', benchmark: '50-200/month', unit: 'count', category: 'revenue' },
    { name: 'Average Order Value', label: 'AOV', formula: 'Total revenue / Total orders', benchmark: '$5,000-50,000', unit: '$', category: 'revenue' },
    { name: 'Quote-to-Order Rate', label: 'Close Rate', formula: 'Orders / Quotes sent × 100', benchmark: '20-40%', unit: '%', category: 'growth' },
    { name: 'On-Time Delivery Rate', label: 'OTD', formula: 'On-time deliveries / Total deliveries × 100', benchmark: '90-98%', unit: '%', category: 'operations' },
    { name: 'Quality Rate', label: 'Quality', formula: 'Units passed QC / Total units × 100', benchmark: '95-99%', unit: '%', category: 'operations' },
    { name: 'Repeat Order Rate', label: 'Repeat', formula: 'Repeat orders / Total orders × 100', benchmark: '25-40%', unit: '%', category: 'retention' },
    { name: 'Production Capacity', label: 'Capacity', formula: 'Actual output / Maximum capacity × 100', benchmark: '70-90%', unit: '%', category: 'operations' },
  ],
  dashboardWidgets: [
    { name: 'Revenue Dashboard', type: 'chart', description: 'Order revenue and production trends', kpis: ['Revenue', 'Average Order Value'], priority: 'primary' },
    { name: 'Production Status', type: 'table', description: 'Active orders with production status', kpis: ['Orders', 'On-Time Delivery Rate'], priority: 'primary' },
    { name: 'Quality Metrics', type: 'stat-card', description: 'Quality and production capacity', kpis: ['Quality Rate', 'Production Capacity'], priority: 'secondary' },
    { name: 'Customer Pipeline', type: 'chart', description: 'Quote-to-order conversion funnel', kpis: ['Quote-to-Order Rate', 'Repeat Order Rate'], priority: 'secondary' },
  ],
  leadCaptureMechanisms: [
    { name: 'RFQ Form', headline: 'Request a Quote', fields: ['company', 'name', 'email', 'phone', 'product', 'quantity'], nextStep: 'Sales team quote preparation', conversionRate: '10-15% of visitors' },
    { name: 'Catalog Download', headline: 'Download Product Catalog', fields: ['name', 'email', 'company', 'industry'], nextStep: 'Catalog delivery + follow-up', conversionRate: '15-20% of visitors' },
    { name: 'Factory Tour', headline: 'Schedule a Facility Tour', fields: ['name', 'email', 'company', 'visit_purpose'], nextStep: 'Tour scheduling', conversionRate: '8-12% of visitors' },
  ],
  morningCheck: {
    primaryMetrics: ['Orders in production', 'Shipments today', 'Pending quotes', 'Quality issues'],
    secondaryMetrics: ['Raw material inventory', 'Machine uptime', 'Staff attendance', 'Delivery schedule'],
    alertConditions: ['Production delay', 'Quality defect', 'Raw material shortage', 'Delivery deadline approaching'],
  },
  revenueModels: [
    { name: 'Product Sales', description: 'Direct product sales', percentage: 70 },
    { name: 'Custom Manufacturing', description: 'Custom/OEM manufacturing', percentage: 15 },
    { name: 'Parts & Service', description: 'Spare parts and maintenance', percentage: 10 },
    { name: 'Design/Engineering', description: 'Design and engineering services', percentage: 5 },
  ],
  vocabulary: {
    'customer': 'buyer',
    'product': 'product',
    'buy': 'order',
    'store': 'factory',
    'cart': 'purchase order',
    'checkout': 'invoice',
    'price': 'quote',
    'order': 'purchase order',
  },
};
