import type { BusinessIntelligenceProfile } from '../../schemas/knowledge/business-intelligence.schema.js';

export const NONPROFIT_BI: BusinessIntelligenceProfile = {
  id: 'bi.nonprofit.charity',
  version: '1.0.0',
  name: 'Nonprofit Organization',
  description: 'How a nonprofit makes money: awareness → donation → engagement → recurring giving → major gifts → legacy',
  revenueCycle: {
    name: 'Awareness → Donation → Recurring → Major Gifts → Legacy',
    description: 'Supporter discovers cause → makes first donation → becomes recurring donor → increases giving → major gift → legacy bequest',
    steps: [
      { name: 'Cause discovery', action: 'Supporter finds organization via search/referral', conversionRate: 0.05, avgTimeToNext: '1-7 days', revenueImpact: 'high' },
      { name: 'First donation', action: 'Supporter makes initial donation', conversionRate: 0.15, avgTimeToNext: '1-3 days', revenueImpact: 'critical' },
      { name: 'Recurring giving', action: 'Supporter sets up monthly recurring donation', conversionRate: 0.20, avgTimeToNext: '7-30 days', revenueImpact: 'critical' },
      { name: 'Engagement', action: 'Supporter volunteers or attends events', conversionRate: 0.30, avgTimeToNext: '30-90 days', revenueImpact: 'medium' },
      { name: 'Increased giving', action: 'Supporter increases donation amount', conversionRate: 0.25, avgTimeToNext: '90-365 days', revenueImpact: 'high' },
      { name: 'Major gift', action: 'Supporter makes significant one-time gift', conversionRate: 0.05, avgTimeToNext: '365-1095 days', revenueImpact: 'critical' },
      { name: 'Legacy gift', action: 'Supporter includes org in estate plan', conversionRate: 0.02, avgTimeToNext: '1095+ days', revenueImpact: 'critical' },
    ],
    avgCycleLength: '1-3 years',
    avgRevenuePerCustomer: '$50-500/year',
  },
  conversionFunnel: {
    name: 'Awareness → Donation → Recurring → Major',
    stages: ['Website Visit', 'About Page', 'First Donation', 'Recurring Setup', 'Event Attendance', 'Major Gift'],
    overallConversionRate: '3-5% of website visitors donate',
    biggestDropOff: 'Website visit → First donation (95% don\'t donate)',
  },
  churnSignals: [
    { name: 'Recurring donation cancelled', detection: 'Monthly donation stopped', window: '0 days', severity: 'critical' },
    { name: 'No donation in 6 months', detection: 'Donor hasn\'t given in 6+ months', window: '180 days', severity: 'high' },
    { name: 'Event non-attendance', detection: 'Invited donor didn\'t attend event', window: '7 days', severity: 'low' },
    { name: 'Email non-engagement', detection: 'Donor hasn\'t opened emails in 90 days', window: '90 days', severity: 'medium' },
    { name: 'Donor complaint', detection: 'Donor raises concern about use of funds', window: '7 days', severity: 'critical' },
  ],
  retentionAutomations: [
    { name: 'Thank you email', trigger: 'Immediately after donation', action: 'Send personalized thank you + impact story', expectedImpact: 'Increases repeat donation by 30%' },
    { name: 'Impact report', trigger: 'Quarterly', action: 'Send impact report with donation usage', expectedImpact: 'Reduces churn by 20%' },
    { name: 'Recurring donor appreciation', trigger: '3 months of recurring giving', action: 'Send special thank you + exclusive update', expectedImpact: 'Increases retention by 25%' },
    { name: 'Year-end appeal', trigger: 'November', action: 'Send annual giving campaign', expectedImpact: 'Generates 30% of annual revenue' },
  ],
  kpis: [
    { name: 'Revenue', label: 'Revenue', formula: 'Total donations received', benchmark: '$10K-500K/month', unit: '$', category: 'revenue' },
    { name: 'Donor Count', label: 'Donors', formula: 'Active donors this period', benchmark: '500-10,000', unit: 'count', category: 'growth' },
    { name: 'Donor Retention Rate', label: 'Retention', formula: 'Returning donors / Total donors × 100', benchmark: '40-60%', unit: '%', category: 'retention' },
    { name: 'Average Donation', label: 'Avg Gift', formula: 'Total donations / Number of gifts', benchmark: '$50-200', unit: '$', category: 'revenue' },
    { name: 'Recurring Donor Rate', label: 'Recurring', formula: 'Recurring donors / Total donors × 100', benchmark: '15-30%', unit: '%', category: 'revenue' },
    { name: 'Cost per Dollar Raised', label: 'CPDR', formula: 'Fundraising costs / Revenue raised', benchmark: '$0.10-0.30', unit: '$', category: 'operations' },
    { name: 'Major Gift Conversion', label: 'Major Gifts', formula: 'Major gifts / Total donors × 100', benchmark: '1-5%', unit: '%', category: 'growth' },
    { name: 'Email Open Rate', label: 'Open Rate', formula: 'Emails opened / Emails sent × 100', benchmark: '20-35%', unit: '%', category: 'engagement' },
  ],
  dashboardWidgets: [
    { name: 'Revenue Dashboard', type: 'chart', description: 'Donation revenue and giving trends', kpis: ['Revenue', 'Average Donation'], priority: 'primary' },
    { name: 'Donor Pipeline', type: 'table', description: 'Donor segments and giving levels', kpis: ['Donor Count', 'Donor Retention Rate'], priority: 'primary' },
    { name: 'Campaign Performance', type: 'chart', description: 'Campaign results and ROI', kpis: ['Cost per Dollar Raised', 'Recurring Donor Rate'], priority: 'secondary' },
    { name: 'Engagement Metrics', type: 'stat-card', description: 'Email, event, and volunteer metrics', kpis: ['Email Open Rate', 'Major Gift Conversion'], priority: 'secondary' },
  ],
  leadCaptureMechanisms: [
    { name: 'Donate Now', headline: 'Make a Difference Today', fields: ['name', 'email', 'amount'], nextStep: 'Donation confirmation + impact story', conversionRate: '10-15% of visitors' },
    { name: 'Newsletter Signup', headline: 'Stay Connected', fields: ['email'], nextStep: 'Welcome email + story series', conversionRate: '15-25% of visitors' },
    { name: 'Volunteer Registration', headline: 'Join Our Mission', fields: ['name', 'email', 'skills', 'availability'], nextStep: 'Volunteer onboarding', conversionRate: '5-10% of visitors' },
  ],
  morningCheck: {
    primaryMetrics: ['Donations today', 'Active campaigns', 'Recurring donors', 'Email engagement'],
    secondaryMetrics: ['Event attendance', 'Volunteer hours', 'Social media reach', 'Grant deadlines'],
    alertConditions: ['Revenue below target', 'Donor complaint', 'Campaign underperforming', 'Grant deadline approaching'],
  },
  revenueModels: [
    { name: 'Individual Donations', description: 'One-time and recurring individual gifts', percentage: 55 },
    { name: 'Grants', description: 'Foundation and government grants', percentage: 25 },
    { name: 'Events', description: 'Fundraising event revenue', percentage: 10 },
    { name: 'Corporate Sponsorships', description: 'Corporate partnerships and sponsorships', percentage: 10 },
  ],
  vocabulary: {
    'customer': 'supporter',
    'product': 'cause',
    'buy': 'donate',
    'store': 'organization',
    'cart': 'giving basket',
    'checkout': 'donation',
    'price': 'suggested amount',
    'order': 'gift',
  },
};
