import type { BusinessIntelligenceProfile } from '../../schemas/knowledge/business-intelligence.schema.js';

export const PORTFOLIO_BI: BusinessIntelligenceProfile = {
  id: 'bi.portfolio.creative',
  version: '1.0.0',
  name: 'Freelancer / Creative Portfolio',
  description: 'How a freelancer makes money: discovery → inquiry → proposal → contract → delivery → payment → referral',
  revenueCycle: {
    name: 'Discovery → Inquiry → Proposal → Contract → Delivery → Referral',
    description: 'Client discovers portfolio → sends inquiry → receives proposal → signs contract → project delivered → payment → referral',
    steps: [
      { name: 'Discovery', action: 'Client finds portfolio via search/social', conversionRate: 0.03, avgTimeToNext: '1-14 days', revenueImpact: 'high' },
      { name: 'Inquiry', action: 'Client sends project inquiry', conversionRate: 0.15, avgTimeToNext: '1-7 days', revenueImpact: 'critical' },
      { name: 'Proposal sent', action: 'Freelancer sends proposal with scope/pricing', conversionRate: 0.50, avgTimeToNext: '3-10 days', revenueImpact: 'high' },
      { name: 'Contract signed', action: 'Client signs contract and pays deposit', conversionRate: 0.40, avgTimeToNext: '1-14 days', revenueImpact: 'critical' },
      { name: 'Delivery', action: 'Project delivered and approved', conversionRate: 0.90, avgTimeToNext: '14-60 days', revenueImpact: 'high' },
      { name: 'Final payment', action: 'Client pays final invoice', conversionRate: 0.95, avgTimeToNext: '7-30 days', revenueImpact: 'critical' },
      { name: 'Referral', action: 'Client refers other prospects', conversionRate: 0.20, avgTimeToNext: '30-365 days', revenueImpact: 'medium' },
    ],
    avgCycleLength: '14-60 days',
    avgRevenuePerCustomer: '$1,000-10,000 per project',
  },
  conversionFunnel: {
    name: 'Discovery → Inquiry → Proposal → Contract',
    stages: ['Portfolio Visit', 'Contact Form', 'Discovery Call', 'Proposal', 'Contract', 'Project', 'Payment'],
    overallConversionRate: '1-3% of visitors become clients',
    biggestDropOff: 'Proposal → Contract (60% don\'t sign)',
  },
  churnSignals: [
    { name: 'Inquiry not converted', detection: 'Inquiry received but no booking in 14 days', window: '14 days', severity: 'high' },
    { name: 'Project delay', detection: 'Project past deadline by 2+ weeks', window: '14 days', severity: 'high' },
    { name: 'No repeat business', detection: 'Client hasn\'t contacted in 6+ months', window: '180 days', severity: 'medium' },
    { name: 'Scope creep', detection: 'Client requests significant scope changes', window: '7 days', severity: 'medium' },
    { name: 'Late payment', detection: 'Invoice unpaid for 30+ days', window: '30 days', severity: 'high' },
  ],
  retentionAutomations: [
    { name: 'Project follow-up', trigger: '30 days after project completion', action: 'Check in + ask for referral', expectedImpact: 'Generates 20% referrals' },
    { name: 'Portfolio update', trigger: 'After each project', action: 'Update portfolio with new case study', expectedImpact: 'Increases inquiries by 15%' },
    { name: 'Newsletter', trigger: 'Monthly', action: 'Share recent work and insights', expectedImpact: 'Maintains top-of-mind awareness' },
    { name: 'Client appreciation', trigger: '1 year since first project', action: 'Send thank you + special offer', expectedImpact: 'Generates 15% repeat business' },
  ],
  kpis: [
    { name: 'Revenue', label: 'Revenue', formula: 'Total project revenue', benchmark: '$5K-30K/month', unit: '$', category: 'revenue' },
    { name: 'Projects', label: 'Projects', formula: 'Total projects completed', benchmark: '2-8/month', unit: 'count', category: 'revenue' },
    { name: 'Average Project Value', label: 'Avg Project', formula: 'Total revenue / Total projects', benchmark: '$2,000-8,000', unit: '$', category: 'revenue' },
    { name: 'Inquiry-to-Contract Rate', label: 'Close Rate', formula: 'Contracts / Inquiries × 100', benchmark: '15-30%', unit: '%', category: 'growth' },
    { name: 'Client Retention Rate', label: 'Retention', formula: 'Returning clients / Total clients × 100', benchmark: '30-50%', unit: '%', category: 'retention' },
    { name: 'Utilization Rate', label: 'Utilization', formula: 'Billable hours / Available hours × 100', benchmark: '60-80%', unit: '%', category: 'operations' },
    { name: 'Average Days to Payment', label: 'Payment Days', formula: 'Average days from invoice to payment', benchmark: '10-30 days', unit: 'days', category: 'operations' },
    { name: 'Referral Rate', label: 'Referrals', formula: 'Referral inquiries / Total inquiries × 100', benchmark: '20-40%', unit: '%', category: 'growth' },
  ],
  dashboardWidgets: [
    { name: 'Revenue Dashboard', type: 'chart', description: 'Project revenue and monthly trends', kpis: ['Revenue', 'Average Project Value'], priority: 'primary' },
    { name: 'Project Pipeline', type: 'table', description: 'Active projects with status and deadlines', kpis: ['Projects', 'Utilization Rate'], priority: 'primary' },
    { name: 'Client Metrics', type: 'stat-card', description: 'Retention and referral rates', kpis: ['Client Retention Rate', 'Referral Rate'], priority: 'secondary' },
    { name: 'Financial Overview', type: 'chart', description: 'Invoicing and payment tracking', kpis: ['Average Days to Payment'], priority: 'secondary' },
  ],
  leadCaptureMechanisms: [
    { name: 'Project Inquiry', headline: 'Let\'s Work Together', fields: ['name', 'email', 'project_type', 'budget', 'timeline'], nextStep: 'Discovery call within 48 hours', conversionRate: '8-12% of visitors' },
    { name: 'Newsletter', headline: 'Behind the Scenes', fields: ['email'], nextStep: 'Monthly insights + work showcase', conversionRate: '10-15% of visitors' },
    { name: 'Free Consultation', headline: 'Free 15-Min Consultation', fields: ['name', 'email', 'project_description'], nextStep: 'Consultation scheduling', conversionRate: '12-18% of visitors' },
  ],
  morningCheck: {
    primaryMetrics: ['Active projects', 'Pending invoices', 'Inquiries this week', 'Portfolio views'],
    secondaryMetrics: ['Deadline status', 'Client communications', 'Skill development', 'Social media engagement'],
    alertConditions: ['Project overdue', 'Invoice >30 days', 'Inquiry >48 hours old', 'Client not responding'],
  },
  revenueModels: [
    { name: 'Project-Based', description: 'Fixed-fee project work', percentage: 65 },
    { name: 'Hourly Consulting', description: 'Hourly consulting fees', percentage: 20 },
    { name: 'Retainer', description: 'Monthly retainer agreements', percentage: 10 },
    { name: 'Digital Products', description: 'Templates, courses, assets', percentage: 5 },
  ],
  vocabulary: {
    'customer': 'client',
    'product': 'project',
    'buy': 'hire',
    'store': 'studio',
    'cart': 'proposal',
    'checkout': 'contract',
    'price': 'rate',
    'order': 'project',
  },
};
