import type { BusinessIntelligenceProfile } from '../../schemas/knowledge/business-intelligence.schema.js';

export const PROPTECH_BI: BusinessIntelligenceProfile = {
  id: 'bi.proptech.rental',
  version: '1.0.0',
  name: 'PropTech / Property Management',
  description: 'How a PropTech business makes money: property listing → tenant screening → lease signing → rent collection → maintenance → renewal',
  revenueCycle: {
    name: 'Listing → Screening → Lease → Rent → Maintenance → Renewal',
    description: 'Property listed → tenant applies → screened → lease signed → rent collected → maintenance handled → lease renewed',
    steps: [
      { name: 'Property listed', action: 'Property manager lists property', conversionRate: 0.15, avgTimeToNext: '1-7 days', revenueImpact: 'high' },
      { name: 'Tenant application', action: 'Prospective tenant applies', conversionRate: 0.30, avgTimeToNext: '1-3 days', revenueImpact: 'critical' },
      { name: 'Tenant screened', action: 'Background and credit check completed', conversionRate: 0.60, avgTimeToNext: '1-3 days', revenueImpact: 'high' },
      { name: 'Lease signed', action: 'Tenant signs lease agreement', conversionRate: 0.70, avgTimeToNext: '1-7 days', revenueImpact: 'critical' },
      { name: 'Rent collected', action: 'First month rent + deposit received', conversionRate: 0.95, avgTimeToNext: '1-14 days', revenueImpact: 'critical' },
      { name: 'Maintenance handled', action: 'Maintenance request resolved', conversionRate: 0.90, avgTimeToNext: '1-14 days', revenueImpact: 'medium' },
      { name: 'Lease renewed', action: 'Tenant renews lease', conversionRate: 0.60, avgTimeToNext: '300-365 days', revenueImpact: 'high' },
    ],
    avgCycleLength: '14-30 days',
    avgRevenuePerCustomer: '$100-500/month management fee',
  },
  conversionFunnel: {
    name: 'Listing → Application → Lease → Renewal',
    stages: ['Property View', 'Application', 'Screening', 'Lease Signing', 'Move-In', 'Lease Term', 'Renewal'],
    overallConversionRate: '10-20% of listings become occupied',
    biggestDropOff: 'Application → Screening (40% don\'t pass)',
  },
  churnSignals: [
    { name: 'Tenant moves out', detection: 'Tenant gives notice to vacate', window: '30 days', severity: 'critical' },
    { name: 'Late rent payment', detection: 'Rent paid 5+ days late', window: '5 days', severity: 'high' },
    { name: 'Maintenance complaint', detection: 'Tenant complains about unresolved maintenance', window: '7 days', severity: 'medium' },
    { name: 'Property owner churn', detection: 'Owner removes property from management', window: '0 days', severity: 'critical' },
    { name: 'Vacancy period', detection: 'Property vacant for 30+ days', window: '30 days', severity: 'high' },
  ],
  retentionAutomations: [
    { name: 'Lease renewal reminder', trigger: '90 days before lease expiry', action: 'Send renewal offer to tenant', expectedImpact: 'Increases renewals by 25%' },
    { name: 'Maintenance follow-up', trigger: '24 hours after maintenance completion', action: 'Confirm tenant satisfaction', expectedImpact: 'Reduces complaints by 20%' },
    { name: 'Owner reporting', trigger: 'Monthly', action: 'Send financial report to property owner', expectedImpact: 'Increases owner retention by 15%' },
    { name: 'Vacancy marketing', trigger: 'Immediately after notice to vacate', action: 'List property on marketing channels', expectedImpact: 'Reduces vacancy by 30%' },
  ],
  kpis: [
    { name: 'Revenue', label: 'Revenue', formula: 'Total management fees + other revenue', benchmark: '$20K-200K/month', unit: '$', category: 'revenue' },
    { name: 'Occupancy Rate', label: 'Occupancy', formula: 'Occupied units / Total units × 100', benchmark: '90-98%', unit: '%', category: 'operations' },
    { name: 'Rent Collection Rate', label: 'Collection', formula: 'Rent collected / Rent due × 100', benchmark: '95-99%', unit: '%', category: 'revenue' },
    { name: 'Tenant Retention Rate', label: 'Retention', formula: 'Renewals / Lease expirations × 100', benchmark: '55-70%', unit: '%', category: 'retention' },
    { name: 'Vacancy Rate', label: 'Vacancy', formula: 'Vacant days / Total days × 100', benchmark: '2-8%', unit: '%', category: 'operations' },
    { name: 'Maintenance Response Time', label: 'Response', formula: 'Average time to resolve maintenance', benchmark: '24-48 hours', unit: 'hours', category: 'operations' },
    { name: 'Net Operating Income', label: 'NOI', formula: 'Revenue - Operating expenses', benchmark: '30-40% margin', unit: '%', category: 'revenue' },
    { name: 'Properties Managed', label: 'Properties', formula: 'Total properties under management', benchmark: '50-500', unit: 'count', category: 'growth' },
  ],
  dashboardWidgets: [
    { name: 'Revenue Dashboard', type: 'chart', description: 'Revenue and occupancy trends', kpis: ['Revenue', 'Occupancy Rate'], priority: 'primary' },
    { name: 'Tenant Pipeline', type: 'table', description: 'Applications, screenings, and move-ins', kpis: ['Tenant Retention Rate', 'Rent Collection Rate'], priority: 'primary' },
    { name: 'Maintenance Tracker', type: 'table', description: 'Open and resolved maintenance requests', kpis: ['Maintenance Response Time', 'Vacancy Rate'], priority: 'secondary' },
    { name: 'Property Portfolio', type: 'stat-card', description: 'Portfolio performance metrics', kpis: ['Properties Managed', 'Net Operating Income'], priority: 'secondary' },
  ],
  leadCaptureMechanisms: [
    { name: 'List Your Property', headline: 'Manage Your Property with Ease', fields: ['name', 'email', 'phone', 'property_address', 'units'], nextStep: 'Property manager consultation', conversionRate: '10-15% of visitors' },
    { name: 'Find a Rental', headline: 'Find Your Next Home', fields: ['budget', 'bedrooms', 'location', 'move_in_date'], nextStep: 'Property listings display', conversionRate: '15-20% of visitors' },
    { name: 'Tenant Portal', headline: 'Tenant Login', fields: ['email', 'password'], nextStep: 'Tenant portal access', conversionRate: '30-40% of visitors' },
  ],
  morningCheck: {
    primaryMetrics: ['Rent collection rate', 'Occupancy rate', 'Open maintenance', 'Applications pending'],
    secondaryMetrics: ['Vacant units', 'Lease expirations', 'Owner payments', 'Vendor payments'],
    alertConditions: ['Occupancy <90%', 'Rent collection <95%', 'Maintenance >48 hours', 'Owner payment due'],
  },
  revenueModels: [
    { name: 'Management Fees', description: 'Monthly management fees (% of rent)', percentage: 55 },
    { name: 'Leasing Fees', description: 'Tenant placement fees', percentage: 20 },
    { name: 'Maintenance Markup', description: 'Markup on maintenance services', percentage: 10 },
    { name: 'Late Fees', description: 'Late rent and violation fees', percentage: 8 },
    { name: 'Other', description: 'Pet fees, application fees, etc.', percentage: 7 },
  ],
  vocabulary: {
    'customer': 'tenant',
    'product': 'unit',
    'buy': 'rent',
    'store': 'property',
    'cart': 'application',
    'checkout': 'lease signing',
    'price': 'rent',
    'order': 'lease',
  },
};
