import type { BusinessIntelligenceProfile } from '../../schemas/knowledge/business-intelligence.schema.js';

export const REAL_ESTATE_BI: BusinessIntelligenceProfile = {
  id: 'bi.realestate.residential',
  version: '1.0.0',
  name: 'Real Estate Agency',
  description: 'How a real estate agency makes money: lead → property search → viewing → offer → closing → commission → referral',
  revenueCycle: {
    name: 'Lead → Property Search → Offer → Closing → Commission',
    description: 'Buyer/seller finds agent → property search → viewings → offer made → closing → commission earned → referral',
    steps: [
      { name: 'Lead generation', action: 'Buyer/seller finds agent via search/referral', conversionRate: 0.05, avgTimeToNext: '1-14 days', revenueImpact: 'high' },
      { name: 'Consultation', action: 'Initial meeting to understand needs', conversionRate: 0.35, avgTimeToNext: '1-7 days', revenueImpact: 'critical' },
      { name: 'Property search', action: 'Agent curates property options', conversionRate: 0.80, avgTimeToNext: '7-30 days', revenueImpact: 'high' },
      { name: 'Viewings', action: 'Client views properties', conversionRate: 0.60, avgTimeToNext: '7-14 days', revenueImpact: 'high' },
      { name: 'Offer made', action: 'Client makes offer on property', conversionRate: 0.30, avgTimeToNext: '1-14 days', revenueImpact: 'critical' },
      { name: 'Closing', action: 'Transaction closes successfully', conversionRate: 0.75, avgTimeToNext: '30-60 days', revenueImpact: 'critical' },
      { name: 'Referral', action: 'Client refers friends/family', conversionRate: 0.20, avgTimeToNext: '30-365 days', revenueImpact: 'medium' },
    ],
    avgCycleLength: '30-120 days',
    avgRevenuePerCustomer: '$5,000-30,000 commission',
  },
  conversionFunnel: {
    name: 'Lead → Viewing → Offer → Closing',
    stages: ['Website Visit', 'Contact', 'Consultation', 'Property Search', 'Viewing', 'Offer', 'Closing', 'Referral'],
    overallConversionRate: '2-4% of leads become transactions',
    biggestDropOff: 'Viewing → Offer (70% don\'t make offer)',
  },
  churnSignals: [
    { name: 'Unresponsive agent', detection: 'Agent hasn\'t contacted lead in 7+ days', window: '7 days', severity: 'critical' },
    { name: 'Property mismatch', detection: 'Client rejected 5+ properties', window: '30 days', severity: 'high' },
    { name: 'Offer rejection', detection: 'Client\'s offer was rejected', window: '0 days', severity: 'medium' },
    { name: 'No closing progress', detection: 'Transaction stalled for 2+ weeks', window: '14 days', severity: 'high' },
    { name: 'Client goes dark', detection: 'Client unresponsive for 14+ days', window: '14 days', severity: 'critical' },
  ],
  retentionAutomations: [
    { name: 'New listing alert', trigger: 'New property matches client criteria', action: 'Send property alert email', expectedImpact: 'Keeps clients engaged during search' },
    { name: 'Post-closing follow-up', trigger: '30 days after closing', action: 'Check-in + home maintenance tips', expectedImpact: 'Generates 25% referrals within 2 years' },
    { name: 'Market update', trigger: 'Monthly', action: 'Send local market insights + property values', expectedImpact: 'Maintains top-of-mind awareness' },
    { name: 'Home anniversary', trigger: '1 year after closing', action: 'Send anniversary card + home value estimate', expectedImpact: 'Generates 10% repeat business' },
  ],
  kpis: [
    { name: 'Revenue', label: 'Revenue', formula: 'Total commissions earned', benchmark: '$20K-200K/month', unit: '$', category: 'revenue' },
    { name: 'Transactions Closed', label: 'Closings', formula: 'Properties sold this month', benchmark: '5-20/month', unit: 'count', category: 'revenue' },
    { name: 'Average Commission', label: 'Avg Commission', formula: 'Total commission / Total transactions', benchmark: '$5,000-20,000', unit: '$', category: 'revenue' },
    { name: 'Lead-to-Close Rate', label: 'Close Rate', formula: 'Closings / Total leads × 100', benchmark: '2-5%', unit: '%', category: 'growth' },
    { name: 'Days on Market', label: 'DOM', formula: 'Average days from listing to sale', benchmark: '30-60 days', unit: 'days', category: 'operations' },
    { name: 'Client Satisfaction', label: 'NPS', formula: 'Net Promoter Score', benchmark: '60-80', unit: 'score', category: 'engagement' },
    { name: 'Listings Taken', label: 'Listings', formula: 'New listings secured this month', benchmark: '10-30/month', unit: 'count', category: 'growth' },
    { name: 'Referral Rate', label: 'Referrals', formula: 'Referral leads / Total leads × 100', benchmark: '20-40%', unit: '%', category: 'growth' },
  ],
  dashboardWidgets: [
    { name: 'Revenue Dashboard', type: 'chart', description: 'Commission revenue and transaction trends', kpis: ['Revenue', 'Transactions Closed'], priority: 'primary' },
    { name: 'Active Listings', type: 'table', description: 'Current listings with status and days on market', kpis: ['Days on Market', 'Listings Taken'], priority: 'primary' },
    { name: 'Lead Pipeline', type: 'chart', description: 'Lead-to-close conversion funnel', kpis: ['Lead-to-Close Rate', 'Client Satisfaction'], priority: 'secondary' },
    { name: 'Client Metrics', type: 'stat-card', description: 'Client satisfaction and referral rates', kpis: ['Referral Rate', 'Average Commission'], priority: 'secondary' },
  ],
  leadCaptureMechanisms: [
    { name: 'Property Search', headline: 'Find Your Dream Home', fields: ['name', 'email', 'phone', 'budget', 'location'], nextStep: 'Property matching + agent contact', conversionRate: '10-15% of visitors' },
    { name: 'Home Valuation', headline: 'What\'s Your Home Worth?', fields: ['address', 'email', 'phone'], nextStep: 'Free home valuation report', conversionRate: '15-20% of visitors' },
    { name: 'Buyer Consultation', headline: 'Free Buyer Consultation', fields: ['name', 'email', 'phone', 'timeline'], nextStep: 'Consultation scheduling', conversionRate: '12-18% of visitors' },
  ],
  morningCheck: {
    primaryMetrics: ['Active listings', 'Pending transactions', 'New leads', 'Showing scheduled'],
    secondaryMetrics: ['Offers pending', 'Commission earned', 'Marketing ROI', 'Client feedback'],
    alertConditions: ['Listing >90 days', 'Transaction stalled', 'Lead unresponsive >7 days', 'Client complaint'],
  },
  revenueModels: [
    { name: 'Buyer Commission', description: 'Commission from buyer side', percentage: 45 },
    { name: 'Seller Commission', description: 'Commission from seller side', percentage: 40 },
    { name: 'Property Management', description: 'Ongoing management fees', percentage: 10 },
    { name: 'Referral Fees', description: 'Referral commissions from other agents', percentage: 5 },
  ],
  vocabulary: {
    'customer': 'client',
    'product': 'property',
    'buy': 'purchase',
    'store': 'agency',
    'cart': 'shortlist',
    'checkout': 'closing',
    'price': 'listing price',
    'order': 'transaction',
  },
};
