import type { BusinessIntelligenceProfile } from '../../schemas/knowledge/business-intelligence.schema.js';

export const SAAS_BI: BusinessIntelligenceProfile = {
  id: 'bi.saas.b2b',
  version: '1.0.0',
  name: 'B2B SaaS Platform',
  description: 'How a SaaS business makes money: free trial → onboarding → activation → subscription → expansion → retention',
  revenueCycle: {
    name: 'Free Trial → MRR → Expansion Revenue',
    description: 'Visitor signs up for free trial → completes onboarding → hits activation moment → converts to paid → upgrades tier → adds seats',
    steps: [
      { name: 'Visitor signs up', action: 'Creates free trial account', conversionRate: 0.08, avgTimeToNext: '0-1 days', revenueImpact: 'critical' },
      { name: 'Completes onboarding', action: 'Finishes setup wizard, connects first integration', conversionRate: 0.45, avgTimeToNext: '1-3 days', revenueImpact: 'high' },
      { name: 'Hits activation moment', action: 'Reaches "aha moment" — core value delivered', conversionRate: 0.35, avgTimeToNext: '3-7 days', revenueImpact: 'critical' },
      { name: 'Converts to paid', action: 'Upgrades from trial to paid plan', conversionRate: 0.15, avgTimeToNext: '7-14 days', revenueImpact: 'critical' },
      { name: 'Upgrades tier', action: 'Moves to higher plan tier', conversionRate: 0.10, avgTimeToNext: '30-90 days', revenueImpact: 'high' },
      { name: 'Adds seats', action: 'Invites team members, increases seat count', conversionRate: 0.20, avgTimeToNext: '14-30 days', revenueImpact: 'medium' },
    ],
    avgCycleLength: '7-14 days',
    avgRevenuePerCustomer: '$49-499/month',
  },
  conversionFunnel: {
    name: 'Visitor → Trial → Paid → Expansion',
    stages: ['Website Visit', 'Trial Signup', 'Onboarding Complete', 'Activation', 'Paid Conversion', 'Tier Upgrade', 'Seat Expansion'],
    overallConversionRate: '2-5% of visitors become paid customers',
    biggestDropOff: 'Trial signup → Onboarding completion (55% abandon)',
  },
  churnSignals: [
    { name: 'Login frequency drop', detection: 'User hasn\'t logged in for 7+ days', window: '7 days', severity: 'high' },
    { name: 'Feature usage decline', detection: 'Core feature usage dropped 50%+', window: '14 days', severity: 'critical' },
    { name: 'Support ticket spike', detection: '3+ unresolved tickets in 7 days', window: '7 days', severity: 'medium' },
    { name: 'Payment failure', detection: 'Credit card declined or subscription past due', window: '3 days', severity: 'critical' },
    { name: 'Admin user inactive', detection: 'Team admin hasn\'t logged in for 14 days', window: '14 days', severity: 'critical' },
  ],
  retentionAutomations: [
    { name: 'Re-engagement email', trigger: 'No login for 5 days', action: 'Send personalized email with tips', expectedImpact: 'Recovers 15% of at-risk users' },
    { name: 'Feature adoption nudges', trigger: 'User hasn\'t tried key feature', action: 'In-app tooltip + email tutorial', expectedImpact: 'Increases activation by 20%' },
    { name: 'Success check-in', trigger: '30 days after signup', action: 'CSM reaches out for feedback', expectedImpact: 'Reduces churn by 12%' },
    { name: 'Win-back offer', trigger: 'Subscription cancelled', action: 'Send 30% discount for 3 months', expectedImpact: 'Recovers 8% of churned customers' },
  ],
  kpis: [
    { name: 'Monthly Recurring Revenue', label: 'MRR', formula: 'Sum of all active subscriptions', benchmark: '$10K-100K', unit: '$', category: 'revenue' },
    { name: 'Churn Rate', label: 'Churn', formula: 'Cancelled / Total subscribers × 100', benchmark: '3-7%/month', unit: '%', category: 'retention' },
    { name: 'Trial-to-Paid Conversion', label: 'Trial Conv.', formula: 'Paid conversions / Trial signups × 100', benchmark: '10-20%', unit: '%', category: 'growth' },
    { name: 'Activation Rate', label: 'Activation', formula: 'Users reaching activation / Total signups × 100', benchmark: '30-50%', unit: '%', category: 'engagement' },
    { name: 'Net Revenue Retention', label: 'NRR', formula: '(MRR start + expansion - contraction - churn) / MRR start', benchmark: '100-120%', unit: '%', category: 'revenue' },
    { name: 'Customer Lifetime Value', label: 'LTV', formula: 'ARPU / Monthly churn rate', benchmark: '$500-5,000', unit: '$', category: 'revenue' },
    { name: 'CAC Payback Period', label: 'CAC Payback', formula: 'CAC / ARPU', benchmark: '6-12 months', unit: 'months', category: 'growth' },
    { name: 'Daily Active Users', label: 'DAU', formula: 'Unique logins today', benchmark: '20-40% of total', unit: 'count', category: 'engagement' },
  ],
  dashboardWidgets: [
    { name: 'MRR Trend', type: 'chart', description: 'Monthly recurring revenue trend with MRR breakdown', kpis: ['Monthly Recurring Revenue'], priority: 'primary' },
    { name: 'Churn Tracker', type: 'chart', description: 'Churn rate trend with cohort analysis', kpis: ['Churn Rate'], priority: 'primary' },
    { name: 'Trial Funnel', type: 'chart', description: 'Trial to paid conversion funnel', kpis: ['Trial-to-Paid Conversion'], priority: 'primary' },
    { name: 'Activation Metrics', type: 'stat-card', description: 'Users reaching activation milestones', kpis: ['Activation Rate'], priority: 'secondary' },
    { name: 'Feature Usage', type: 'table', description: 'Top features by usage frequency', kpis: ['Daily Active Users'], priority: 'secondary' },
    { name: 'Expansion Revenue', type: 'chart', description: 'Upsells and seat additions over time', kpis: ['Net Revenue Retention'], priority: 'secondary' },
  ],
  leadCaptureMechanisms: [
    { name: 'Free Trial Signup', headline: 'Start Your Free 14-Day Trial', fields: ['name', 'email', 'company'], nextStep: 'Onboarding wizard', conversionRate: '8-12% of visitors' },
    { name: 'Demo Request', headline: 'See It In Action', fields: ['name', 'email', 'company', 'team_size'], nextStep: 'Sales demo call', conversionRate: '15-20% of visitors' },
    { name: 'Newsletter', headline: 'Get Product Updates', fields: ['email'], nextStep: 'Nurture sequence', conversionRate: '25-35% of visitors' },
  ],
  morningCheck: {
    primaryMetrics: ['MRR', 'New signups today', 'Trial conversions', 'Churn alerts'],
    secondaryMetrics: ['DAU/WAU ratio', 'Feature adoption', 'Support ticket volume', 'Revenue per user'],
    alertConditions: ['MRR dropped >3%', 'Churn rate >8%', 'Trial conversion <5%', 'Support SLA breach'],
  },
  revenueModels: [
    { name: 'Monthly Subscription', description: 'Recurring monthly plan fees', percentage: 70 },
    { name: 'Annual Subscription', description: 'Discounted yearly plans', percentage: 15 },
    { name: 'Seat Expansion', description: 'Additional team member seats', percentage: 10 },
    { name: 'Usage Overage', description: 'Pay-per-use for exceeding limits', percentage: 5 },
  ],
  vocabulary: {
    'customer': 'user',
    'product': 'feature',
    'buy': 'subscribe',
    'store': 'platform',
    'cart': 'workspace',
    'checkout': 'upgrade',
    'price': 'plan',
    'order': 'subscription',
  },
};
