import type { BusinessIntelligenceProfile } from '../../schemas/knowledge/business-intelligence.schema.js';

export const SUPPLEMENT_MARKETPLACE_BI: BusinessIntelligenceProfile = {
  id: 'bi.ecommerce.supplement',
  version: '1.0.0',
  name: 'Supplement Marketplace',
  description: 'How a supplement marketplace makes money: discovery → product research → purchase → subscription → loyalty → advocacy',
  revenueCycle: {
    name: 'Discovery → Research → Purchase → Subscription → Loyalty',
    description: 'Customer discovers supplements → researches products → first purchase → subscribes for auto-delivery → loyalty program → refers friends',
    steps: [
      { name: 'Discovery', action: 'Customer finds marketplace via search/ad/influencer', conversionRate: 0.08, avgTimeToNext: '1-7 days', revenueImpact: 'high' },
      { name: 'Product research', action: 'Customer reads reviews/ingredients/labels', conversionRate: 0.40, avgTimeToNext: '0-3 days', revenueImpact: 'critical' },
      { name: 'First purchase', action: 'Customer places first order', conversionRate: 0.15, avgTimeToNext: '1-7 days', revenueImpact: 'critical' },
      { name: 'Subscription signup', action: 'Customer subscribes for auto-delivery', conversionRate: 0.20, avgTimeToNext: '14-30 days', revenueImpact: 'high' },
      { name: 'Repeat purchase', action: 'Customer reorders (one-time or subscription)', conversionRate: 0.45, avgTimeToNext: '30-90 days', revenueImpact: 'critical' },
      { name: 'Loyalty enrollment', action: 'Customer joins loyalty program', conversionRate: 0.30, avgTimeToNext: '30-60 days', revenueImpact: 'medium' },
      { name: 'Referral', action: 'Customer refers friends/family', conversionRate: 0.10, avgTimeToNext: '30-180 days', revenueImpact: 'medium' },
    ],
    avgCycleLength: '7-30 days',
    avgRevenuePerCustomer: '$50-200 per order',
  },
  conversionFunnel: {
    name: 'Discovery → Research → Purchase → Subscribe',
    stages: ['Website Visit', 'Product View', 'Add to Cart', 'Checkout', 'First Order', 'Subscription', 'Referral'],
    overallConversionRate: '2-4% of visitors purchase',
    biggestDropOff: 'Product view → Add to cart (85% don\'t add)',
  },
  churnSignals: [
    { name: 'Subscription cancelled', detection: 'Auto-delivery subscription stopped', window: '0 days', severity: 'critical' },
    { name: 'No reorder in 60 days', detection: 'Customer hasn\'t reordered in 60 days', window: '60 days', severity: 'high' },
    { name: 'Product return', detection: 'Customer returns supplement', window: '0 days', severity: 'high' },
    { name: 'Negative review', detection: 'Customer leaves 1-2 star review', window: '7 days', severity: 'critical' },
    { name: 'Low engagement', detection: 'Customer hasn\'t logged in for 30 days', window: '30 days', severity: 'medium' },
  ],
  retentionAutomations: [
    { name: 'Replenishment reminder', trigger: '5 days before estimated supply runs out', action: 'Send reorder reminder with one-click reorder', expectedImpact: 'Recovers 25% of lapsed subscribers' },
    { name: 'Subscription pause offer', trigger: 'Customer tries to cancel', action: 'Offer to pause subscription instead', expectedImpact: 'Retains 30% of would-be cancellations' },
    { name: 'Loyalty rewards', trigger: 'Every $50 spent', action: 'Send loyalty points + reward options', expectedImpact: 'Increases repeat rate by 20%' },
    { name: 'New product alert', trigger: 'Based on purchase history', action: 'Recommend new supplements matching goals', expectedImpact: 'Generates 15% additional revenue' },
    { name: 'FSSAI compliance badge', trigger: 'All products', action: 'Display FSSAI certification prominently', expectedImpact: 'Increases trust and conversion by 10%' },
  ],
  kpis: [
    { name: 'Revenue', label: 'Revenue', formula: 'Total sales revenue', benchmark: '$20K-200K/month', unit: '$', category: 'revenue' },
    { name: 'Orders', label: 'Orders', formula: 'Total orders this month', benchmark: '500-5,000/month', unit: 'count', category: 'revenue' },
    { name: 'Average Order Value', label: 'AOV', formula: 'Total revenue / Total orders', benchmark: '$50-150', unit: '$', category: 'revenue' },
    { name: 'Subscription Rate', label: 'Subscription', formula: 'Subscribers / Total customers × 100', benchmark: '20-40%', unit: '%', category: 'revenue' },
    { name: 'Customer Retention Rate', label: 'Retention', formula: 'Repeat customers / Total customers × 100', benchmark: '30-50%', unit: '%', category: 'retention' },
    { name: 'Customer Lifetime Value', label: 'LTV', formula: 'AOV × Purchase frequency × Lifespan', benchmark: '$200-800', unit: '$', category: 'revenue' },
    { name: 'Return Rate', label: 'Returns', formula: 'Returns / Orders × 100', benchmark: '3-8%', unit: '%', category: 'operations' },
    { name: 'Referral Rate', label: 'Referrals', formula: 'Referral orders / Total orders × 100', benchmark: '8-15%', unit: '%', category: 'growth' },
  ],
  dashboardWidgets: [
    { name: 'Revenue Dashboard', type: 'chart', description: 'Sales revenue and subscription trends', kpis: ['Revenue', 'Subscription Rate'], priority: 'primary' },
    { name: 'Order Pipeline', type: 'table', description: 'Recent orders with status and customer details', kpis: ['Orders', 'Average Order Value'], priority: 'primary' },
    { name: 'Customer Metrics', type: 'stat-card', description: 'Retention, LTV, and loyalty metrics', kpis: ['Customer Retention Rate', 'Customer Lifetime Value'], priority: 'secondary' },
    { name: 'Product Performance', type: 'chart', description: 'Top products by revenue and units', kpis: ['Return Rate', 'Referral Rate'], priority: 'secondary' },
  ],
  leadCaptureMechanisms: [
    { name: 'First Purchase Offer', headline: 'Get 15% Off Your First Order', fields: ['email'], nextStep: 'Welcome email with discount code', conversionRate: '10-20% of visitors' },
    { name: 'Quiz', headline: 'Find Your Perfect Supplement Stack', fields: ['email', 'goals'], nextStep: 'Personalized recommendations', conversionRate: '15-25% of visitors' },
    { name: 'Newsletter', headline: 'Health Tips & Exclusive Deals', fields: ['email'], nextStep: 'Nurture sequence with content + offers', conversionRate: '20-30% of visitors' },
  ],
  morningCheck: {
    primaryMetrics: ['Revenue today', 'Orders today', 'Subscription renewals', 'FSSAI compliance status'],
    secondaryMetrics: ['Top selling products', 'Inventory alerts', 'Customer reviews', 'Marketing ROI'],
    alertConditions: ['Revenue dropped >15%', 'Subscription churn spike', 'FSSAI compliance issue', 'Negative review posted'],
  },
  revenueModels: [
    { name: 'One-Time Purchases', description: 'Individual supplement orders', percentage: 55 },
    { name: 'Subscriptions', description: 'Auto-delivery subscription orders', percentage: 30 },
    { name: 'Bundles', description: 'Pre-configured supplement stacks', percentage: 10 },
    { name: 'Affiliate Commissions', description: 'Revenue from brand partnerships', percentage: 5 },
  ],
  vocabulary: {
    'customer': 'health enthusiast',
    'product': 'supplement',
    'buy': 'order',
    'store': 'marketplace',
    'cart': 'cart',
    'checkout': 'checkout',
    'price': 'price',
    'order': 'order',
  },
};
