import type { BusinessIntelligenceProfile } from '../../schemas/knowledge/business-intelligence.schema.js';

export const TRAVEL_BI: BusinessIntelligenceProfile = {
  id: 'bi.travel.agency',
  version: '1.0.0',
  name: 'Travel Agency / Tour Operator',
  description: 'How a travel business makes money: inspiration → planning → booking → trip → review → referral → rebooking',
  revenueCycle: {
    name: 'Inspiration → Planning → Booking → Trip → Rebooking',
    description: 'Traveler discovers destination → requests quote → books trip → travels → leaves review → rebooks or refers',
    steps: [
      { name: 'Inspiration', action: 'Traveler discovers destination via search/social', conversionRate: 0.05, avgTimeToNext: '1-30 days', revenueImpact: 'high' },
      { name: 'Inquiry', action: 'Traveler requests quote or consultation', conversionRate: 0.20, avgTimeToNext: '1-7 days', revenueImpact: 'critical' },
      { name: 'Planning', action: 'Agent creates custom itinerary', conversionRate: 0.60, avgTimeToNext: '3-14 days', revenueImpact: 'high' },
      { name: 'Booking', action: 'Traveler confirms and pays deposit', conversionRate: 0.50, avgTimeToNext: '1-7 days', revenueImpact: 'critical' },
      { name: 'Trip completed', action: 'Traveler completes trip', conversionRate: 0.95, avgTimeToNext: '30-365 days', revenueImpact: 'high' },
      { name: 'Review left', action: 'Traveler leaves review or testimonial', conversionRate: 0.30, avgTimeToNext: '1-7 days', revenueImpact: 'medium' },
      { name: 'Rebooking', action: 'Traveler books another trip', conversionRate: 0.25, avgTimeToNext: '90-365 days', revenueImpact: 'high' },
    ],
    avgCycleLength: '30-365 days',
    avgRevenuePerCustomer: '$1,000-10,000 per trip',
  },
  conversionFunnel: {
    name: 'Inspiration → Inquiry → Booking → Trip',
    stages: ['Website Visit', 'Destination View', 'Inquiry', 'Quote Sent', 'Booking Confirmed', 'Trip Completed', 'Referral'],
    overallConversionRate: '2-4% of visitors book',
    biggestDropOff: 'Quote sent → Booking (50% don\'t book)',
  },
  churnSignals: [
    { name: 'Quote not accepted', detection: 'Quote sent but no response in 14 days', window: '14 days', severity: 'high' },
    { name: 'Booking cancellation', detection: 'Traveler cancels booking', window: '0 days', severity: 'critical' },
    { name: 'No rebooking', detection: 'Traveler hasn\'t booked in 18+ months', window: '540 days', severity: 'medium' },
    { name: 'Negative review', detection: 'Traveler leaves negative review', window: '7 days', severity: 'critical' },
    { name: 'Competition comparison', detection: 'Traveler asks for price match', window: '7 days', severity: 'medium' },
  ],
  retentionAutomations: [
    { name: 'Post-trip follow-up', trigger: '7 days after return', action: 'Request review + photo sharing', expectedImpact: 'Increases reviews by 40%' },
    { name: 'Anniversary reminder', trigger: '1 year since trip', action: 'Send trip memories + new destinations', expectedImpact: 'Generates 15% rebookings' },
    { name: 'Early bird offer', trigger: '6 months before peak season', action: 'Send early booking discounts', expectedImpact: 'Increases early bookings by 20%' },
    { name: 'Loyalty program', trigger: '2+ trips booked', action: 'Enroll in VIP program with perks', expectedImpact: 'Increases rebooking by 30%' },
  ],
  kpis: [
    { name: 'Revenue', label: 'Revenue', formula: 'Total bookings revenue', benchmark: '$20K-200K/month', unit: '$', category: 'revenue' },
    { name: 'Bookings', label: 'Bookings', formula: 'Total bookings this month', benchmark: '20-100/month', unit: 'count', category: 'revenue' },
    { name: 'Average Trip Value', label: 'Avg Trip', formula: 'Total revenue / Total bookings', benchmark: '$2,000-8,000', unit: '$', category: 'revenue' },
    { name: 'Conversion Rate', label: 'Conv. Rate', formula: 'Bookings / Inquiries × 100', benchmark: '10-25%', unit: '%', category: 'growth' },
    { name: 'Client Retention Rate', label: 'Retention', formula: 'Returning clients / Total clients × 100', benchmark: '25-40%', unit: '%', category: 'retention' },
    { name: 'Trip Rating', label: 'Rating', formula: 'Average trip rating', benchmark: '4.5-4.8 stars', unit: 'stars', category: 'engagement' },
    { name: 'Referral Rate', label: 'Referrals', formula: 'Referral bookings / Total bookings × 100', benchmark: '15-30%', unit: '%', category: 'growth' },
    { name: 'Cancellation Rate', label: 'Cancellations', formula: 'Cancellations / Total bookings × 100', benchmark: '5-10%', unit: '%', category: 'operations' },
  ],
  dashboardWidgets: [
    { name: 'Revenue Dashboard', type: 'chart', description: 'Booking revenue and seasonal trends', kpis: ['Revenue', 'Average Trip Value'], priority: 'primary' },
    { name: 'Booking Pipeline', type: 'table', description: 'Active bookings with status and departure dates', kpis: ['Bookings', 'Conversion Rate'], priority: 'primary' },
    { name: 'Client Metrics', type: 'stat-card', description: 'Retention, satisfaction, and referrals', kpis: ['Client Retention Rate', 'Trip Rating'], priority: 'secondary' },
    { name: 'Seasonal Forecast', type: 'chart', description: 'Booking trends by season and destination', kpis: ['Cancellation Rate', 'Referral Rate'], priority: 'secondary' },
  ],
  leadCaptureMechanisms: [
    { name: 'Trip Inquiry', headline: 'Plan Your Dream Trip', fields: ['name', 'email', 'phone', 'destination', 'dates', 'budget'], nextStep: 'Consultation call + custom quote', conversionRate: '10-15% of visitors' },
    { name: 'Newsletter', headline: 'Travel Deals & Inspiration', fields: ['email'], nextStep: 'Destination inspiration emails', conversionRate: '15-25% of visitors' },
    { name: 'Brochure Download', headline: 'Free Travel Guide', fields: ['name', 'email', 'destination_interest'], nextStep: 'Guide delivery + follow-up', conversionRate: '20-30% of visitors' },
  ],
  morningCheck: {
    primaryMetrics: ['Inquiries today', 'Pending bookings', 'Departures this week', 'Revenue this month'],
    secondaryMetrics: ['Active quotes', 'Client feedback', 'Partner availability', 'Marketing performance'],
    alertConditions: ['Departure in 48 hours + issue', 'Quote pending >7 days', 'Client complaint', 'Partner overbooked'],
  },
  revenueModels: [
    { name: 'Commissions', description: 'Supplier commissions (hotels, airlines)', percentage: 45 },
    { name: 'Service Fees', description: 'Planning and booking service fees', percentage: 30 },
    { name: 'Packages', description: 'Bundled tour packages', percentage: 20 },
    { name: 'Insurance', description: 'Travel insurance commissions', percentage: 5 },
  ],
  vocabulary: {
    'customer': 'traveler',
    'product': 'trip',
    'buy': 'book',
    'store': 'agency',
    'cart': 'itinerary',
    'checkout': 'booking',
    'price': 'fare',
    'order': 'reservation',
  },
};
