/**
 * Auth Generator — produces working authentication code for FastAPI and Next.js.
 *
 * Generates:
 * - JWT access + refresh tokens
 * - Password hashing (bcrypt / argon2)
 * - Login / register endpoints for FastAPI and Next.js
 * - Auth middleware with RBAC support
 * - Session management (cookie or header)
 * - CSRF protection, rate limiting, proper error responses
 *
 * Every output is a real, copy-paste-ready file — not a template placeholder.
 */

// ─── Types ────────────────────────────────────────────────────────────────────

export interface AuthConfig {
  provider: 'jwt' | 'session';
  passwordHashing: 'bcrypt' | 'argon2';
  tokenExpiry: string;
  refreshExpiry: string;
  secretKey: string;
  roles?: string[];
  rateLimitWindow?: string;
  rateLimitMax?: number;
  cookieDomain?: string;
  csrfEnabled?: boolean;
}

export interface AuthCode {
  fastapi: {
    authRouter: string;
    middleware: string;
    models: string;
    utils: string;
  };
  nextjs: {
    authApi: string;
    middleware: string;
    authHook: string;
    loginPage: string;
    registerPage: string;
  };
  config: string;
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function rolesList(config: AuthConfig): string[] {
  return config.roles ?? ['admin', 'user'];
}

function tokenExpiryPy(config: AuthConfig): string {
  if (config.tokenExpiry.includes('m')) {
    return 'timedelta(minutes=' + config.tokenExpiry.replace('m', '').trim() + ')';
  }
  return 'timedelta(hours=' + config.tokenExpiry.replace('h', '').trim() + ')';
}

function refreshExpiryPy(config: AuthConfig): string {
  if (config.refreshExpiry.includes('d')) {
    return 'timedelta(days=' + config.refreshExpiry.replace('d', '').trim() + ')';
  }
  return 'timedelta(hours=' + config.refreshExpiry.replace('h', '').trim() + ')';
}

function rateWindowPy(config: AuthConfig): string {
  if (!config.rateLimitWindow) return '60.0';
  if (config.rateLimitWindow.includes('m')) {
    return config.rateLimitWindow.replace('m', '').trim() + '.0 * 60';
  }
  return config.rateLimitWindow.replace('h', '').trim() + '.0 * 3600';
}

function rateWindowMs(config: AuthConfig): string {
  if (!config.rateLimitWindow) return '60 * 1000';
  if (config.rateLimitWindow.includes('m')) {
    return config.rateLimitWindow.replace('m', '').trim() + ' * 60 * 1000';
  }
  return config.rateLimitWindow.replace('h', '').trim() + ' * 3600 * 1000';
}

function refreshMaxAge(config: AuthConfig): string {
  if (config.refreshExpiry.includes('d')) {
    return "parseInt('" + config.refreshExpiry.replace('d', '').trim() + "') * 86400";
  }
  return '7 * 86400';
}

// ─── FastAPI Auth Router ──────────────────────────────────────────────────────

function generateFastAPIAuthRouter(config: AuthConfig): string {
  const csrfImport = config.csrfEnabled !== false
    ? 'import secrets\nfrom middleware.auth import csrf_protect'
    : '# CSRF protection is disabled for this configuration.';

  const cookieBlock = config.csrfEnabled !== false
    ? [
        '    if True:',
        '        response.set_cookie(',
        '            key="access_token",',
        '            value=access,',
        '            httponly=True,',
        '            secure=True,',
        '            samesite="lax",',
        '            max_age=int(ACCESS_TOKEN_EXPIRE.total_seconds()),',
        '            domain=os.environ.get("COOKIE_DOMAIN", None),',
        '        )',
        '        response.set_cookie(',
        '            key="refresh_token",',
        '            value=refresh,',
        '            httponly=True,',
        '            secure=True,',
        '            samesite="lax",',
        '            max_age=int(REFRESH_TOKEN_EXPIRE.total_seconds()),',
        '            domain=os.environ.get("COOKIE_DOMAIN", None),',
        '        )',
      ].join('\n')
    : [
        '    response.set_cookie(',
        '        key="access_token",',
        '        value=access,',
        '        httponly=True,',
        '        secure=True,',
        '        samesite="lax",',
        '        max_age=int(ACCESS_TOKEN_EXPIRE.total_seconds()),',
        '        domain=os.environ.get("COOKIE_DOMAIN", None),',
        '    )',
        '    response.set_cookie(',
        '        key="refresh_token",',
        '        value=refresh,',
        '        httponly=True,',
        '        secure=True,',
        '        samesite="lax",',
        '        max_age=int(REFRESH_TOKEN_EXPIRE.total_seconds()),',
        '        domain=os.environ.get("COOKIE_DOMAIN", None),',
        '    )',
      ].join('\n');

  return [
    '"""',
    'Auth Router — login, register, refresh, logout endpoints.',
    '',
    'Usage in main.py:',
    '    from routes.auth import auth_router',
    '    app.include_router(auth_router, prefix="/api/auth", tags=["auth"])',
    '"""',
    'from __future__ import annotations',
    '',
    'from datetime import datetime, timedelta, timezone',
    'from typing import Annotated',
    '',
    'from fastapi import APIRouter, Depends, HTTPException, Request, Response, status',
    'from fastapi.security import OAuth2PasswordBearer, OAuth2PasswordRequestForm',
    'from jose import JWTError, jwt',
    'from pydantic import BaseModel, EmailStr, Field, field_validator',
    'from sqlalchemy import select',
    'from sqlalchemy.ext.asyncio import AsyncSession',
    '',
    'from database import get_db',
    'from models.auth import User',
    'from middleware.auth import get_current_user, require_roles',
    'from utils.security import (',
    "    create_access_token, create_refresh_token, decode_token",
    ')',
    '',
    'auth_router = APIRouter()',
    'oauth2_scheme = OAuth2PasswordBearer(tokenUrl="/api/auth/login")',
    '',
    '# \u2500\u2500\u2500 Config \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500',
    '',
    'import os',
    '',
    'SECRET_KEY = os.environ.get("' + config.secretKey + '", "CHANGE-ME-IN-PRODUCTION")',
    'ALGORITHM = "HS256"',
    'ACCESS_TOKEN_EXPIRE = ' + tokenExpiryPy(config),
    'REFRESH_TOKEN_EXPIRE = ' + refreshExpiryPy(config),
    '',
    '# \u2500\u2500\u2500 Rate Limiting (simple in-memory) \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500',
    '',
    'from collections import defaultdict',
    'import time',
    '',
    '_rate_store: dict[str, list[float]] = defaultdict(list)',
    'RATE_WINDOW = ' + rateWindowPy(config),
    'RATE_MAX = ' + String(config.rateLimitMax ?? 30),
    '',
    'def check_rate_limit(key: str) -> None:',
    '    now = time.time()',
    '    _rate_store[key] = [t for t in _rate_store[key] if now - t < RATE_WINDOW]',
    '    if len(_rate_store[key]) >= RATE_MAX:',
    '        raise HTTPException(',
    '            status_code=status.HTTP_429_TOO_MANY_REQUESTS,',
    '            detail="Too many requests. Please try again later.",',
    '        )',
    '    _rate_store[key].append(now)',
    '',
    '# \u2500\u2500\u2500 CSRF Protection \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500',
    '',
    csrfImport,
    '',
    '# \u2500\u2500\u2500 Password Validation \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500',
    '',
    'import re',
    '',
    '_PASSWORD_RE = re.compile(r"^(?=.*[a-z])(?=.*[A-Z])(?=.*\\\\d)(?=.*[!@#$%^&*]).{8,}$")',
    '',
    'def validate_password(password: str) -> str:',
    '    if len(password) < 8:',
    '        raise HTTPException(status_code=422, detail="Password must be at least 8 characters.")',
    '    if not _PASSWORD_RE.match(password):',
    '        raise HTTPException(',
    '            status_code=422,',
    '            detail="Password must include uppercase, lowercase, digit, and special character.",',
    '        )',
    '    return password',
    '',
    '# \u2500\u2500\u2500 Schemas \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500',
    '',
    'class RegisterRequest(BaseModel):',
    '    email: EmailStr',
    '    password: str = Field(..., min_length=8)',
    '    name: str = Field(..., min_length=1, max_length=100)',
    '',
    '    @field_validator("password")',
    '    @classmethod',
    '    def strong_password(cls, v: str) -> str:',
    '        return validate_password(v)',
    '',
    'class LoginRequest(BaseModel):',
    '    email: EmailStr',
    '    password: str',
    '',
    'class TokenResponse(BaseModel):',
    '    access_token: str',
    '    refresh_token: str',
    '    token_type: str = "bearer"',
    '    expires_in: int',
    '',
    'class UserResponse(BaseModel):',
    '    id: int',
    '    email: str',
    '    name: str',
    '    role: str',
    '    created_at: datetime',
    '',
    '# \u2500\u2500\u2500 Token Helpers \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500',
    '',
    'def create_access_token(data: dict) -> str:',
    '    to_encode = data.copy()',
    '    expire = datetime.now(timezone.utc) + ACCESS_TOKEN_EXPIRE',
    '    to_encode.update({"exp": expire, "type": "access"})',
    '    return jwt.encode(to_encode, SECRET_KEY, algorithm=ALGORITHM)',
    '',
    'def create_refresh_token(data: dict) -> str:',
    '    to_encode = data.copy()',
    '    expire = datetime.now(timezone.utc) + REFRESH_TOKEN_EXPIRE',
    '    to_encode.update({"exp": expire, "type": "refresh"})',
    '    return jwt.encode(to_encode, SECRET_KEY, algorithm=ALGORITHM)',
    '',
    'def decode_token(token: str) -> dict:',
    '    try:',
    '        payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])',
    '        return payload',
    '    except JWTError:',
    '        raise HTTPException(',
    '            status_code=status.HTTP_401_UNAUTHORIZED,',
    '            detail="Invalid or expired token.",',
    '            headers={"WWW-Authenticate": "Bearer"},',
    '        )',
    '',
    '# \u2500\u2500\u2500 Routes \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500',
    '',
    '@auth_router.post("/register", response_model=UserResponse, status_code=status.HTTP_201_CREATED)',
    'async def register(body: RegisterRequest, request: Request, db: Annotated[AsyncSession, Depends(get_db)]):',
    "    check_rate_limit(f\"register:{request.client.host if request.client else 'unknown'}\")",
    '',
    '    existing = await db.execute(select(User).where(User.email == body.email))',
    '    if existing.scalar_one_or_none():',
    '        raise HTTPException(status_code=status.HTTP_409_CONFLICT, detail="Email already registered.")',
    '',
    '    user = User(',
    '        email=body.email,',
    '        hashed_password=hash_password(body.password),',
    '        name=body.name,',
    '        role="user",',
    '        created_at=datetime.now(timezone.utc),',
    '    )',
    '    db.add(user)',
    '    await db.commit()',
    '    await db.refresh(user)',
    '    return user',
    '',
    '',
    '@auth_router.post("/login", response_model=TokenResponse)',
    'async def login(body: LoginRequest, request: Request, response: Response, db: Annotated[AsyncSession, Depends(get_db)]):',
    "    check_rate_limit(f\"login:{request.client.host if request.client else 'unknown'}\")",
    '',
    '    result = await db.execute(select(User).where(User.email == body.email))',
    '    user = result.scalar_one_or_none()',
    '    if not user or not verify_password(body.password, user.hashed_password):',
    '        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Invalid credentials.")',
    '',
    '    access = create_access_token({"sub": str(user.id), "role": user.role})',
    '    refresh = create_refresh_token({"sub": str(user.id), "role": user.role})',
    '',
    cookieBlock,
    '',
    '    return TokenResponse(',
    '        access_token=access,',
    '        refresh_token=refresh,',
    '        expires_in=int(ACCESS_TOKEN_EXPIRE.total_seconds()),',
    '    )',
    '',
    '',
    '@auth_router.post("/refresh", response_model=TokenResponse)',
    'async def refresh_token(request: Request, db: Annotated[AsyncSession, Depends(get_db)]):',
    "    check_rate_limit(f\"refresh:{request.client.host if request.client else 'unknown'}\")",
    '',
    '    token = request.cookies.get("refresh_token")',
    '    if not token:',
    '        body = await request.json()',
    '        token = body.get("refresh_token")',
    '    if not token:',
    '        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Refresh token required.")',
    '',
    '    payload = decode_token(token)',
    '    if payload.get("type") != "refresh":',
    '        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Invalid token type.")',
    '',
    '    user_id = payload.get("sub")',
    '    result = await db.execute(select(User).where(User.id == int(user_id)))',
    '    user = result.scalar_one_or_none()',
    '    if not user:',
    '        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="User not found.")',
    '',
    '    access = create_access_token({"sub": str(user.id), "role": user.role})',
    '    new_refresh = create_refresh_token({"sub": str(user.id), "role": user.role})',
    '',
    '    return TokenResponse(',
    '        access_token=access,',
    '        refresh_token=new_refresh,',
    '        expires_in=int(ACCESS_TOKEN_EXPIRE.total_seconds()),',
    '    )',
    '',
    '',
    '@auth_router.post("/logout", status_code=status.HTTP_204_NO_CONTENT)',
    'async def logout(response: Response):',
    '    response.delete_cookie("access_token")',
    '    response.delete_cookie("refresh_token")',
    '    return None',
    '',
    '',
    '@auth_router.get("/me", response_model=UserResponse)',
    'async def me(current_user: Annotated[User, Depends(get_current_user)]):',
    '    return current_user',
    '',
  ].join('\n');
}

function String(val: number | string): string {
  return String(val);
}

// ─── FastAPI Middleware ───────────────────────────────────────────────────────

function generateFastAPIMiddleware(config: AuthConfig): string {
  const csrfBlock = config.csrfEnabled !== false
    ? [
        '',
        '# \u2500\u2500\u2500 CSRF Protection \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500',
        '',
        'def create_csrf_token(session_id: str) -> str:',
        '    timestamp = str(int(datetime.now(timezone.utc).timestamp()))',
        '    payload = f"{session_id}:{timestamp}"',
        '    signature = hmac.new(CSRF_SECRET.encode(), payload.encode(), hashlib.sha256).hexdigest()',
        '    return f"{payload}:{signature}"',
        '',
        'def verify_csrf_token(token: str, session_id: str) -> bool:',
        '    parts = token.split(":")',
        '    if len(parts) != 3:',
        '        return False',
        '    payload_ts = f"{session_id}:{parts[1]}"',
        '    expected = hmac.new(CSRF_SECRET.encode(), payload_ts.encode(), hashlib.sha256).hexdigest()',
        '    return hmac.compare_digest(expected, parts[2])',
        '',
        'async def csrf_protect(request: Request):',
        '    if request.method in ("GET", "HEAD", "OPTIONS"):',
        '        return',
        '    if request.url.path.startswith("/api/"):',
        '        token = request.headers.get("X-CSRF-Token") or request.cookies.get("csrf_token")',
        '        session_id = request.cookies.get("session_id", "")',
        '        if not token or not verify_csrf_token(token, session_id):',
        '            raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="Invalid CSRF token.")',
        '',
      ].join('\n')
    : '';

  return [
    '"""',
    'Auth Middleware \u2014 JWT verification, role-based access control, CSRF protection.',
    '"""',
    'from __future__ import annotations',
    '',
    'import hashlib',
    'import hmac',
    'import os',
    'import secrets',
    'from datetime import datetime, timezone',
    'from typing import Annotated',
    '',
    'from fastapi import Cookie, Depends, HTTPException, Request, status',
    'from fastapi.security import HTTPAuthorizationCredentials, HTTPBearer',
    'from jose import JWTError, jwt',
    '',
    'security = HTTPBearer(auto_error=False)',
    '',
    'SECRET_KEY = os.environ.get("' + config.secretKey + '", "CHANGE-ME-IN-PRODUCTION")',
    'ALGORITHM = "HS256"',
    'CSRF_SECRET = os.environ.get("CSRF_SECRET", os.urandom(32).hex())',
    '',
    csrfBlock,
    '# \u2500\u2500\u2500 Token Verification \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500',
    '',
    'def decode_token(token: str) -> dict:',
    '    try:',
    '        payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])',
    '        exp = payload.get("exp")',
    '        if exp and datetime.fromtimestamp(exp, tz=timezone.utc) < datetime.now(timezone.utc):',
    '            raise HTTPException(',
    '                status_code=status.HTTP_401_UNAUTHORIZED,',
    '                detail="Token has expired.",',
    '                headers={"WWW-Authenticate": "Bearer"},',
    '            )',
    '        return payload',
    '    except JWTError:',
    '        raise HTTPException(',
    '            status_code=status.HTTP_401_UNAUTHORIZED,',
    '            detail="Invalid token.",',
    '            headers={"WWW-Authenticate": "Bearer"},',
    '        )',
    '',
    '# \u2500\u2500\u2500 Current User Dependency \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500',
    '',
    'async def get_current_user(',
    '    request: Request,',
    '    credentials: Annotated[HTTPAuthorizationCredentials | None, Depends(security)] = None,',
    '):',
    '    token: str | None = None',
    '',
    '    if credentials:',
    '        token = credentials.credentials',
    '    else:',
    '        token = request.cookies.get("access_token")',
    '',
    '    if not token:',
    '        raise HTTPException(',
    '            status_code=status.HTTP_401_UNAUTHORIZED,',
    '            detail="Not authenticated.",',
    '            headers={"WWW-Authenticate": "Bearer"},',
    '        )',
    '',
    '    payload = decode_token(token)',
    '    user_id = payload.get("sub")',
    '    if not user_id:',
    '        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Invalid token payload.")',
    '',
    '    request.state.user_id = user_id',
    '    request.state.user_role = payload.get("role", "user")',
    '    return {"id": user_id, "role": payload.get("role", "user")}',
    '',
    '# \u2500\u2500\u2500 Role-Based Access Control \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500',
    '',
    'def require_roles(*allowed_roles: str):',
    '    async def role_checker(',
    '        current_user: Annotated[dict, Depends(get_current_user)],',
    '    ):',
    '        user_role = current_user.get("role", "")',
    '        if user_role not in allowed_roles:',
    '            raise HTTPException(',
    '                status_code=status.HTTP_403_FORBIDDEN,',
    '                detail=f"Role \'{user_role}\' is not authorized. Required: {\', \'.join(allowed_roles)}",',
    '            )',
    '        return current_user',
    '    return Depends(role_checker)',
    '',
    '# \u2500\u2500\u2500 Convenience Defaults \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500',
    '',
    'require_admin = require_roles("admin")',
    'require_user = require_roles("user", "admin")',
    '',
  ].join('\n');
}

// ─── FastAPI Models ───────────────────────────────────────────────────────────

function generateFastAPIModels(config: AuthConfig): string {
  return [
    '"""',
    'Auth Models \u2014 SQLAlchemy ORM and Pydantic schemas for auth.',
    '"""',
    'from __future__ import annotations',
    '',
    'from datetime import datetime',
    '',
    'from pydantic import BaseModel, EmailStr',
    'from sqlalchemy import Boolean, DateTime, Integer, String, Text, func',
    'from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column',
    '',
    '',
    'class Base(DeclarativeBase):',
    '    pass',
    '',
    '',
    'class User(Base):',
    '    __tablename__ = "users"',
    '',
    '    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)',
    '    email: Mapped[str] = mapped_column(String(255), unique=True, nullable=False, index=True)',
    '    name: Mapped[str] = mapped_column(String(100), nullable=False)',
    '    hashed_password: Mapped[str] = mapped_column(Text, nullable=False)',
    '    role: Mapped[str] = mapped_column(String(50), nullable=False, default="user")',
    '    is_active: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)',
    '    created_at: Mapped[datetime] = mapped_column(',
    '        DateTime(timezone=True), server_default=func.now(), nullable=False',
    '    )',
    '    updated_at: Mapped[datetime] = mapped_column(',
    '        DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False',
    '    )',
    '',
    '    def __repr__(self) -> str:',
    '        return f"<User id={self.id} email={self.email!r} role={self.role!r}>"',
    '',
    '',
    'class RefreshToken(Base):',
    '    __tablename__ = "refresh_tokens"',
    '',
    '    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)',
    '    token: Mapped[str] = mapped_column(Text, unique=True, nullable=False, index=True)',
    '    user_id: Mapped[int] = mapped_column(Integer, nullable=False)',
    '    expires_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)',
    '    revoked: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)',
    '    created_at: Mapped[datetime] = mapped_column(',
    '        DateTime(timezone=True), server_default=func.now(), nullable=False',
    '    )',
    '',
  ].join('\n');
}

// ─── FastAPI Security Utils ───────────────────────────────────────────────────

function generateFastAPISecurityUtils(config: AuthConfig): string {
  const hashBlock = config.passwordHashing === 'argon2'
    ? [
        'from argon2 import PasswordHasher',
        'from argon2.exceptions import VerifyMismatchError',
        '',
        '_ph = PasswordHasher()',
        '',
        '',
        'def hash_password(plain: str) -> str:',
        '    return _ph.hash(plain)',
        '',
        '',
        'def verify_password(plain: str, hashed: str) -> bool:',
        '    try:',
        '        return _ph.verify(hashed, plain)',
        '    except VerifyMismatchError:',
        '        return False',
      ].join('\n')
    : [
        'import bcrypt',
        '',
        '',
        'def hash_password(plain: str) -> str:',
        '    return bcrypt.hashpw(plain.encode(), bcrypt.gensalt()).decode()',
        '',
        '',
        'def verify_password(plain: str, hashed: str) -> bool:',
        '    return bcrypt.checkpw(plain.encode(), hashed.encode())',
      ].join('\n');

  return [
    '"""',
    'Security Utils \u2014 password hashing and token utilities.',
    '"""',
    'from __future__ import annotations',
    '',
    'import os',
    'from datetime import datetime, timedelta, timezone',
    '',
    'from jose import jwt',
    'from passlib.context import CryptContext',
    '',
    hashBlock,
    '',
    'SECRET_KEY = os.environ.get("' + config.secretKey + '", "CHANGE-ME-IN-PRODUCTION")',
    'ALGORITHM = "HS256"',
    'ACCESS_TOKEN_EXPIRE = ' + tokenExpiryPy(config),
    'REFRESH_TOKEN_EXPIRE = ' + refreshExpiryPy(config),
    '',
    '# \u2500\u2500\u2500 Token Creation \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500',
    '',
    'def create_access_token(data: dict) -> str:',
    '    to_encode = data.copy()',
    '    expire = datetime.now(timezone.utc) + ACCESS_TOKEN_EXPIRE',
    '    to_encode.update({"exp": expire, "type": "access"})',
    '    return jwt.encode(to_encode, SECRET_KEY, algorithm=ALGORITHM)',
    '',
    '',
    'def create_refresh_token(data: dict) -> str:',
    '    to_encode = data.copy()',
    '    expire = datetime.now(timezone.utc) + REFRESH_TOKEN_EXPIRE',
    '    to_encode.update({"exp": expire, "type": "refresh"})',
    '    return jwt.encode(to_encode, SECRET_KEY, algorithm=ALGORITHM)',
    '',
    '',
    'def decode_token(token: str) -> dict:',
    '    from jose import JWTError',
    '    try:',
    '        payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])',
    '        return payload',
    '    except JWTError:',
    '        return {}',
    '',
  ].join('\n');
}

// ─── Next.js Auth API Route ───────────────────────────────────────────────────

function generateNextAuthApi(config: AuthConfig): string {
  return [
    '/**',
    ' * NextAuth API Route \u2014 handles login, register, refresh, logout.',
    ' *',
    ' * POST /api/auth/login    \u2014 { email, password } -> { access_token, refresh_token }',
    ' * POST /api/auth/register \u2014 { email, password, name } -> { user }',
    ' * POST /api/auth/refresh  \u2014 { refresh_token } -> { access_token }',
    ' * POST /api/auth/logout   \u2014 clears cookies',
    ' * GET  /api/auth/me       \u2014 returns current user from token',
    ' */',
    "import { NextRequest, NextResponse } from 'next/server';",
    '',
    "const API_SECRET = process.env." + config.secretKey + " || 'CHANGE-ME-IN-PRODUCTION';",
    "const BACKEND_URL = process.env.BACKEND_URL || 'http://localhost:8000';",
    '',
    'interface AuthUser {',
    '  id: number;',
    '  email: string;',
    '  name: string;',
    '  role: string;',
    '}',
    '',
    'interface TokenPayload {',
    '  sub: string;',
    '  role: string;',
    '  exp: number;',
    '  type: string;',
    '}',
    '',
    '// \u2500\u2500\u2500 Helpers \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500',
    '',
    'function jsonResponse(data: Record<string, unknown>, status = 200): NextResponse {',
    '  return NextResponse.json(data, {',
    '    status,',
    "    headers: { 'Content-Type': 'application/json' },",
    '  });',
    '}',
    '',
    'function errorResponse(message: string, status = 400): NextResponse {',
    '  return jsonResponse({ error: message }, status);',
    '}',
    '',
    '// \u2500\u2500\u2500 Password validation \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500',
    '',
    "const PASSWORD_RE = /^(?=.*[a-z])(?=.*[A-Z])(?=.*\\\\d)(?=.*[!@#$%^&*]).{8,}$/;",
    '',
    'function validatePassword(password: string): string | null {',
    "  if (password.length < 8) return 'Password must be at least 8 characters.';",
    "  if (!PASSWORD_RE.test(password)) return 'Password must include uppercase, lowercase, digit, and special character.';",
    '  return null;',
    '}',
    '',
    '// \u2500\u2500\u2500 Rate Limiting \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500',
    '',
    'const rateStore = new Map<string, number[]>();',
    'const RATE_WINDOW = ' + rateWindowMs(config) + ';',
    'const RATE_MAX = ' + (config.rateLimitMax ?? 30) + ';',
    '',
    'function checkRateLimit(key: string): boolean {',
    '  const now = Date.now();',
    '  const timestamps = (rateStore.get(key) ?? []).filter((t) => now - t < RATE_WINDOW);',
    '  if (timestamps.length >= RATE_MAX) return false;',
    '  timestamps.push(now);',
    '  rateStore.set(key, timestamps);',
    '  return true;',
    '}',
    '',
    '// \u2500\u2500\u2500 JWT Helpers (jose for edge runtime) \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500',
    '',
    "async function signToken(payload: Record<string, unknown>, expiresIn: string): Promise<string> {",
    "  const { SignJWT } = await import('jose');",
    '  const encoder = new TextEncoder();',
    '  const key = encoder.encode(API_SECRET);',
    "  const expiryMs = expiresIn.endsWith('h')",
    '    ? parseInt(expiresIn) * 3600 * 1000',
    "    : expiresIn.endsWith('d')",
    '    ? parseInt(expiresIn) * 86400 * 1000',
    '    : parseInt(expiresIn) * 60 * 1000;',
    '',
    '  const token = await new SignJWT(payload)',
    "    .setProtectedHeader({ alg: 'HS256' })",
    '    .setIssuedAt()',
    '    .setExpirationTime(Math.floor((Date.now() + expiryMs) / 1000))',
    '    .sign(key);',
    '',
    '  return token;',
    '}',
    '',
    'async function verifyToken(token: string): Promise<TokenPayload | null> {',
    '  try {',
    "    const { jwtVerify } = await import('jose');",
    '    const encoder = new TextEncoder();',
    '    const key = encoder.encode(API_SECRET);',
    '    const { payload } = await jwtVerify(token, key);',
    '    return payload as unknown as TokenPayload;',
    '  } catch {',
    '    return null;',
    '  }',
    '}',
    '',
    '// \u2500\u2500\u2500 CSRF Token \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500',
    '',
    'function generateCsrfToken(): string {',
    '  return crypto.randomUUID();',
    '}',
    '',
    '// \u2500\u2500\u2500 Route Handlers \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500',
    '',
    'export async function POST(request: NextRequest): Promise<NextResponse> {',
    '  const url = new URL(request.url);',
    "  const action = url.pathname.split('/').pop();",
    "  const ip = request.headers.get('x-forwarded-for') ?? 'unknown';",
    '',
    '  if (!checkRateLimit(action + ":" + ip)) {',
    "    return errorResponse('Too many requests. Please try again later.', 429);",
    '  }',
    '',
    '  switch (action) {',
    "    case 'login': {",
    "      const body = (await request.json()) as { email?: string; password?: string };",
    "      if (!body.email || !body.password) {",
    "        return errorResponse('Email and password are required.', 422);",
    '      }',
    '',
    '      try {',
    '        const res = await fetch(BACKEND_URL + "/api/auth/login", {',
    "          method: 'POST',",
    "          headers: { 'Content-Type': 'application/json' },",
    '          body: JSON.stringify({ email: body.email, password: body.password }),',
    '        });',
    '',
    '        if (!res.ok) {',
    '          const err = (await res.json()) as { detail?: string };',
    "          return errorResponse(err.detail ?? 'Invalid credentials.', res.status);",
    '        }',
    '',
    '        const data = (await res.json()) as { access_token: string; refresh_token: string; expires_in: number };',
    '        const csrfToken = generateCsrfToken();',
    '',
    '        const response = jsonResponse({',
    '          access_token: data.access_token,',
    '          expires_in: data.expires_in,',
    '          csrf_token: csrfToken,',
    '        });',
    '',
    "        response.cookies.set('access_token', data.access_token, {",
    '          httpOnly: true,',
    '          secure: true,',
    "          sameSite: 'lax',",
    '          maxAge: data.expires_in,',
    "          path: '/',",
    '        });',
    '',
    "        response.cookies.set('refresh_token', data.refresh_token, {",
    '          httpOnly: true,',
    '          secure: true,',
    "          sameSite: 'lax',",
    '          maxAge: ' + refreshMaxAge(config) + ',',
    "          path: '/',",
    '        });',
    '',
    config.csrfEnabled !== false
      ? [
          "        response.cookies.set('csrf_token', csrfToken, {",
          '          httpOnly: false,',
          '          secure: true,',
          "          sameSite: 'lax',",
          '          maxAge: data.expires_in,',
          "          path: '/',",
          '        });',
        ].join('\n')
      : '',
    '',
    '        return response;',
    '      } catch {',
    "        return errorResponse('Authentication service unavailable.', 503);",
    '      }',
    '    }',
    '',
    "    case 'register': {",
    "      const body = (await request.json()) as { email?: string; password?: string; name?: string };",
    "      if (!body.email || !body.password || !body.name) {",
    "        return errorResponse('Email, password, and name are required.', 422);",
    '      }',
    '',
    '      const passwordError = validatePassword(body.password);',
    '      if (passwordError) {',
    '        return errorResponse(passwordError, 422);',
    '      }',
    '',
    '      try {',
    '        const res = await fetch(BACKEND_URL + "/api/auth/register", {',
    "          method: 'POST',",
    "          headers: { 'Content-Type': 'application/json' },",
    '          body: JSON.stringify({ email: body.email, password: body.password, name: body.name }),',
    '        });',
    '',
    '        if (!res.ok) {',
    '          const err = (await res.json()) as { detail?: string };',
    "          return errorResponse(err.detail ?? 'Registration failed.', res.status);",
    '        }',
    '',
    '        const user = (await res.json()) as AuthUser;',
    '        return jsonResponse({ user }, 201);',
    '      } catch {',
    "        return errorResponse('Registration service unavailable.', 503);",
    '      }',
    '    }',
    '',
    "    case 'refresh': {",
    "      const refreshToken = request.cookies.get('refresh_token')?.value;",
    "      if (!refreshToken) {",
    "        return errorResponse('Refresh token required.', 401);",
    '      }',
    '',
    '      try {',
    '        const res = await fetch(BACKEND_URL + "/api/auth/refresh", {',
    "          method: 'POST',",
    "          headers: { 'Content-Type': 'application/json' },",
    '          body: JSON.stringify({ refresh_token: refreshToken }),',
    '        });',
    '',
    '        if (!res.ok) {',
    "          return errorResponse('Token refresh failed.', 401);",
    '        }',
    '',
    '        const data = (await res.json()) as { access_token: string; refresh_token: string; expires_in: number };',
    '        const response = jsonResponse({ access_token: data.access_token, expires_in: data.expires_in });',
    '',
    "        response.cookies.set('access_token', data.access_token, {",
    '          httpOnly: true,',
    '          secure: true,',
    "          sameSite: 'lax',",
    '          maxAge: data.expires_in,',
    "          path: '/',",
    '        });',
    '',
    "        response.cookies.set('refresh_token', data.refresh_token, {",
    '          httpOnly: true,',
    '          secure: true,',
    "          sameSite: 'lax',",
    '          maxAge: ' + refreshMaxAge(config) + ',',
    "          path: '/',",
    '        });',
    '',
    '        return response;',
    '      } catch {',
    "        return errorResponse('Token refresh service unavailable.', 503);",
    '      }',
    '    }',
    '',
    "    case 'logout': {",
    "      const response = jsonResponse({ message: 'Logged out.' });",
    "      response.cookies.delete('access_token');",
    "      response.cookies.delete('refresh_token');",
    config.csrfEnabled !== false ? "      response.cookies.delete('csrf_token');" : '',
    '      return response;',
    '    }',
    '',
    '    default:',
    "      return errorResponse('Not found.', 404);",
    '  }',
    '}',
    '',
    'export async function GET(request: NextRequest): Promise<NextResponse> {',
    '  const url = new URL(request.url);',
    "  const action = url.pathname.split('/').pop();",
    '',
    "  if (action === 'me') {",
    "    const token = request.cookies.get('access_token')?.value",
    "      ?? request.headers.get('Authorization')?.replace('Bearer ', '');",
    '',
    '    if (!token) {',
    "      return errorResponse('Not authenticated.', 401);",
    '    }',
    '',
    '    const payload = await verifyToken(token);',
    '    if (!payload) {',
    "      return errorResponse('Invalid or expired token.', 401);",
    '    }',
    '',
    '    return jsonResponse({',
    '      user: {',
    '        id: payload.sub,',
    '        role: payload.role,',
    '      },',
    '    });',
    '  }',
    '',
    "  return errorResponse('Not found.', 404);",
    '}',
  ].join('\n');
}

// ─── Next.js Middleware ───────────────────────────────────────────────────────

function generateNextJSMiddleware(config: AuthConfig): string {
  return [
    '/**',
    ' * Next.js Middleware \u2014 protects routes and refreshes tokens.',
    ' *',
    ' * Add protected paths to PROTECTED_ROUTES below.',
    ' */',
    "import { NextRequest, NextResponse } from 'next/server';",
    '',
    "const PROTECTED_ROUTES = ['/dashboard', '/settings', '/admin'];",
    "const AUTH_ROUTES = ['/login', '/register'];",
    '',
    'export function middleware(request: NextRequest): NextResponse {',
    '  const { pathname } = request.nextUrl;',
    '',
    '  const isProtected = PROTECTED_ROUTES.some((route) => pathname.startsWith(route));',
    '  const isAuthPage = AUTH_ROUTES.some((route) => pathname.startsWith(route));',
    '',
    "  const accessToken = request.cookies.get('access_token')?.value;",
    "  const refreshToken = request.cookies.get('refresh_token')?.value;",
    '',
    '  if (isProtected && !accessToken) {',
    '    if (refreshToken) {',
    "      const refreshUrl = new URL('/api/auth/refresh', request.url);",
    "      refreshUrl.searchParams.set('redirect', pathname);",
    '      return NextResponse.redirect(refreshUrl);',
    '    }',
    '',
    "    const loginUrl = new URL('/login', request.url);",
    "    loginUrl.searchParams.set('redirect', pathname);",
    '    return NextResponse.redirect(loginUrl);',
    '  }',
    '',
    '  if (isAuthPage && accessToken) {',
    "    return NextResponse.redirect(new URL('/dashboard', request.url));",
    '  }',
    '',
    '  const response = NextResponse.next();',
    '',
    config.csrfEnabled !== false
      ? [
          "  // Attach CSRF token from cookie to headers for API calls",
          "  const csrfToken = request.cookies.get('csrf_token')?.value;",
          '  if (csrfToken) {',
          "    response.headers.set('X-CSRF-Token', csrfToken);",
          '  }',
        ].join('\n')
      : '',
    '',
    '  // Security headers',
    "  response.headers.set('X-Content-Type-Options', 'nosniff');",
    "  response.headers.set('X-Frame-Options', 'DENY');",
    "  response.headers.set('Referrer-Policy', 'strict-origin-when-cross-origin');",
    '',
    '  return response;',
    '}',
    '',
    'export const config = {',
    '  matcher: [',
    "    '/((?!_next/static|_next/image|favicon.ico|public/).*)',",
    '  ],',
    '};',
    '',
  ].join('\n');
}

// ─── Next.js useAuth Hook ─────────────────────────────────────────────────────

function generateNextAuthHook(config: AuthConfig): string {
  return [
    '/**',
    ' * useAuth \u2014 React hook for authentication state and actions.',
    ' */',
    "'use client';",
    '',
    "import { useCallback, useEffect, useState } from 'react';",
    "import { useRouter } from 'next/navigation';",
    '',
    'interface AuthUser {',
    '  id: string;',
    '  role: string;',
    '}',
    '',
    'interface AuthState {',
    '  user: AuthUser | null;',
    '  isLoading: boolean;',
    '  isAuthenticated: boolean;',
    '  error: string | null;',
    '}',
    '',
    'interface LoginParams {',
    '  email: string;',
    '  password: string;',
    '  redirect?: string;',
    '}',
    '',
    'interface RegisterParams {',
    '  email: string;',
    '  password: string;',
    '  name: string;',
    '}',
    '',
    'export function useAuth(): AuthState & {',
    '  login: (params: LoginParams) => Promise<void>;',
    '  register: (params: RegisterParams) => Promise<void>;',
    '  logout: () => Promise<void>;',
    '  fetchWithAuth: (url: string, init?: RequestInit) => Promise<Response>;',
    '} {',
    '  const router = useRouter();',
    '  const [state, setState] = useState<AuthState>({',
    '    user: null,',
    '    isLoading: true,',
    '    isAuthenticated: false,',
    '    error: null,',
    '  });',
    '',
    '  useEffect(() => {',
    '    checkAuth();',
    '  }, []); // eslint-disable-line react-hooks/exhaustive-deps',
    '',
    '  async function checkAuth(): Promise<void> {',
    '    try {',
    "      const res = await fetch('/api/auth/me');",
    '      if (res.ok) {',
    '        const data = (await res.json()) as { user: AuthUser };',
    '        setState({ user: data.user, isLoading: false, isAuthenticated: true, error: null });',
    '      } else {',
    '        setState({ user: null, isLoading: false, isAuthenticated: false, error: null });',
    '      }',
    '    } catch {',
    '      setState({ user: null, isLoading: false, isAuthenticated: false, error: null });',
    '    }',
    '  }',
    '',
    '  const login = useCallback(async ({ email, password, redirect }: LoginParams) => {',
    '    setState((prev) => ({ ...prev, isLoading: true, error: null }));',
    '    try {',
    "      const res = await fetch('/api/auth/login', {",
    "        method: 'POST',",
    "        headers: { 'Content-Type': 'application/json' },",
    '        body: JSON.stringify({ email, password }),',
    '      });',
    '',
    '      const data = (await res.json()) as Record<string, unknown>;',
    '',
    '      if (!res.ok) {',
    '        setState((prev) => ({',
    '          ...prev,',
    '          isLoading: false,',
    '          error: (data.error as string) || \'Login failed\',',
    '        }));',
    '        return;',
    '      }',
    '',
    '      setState((prev) => ({',
    '        ...prev,',
    '        user: { id: ((data.user as AuthUser)?.id ?? \'\') as string, role: ((data.user as AuthUser)?.role ?? \'user\') as string },',
    '        isLoading: false,',
    '        isAuthenticated: true,',
    '        error: null,',
    '      }));',
    '',
    '      router.push(redirect ?? \'/dashboard\');',
    '    } catch {',
    '      setState((prev) => ({',
    '        ...prev,',
    '        isLoading: false,',
    "        error: 'Network error. Please try again.',",
    '      }));',
    '    }',
    '  }, [router]);',
    '',
    '  const register = useCallback(async ({ email, password, name }: RegisterParams) => {',
    '    setState((prev) => ({ ...prev, isLoading: true, error: null }));',
    '    try {',
    "      const res = await fetch('/api/auth/register', {",
    "        method: 'POST',",
    "        headers: { 'Content-Type': 'application/json' },",
    '        body: JSON.stringify({ email, password, name }),',
    '      });',
    '',
    '      const data = (await res.json()) as Record<string, unknown>;',
    '',
    '      if (!res.ok) {',
    '        setState((prev) => ({',
    '          ...prev,',
    '          isLoading: false,',
    '          error: (data.error as string) || \'Registration failed\',',
    '        }));',
    '        return;',
    '      }',
    '',
    "      router.push('/login?registered=true');",
    '    } catch {',
    '      setState((prev) => ({',
    '        ...prev,',
    '        isLoading: false,',
    "        error: 'Network error. Please try again.',",
    '      }));',
    '    }',
    '  }, [router]);',
    '',
    '  const logout = useCallback(async () => {',
    "    await fetch('/api/auth/logout', { method: 'POST' });",
    '    setState({ user: null, isLoading: false, isAuthenticated: false, error: null });',
    "    router.push('/login');",
    '  }, [router]);',
    '',
    '  const fetchWithAuth = useCallback(async (url: string, init?: RequestInit): Promise<Response> => {',
    '    const res = await fetch(url, {',
    '      ...init,',
    '      headers: {',
    '        ...init?.headers,',
    "        'Content-Type': 'application/json',",
    '      },',
    "      credentials: 'include',",
    '    });',
    '',
    '    if (res.status === 401) {',
    "      const refreshRes = await fetch('/api/auth/refresh', { method: 'POST' });",
    '      if (refreshRes.ok) {',
    '        return fetch(url, { ...init, credentials: \'include\' });',
    '      }',
    '      await logout();',
    "      throw new Error('Session expired');",
    '    }',
    '',
    '    return res;',
    '  }, [logout]);',
    '',
    '  return { ...state, login, register, logout, fetchWithAuth };',
    '}',
    '',
  ].join('\n');
}

// ─── Next.js Login Page ───────────────────────────────────────────────────────

function buildLoginPage(config: AuthConfig): string {
  return [
    "'use client';",
    '',
    "import { useState, type FormEvent } from 'react';",
    "import { useAuth } from '@/hooks/useAuth';",
    "import Link from 'next/link';",
    '',
    'export default function LoginPage() {',
    '  const { login, isLoading, error } = useAuth();',
    '  const [email, setEmail] = useState(\'\');',
    '  const [password, setPassword] = useState(\'\');',
    '',
    '  async function handleSubmit(e: FormEvent<HTMLFormElement>) {',
    '    e.preventDefault();',
    '    await login({ email, password });',
    '  }',
    '',
    '  return (',
    '    <div className="min-h-screen flex items-center justify-center bg-gray-50 px-4">',
    '      <div className="w-full max-w-md bg-white rounded-2xl shadow-lg p-8">',
    '        <div className="mb-8 text-center">',
    '          <h1 className="text-2xl font-bold text-gray-900">Sign In</h1>',
    '          <p className="mt-2 text-sm text-gray-500">Enter your credentials to access your account</p>',
    '        </div>',
    '',
    '        {error && (',
    '          <div className="mb-4 p-3 rounded-lg bg-red-50 border border-red-200 text-red-700 text-sm">',
    '            {error}',
    '          </div>',
    '        )}',
    '',
    '        <form onSubmit={handleSubmit} className="space-y-5">',
    '          <div>',
    '            <label htmlFor="email" className="block text-sm font-medium text-gray-700 mb-1">',
    '              Email',
    '            </label>',
    '            <input',
    '              id="email"',
    '              type="email"',
    '              required',
    '              value={email}',
    '              onChange={(e) => setEmail(e.target.value)}',
    '              placeholder="you@example.com"',
    '              className="w-full px-4 py-2.5 rounded-xl border border-gray-300 text-gray-900 placeholder-gray-400 focus:border-violet-500 focus:ring-2 focus:ring-violet-500/20 outline-none transition-colors"',
    '            />',
    '          </div>',
    '',
    '          <div>',
    '            <label htmlFor="password" className="block text-sm font-medium text-gray-700 mb-1">',
    '              Password',
    '            </label>',
    '            <input',
    '              id="password"',
    '              type="password"',
    '              required',
    '              value={password}',
    '              onChange={(e) => setPassword(e.target.value)}',
    '              placeholder="Enter your password"',
    '              className="w-full px-4 py-2.5 rounded-xl border border-gray-300 text-gray-900 placeholder-gray-400 focus:border-violet-500 focus:ring-2 focus:ring-violet-500/20 outline-none transition-colors"',
    '            />',
    '          </div>',
    '',
    '          <button',
    '            type="submit"',
    '            disabled={isLoading}',
    '            className="w-full py-2.5 px-4 rounded-xl bg-violet-600 text-white font-semibold hover:bg-violet-700 focus:ring-2 focus:ring-violet-500/20 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"',
    '          >',
    "            {isLoading ? 'Signing in...' : 'Sign In'}",
    '          </button>',
    '        </form>',
    '',
    '        <p className="mt-6 text-center text-sm text-gray-500">',
    "          Don&apos;t have an account?{' '}",
    '          <Link href="/register" className="text-violet-600 font-medium hover:text-violet-700">',
    '            Create one',
    '          </Link>',
    '        </p>',
    '      </div>',
    '    </div>',
    '  );',
    '}',
    '',
  ].join('\n');
}

// ─── Next.js Register Page ────────────────────────────────────────────────────

function buildRegisterPage(config: AuthConfig): string {
  return [
    "'use client';",
    '',
    "import { useState, type FormEvent } from 'react';",
    "import { useAuth } from '@/hooks/useAuth';",
    "import Link from 'next/link';",
    '',
    'export default function RegisterPage() {',
    '  const { register, isLoading, error } = useAuth();',
    '  const [name, setName] = useState(\'\');',
    '  const [email, setEmail] = useState(\'\');',
    '  const [password, setPassword] = useState(\'\');',
    '  const [confirmPassword, setConfirmPassword] = useState(\'\');',
    '  const [localError, setLocalError] = useState(\'\');',
    '',
    '  async function handleSubmit(e: FormEvent<HTMLFormElement>) {',
    '    e.preventDefault();',
    '    setLocalError(\'\');',
    '',
    '    if (password !== confirmPassword) {',
    "      setLocalError('Passwords do not match.');",
    '      return;',
    '    }',
    '',
    '    if (password.length < 8) {',
    "      setLocalError('Password must be at least 8 characters.');",
    '      return;',
    '    }',
    '',
    "    if (!/(?=.*[a-z])(?=.*[A-Z])(?=.*\\\\d)(?=.*[!@#$%^&*])/.test(password)) {",
    "      setLocalError('Password must include uppercase, lowercase, digit, and special character.');",
    '      return;',
    '    }',
    '',
    '    await register({ email, password, name });',
    '  }',
    '',
    '  const displayError = localError || error;',
    '',
    '  return (',
    '    <div className="min-h-screen flex items-center justify-center bg-gray-50 px-4">',
    '      <div className="w-full max-w-md bg-white rounded-2xl shadow-lg p-8">',
    '        <div className="mb-8 text-center">',
    '          <h1 className="text-2xl font-bold text-gray-900">Create Account</h1>',
    '          <p className="mt-2 text-sm text-gray-500">Get started with your free account</p>',
    '        </div>',
    '',
    '        {displayError && (',
    '          <div className="mb-4 p-3 rounded-lg bg-red-50 border border-red-200 text-red-700 text-sm">',
    '            {displayError}',
    '          </div>',
    '        )}',
    '',
    '        <form onSubmit={handleSubmit} className="space-y-5">',
    '          <div>',
    '            <label htmlFor="name" className="block text-sm font-medium text-gray-700 mb-1">',
    '              Full Name',
    '            </label>',
    '            <input',
    '              id="name"',
    '              type="text"',
    '              required',
    '              value={name}',
    '              onChange={(e) => setName(e.target.value)}',
    '              placeholder="John Doe"',
    '              className="w-full px-4 py-2.5 rounded-xl border border-gray-300 text-gray-900 placeholder-gray-400 focus:border-violet-500 focus:ring-2 focus:ring-violet-500/20 outline-none transition-colors"',
    '            />',
    '          </div>',
    '',
    '          <div>',
    '            <label htmlFor="email" className="block text-sm font-medium text-gray-700 mb-1">',
    '              Email',
    '            </label>',
    '            <input',
    '              id="email"',
    '              type="email"',
    '              required',
    '              value={email}',
    '              onChange={(e) => setEmail(e.target.value)}',
    '              placeholder="you@example.com"',
    '              className="w-full px-4 py-2.5 rounded-xl border border-gray-300 text-gray-900 placeholder-gray-400 focus:border-violet-500 focus:ring-2 focus:ring-violet-500/20 outline-none transition-colors"',
    '            />',
    '          </div>',
    '',
    '          <div>',
    '            <label htmlFor="password" className="block text-sm font-medium text-gray-700 mb-1">',
    '              Password',
    '            </label>',
    '            <input',
    '              id="password"',
    '              type="password"',
    '              required',
    '              value={password}',
    '              onChange={(e) => setPassword(e.target.value)}',
    '              placeholder="At least 8 characters"',
    '              className="w-full px-4 py-2.5 rounded-xl border border-gray-300 text-gray-900 placeholder-gray-400 focus:border-violet-500 focus:ring-2 focus:ring-violet-500/20 outline-none transition-colors"',
    '            />',
    '          </div>',
    '',
    '          <div>',
    '            <label htmlFor="confirmPassword" className="block text-sm font-medium text-gray-700 mb-1">',
    '              Confirm Password',
    '            </label>',
    '            <input',
    '              id="confirmPassword"',
    '              type="password"',
    '              required',
    '              value={confirmPassword}',
    '              onChange={(e) => setConfirmPassword(e.target.value)}',
    '              placeholder="Repeat your password"',
    '              className="w-full px-4 py-2.5 rounded-xl border border-gray-300 text-gray-900 placeholder-gray-400 focus:border-violet-500 focus:ring-2 focus:ring-violet-500/20 outline-none transition-colors"',
    '            />',
    '          </div>',
    '',
    '          <button',
    '            type="submit"',
    '            disabled={isLoading}',
    '            className="w-full py-2.5 px-4 rounded-xl bg-violet-600 text-white font-semibold hover:bg-violet-700 focus:ring-2 focus:ring-violet-500/20 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"',
    '          >',
    "            {isLoading ? 'Creating account...' : 'Create Account'}",
    '          </button>',
    '        </form>',
    '',
    '        <p className="mt-6 text-center text-sm text-gray-500">',
    "          Already have an account?{' '}",
    '          <Link href="/login" className="text-violet-600 font-medium hover:text-violet-700">',
    '            Sign in',
    '          </Link>',
    '        </p>',
    '      </div>',
    '    </div>',
    '  );',
    '}',
    '',
  ].join('\n');
}

// ─── Environment Config ───────────────────────────────────────────────────────

function generateEnvConfig(config: AuthConfig): string {
  return [
    '# \u2500\u2500\u2500 Authentication Configuration \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500',
    '# Copy this file to .env.local and fill in real values.',
    '',
    '# Security keys \u2014 generate with: openssl rand -hex 32',
    config.secretKey + '=CHANGE-ME-GENERATE-WITH-openssl-rand-hex-32',
    'CSRF_SECRET=CHANGE-ME-GENERATE-WITH-openssl-rand-hex-32',
    '',
    '# Token configuration',
    'TOKEN_EXPIRY=' + config.tokenExpiry,
    'REFRESH_EXPIRY=' + config.refreshExpiry,
    '',
    '# Password hashing algorithm',
    'PASSWORD_HASHING=' + config.passwordHashing,
    '',
    '# Database URL (for FastAPI)',
    'DATABASE_URL=postgresql+asyncpg://user:password@localhost:5432/auth_db',
    '',
    '# Backend URL (for Next.js API proxy)',
    'BACKEND_URL=http://localhost:8000',
    '',
    '# Cookie settings',
    'COOKIE_DOMAIN=localhost',
    '',
    '# CSRF protection',
    'CSRF_ENABLED=' + (config.csrfEnabled === false ? 'false' : 'true'),
    '',
    '# Rate limiting',
    'RATE_LIMIT_WINDOW=' + (config.rateLimitWindow ?? '1m'),
    'RATE_LIMIT_MAX=' + (config.rateLimitMax ?? 30),
    '',
    '# Role-based access control',
    'DEFAULT_ROLE=user',
    'ADMIN_EMAILS=admin@example.com',
    '',
    '# Provider',
    'AUTH_PROVIDER=' + config.provider,
    '',
    '# \u2500\u2500\u2500 CORS (FastAPI) \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500',
    'CORS_ORIGINS=["http://localhost:3000"]',
    '',
  ].join('\n');
}

// ─── Main Generator ───────────────────────────────────────────────────────────

export function generateAuth(config: AuthConfig): AuthCode {
  return {
    fastapi: {
      authRouter: generateFastAPIAuthRouter(config),
      middleware: generateFastAPIMiddleware(config),
      models: generateFastAPIModels(config),
      utils: generateFastAPISecurityUtils(config),
    },
    nextjs: {
      authApi: generateNextAuthApi(config),
      middleware: generateNextJSMiddleware(config),
      authHook: generateNextAuthHook(config),
      loginPage: buildLoginPage(config),
      registerPage: buildRegisterPage(config),
    },
    config: generateEnvConfig(config),
  };
}

export function generateAuthMiddleware(config: AuthConfig): string {
  return generateFastAPIMiddleware(config);
}

export function generateLoginPage(config: AuthConfig): string {
  return buildLoginPage(config);
}

export function generateRegisterPage(config: AuthConfig): string {
  return buildRegisterPage(config);
}
