/**
 * Design Brief generator — produces the `design.md` artifact.
 *
 * This is the "design.md created by the agents using all the required skills"
 * handoff the pipeline was missing. It composes ONE readable brief from:
 *   - extracted business intents (Universal Signal Extraction)
 *   - SkillIntegrator recommendation (UI/UX Pro Max + Framer Motion data)
 *   - Design Intelligence decision (21st.dev component suggestions)
 *   - Design DNA (per-signal design system)
 *   - live evidence (competitors / market trends from WebResearchProvider)
 *
 * The renderer and downstream agents read `design.md` to stay faithful to the
 * signals instead of re-deriving visuals from thin air.
 */
import type { BusinessKnowledge } from '../orchestration/business-intelligence/types.js';
import type { DesignRecommendation } from './skill-integrator.js';
import type { DesignDecision } from '../orchestration/design-intelligence/types.js';
import type { DesignDNA } from './design-dna.js';
import type { EvidenceCollection } from '../orchestration/knowledge-acquisition/types.js';

export interface DesignBriefInput {
  appName: string;
  businessKnowledge?: BusinessKnowledge;
  intents?: BusinessKnowledge['intents'];
  skillRecommendations?: DesignRecommendation;
  designDecision?: DesignDecision;
  designDNA?: DesignDNA;
  evidence?: EvidenceCollection;
}

function bullet(list: string[] | undefined, fallback: string[] = []): string {
  const items = (list && list.length ? list : fallback);
  if (!items.length) return '  - _none specified_';
  return items.map((i) => `  - ${i}`).join('\n');
}

function intentLines(intents: BusinessKnowledge['intents'] | undefined): string {
  if (!intents) return '  - _no explicit intents extracted_';
  const rows: string[] = [];
  (Object.keys(intents) as (keyof BusinessKnowledge['intents'])[]).forEach((key) => {
    const vals = intents[key];
    if (Array.isArray(vals) && vals.length) {
      rows.push(`  - **${key}**: ${vals.join(', ')}`);
    }
  });
  return rows.length ? rows.join('\n') : '  - _no explicit intents extracted_';
}

export function generateDesignBrief(input: DesignBriefInput): string {
  const {
    appName,
    businessKnowledge,
    intents,
    skillRecommendations: sr,
    designDecision,
    designDNA,
    evidence,
  } = input;

  const palette = sr?.colors;
  const typography = sr?.typography;
  const animation = sr?.animation;
  const competitors = evidence?.competitors?.value ?? [];
  const trends = evidence?.market?.value?.trends ?? [];
  const assets = evidence?.assets?.value ?? [];

  const components21st = (designDecision?.recommendations ?? [])
    .filter((r) => r.domain === 'component' && r.components)
    .flatMap((r) => r.components ?? [])
    .filter((c) => c.source === '21st.dev')
    .map((c) => c.name);

  const lines: string[] = [];
  lines.push(`# Design Brief — ${appName}`);
  lines.push('');
  lines.push(`> Generated by the Build Engine from Universal Signal Extraction + skill-driven`);
  lines.push(`> recommendations (UI/UX Pro Max, Framer Motion, 21st.dev, Design DNA).`);
  lines.push('');

  lines.push(`## 1. Business Intent (extracted signals)`);
  lines.push('');
  lines.push(intentLines(intents));
  lines.push('');

  if (businessKnowledge?.discovery) {
    const d = businessKnowledge.discovery;
    lines.push(`**Domain**: ${d.industry ?? d.businessType ?? '_unknown_'}`);
    lines.push(`**Intent**: ${d.intent ?? '_n/a_'}`);
    lines.push('');
  }

  lines.push(`## 2. Visual System (UI/UX Pro Max)`);
  lines.push('');
  if (palette) {
    const p = palette.palette as unknown;
    const paletteStr = Array.isArray(p)
      ? p.join(' · ')
      : typeof p === 'object' && p !== null
        ? Object.entries(p as Record<string, unknown>).map(([k, v]) => `${k}: ${v}`).join(' · ')
        : String(p ?? '_n/a_');
    lines.push(`**Palette**: ${paletteStr}`);
    lines.push(`- primary: \`${palette.primary}\`  secondary: \`${palette.secondary}\`  accent: \`${palette.accent}\``);
    lines.push(`- background: \`${palette.background}\`  foreground: \`${palette.foreground}\``);
    lines.push(`- reasoning: ${palette.reasoning ?? '_n/a_'}`);
  } else {
    lines.push(`  - _derived from Design DNA / Design Intelligence_`);
  }
  lines.push('');
  if (typography) {
    lines.push(`**Typography**: heading \`${typography.headingFont}\` · body \`${typography.bodyFont}\` · mono \`${typography.monoFont}\``);
    lines.push(`- reasoning: ${typography.reasoning ?? '_n/a_'}`);
  }
  lines.push('');

  lines.push(`## 3. Motion System (Framer Motion)`);
  lines.push('');
  if (animation) {
    lines.push(`- library: **${animation.library}**`);
    lines.push(`- scrollReveal: ${animation.scrollReveal} · stagger: ${animation.staggerAnimations} · hover: ${animation.hoverEffects} · pageTransitions: ${animation.pageTransitions}`);
    lines.push(`- reasoning: ${animation.reasoning}`);
  } else {
    lines.push(`  - _default framer-motion presets_`);
  }
  lines.push('');

  lines.push(`## 4. Components (21st.dev + primitives)`);
  lines.push('');
  if (components21st.length) {
    lines.push(...components21st.map((c) => `  - \`${c}\` (21st.dev)`));
  } else {
    lines.push(`  - _use primitives / shadcn defaults_`);
  }
  if (sr?.components?.length) {
    lines.push('');
    lines.push(`SkillIntegrator suggested: ${sr.components.map((c) => `\`${c?.name ?? 'component'}\``).join(', ')}`);
  }
  lines.push('');

  if (sr?.uxGuidelines?.length) {
    lines.push(`## 5. UX Guidelines (UI/UX Pro Max)`);
    lines.push('');
    lines.push(bullet(sr.uxGuidelines));
    lines.push('');
  }

  if (sr?.designPhilosophy) {
    lines.push(`## 6. Design Philosophy`);
    lines.push('');
    lines.push(`- aesthetic direction: **${sr.designPhilosophy.aestheticDirection}**`);
    lines.push(`- quality level: ${sr.designPhilosophy.qualityLevel ?? '_n/a_'}`);
    lines.push(`- banned defaults: ${(sr.designPhilosophy.bannedDefaults ?? []).join(', ') || '_none_'}`);
    lines.push(`- polish passes: ${(sr.designPhilosophy.polishPasses ?? []).join(' → ')}`);
    lines.push('');
  }

  if (designDNA) {
    lines.push(`## 7. Design DNA (signal-driven system)`);
    lines.push('');
    lines.push(`- designStyle: \`${designDNA.designStyle ?? '_derived_'}\``);
    lines.push(`- brandPersonality: \`${designDNA.brandPersonality ?? '_derived_'}\``);
    lines.push('');
  }

  lines.push(`## 8. Live Evidence (web research)`);
  lines.push('');
  if (competitors.length) {
    lines.push(`**Competitors / references observed:**`);
    lines.push(...competitors.slice(0, 6).map((c) => `  - [${c.name}](${c.url}) — confidence ${(c.confidence * 100).toFixed(0)}%`));
  } else {
    lines.push(`  - _no live evidence collected (offline / no matches)_`);
  }
  lines.push('');
  if (trends.length) {
    lines.push(`**Market trends:**`);
    lines.push(bullet(trends));
    lines.push('');
  }

  if (assets.length) {
    lines.push(`**Real brand assets discovered:**`);
    lines.push(...assets.slice(0, 8).map((a) => `  - [${a.kind}](${a.url}) — ${a.source}`));
    lines.push('');
  }

  lines.push(`---`);
  lines.push(`_This brief is the single source of truth for the build. Honor the extracted`);
  lines.push(`intents and the live evidence above; do not reintroduce generic AI defaults._`);
  lines.push('');

  return lines.join('\n');
}
