/**
 * Production Manifest: Generates workspace.manifest.json as the canonical
 * build artifact containing project metadata, routes, API endpoints,
 * database models, environment variables, and deployment targets.
 */

import * as fs from 'fs';
import * as path from 'path';

export interface ManifestRoute {
  path: string;
  method?: string;
  description: string;
  auth?: boolean;
}

export interface ManifestApiEndpoint {
  path: string;
  method: string;
  description: string;
  auth: boolean;
}

export interface ManifestModel {
  name: string;
  fields: Array<{
    name: string;
    type: string;
    required: boolean;
    isId?: boolean;
  }>;
  relations?: Array<{
    name: string;
    type: string;
    model: string;
  }>;
}

export interface ManifestEnvironment {
  key: string;
  required: boolean;
  description: string;
  defaultValue?: string;
}

export interface ManifestDeployment {
  platform: string;
  config: Record<string, unknown>;
}

export interface ProductionManifest {
  $schema: string;
  version: string;
  metadata: {
    name: string;
    description: string;
    generatedAt: string;
    generator: string;
    buildId?: string | undefined;
  };
  framework: {
    name: string;
    version: string;
    runtime: string;
  };
  dependencies: Record<string, string>;
  routes: ManifestRoute[];
  apiEndpoints: ManifestApiEndpoint[];
  database: {
    provider: string;
    models: ManifestModel[];
  };
  environment: ManifestEnvironment[];
  deployment: ManifestDeployment[];
}

export class ProductionManifestGenerator {
  private workspacePath: string;

  constructor(workspacePath: string) {
    this.workspacePath = workspacePath;
  }

  /**
   * Generate the complete production manifest from workspace files.
   */
  generate(options: {
    name: string;
    description?: string | undefined;
    buildId?: string | undefined;
  }): ProductionManifest {
    const packageJson = this.readPackageJson();
    const prismaSchema = this.readPrismaSchema();
    const appRoutes = this.scanAppRoutes();
    const apiRoutes = this.scanApiRoutes();

    const manifest: ProductionManifest = {
      $schema: 'https://build-same.dev/schemas/manifest.json',
      version: '1.0.0',
      metadata: {
        name: options.name,
        description: options.description ?? `Generated by Build.Same Engine`,
        generatedAt: new Date().toISOString(),
        generator: 'build-same-engine@1.0.0',
        buildId: options.buildId ?? undefined,
      },
      framework: {
        name: 'next',
        version: (packageJson?.dependencies as Record<string, string>)?.['next'] ?? '16.0.0',
        runtime: 'nodejs',
      },
      dependencies: this.extractDependencies(packageJson),
      routes: appRoutes,
      apiEndpoints: apiRoutes,
      database: {
        provider: 'postgresql',
        models: prismaSchema,
      },
      environment: this.extractEnvironment(),
      deployment: [
        {
          platform: 'vercel',
          config: {
            framework: 'nextjs',
            buildCommand: 'npm run build',
            outputDirectory: '.next',
          },
        },
        {
          platform: 'node',
          config: {
            startCommand: 'npm run start',
            port: 3000,
          },
        },
      ],
    };

    return manifest;
  }

  /**
   * Write manifest to workspace.
   */
  writeManifest(manifest: ProductionManifest): string {
    const manifestPath = path.join(this.workspacePath, 'workspace.manifest.json');
    fs.writeFileSync(manifestPath, JSON.stringify(manifest, null, 2), 'utf-8');
    console.log(`[manifest] Written to ${manifestPath}`);
    return manifestPath;
  }

  /**
   * Generate and write manifest in one call.
   */
  generateAndWrite(options: {
    name: string;
    description?: string;
    buildId?: string;
  }): string {
    const manifest = this.generate(options);
    return this.writeManifest(manifest);
  }

  private readPackageJson(): Record<string, unknown> | null {
    try {
      const pkgPath = path.join(this.workspacePath, 'package.json');
      if (fs.existsSync(pkgPath)) {
        return JSON.parse(fs.readFileSync(pkgPath, 'utf-8'));
      }
    } catch {
      // Ignore errors
    }
    return null;
  }

  private readPrismaSchema(): ManifestModel[] {
    const models: ManifestModel[] = [];
    try {
      const schemaPath = path.join(this.workspacePath, 'prisma', 'schema.prisma');
      if (!fs.existsSync(schemaPath)) return models;

      const content = fs.readFileSync(schemaPath, 'utf-8');
      const modelBlocks = content.match(/model\s+(\w+)\s*\{([^}]+)\}/g) ?? [];

      for (const block of modelBlocks) {
        const nameMatch = block.match(/model\s+(\w+)/);
        if (!nameMatch?.[1]) continue;

        const body = block.match(/\{([^}]+)\}/)?.[1] ?? '';
        const fields: ManifestModel['fields'] = [];
        const relations: ManifestModel['relations'] = [];

        const lines = body.split('\n').map(l => l.trim()).filter(l => l && !l.startsWith('//'));
        const scalarTypes = new Set(['Int', 'String', 'Boolean', 'Float', 'DateTime', 'Json', 'BigInt', 'Decimal', 'Bytes', 'Unsupported']);
        for (const line of lines) {
          // Skip relation blocks and unsupported lines
          if (line.startsWith('@@')) continue;

          const parts = line.split(/\s+/);
          if (parts.length >= 2) {
            const fieldName = parts[0];
            const fieldType = parts[1];

            // Check if it's a scalar type (Int, String, Boolean, etc.)
            const isScalar = fieldType !== undefined && scalarTypes.has(fieldType);
            // Check if it's a list type (ends with [])
            const isList = fieldType?.endsWith('[]') ?? false;
            // Check if it's an optional scalar (ends with ?)
            const isOptionalScalar = fieldType?.endsWith('?') ?? false;
            // Base type without [] or ?
            const baseType = fieldType?.replace(/[[\]?]/g, '') ?? '';

            if (isList && !scalarTypes.has(baseType)) {
              // List relation like `posts Post[]`
              relations.push({
                name: fieldName ?? '',
                type: 'one-to-many',
                model: baseType,
              });
            } else if (!isScalar && !isList && !isOptionalScalar && baseType[0] === baseType[0]?.toUpperCase() && baseType[0] !== baseType[0]?.toLowerCase() && !scalarTypes.has(baseType)) {
              relations.push({
                name: fieldName ?? '',
                type: 'many-to-one',
                model: baseType,
              });
            } else {
              fields.push({
                name: fieldName ?? '',
                type: fieldType ?? 'String',
                required: line.includes('required: true') || (!line.includes('?') && !line.includes('default')),
                isId: line.includes('@id'),
              });
            }
          }
        }

        models.push({
          name: nameMatch[1],
          fields,
          relations: relations.length > 0 ? relations : [],
        });
      }
    } catch (err: any) {
      console.warn(`[manifest] Failed to parse Prisma schema: ${err.message}`);
    }
    return models;
  }

  private scanAppRoutes(): ManifestRoute[] {
    const routes: ManifestRoute[] = [];
    const appDir = path.join(this.workspacePath, 'src', 'app');

    if (!fs.existsSync(appDir)) return routes;

    const walk = (dir: string, baseRoute: string) => {
      const items = fs.readdirSync(dir, { withFileTypes: true });
      for (const item of items) {
        if (item.name.startsWith('.')) continue;

        const fullPath = path.join(dir, item.name);
        const routePath = item.name === 'page.tsx'
          ? baseRoute || '/'
          : item.name === 'page.ts'
            ? baseRoute || '/'
            : undefined;

        if (item.isDirectory() && item.name !== 'api') {
          const newBase = item.name === 'page.tsx' || item.name === 'page.ts'
            ? baseRoute
            : `${baseRoute}/${item.name}`.replace(/\/+/g, '/');
          walk(fullPath, newBase);
        } else if (item.isFile() && (item.name === 'page.tsx' || item.name === 'page.ts')) {
          const route = baseRoute || '/';
          if (!routes.some(r => r.path === route)) {
            routes.push({
              path: route,
              description: `Page at ${route}`,
            });
          }
        }
      }
    };

    walk(appDir, '');
    return routes;
  }

  private scanApiRoutes(): ManifestApiEndpoint[] {
    const endpoints: ManifestApiEndpoint[] = [];
    const apiDir = path.join(this.workspacePath, 'src', 'app', 'api');

    if (!fs.existsSync(apiDir)) return endpoints;

    const walk = (dir: string, basePath: string) => {
      const items = fs.readdirSync(dir, { withFileTypes: true });
      for (const item of items) {
        if (item.name.startsWith('.')) continue;

        const fullPath = path.join(dir, item.name);
        const routePath = `${basePath}/${item.name}`.replace(/\/+/g, '/');

        if (item.isDirectory()) {
          walk(fullPath, routePath);
        } else if (item.name === 'route.ts' || item.name === 'route.js') {
          // Detect methods from file content
          try {
            const content = fs.readFileSync(fullPath, 'utf-8');
            const methods = ['GET', 'POST', 'PUT', 'DELETE', 'PATCH']
              .filter(m => content.includes(`export async function ${m}`) || content.includes(`export const ${m}`));

            for (const method of methods) {
              endpoints.push({
                path: basePath,
                method,
                description: `${method} ${basePath}`,
                auth: content.includes('auth') || content.includes('session'),
              });
            }
          } catch {
            endpoints.push({
              path: basePath,
              method: 'GET',
              description: `${basePath}`,
              auth: false,
            });
          }
        }
      }
    };

    walk(apiDir, '/api');
    return endpoints;
  }

  private extractDependencies(packageJson: Record<string, unknown> | null): Record<string, string> {
    if (!packageJson) return {};
    const deps = packageJson.dependencies as Record<string, string> ?? {};
    const devDeps = packageJson.devDependencies as Record<string, string> ?? {};
    return { ...deps, ...devDeps };
  }

  private extractEnvironment(): ManifestEnvironment[] {
    const envVars: ManifestEnvironment[] = [];

    // Check .env.example
    const envExamplePath = path.join(this.workspacePath, '.env.example');
    if (fs.existsSync(envExamplePath)) {
      const content = fs.readFileSync(envExamplePath, 'utf-8');
      const lines = content.split('\n').filter(l => l && !l.startsWith('#'));
      for (const line of lines) {
        const match = line.match(/^(\w+)=/);
        if (match?.[1]) {
          envVars.push({
            key: match[1],
            required: true,
            description: line.includes('#') ? line.split('#')[1]?.trim() ?? '' : '',
          });
        }
      }
    }

    // Always include standard vars
    const standardVars = [
      { key: 'DATABASE_URL', required: true, description: 'PostgreSQL connection string' },
      { key: 'NEXTAUTH_SECRET', required: true, description: 'NextAuth.js secret' },
      { key: 'NEXTAUTH_URL', required: false, description: 'NextAuth.js URL', defaultValue: 'http://localhost:3000' },
    ];

    for (const v of standardVars) {
      if (!envVars.some(e => e.key === v.key)) {
        envVars.push(v);
      }
    }

    return envVars;
  }
}
