/**
 * Content Intelligence Engine
 *
 * The SINGLE AUTHORITY for:
 * - Hero copy / messaging hierarchy
 * - CTA strategy
 * - Media strategy
 * - Copy direction
 * - Content density
 * - Voice and tone
 *
 * Consumes BusinessKnowledge + ExperienceBlueprint from upstream.
 * Produces ContentBlueprint for downstream.
 *
 * CONSTRAINTS:
 * - Must NOT decide business logic
 * - Must NOT decide experience flow
 * - Must NOT decide visual system
 * - Must NOT decide backend architecture
 */

import type { BusinessKnowledge } from '../business-intelligence/types.js';
import type { ExperienceBlueprint, Provenance } from '../experience-intelligence/types.js';
import type {
  ContentBlueprint,
  CTAStrategy,
  CTA,
  MediaStrategy,
  CopyDirection,
  ContentDensity,
  BrandVoice,
  ToneVariation,
  IContentIntelligenceLayer,
} from './types.js';
import type { ValidationResult } from '../shared/types.js';

// ─── Helpers ──────────────────────────────────────────────────────────────────

function makeProvenance(layer: Provenance['layer'], confidence: number, evidence: string[] = []): Provenance {
  return {
    layer,
    confidence,
    evidence,
    timestamp: new Date(),
    reasoning: `Generated by ${layer}`,
    source: 'content-intelligence',
  };
}

// ─── Signal-derived Content Profile ───────────────────────────────────────────
// NO hardcoded industry keyed profiles. The voice, tone, CTA and media strategy
// are derived from BusinessKnowledge signals (personas, revenue model, entity
// count, experience blueprint motion language) so the engine reasons over the
// business, not over a vertical lookup table.

interface ContentProfile {
  personality: BrandVoice['personality'];
  formality: number;
  technicalLevel: number;
  emotionalLevel: number;
  vocabularyComplexity: BrandVoice['vocabularyComplexity'];
  defaultTone: ToneVariation['tone'];
  ctaAction: CTA['action'];
  ctaStyle: CTA['style'];
  contentDensity: 'minimal' | 'balanced' | 'rich';
  mediaStyle: 'photography' | 'illustration' | '3d' | 'abstract' | 'mixed';
  animationLevel: 'none' | 'subtle' | 'moderate' | 'aggressive';
}

/**
 * Derive a content profile from BusinessKnowledge signals. This is the single
 * replacement for the old INDUSTRY_CONTENT_PROFILES lookup — no industry key is
 * read. Signals:
 *  - customer persona formality/role → personality + formality
 *  - revenue model (subscription/sale/service) → CTA action
 *  - entity count + experience motion language → density + animation
 *  - technical vocabulary depth → technicalLevel + vocabularyComplexity
 */
function deriveContentProfile(bk: BusinessKnowledge, exp: ExperienceBlueprint): ContentProfile {
  const personas = bk.customerPersonas ?? [];
  const topPersonaLabel = personas[0]?.label?.toLowerCase() ?? '';
  const revenueModel = (bk.revenue?.model ?? '').toLowerCase();
  const entityCount = (bk.entities ?? []).length;
  const hasCommerce = /sell|purchase|checkout|commerce|shop|store|cart/.test(revenueModel);
  const hasSubscription = /subscri|membership|recurring/.test(revenueModel);
  const isService = /service|booking|appointment|consult/.test(revenueModel);

  // Personality + formality from persona signal (universal defaults if unknown).
  let personality: BrandVoice['personality'] = 'professional';
  let formality = 0.5;
  if (/member|community|friend|casual|playful/.test(topPersonaLabel)) { personality = 'friendly'; formality = 0.35; }
  else if (/client|enterprise|business|professional|authority/.test(topPersonaLabel)) { personality = 'authoritative'; formality = 0.65; }
  else if (/luxury|sophisticat|premium|editorial/.test(topPersonaLabel)) { personality = 'sophisticated'; formality = 0.75; }

  // CTA action from business model signal.
  let ctaAction: CTA['action'] = 'sign-up';
  if (hasCommerce) ctaAction = 'purchase';
  else if (isService) ctaAction = 'contact';
  else if (hasSubscription) ctaAction = 'subscribe';

  // Density + animation from entity count and experience interaction signals
  // (no industry key, no motionLanguage string parsing — derive from counts
  // and the experience blueprint's interaction density when available).
  const interactionDensity = (exp as any).interactionDensity?.value;
  const contentDensity: ContentProfile['contentDensity'] =
    entityCount <= 3 ? 'minimal' : entityCount >= 8 ? 'rich' : 'balanced';
  let animationLevel: ContentProfile['animationLevel'] = 'subtle';
  if (interactionDensity === 'immersive' || interactionDensity === 'rich') animationLevel = 'moderate';
  else if (interactionDensity === 'minimal' || interactionDensity === 'light') animationLevel = 'none';

  // Technical level from vocabulary depth signal.
  const vocab = bk.vocabulary?.domainNouns ?? [];
  const technicalLevel = Math.min(0.9, 0.3 + vocab.length * 0.05);

  const vocabularyComplexity: BrandVoice['vocabularyComplexity'] =
    technicalLevel > 0.65 ? 'advanced' : technicalLevel > 0.45 ? 'moderate' : 'simple';

  const defaultTone: ToneVariation['tone'] =
    personality === 'sophisticated' ? 'inspirational'
      : personality === 'authoritative' ? 'reassuring'
      : personality === 'friendly' ? 'excited'
      : 'educational';

  return {
    personality,
    formality,
    technicalLevel,
    emotionalLevel: personality === 'friendly' || personality === 'sophisticated' ? 0.75 : 0.5,
    vocabularyComplexity,
    defaultTone,
    ctaAction,
    ctaStyle: 'primary',
    contentDensity,
    mediaStyle: 'photography',
    animationLevel,
  };
}

// ─── Content Intelligence Engine ──────────────────────────────────────────────

export class ContentIntelligenceEngine implements IContentIntelligenceLayer {
  readonly id = 'content-intelligence' as const;
  readonly name = 'Content Intelligence Engine';
  readonly version = '1.0.0';

  async process(
    businessKnowledge: BusinessKnowledge,
    experienceBlueprint: ExperienceBlueprint
  ): Promise<ContentBlueprint> {
    const profile = deriveContentProfile(businessKnowledge, experienceBlueprint);
    const prov = (conf: number) => makeProvenance('content-intelligence', conf);
    const bkId = `bk-${Buffer.from(businessKnowledge.discovery.businessType || 'unknown').toString('base64').slice(0, 12)}`;

    return {
      id: `content-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
      createdAt: new Date(),
      version: '1.0.0',
      businessKnowledgeId: bkId,
      experienceBlueprintId: experienceBlueprint.id,
      primaryMessage: {
        value: this.buildPrimaryMessage(businessKnowledge),
        provenance: prov(0.8),
      },
      supportingMessages: {
        value: this.buildSupportingMessages(businessKnowledge),
        provenance: prov(0.75),
      },
      taglineOptions: {
        value: this.buildTaglineOptions(businessKnowledge),
        provenance: prov(0.7),
      },
      ctaHierarchy: {
        value: this.buildCTAStrategy(businessKnowledge, profile),
        provenance: prov(0.8),
      },
      mediaStrategy: {
        value: this.buildMediaStrategy(businessKnowledge, experienceBlueprint, profile),
        provenance: prov(0.75),
      },
      copyDirection: {
        value: this.buildCopyDirection(businessKnowledge, experienceBlueprint),
        provenance: prov(0.8),
      },
      contentDensity: {
        value: this.buildContentDensity(experienceBlueprint, profile),
        provenance: prov(0.8),
      },
      voice: {
        value: this.buildVoice(profile),
        provenance: prov(0.85),
      },
      toneVariations: {
        value: this.buildToneVariations(experienceBlueprint, profile),
        provenance: prov(0.8),
      },
    };
  }

  validate(blueprint: ContentBlueprint): ValidationResult {
    const issues: Array<{ severity: 'error' | 'warning' | 'info'; message: string; field?: string; fix?: string }> = [];

    if (!blueprint.primaryMessage?.value) {
      issues.push({ severity: 'error', message: 'Missing primary message', field: 'primaryMessage' });
    }
    if (!blueprint.ctaHierarchy?.value?.primary) {
      issues.push({ severity: 'error', message: 'Missing primary CTA', field: 'ctaHierarchy.primary' });
    }
    if (!blueprint.voice?.value?.personality) {
      issues.push({ severity: 'warning', message: 'Empty brand personality', field: 'voice.personality' });
    }
    if (!blueprint.copyDirection?.value?.length) {
      issues.push({ severity: 'warning', message: 'No copy directions defined', field: 'copyDirection' });
    }

    return { valid: issues.filter(i => i.severity === 'error').length === 0, issues };
  }

  // ─── Private Builders ──────────────────────────────────────────────────────

  private buildPrimaryMessage(bk: BusinessKnowledge): string {
    // discovery.intent is a free-text business description (signal, not a vertical).
    const intent = bk.discovery.intent;
    if (intent && typeof intent === 'string' && intent.length > 10) return intent;
    const persona = bk.customerPersonas?.[0]?.label || 'you';
    return `We help ${persona} with ${bk.discovery.businessType}`;
  }

  private buildSupportingMessages(bk: BusinessKnowledge): string[] {
    const msgs: string[] = [];
    if (bk.entities?.length) msgs.push(`Explore our ${bk.entities.length} offerings`);
    if (bk.revenue?.model) msgs.push(`${bk.revenue.model} designed for you`);
    if (bk.workflows?.length) msgs.push(`Streamlined ${bk.workflows.length} processes`);
    return msgs.slice(0, 3);
  }

  private buildTaglineOptions(bk: BusinessKnowledge): string[] {
    const brand = bk.vocabulary?.domainNouns?.[0] || bk.discovery.businessType;
    const opts: string[] = [];
    if (bk.discovery.intent && bk.discovery.intent.length > 10) opts.push(bk.discovery.intent);
    opts.push(`The future of ${brand}`);
    opts.push(`Built for ${bk.customerPersonas?.[0]?.label || 'you'}`);
    return opts.slice(0, 3);
  }

  private buildCTAStrategy(bk: BusinessKnowledge, profile: ContentProfile): CTAStrategy {
    const primary: CTA = {
      text: this.getCTAText(profile.ctaAction),
      action: profile.ctaAction,
      style: profile.ctaStyle,
      urgency: 0.6,
      trustSignals: bk.compliance?.slice(0, 2).map(c => c.pack) || [],
    };
    return {
      primary,
      secondary: [{ text: 'Learn More', action: 'learn-more', style: 'secondary', urgency: 0.3, trustSignals: [] }],
      tertiary: [{ text: 'Contact Us', action: 'contact', style: 'ghost', urgency: 0.2, trustSignals: [] }],
      placementRules: [
        { sectionType: 'hero', position: 'top', style: 'primary', maxFrequency: 1 },
        { sectionType: 'features', position: 'bottom', style: 'secondary', maxFrequency: 1 },
        { sectionType: 'testimonials', position: 'bottom', style: 'primary', maxFrequency: 1 },
      ],
    };
  }

  private buildMediaStrategy(bk: BusinessKnowledge, exp: ExperienceBlueprint, profile: ContentProfile): MediaStrategy {
    const sections = (exp.sectionOrder?.value || []) as any[];
    return {
      sections: sections.map((s: any, i: number) => ({
        sectionId: s.id || `section-${i}`,
        type: 'image',
        purpose: i === 0 ? 'hero' : 'product',
        aspectRatio: i === 0 ? '16:9' : '4:3',
        quality: 'high',
        altTextDirection: `${bk.discovery.businessType} - section ${i + 1}`,
      })),
      global: {
        imageStyle: profile.mediaStyle as any,
        colorTreatment: 'full-color',
        animationLevel: profile.animationLevel,
      },
    };
  }

  private buildCopyDirection(bk: BusinessKnowledge, exp: ExperienceBlueprint): CopyDirection[] {
    const sections = (exp.sectionOrder?.value || []) as any[];
    const brand = bk.vocabulary?.domainNouns?.[0] || bk.discovery.businessType;
    return sections.map((s: any, i: number) => ({
      sectionId: s.id || `section-${i}`,
      heading: i === 0 ? `Welcome to ${brand}` : s.keyMessage || `Section ${i + 1}`,
      body: s.emotionalGoal || `Content for section ${i + 1}`,
      keyPoints: [],
      useWords: [],
      avoidWords: [],
    }));
  }

  private buildContentDensity(exp: ExperienceBlueprint, profile: ContentProfile): ContentDensity[] {
    const sections = (exp.sectionOrder?.value || []) as any[];
    const isMinimal = profile.contentDensity === 'minimal';
    return sections.map((s: any, i: number) => ({
      sectionId: s.id || `section-${i}`,
      textDensity: isMinimal ? 0.3 : 0.6,
      imageDensity: isMinimal ? 0.7 : 0.4,
      videoDensity: 0,
      whitespaceRatio: isMinimal ? 0.5 : 0.3,
    }));
  }

  private buildVoice(profile: ContentProfile): BrandVoice {
    return {
      personality: profile.personality,
      formality: profile.formality,
      technicalLevel: profile.technicalLevel,
      emotionalLevel: profile.emotionalLevel,
      vocabularyComplexity: profile.vocabularyComplexity,
    };
  }

  private buildToneVariations(exp: ExperienceBlueprint, profile: ContentProfile): ToneVariation[] {
    const sections = (exp.sectionOrder?.value || []) as any[];
    return sections.map((s: any, i: number) => ({
      sectionId: s.id || `section-${i}`,
      tone: i === 0 ? profile.defaultTone : 'educational',
      intensity: i === 0 ? 0.8 : 0.5,
    }));
  }

  private getCTAText(action: CTA['action']): string {
    const texts: Record<CTA['action'], string> = {
      'sign-up': 'Get Started', 'purchase': 'Buy Now', 'contact': 'Contact Us',
      'download': 'Download', 'learn-more': 'Learn More', 'demo': 'Request Demo', 'subscribe': 'Subscribe',
    };
    return texts[action] || 'Get Started';
  }
}

type MediaSection = import('./types.js').MediaSection;
type MediaGuidelines = import('./types.js').MediaGuidelines;
