/**
 * Content Intelligence Engine
 *
 * The SINGLE AUTHORITY for:
 * - Hero copy / messaging hierarchy
 * - CTA strategy
 * - Media strategy
 * - Copy direction
 * - Content density
 * - Voice and tone
 *
 * Consumes BusinessKnowledge + ExperienceBlueprint from upstream.
 * Produces ContentBlueprint for downstream.
 *
 * CONSTRAINTS:
 * - Must NOT decide business logic
 * - Must NOT decide experience flow
 * - Must NOT decide visual system
 * - Must NOT decide backend architecture
 */

import type { BusinessKnowledge } from '../business-intelligence/types.js';
import type { ExperienceBlueprint, Provenance } from '../experience-intelligence/types.js';
import type {
  ContentBlueprint,
  CTAStrategy,
  CTA,
  MediaStrategy,
  CopyDirection,
  ContentDensity,
  BrandVoice,
  ToneVariation,
  IContentIntelligenceLayer,
} from './types.js';
import type { ValidationResult } from '../shared/types.js';
import { getIndustryCopy } from '../../bos/industry-copy-schema.js';

// ─── Helpers ──────────────────────────────────────────────────────────────────

function makeProvenance(layer: Provenance['layer'], confidence: number, evidence: string[] = []): Provenance {
  return {
    layer,
    confidence,
    evidence,
    timestamp: new Date(),
    reasoning: `Generated by ${layer}`,
    source: 'content-intelligence',
  };
}

// ─── Industry Content Profiles ────────────────────────────────────────────────

interface IndustryContentProfile {
  personality: BrandVoice['personality'];
  formality: number;
  technicalLevel: number;
  emotionalLevel: number;
  vocabularyComplexity: BrandVoice['vocabularyComplexity'];
  defaultTone: ToneVariation['tone'];
  ctaAction: CTA['action'];
  ctaStyle: CTA['style'];
  contentDensity: 'minimal' | 'balanced' | 'rich';
  mediaStyle: 'photography' | 'illustration' | '3d' | 'abstract' | 'mixed';
  animationLevel: 'none' | 'subtle' | 'moderate' | 'aggressive';
}

const INDUSTRY_CONTENT_PROFILES: Record<string, IndustryContentProfile> = {
  restaurant: { personality: 'friendly', formality: 0.3, technicalLevel: 0.2, emotionalLevel: 0.7, vocabularyComplexity: 'simple', defaultTone: 'excited', ctaAction: 'contact', ctaStyle: 'primary', contentDensity: 'rich', mediaStyle: 'photography', animationLevel: 'subtle' },
  saas: { personality: 'professional', formality: 0.5, technicalLevel: 0.6, emotionalLevel: 0.4, vocabularyComplexity: 'moderate', defaultTone: 'educational', ctaAction: 'sign-up', ctaStyle: 'primary', contentDensity: 'balanced', mediaStyle: 'illustration', animationLevel: 'moderate' },
  ecommerce: { personality: 'friendly', formality: 0.4, technicalLevel: 0.3, emotionalLevel: 0.6, vocabularyComplexity: 'simple', defaultTone: 'excited', ctaAction: 'purchase', ctaStyle: 'primary', contentDensity: 'rich', mediaStyle: 'photography', animationLevel: 'moderate' },
  fitness: { personality: 'friendly', formality: 0.3, technicalLevel: 0.4, emotionalLevel: 0.8, vocabularyComplexity: 'simple', defaultTone: 'inspirational', ctaAction: 'sign-up', ctaStyle: 'primary', contentDensity: 'rich', mediaStyle: 'photography', animationLevel: 'aggressive' },
  healthcare: { personality: 'professional', formality: 0.7, technicalLevel: 0.5, emotionalLevel: 0.5, vocabularyComplexity: 'moderate', defaultTone: 'reassuring', ctaAction: 'contact', ctaStyle: 'primary', contentDensity: 'balanced', mediaStyle: 'photography', animationLevel: 'subtle' },
  'real-estate': { personality: 'professional', formality: 0.6, technicalLevel: 0.4, emotionalLevel: 0.6, vocabularyComplexity: 'moderate', defaultTone: 'inspirational', ctaAction: 'contact', ctaStyle: 'primary', contentDensity: 'rich', mediaStyle: 'photography', animationLevel: 'moderate' },
  fintech: { personality: 'authoritative', formality: 0.6, technicalLevel: 0.7, emotionalLevel: 0.3, vocabularyComplexity: 'advanced', defaultTone: 'reassuring', ctaAction: 'sign-up', ctaStyle: 'primary', contentDensity: 'balanced', mediaStyle: 'illustration', animationLevel: 'subtle' },
  education: { personality: 'friendly', formality: 0.5, technicalLevel: 0.5, emotionalLevel: 0.6, vocabularyComplexity: 'moderate', defaultTone: 'educational', ctaAction: 'sign-up', ctaStyle: 'primary', contentDensity: 'rich', mediaStyle: 'mixed', animationLevel: 'moderate' },
  perfume: { personality: 'sophisticated', formality: 0.7, technicalLevel: 0.3, emotionalLevel: 0.9, vocabularyComplexity: 'advanced', defaultTone: 'inspirational', ctaAction: 'learn-more', ctaStyle: 'primary', contentDensity: 'minimal', mediaStyle: 'photography', animationLevel: 'moderate' },
  fragrance: { personality: 'sophisticated', formality: 0.7, technicalLevel: 0.3, emotionalLevel: 0.9, vocabularyComplexity: 'advanced', defaultTone: 'inspirational', ctaAction: 'learn-more', ctaStyle: 'primary', contentDensity: 'minimal', mediaStyle: 'photography', animationLevel: 'moderate' },
  luxury: { personality: 'sophisticated', formality: 0.8, technicalLevel: 0.2, emotionalLevel: 0.8, vocabularyComplexity: 'advanced', defaultTone: 'inspirational', ctaAction: 'learn-more', ctaStyle: 'primary', contentDensity: 'minimal', mediaStyle: 'photography', animationLevel: 'subtle' },
  beauty: { personality: 'playful', formality: 0.4, technicalLevel: 0.3, emotionalLevel: 0.8, vocabularyComplexity: 'simple', defaultTone: 'excited', ctaAction: 'purchase', ctaStyle: 'primary', contentDensity: 'balanced', mediaStyle: 'photography', animationLevel: 'moderate' },
  nonprofit: { personality: 'authoritative', formality: 0.5, technicalLevel: 0.3, emotionalLevel: 0.9, vocabularyComplexity: 'simple', defaultTone: 'inspirational', ctaAction: 'subscribe', ctaStyle: 'primary', contentDensity: 'rich', mediaStyle: 'photography', animationLevel: 'subtle' },
  portfolio: { personality: 'casual', formality: 0.3, technicalLevel: 0.4, emotionalLevel: 0.7, vocabularyComplexity: 'simple', defaultTone: 'inspirational', ctaAction: 'contact', ctaStyle: 'ghost', contentDensity: 'minimal', mediaStyle: 'mixed', animationLevel: 'moderate' },
  media: { personality: 'playful', formality: 0.4, technicalLevel: 0.4, emotionalLevel: 0.7, vocabularyComplexity: 'moderate', defaultTone: 'excited', ctaAction: 'subscribe', ctaStyle: 'primary', contentDensity: 'rich', mediaStyle: 'mixed', animationLevel: 'moderate' },
  marketplace: { personality: 'friendly', formality: 0.4, technicalLevel: 0.4, emotionalLevel: 0.5, vocabularyComplexity: 'simple', defaultTone: 'educational', ctaAction: 'sign-up', ctaStyle: 'primary', contentDensity: 'rich', mediaStyle: 'photography', animationLevel: 'moderate' },
};

const DEFAULT_CONTENT_PROFILE: IndustryContentProfile = {
  personality: 'professional', formality: 0.5, technicalLevel: 0.4, emotionalLevel: 0.5,
  vocabularyComplexity: 'moderate', defaultTone: 'educational', ctaAction: 'sign-up',
  ctaStyle: 'primary', contentDensity: 'balanced', mediaStyle: 'photography', animationLevel: 'subtle',
};

// ─── Content Intelligence Engine ──────────────────────────────────────────────

export class ContentIntelligenceEngine implements IContentIntelligenceLayer {
  readonly id = 'content-intelligence' as const;
  readonly name = 'Content Intelligence Engine';
  readonly version = '1.0.0';

  async process(
    businessKnowledge: BusinessKnowledge,
    experienceBlueprint: ExperienceBlueprint
  ): Promise<ContentBlueprint> {
    const industry = businessKnowledge.discovery.industry || businessKnowledge.discovery.businessType;
    const profile = INDUSTRY_CONTENT_PROFILES[industry] || DEFAULT_CONTENT_PROFILE;
    const industryCopy = getIndustryCopy(industry);
    const prov = (conf: number) => makeProvenance('content-intelligence', conf);
    const bkId = `bk-${Buffer.from(businessKnowledge.discovery.businessType || 'unknown').toString('base64').slice(0, 12)}`;

    return {
      id: `content-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
      createdAt: new Date(),
      version: '1.0.0',
      businessKnowledgeId: bkId,
      experienceBlueprintId: experienceBlueprint.id,
      primaryMessage: {
        value: this.buildPrimaryMessage(businessKnowledge, industryCopy),
        provenance: prov(0.8),
      },
      supportingMessages: {
        value: this.buildSupportingMessages(businessKnowledge),
        provenance: prov(0.75),
      },
      taglineOptions: {
        value: this.buildTaglineOptions(businessKnowledge, industryCopy),
        provenance: prov(0.7),
      },
      ctaHierarchy: {
        value: this.buildCTAStrategy(businessKnowledge, profile),
        provenance: prov(0.8),
      },
      mediaStrategy: {
        value: this.buildMediaStrategy(businessKnowledge, experienceBlueprint, profile),
        provenance: prov(0.75),
      },
      copyDirection: {
        value: this.buildCopyDirection(businessKnowledge, experienceBlueprint),
        provenance: prov(0.8),
      },
      contentDensity: {
        value: this.buildContentDensity(experienceBlueprint, profile),
        provenance: prov(0.8),
      },
      voice: {
        value: this.buildVoice(profile),
        provenance: prov(0.85),
      },
      toneVariations: {
        value: this.buildToneVariations(experienceBlueprint, profile),
        provenance: prov(0.8),
      },
    };
  }

  validate(blueprint: ContentBlueprint): ValidationResult {
    const issues: Array<{ severity: 'error' | 'warning' | 'info'; message: string; field?: string; fix?: string }> = [];

    if (!blueprint.primaryMessage?.value) {
      issues.push({ severity: 'error', message: 'Missing primary message', field: 'primaryMessage' });
    }
    if (!blueprint.ctaHierarchy?.value?.primary) {
      issues.push({ severity: 'error', message: 'Missing primary CTA', field: 'ctaHierarchy.primary' });
    }
    if (!blueprint.voice?.value?.personality) {
      issues.push({ severity: 'warning', message: 'Empty brand personality', field: 'voice.personality' });
    }
    if (!blueprint.copyDirection?.value?.length) {
      issues.push({ severity: 'warning', message: 'No copy directions defined', field: 'copyDirection' });
    }

    return { valid: issues.filter(i => i.severity === 'error').length === 0, issues };
  }

  // ─── Private Builders ──────────────────────────────────────────────────────

  private buildPrimaryMessage(bk: BusinessKnowledge, _copy: ReturnType<typeof getIndustryCopy>): string {
    // discovery.intent is a string like "A restaurant aimed at..."
    const intent = bk.discovery.intent;
    if (intent && typeof intent === 'string' && intent.length > 10) return intent;
    const persona = bk.customerPersonas?.[0]?.label || 'you';
    return `We help ${persona} with ${bk.discovery.businessType}`;
  }

  private buildSupportingMessages(bk: BusinessKnowledge): string[] {
    const msgs: string[] = [];
    if (bk.entities?.length) msgs.push(`Explore our ${bk.entities.length} offerings`);
    if (bk.revenue?.model) msgs.push(`${bk.revenue.model} designed for you`);
    if (bk.workflows?.length) msgs.push(`Streamlined ${bk.workflows.length} processes`);
    return msgs.slice(0, 3);
  }

  private buildTaglineOptions(bk: BusinessKnowledge, copy: ReturnType<typeof getIndustryCopy>): string[] {
    const opts: string[] = [];
    if (copy?.heroSubheading) opts.push(copy.heroSubheading);
    opts.push(`The future of ${bk.discovery.businessType}`);
    opts.push(`Built for ${bk.customerPersonas?.[0]?.label || 'you'}`);
    return opts.slice(0, 3);
  }

  private buildCTAStrategy(bk: BusinessKnowledge, profile: IndustryContentProfile): CTAStrategy {
    const primary: CTA = {
      text: this.getCTAText(profile.ctaAction),
      action: profile.ctaAction,
      style: profile.ctaStyle,
      urgency: 0.6,
      trustSignals: bk.compliance?.slice(0, 2).map(c => c.pack) || [],
    };
    return {
      primary,
      secondary: [{ text: 'Learn More', action: 'learn-more', style: 'secondary', urgency: 0.3, trustSignals: [] }],
      tertiary: [{ text: 'Contact Us', action: 'contact', style: 'ghost', urgency: 0.2, trustSignals: [] }],
      placementRules: [
        { sectionType: 'hero', position: 'top', style: 'primary', maxFrequency: 1 },
        { sectionType: 'features', position: 'bottom', style: 'secondary', maxFrequency: 1 },
        { sectionType: 'testimonials', position: 'bottom', style: 'primary', maxFrequency: 1 },
      ],
    };
  }

  private buildMediaStrategy(bk: BusinessKnowledge, exp: ExperienceBlueprint, profile: IndustryContentProfile): MediaStrategy {
    const sections = (exp.sectionOrder?.value || []) as any[];
    return {
      sections: sections.map((s: any, i: number) => ({
        sectionId: s.id || `section-${i}`,
        type: 'image',
        purpose: i === 0 ? 'hero' : 'product',
        aspectRatio: i === 0 ? '16:9' : '4:3',
        quality: 'high',
        altTextDirection: `${bk.discovery.businessType} - section ${i + 1}`,
      })),
      global: {
        imageStyle: profile.mediaStyle as any,
        colorTreatment: 'full-color',
        animationLevel: profile.animationLevel,
      },
    };
  }

  private buildCopyDirection(bk: BusinessKnowledge, exp: ExperienceBlueprint): CopyDirection[] {
    const sections = (exp.sectionOrder?.value || []) as any[];
    const brand = bk.vocabulary?.domainNouns?.[0] || bk.discovery.businessType;
    return sections.map((s: any, i: number) => ({
      sectionId: s.id || `section-${i}`,
      heading: i === 0 ? `Welcome to ${brand}` : s.keyMessage || `Section ${i + 1}`,
      body: s.emotionalGoal || `Content for section ${i + 1}`,
      keyPoints: [],
      useWords: [],
      avoidWords: [],
    }));
  }

  private buildContentDensity(exp: ExperienceBlueprint, profile: IndustryContentProfile): ContentDensity[] {
    const sections = (exp.sectionOrder?.value || []) as any[];
    const isMinimal = profile.contentDensity === 'minimal';
    return sections.map((s: any, i: number) => ({
      sectionId: s.id || `section-${i}`,
      textDensity: isMinimal ? 0.3 : 0.6,
      imageDensity: isMinimal ? 0.7 : 0.4,
      videoDensity: 0,
      whitespaceRatio: isMinimal ? 0.5 : 0.3,
    }));
  }

  private buildVoice(profile: IndustryContentProfile): BrandVoice {
    return {
      personality: profile.personality,
      formality: profile.formality,
      technicalLevel: profile.technicalLevel,
      emotionalLevel: profile.emotionalLevel,
      vocabularyComplexity: profile.vocabularyComplexity,
    };
  }

  private buildToneVariations(exp: ExperienceBlueprint, profile: IndustryContentProfile): ToneVariation[] {
    const sections = (exp.sectionOrder?.value || []) as any[];
    return sections.map((s: any, i: number) => ({
      sectionId: s.id || `section-${i}`,
      tone: i === 0 ? profile.defaultTone : 'educational',
      intensity: i === 0 ? 0.8 : 0.5,
    }));
  }

  private getCTAText(action: CTA['action']): string {
    const texts: Record<CTA['action'], string> = {
      'sign-up': 'Get Started', 'purchase': 'Buy Now', 'contact': 'Contact Us',
      'download': 'Download', 'learn-more': 'Learn More', 'demo': 'Request Demo', 'subscribe': 'Subscribe',
    };
    return texts[action] || 'Get Started';
  }
}

type MediaSection = import('./types.js').MediaSection;
type MediaGuidelines = import('./types.js').MediaGuidelines;
