/**
 * Default Taxonomy Registry
 * =========================
 *
 * Bootstrap taxonomy covering all known industries.
 * Knowledge packs can extend this at runtime.
 *
 * This replaces the hardcoded INDUSTRY_MAPPINGS in intake-parser.ts.
 */

import type { TaxonomyRegistry, TaxonomyNode } from './types.js';

const DEFAULT_NODES: TaxonomyNode[] = [
  // ── Retail ──────────────────────────────────────────────────────────────
  {
    slug: 'retail',
    label: 'Retail',
    aliases: ['shop', 'store', 'commerce', 'ecommerce', 'e-commerce', 'online store'],
    evidenceKeywords: ['shop', 'store', 'product', 'cart', 'checkout', 'buy', 'sell', 'inventory'],
    defaultPersonality: 'professional',
    defaultColorHint: '#2563eb',
  },
  {
    slug: 'retail/footwear',
    label: 'Footwear',
    parent: 'retail',
    aliases: ['shoes', 'footwear', 'boot', 'sandal', 'sneaker store'],
    evidenceKeywords: ['shoe', 'footwear', 'boot', 'sandal', 'sneaker', 'running shoe', 'athletic shoe'],
    defaultPersonality: 'bold',
    defaultColorHint: '#FF4500',
  },
  {
    slug: 'retail/footwear/athletic',
    label: 'Athletic Footwear',
    parent: 'retail/footwear',
    aliases: ['athletic shoes', 'running shoes', 'sports shoes', 'gym shoes'],
    evidenceKeywords: ['running', 'athletic', 'sports', 'gym', 'training', 'marathon'],
    defaultPersonality: 'bold',
    defaultColorHint: '#FF4500',
  },
  {
    slug: 'retail/footwear/casual',
    label: 'Casual Footwear',
    parent: 'retail/footwear',
    aliases: ['casual shoes', 'everyday shoes', 'lifestyle shoes'],
    evidenceKeywords: ['casual', 'everyday', 'lifestyle', 'comfort'],
    defaultPersonality: 'friendly',
    defaultColorHint: '#FF6B35',
  },
  {
    slug: 'retail/footwear/luxury',
    label: 'Luxury Footwear',
    parent: 'retail/footwear',
    aliases: ['designer shoes', 'luxury shoes', 'high-end footwear'],
    evidenceKeywords: ['luxury', 'designer', 'premium', 'high-end', 'exclusive'],
    defaultPersonality: 'sophisticated',
    defaultColorHint: '#1a1a2e',
  },
  {
    slug: 'retail/supplement',
    label: 'Supplements',
    parent: 'retail',
    aliases: ['supplement store', 'health supplements', 'nutrition store', 'protein shop'],
    evidenceKeywords: ['supplement', 'protein', 'vitamin', 'nutrition', 'pre-workout', 'creatine'],
    defaultPersonality: 'energetic',
    defaultColorHint: '#10b981',
  },
  {
    slug: 'retail/electronics',
    label: 'Electronics',
    parent: 'retail',
    aliases: ['electronics store', 'tech store', 'gadget shop'],
    evidenceKeywords: ['electronic', 'gadget', 'tech', 'computer', 'phone', 'laptop'],
    defaultPersonality: 'modern',
    defaultColorHint: '#3b82f6',
  },
  {
    slug: 'retail/beauty',
    label: 'Beauty Products',
    parent: 'retail',
    aliases: ['beauty store', 'cosmetics shop', 'makeup store'],
    evidenceKeywords: ['cosmetic', 'makeup', 'skincare', 'beauty product'],
    defaultPersonality: 'elegant',
    defaultColorHint: '#ec4899',
  },
  {
    slug: 'retail/fashion',
    label: 'Fashion',
    parent: 'retail',
    aliases: ['clothing store', 'fashion boutique', 'apparel shop'],
    evidenceKeywords: ['fashion', 'clothing', 'apparel', 'wear', 'outfit', 'dress'],
    defaultPersonality: 'creative',
    defaultColorHint: '#8b5cf6',
  },
  {
    slug: 'retail/food',
    label: 'Food Retail',
    parent: 'retail',
    aliases: ['grocery', 'food store', 'organic store'],
    evidenceKeywords: ['grocery', 'organic', 'food product', 'gourmet'],
    defaultPersonality: 'warm',
    defaultColorHint: '#f59e0b',
  },
  {
    slug: 'retail/wholesale',
    label: 'Wholesale',
    parent: 'retail',
    aliases: ['wholesale', 'bulk store', 'distributor'],
    evidenceKeywords: ['wholesale', 'bulk', 'distributor', 'B2B'],
    defaultPersonality: 'professional',
    defaultColorHint: '#64748b',
  },
  {
    slug: 'retail/luxury',
    label: 'Luxury Retail',
    parent: 'retail',
    aliases: ['luxury store', 'high-end retail', 'premium boutique'],
    evidenceKeywords: ['luxury', 'premium', 'exclusive', 'high-end', 'bespoke'],
    defaultPersonality: 'sophisticated',
    defaultColorHint: '#1a1a2e',
  },
  {
    slug: 'retail/perfume',
    label: 'Perfume',
    parent: 'retail',
    aliases: ['perfume store', 'fragrance shop', 'perfumery'],
    evidenceKeywords: ['perfume', 'fragrance', 'scent', 'cologne', 'eau de'],
    defaultPersonality: 'sophisticated',
    defaultColorHint: '#d4a373',
  },
  {
    slug: 'retail/fragrance',
    label: 'Fragrance',
    parent: 'retail',
    aliases: ['fragrance store', 'niche perfume', 'oud', 'attar'],
    evidenceKeywords: ['fragrance', 'oud', 'attar', 'niche perfume', 'artisan scent'],
    defaultPersonality: 'sophisticated',
    defaultColorHint: '#d4a373',
  },
  {
    slug: 'retail/pet',
    label: 'Pet Services',
    parent: 'retail',
    aliases: ['pet store', 'pet shop', 'pet supplies'],
    evidenceKeywords: ['pet', 'dog', 'cat', 'animal', 'pet food', 'pet supplies'],
    defaultPersonality: 'friendly',
    defaultColorHint: '#f97316',
  },

  // ── Services ────────────────────────────────────────────────────────────
  {
    slug: 'services',
    label: 'Services',
    aliases: ['service', 'agency', 'consulting'],
    evidenceKeywords: ['service', 'consult', 'agency', 'hire', 'booking'],
    defaultPersonality: 'professional',
    defaultColorHint: '#3b82f6',
  },
  {
    slug: 'services/healthcare',
    label: 'Healthcare',
    parent: 'services',
    aliases: ['health', 'medical', 'clinic', 'hospital', 'doctor'],
    evidenceKeywords: ['health', 'medical', 'clinic', 'hospital', 'doctor', 'patient', 'treatment'],
    defaultPersonality: 'trustworthy',
    defaultColorHint: '#059669',
  },
  {
    slug: 'services/healthcare/dental',
    label: 'Dental',
    parent: 'services/healthcare',
    aliases: ['dental', 'dentist', 'dental clinic', 'dental practice'],
    evidenceKeywords: ['dental', 'dentist', 'tooth', 'teeth', 'orthodontist', 'braces'],
    defaultPersonality: 'trustworthy',
    defaultColorHint: '#0ea5e9',
  },
  {
    slug: 'services/healthcare/veterinary',
    label: 'Veterinary',
    parent: 'services/healthcare',
    aliases: ['vet', 'veterinary', 'animal hospital'],
    evidenceKeywords: ['veterinary', 'vet', 'animal hospital', 'pet clinic'],
    defaultPersonality: 'caring',
    defaultColorHint: '#10b981',
  },
  {
    slug: 'services/healthcare/therapy',
    label: 'Therapy',
    parent: 'services/healthcare',
    aliases: ['therapy', 'physiotherapy', 'counseling', 'mental health'],
    evidenceKeywords: ['therapy', 'physiotherapy', 'counseling', 'mental health', 'rehabilitation'],
    defaultPersonality: 'calming',
    defaultColorHint: '#8b5cf6',
  },
  {
    slug: 'services/healthcare/pharmacy',
    label: 'Pharmacy',
    parent: 'services/healthcare',
    aliases: ['pharmacy', 'drugstore', 'chemist'],
    evidenceKeywords: ['pharmacy', 'drugstore', 'medicine', 'prescription'],
    defaultPersonality: 'trustworthy',
    defaultColorHint: '#059669',
  },
  {
    slug: 'services/healthcare/cosmetic',
    label: 'Cosmetic Surgery',
    parent: 'services/healthcare',
    aliases: ['cosmetic surgery', 'plastic surgery', 'aesthetic clinic'],
    evidenceKeywords: ['cosmetic', 'plastic surgery', 'aesthetic', 'botox'],
    defaultPersonality: 'sophisticated',
    defaultColorHint: '#ec4899',
  },
  {
    slug: 'services/legal',
    label: 'Legal',
    parent: 'services',
    aliases: ['law', 'lawyer', 'attorney', 'law firm', 'legal services'],
    evidenceKeywords: ['law', 'lawyer', 'attorney', 'legal', 'litigation', 'court'],
    defaultPersonality: 'authoritative',
    defaultColorHint: '#1e293b',
  },
  {
    slug: 'services/legal/corporate',
    label: 'Corporate Law',
    parent: 'services/legal',
    aliases: ['corporate law', 'business law', 'corporate legal'],
    evidenceKeywords: ['corporate', 'business law', 'merger', 'acquisition'],
    defaultPersonality: 'authoritative',
    defaultColorHint: '#1e293b',
  },
  {
    slug: 'services/legal/family',
    label: 'Family Law',
    parent: 'services/legal',
    aliases: ['family law', 'divorce lawyer', 'custody'],
    evidenceKeywords: ['family', 'divorce', 'custody', 'adoption'],
    defaultPersonality: 'caring',
    defaultColorHint: '#6366f1',
  },
  {
    slug: 'services/legal/litigation',
    label: 'Litigation',
    parent: 'services/legal',
    aliases: ['litigation', 'trial lawyer', 'civil litigation'],
    evidenceKeywords: ['litigation', 'trial', 'lawsuit', 'court'],
    defaultPersonality: 'bold',
    defaultColorHint: '#dc2626',
  },
  {
    slug: 'services/real-estate',
    label: 'Real Estate',
    parent: 'services',
    aliases: ['property', 'real estate', 'realty', 'house', 'apartment'],
    evidenceKeywords: ['property', 'house', 'apartment', 'real estate', 'listing', 'agent'],
    defaultPersonality: 'trustworthy',
    defaultColorHint: '#059669',
  },
  {
    slug: 'services/real-estate/commercial',
    label: 'Commercial Real Estate',
    parent: 'services/real-estate',
    aliases: ['commercial property', 'office space', 'retail space'],
    evidenceKeywords: ['commercial', 'office', 'retail space', 'warehouse'],
    defaultPersonality: 'professional',
    defaultColorHint: '#1e40af',
  },
  {
    slug: 'services/real-estate/residential',
    label: 'Residential Real Estate',
    parent: 'services/real-estate',
    aliases: ['residential', 'home sale', 'house sale'],
    evidenceKeywords: ['residential', 'home', 'house', 'condo', 'townhouse'],
    defaultPersonality: 'warm',
    defaultColorHint: '#059669',
  },
  {
    slug: 'services/real-estate/luxury',
    label: 'Luxury Real Estate',
    parent: 'services/real-estate',
    aliases: ['luxury property', 'luxury home', 'high-end real estate'],
    evidenceKeywords: ['luxury', 'premium', 'high-end', 'mansion', 'villa'],
    defaultPersonality: 'sophisticated',
    defaultColorHint: '#1a1a2e',
  },
  {
    slug: 'services/real-estate/rental',
    label: 'Rental Properties',
    parent: 'services/real-estate',
    aliases: ['rental', 'rent property', 'vacation rental'],
    evidenceKeywords: ['rental', 'rent', 'lease', 'tenant', 'airbnb'],
    defaultPersonality: 'friendly',
    defaultColorHint: '#10b981',
  },
  {
    slug: 'services/fitness',
    label: 'Fitness',
    parent: 'services',
    aliases: ['gym', 'fitness center', 'health club', 'workout'],
    evidenceKeywords: ['gym', 'workout', 'exercise', 'fitness', 'training', 'muscle'],
    defaultPersonality: 'energetic',
    defaultColorHint: '#ef4444',
  },
  {
    slug: 'services/fitness/crossfit',
    label: 'CrossFit',
    parent: 'services/fitness',
    aliases: ['crossfit', 'crossfit box', 'functional fitness'],
    evidenceKeywords: ['crossfit', 'WOD', 'functional fitness', 'box'],
    defaultPersonality: 'energetic',
    defaultColorHint: '#dc2626',
  },
  {
    slug: 'services/fitness/yoga',
    label: 'Yoga',
    parent: 'services/fitness',
    aliases: ['yoga', 'yoga studio', 'yoga class'],
    evidenceKeywords: ['yoga', 'meditation', 'mindfulness', 'flexibility'],
    defaultPersonality: 'calming',
    defaultColorHint: '#8b5cf6',
  },
  {
    slug: 'services/fitness/personal-training',
    label: 'Personal Training',
    parent: 'services/fitness',
    aliases: ['personal trainer', 'private training', '1-on-1 training'],
    evidenceKeywords: ['personal trainer', 'private training', '1-on-1', 'coaching'],
    defaultPersonality: 'motivational',
    defaultColorHint: '#f97316',
  },
  {
    slug: 'services/beauty',
    label: 'Beauty Services',
    parent: 'services',
    aliases: ['salon', 'beauty salon', 'beauty parlor', 'spa'],
    evidenceKeywords: ['salon', 'beauty', 'spa', 'makeup', 'facial', 'hair'],
    defaultPersonality: 'elegant',
    defaultColorHint: '#ec4899',
  },
  {
    slug: 'services/beauty/salon',
    label: 'Salon',
    parent: 'services/beauty',
    aliases: ['hair salon', 'beauty salon', 'nail salon'],
    evidenceKeywords: ['hair', 'nail', 'salon', 'styling', 'manicure'],
    defaultPersonality: 'elegant',
    defaultColorHint: '#ec4899',
  },
  {
    slug: 'services/beauty/spa',
    label: 'Spa',
    parent: 'services/beauty',
    aliases: ['day spa', 'wellness spa', 'medical spa'],
    evidenceKeywords: ['spa', 'massage', 'facial', 'wellness', 'relaxation'],
    defaultPersonality: 'calming',
    defaultColorHint: '#06b6d4',
  },
  {
    slug: 'services/event',
    label: 'Events',
    parent: 'services',
    aliases: ['event planning', 'event management', 'conference'],
    evidenceKeywords: ['event', 'wedding', 'conference', 'party', 'celebration'],
    defaultPersonality: 'creative',
    defaultColorHint: '#f59e0b',
  },
  {
    slug: 'services/event/wedding',
    label: 'Wedding Planning',
    parent: 'services/event',
    aliases: ['wedding planner', 'wedding coordinator', 'wedding planning'],
    evidenceKeywords: ['wedding', 'bride', 'ceremony', 'reception'],
    defaultPersonality: 'romantic',
    defaultColorHint: '#f472b6',
  },
  {
    slug: 'services/event/corporate',
    label: 'Corporate Events',
    parent: 'services/event',
    aliases: ['corporate event', 'conference planning', 'corporate meeting'],
    evidenceKeywords: ['corporate', 'conference', 'summit', 'seminar'],
    defaultPersonality: 'professional',
    defaultColorHint: '#1e40af',
  },
  {
    slug: 'services/travel',
    label: 'Travel',
    parent: 'services',
    aliases: ['travel agency', 'tour operator', 'travel company'],
    evidenceKeywords: ['travel', 'tour', 'trip', 'vacation', 'holiday', 'booking'],
    defaultPersonality: 'adventurous',
    defaultColorHint: '#0ea5e9',
  },
  {
    slug: 'services/travel/luxury',
    label: 'Luxury Travel',
    parent: 'services/travel',
    aliases: ['luxury travel', 'luxury vacation', 'high-end travel'],
    evidenceKeywords: ['luxury', 'premium', 'high-end', 'exclusive', 'bespoke'],
    defaultPersonality: 'sophisticated',
    defaultColorHint: '#1a1a2e',
  },
  {
    slug: 'services/automotive',
    label: 'Automotive',
    parent: 'services',
    aliases: ['car dealer', 'auto dealer', 'car showroom', 'vehicle dealer'],
    evidenceKeywords: ['car', 'vehicle', 'auto', 'dealership', 'showroom', 'motor'],
    defaultPersonality: 'bold',
    defaultColorHint: '#1e293b',
  },
  {
    slug: 'services/automotive/ev',
    label: 'Electric Vehicles',
    parent: 'services/automotive',
    aliases: ['ev', 'electric car', 'electric vehicle', 'tesla'],
    evidenceKeywords: ['electric', 'ev', 'battery', 'charging', 'sustainable'],
    defaultPersonality: 'innovative',
    defaultColorHint: '#10b981',
  },

  // ── Software ────────────────────────────────────────────────────────────
  {
    slug: 'software',
    label: 'Software',
    aliases: ['software', 'tech', 'technology', 'digital'],
    evidenceKeywords: ['software', 'app', 'platform', 'digital', 'cloud', 'SaaS'],
    defaultPersonality: 'modern',
    defaultColorHint: '#3b82f6',
  },
  {
    slug: 'software/saas',
    label: 'SaaS',
    parent: 'software',
    aliases: ['saas', 'software as a service', 'cloud software', 'web app'],
    evidenceKeywords: ['saas', 'subscription', 'cloud', 'dashboard', 'analytics', 'API'],
    defaultPersonality: 'modern',
    defaultColorHint: '#3b82f6',
  },
  {
    slug: 'software/saas/dev-tools',
    label: 'Developer Tools',
    parent: 'software/saas',
    aliases: ['dev tools', 'developer tools', 'code tools', 'programming tools'],
    evidenceKeywords: ['developer', 'code', 'API', 'SDK', 'git', 'IDE'],
    defaultPersonality: 'technical',
    defaultColorHint: '#6366f1',
  },
  {
    slug: 'software/saas/analytics',
    label: 'Analytics',
    parent: 'software/saas',
    aliases: ['analytics', 'data analytics', 'business intelligence', 'BI'],
    evidenceKeywords: ['analytics', 'dashboard', 'report', 'metric', 'KPI', 'insight'],
    defaultPersonality: 'analytical',
    defaultColorHint: '#0ea5e9',
  },
  {
    slug: 'software/saas/crm',
    label: 'CRM',
    parent: 'software/saas',
    aliases: ['crm', 'customer relationship', 'sales software'],
    evidenceKeywords: ['CRM', 'lead', 'customer', 'pipeline', 'sales'],
    defaultPersonality: 'professional',
    defaultColorHint: '#2563eb',
  },
  {
    slug: 'software/saas/erp',
    label: 'ERP',
    parent: 'software/saas',
    aliases: ['erp', 'enterprise resource', 'business management'],
    evidenceKeywords: ['ERP', 'enterprise', 'resource planning', 'supply chain'],
    defaultPersonality: 'authoritative',
    defaultColorHint: '#1e40af',
  },
  {
    slug: 'software/saas/project-mgmt',
    label: 'Project Management',
    parent: 'software/saas',
    aliases: ['project management', 'task management', 'productivity'],
    evidenceKeywords: ['project', 'task', 'kanban', 'sprint', 'agile', 'scrum'],
    defaultPersonality: 'organized',
    defaultColorHint: '#8b5cf6',
  },
  {
    slug: 'software/fintech',
    label: 'FinTech',
    parent: 'software',
    aliases: ['fintech', 'financial technology', 'banking software'],
    evidenceKeywords: ['fintech', 'banking', 'payment', 'finance', 'money'],
    defaultPersonality: 'trustworthy',
    defaultColorHint: '#059669',
  },
  {
    slug: 'software/fintech/banking',
    label: 'Banking',
    parent: 'software/fintech',
    aliases: ['banking', 'digital bank', 'neobank'],
    evidenceKeywords: ['bank', 'account', 'transfer', 'deposit', 'loan'],
    defaultPersonality: 'trustworthy',
    defaultColorHint: '#1e40af',
  },
  {
    slug: 'software/fintech/payments',
    label: 'Payments',
    parent: 'software/fintech',
    aliases: ['payment', 'payment processing', 'payment gateway'],
    evidenceKeywords: ['payment', 'checkout', 'transaction', 'gateway', 'UPI'],
    defaultPersonality: 'secure',
    defaultColorHint: '#059669',
  },
  {
    slug: 'software/fintech/insurance',
    label: 'InsurTech',
    parent: 'software/fintech',
    aliases: ['insurance', 'insurtech', 'digital insurance'],
    evidenceKeywords: ['insurance', 'policy', 'claim', 'coverage', 'premium'],
    defaultPersonality: 'trustworthy',
    defaultColorHint: '#6366f1',
  },
  {
    slug: 'software/fintech/crypto',
    label: 'Crypto',
    parent: 'software/fintech',
    aliases: ['crypto', 'cryptocurrency', 'blockchain', 'web3'],
    evidenceKeywords: ['crypto', 'bitcoin', 'ethereum', 'blockchain', 'wallet', 'DeFi'],
    defaultPersonality: 'innovative',
    defaultColorHint: '#f59e0b',
  },
  {
    slug: 'software/logistics',
    label: 'Logistics',
    parent: 'software',
    aliases: ['logistics', 'shipping', 'delivery', 'fleet management'],
    evidenceKeywords: ['logistics', 'shipping', 'delivery', 'fleet', 'warehouse', '3PL'],
    defaultPersonality: 'efficient',
    defaultColorHint: '#64748b',
  },
  {
    slug: 'software/manufacturing',
    label: 'Manufacturing',
    parent: 'software',
    aliases: ['manufacturing', 'factory', 'production', 'industrial'],
    evidenceKeywords: ['manufacturing', 'factory', 'production', 'assembly', 'industrial'],
    defaultPersonality: 'industrial',
    defaultColorHint: '#374151',
  },
  {
    slug: 'software/enterprise',
    label: 'Enterprise Software',
    parent: 'software',
    aliases: ['enterprise', 'enterprise software', 'internal tools'],
    evidenceKeywords: ['enterprise', 'internal', 'employee', 'workflow', 'approval'],
    defaultPersonality: 'authoritative',
    defaultColorHint: '#1e40af',
  },

  // ── Food & Beverage ─────────────────────────────────────────────────────
  {
    slug: 'food-and-beverage',
    label: 'Food & Beverage',
    aliases: ['food', 'beverage', 'restaurant', 'cafe', 'dining', 'culinary'],
    evidenceKeywords: ['food', 'restaurant', 'dining', 'menu', 'chef', 'cuisine', 'cafe', 'coffee'],
    defaultPersonality: 'warm',
    defaultColorHint: '#f59e0b',
  },
  {
    slug: 'food-and-beverage/restaurant',
    label: 'Restaurant',
    parent: 'food-and-beverage',
    aliases: ['restaurant', 'diner', 'eatery', 'bistro'],
    evidenceKeywords: ['restaurant', 'menu', 'chef', 'dining', 'kitchen', 'meal'],
    defaultPersonality: 'warm',
    defaultColorHint: '#f59e0b',
  },
  {
    slug: 'food-and-beverage/restaurant/coffee',
    label: 'Coffee Shop',
    parent: 'food-and-beverage/restaurant',
    aliases: ['coffee shop', 'cafe', 'coffeehouse', 'espresso bar'],
    evidenceKeywords: ['coffee', 'espresso', 'latte', 'cafe', 'barista', 'brew'],
    defaultPersonality: 'cozy',
    defaultColorHint: '#92400e',
  },
  {
    slug: 'food-and-beverage/restaurant/bakery',
    label: 'Bakery',
    parent: 'food-and-beverage/restaurant',
    aliases: ['bakery', 'bake shop', 'patisserie'],
    evidenceKeywords: ['bakery', 'bread', 'pastry', 'cake', 'baking'],
    defaultPersonality: 'warm',
    defaultColorHint: '#f59e0b',
  },
  {
    slug: 'food-and-beverage/restaurant/fine-dining',
    label: 'Fine Dining',
    parent: 'food-and-beverage/restaurant',
    aliases: ['fine dining', 'upscale restaurant', 'gourmet'],
    evidenceKeywords: ['fine dining', 'gourmet', 'michelin', 'upscale', 'tasting menu'],
    defaultPersonality: 'sophisticated',
    defaultColorHint: '#1a1a2e',
  },
  {
    slug: 'food-and-beverage/restaurant/fast-food',
    label: 'Fast Food',
    parent: 'food-and-beverage/restaurant',
    aliases: ['fast food', 'quick service', 'QSR'],
    evidenceKeywords: ['fast food', 'quick service', 'drive-through', 'takeout'],
    defaultPersonality: 'energetic',
    defaultColorHint: '#ef4444',
  },
  {
    slug: 'food-and-beverage/cafe',
    label: 'Cafe',
    parent: 'food-and-beverage',
    aliases: ['cafe', 'coffee shop', 'teahouse'],
    evidenceKeywords: ['cafe', 'coffee', 'tea', 'pastry', 'light meal'],
    defaultPersonality: 'cozy',
    defaultColorHint: '#92400e',
  },
  {
    slug: 'food-and-beverage/bakery',
    label: 'Bakery',
    parent: 'food-and-beverage',
    aliases: ['bakery', 'bake shop', 'patisserie'],
    evidenceKeywords: ['bakery', 'bread', 'pastry', 'cake', 'cookie'],
    defaultPersonality: 'warm',
    defaultColorHint: '#f59e0b',
  },

  // ── Education ───────────────────────────────────────────────────────────
  {
    slug: 'education',
    label: 'Education',
    aliases: ['school', 'university', 'college', 'learning', 'training', 'course', 'tutor'],
    evidenceKeywords: ['school', 'course', 'learn', 'teach', 'tutor', 'education', 'training'],
    defaultPersonality: 'trustworthy',
    defaultColorHint: '#2563eb',
  },
  {
    slug: 'education/coaching',
    label: 'Coaching',
    parent: 'education',
    aliases: ['coaching', 'coaching center', 'coaching institute'],
    evidenceKeywords: ['coaching', 'mentor', 'coaching center', 'exam prep'],
    defaultPersonality: 'motivational',
    defaultColorHint: '#f59e0b',
  },
  {
    slug: 'education/university',
    label: 'University',
    parent: 'education',
    aliases: ['university', 'college', 'institute'],
    evidenceKeywords: ['university', 'college', 'degree', 'campus', 'faculty'],
    defaultPersonality: 'authoritative',
    defaultColorHint: '#1e40af',
  },
  {
    slug: 'education/k-12',
    label: 'K-12',
    parent: 'education',
    aliases: ['k-12', 'school', 'high school', 'elementary'],
    evidenceKeywords: ['school', 'student', 'classroom', 'teacher', 'homework'],
    defaultPersonality: 'friendly',
    defaultColorHint: '#10b981',
  },
  {
    slug: 'education/upsc',
    label: 'UPSC',
    parent: 'education',
    aliases: ['upsc', 'civil services', 'ias preparation'],
    evidenceKeywords: ['UPSC', 'civil services', 'IAS', 'government exam'],
    defaultPersonality: 'authoritative',
    defaultColorHint: '#1e40af',
  },

  // ── Creative ────────────────────────────────────────────────────────────
  {
    slug: 'creative',
    label: 'Creative',
    aliases: ['creative', 'design', 'art', 'studio'],
    evidenceKeywords: ['creative', 'design', 'art', 'studio', 'portfolio'],
    defaultPersonality: 'creative',
    defaultColorHint: '#8b5cf6',
  },
  {
    slug: 'creative/portfolio',
    label: 'Portfolio',
    parent: 'creative',
    aliases: ['portfolio', 'personal portfolio', 'creative portfolio'],
    evidenceKeywords: ['portfolio', 'personal', 'showcase', 'work', 'projects'],
    defaultPersonality: 'creative',
    defaultColorHint: '#8b5cf6',
  },
  {
    slug: 'creative/agency',
    label: 'Agency',
    parent: 'creative',
    aliases: ['agency', 'digital agency', 'marketing agency', 'creative agency'],
    evidenceKeywords: ['agency', 'marketing', 'branding', 'advertising', 'campaign'],
    defaultPersonality: 'bold',
    defaultColorHint: '#f43f5e',
  },

  // ── Media ───────────────────────────────────────────────────────────────
  {
    slug: 'media',
    label: 'Media',
    aliases: ['media', 'blog', 'news', 'magazine', 'publication'],
    evidenceKeywords: ['blog', 'news', 'article', 'magazine', 'editorial', 'publish'],
    defaultPersonality: 'editorial',
    defaultColorHint: '#1e293b',
  },
  {
    slug: 'media/blog',
    label: 'Blog',
    parent: 'media',
    aliases: ['blog', 'personal blog', 'content site'],
    evidenceKeywords: ['blog', 'post', 'article', 'content', 'writing'],
    defaultPersonality: 'editorial',
    defaultColorHint: '#1e293b',
  },
  {
    slug: 'media/news',
    label: 'News',
    parent: 'media',
    aliases: ['news', 'news site', 'news publication'],
    evidenceKeywords: ['news', 'headline', 'report', 'journalism'],
    defaultPersonality: 'authoritative',
    defaultColorHint: '#dc2626',
  },
  {
    slug: 'media/magazine',
    label: 'Magazine',
    parent: 'media',
    aliases: ['magazine', 'digital magazine', 'publication'],
    evidenceKeywords: ['magazine', 'issue', 'editorial', 'feature'],
    defaultPersonality: 'sophisticated',
    defaultColorHint: '#1e293b',
  },
  {
    slug: 'media/podcast',
    label: 'Podcast',
    parent: 'media',
    aliases: ['podcast', 'podcast show', 'audio show'],
    evidenceKeywords: ['podcast', 'episode', 'host', 'interview', 'audio'],
    defaultPersonality: 'conversational',
    defaultColorHint: '#8b5cf6',
  },
  {
    slug: 'media/youtube',
    label: 'YouTube',
    parent: 'media',
    aliases: ['youtube', 'youtube channel', 'video channel'],
    evidenceKeywords: ['youtube', 'video', 'channel', 'subscriber', 'view'],
    defaultPersonality: 'energetic',
    defaultColorHint: '#ef4444',
  },
  {
    slug: 'media/newsletter',
    label: 'Newsletter',
    parent: 'media',
    aliases: ['newsletter', 'email newsletter', 'email list'],
    evidenceKeywords: ['newsletter', 'email', 'subscriber', 'inbox', 'digest'],
    defaultPersonality: 'editorial',
    defaultColorHint: '#1e293b',
  },

  // ── Nonprofit ───────────────────────────────────────────────────────────
  {
    slug: 'nonprofit',
    label: 'Nonprofit',
    aliases: ['nonprofit', 'ngo', 'charity', 'foundation', 'not-for-profit'],
    evidenceKeywords: ['nonprofit', 'ngo', 'charity', 'donation', 'cause', 'mission'],
    defaultPersonality: 'compassionate',
    defaultColorHint: '#10b981',
  },
  {
    slug: 'nonprofit/charity',
    label: 'Charity',
    parent: 'nonprofit',
    aliases: ['charity', 'charitable organization'],
    evidenceKeywords: ['charity', 'donate', 'fundraise', 'volunteer'],
    defaultPersonality: 'compassionate',
    defaultColorHint: '#10b981',
  },
  {
    slug: 'nonprofit/foundation',
    label: 'Foundation',
    parent: 'nonprofit',
    aliases: ['foundation', 'grant foundation', 'philanthropy'],
    evidenceKeywords: ['foundation', 'grant', 'philanthropy', 'endowment'],
    defaultPersonality: 'authoritative',
    defaultColorHint: '#1e40af',
  },
  {
    slug: 'nonprofit/community',
    label: 'Community',
    parent: 'nonprofit',
    aliases: ['community organization', 'community group', 'grassroots'],
    evidenceKeywords: ['community', 'grassroots', 'local', 'volunteer'],
    defaultPersonality: 'friendly',
    defaultColorHint: '#f59e0b',
  },
];

export const DEFAULT_TAXONOMY: TaxonomyRegistry = {
  version: '1.0.0',
  nodes: DEFAULT_NODES,
};
