/**
 * Enterprise Patterns — Phase 1A
 *
 * Covers: Hospital ERP, Generic ERP, HRM, School LMS, Enterprise CRM,
 *         Logistics Platform, Manufacturing ERP.
 *
 * All patterns use sidebar navigation (enterprise/admin convention),
 * domain-specific roles, departments, KPIs, vocabulary, and business rules.
 * These fields are consumed by the KnowledgeGraph enricher (Phase 2)
 * and surfaced in the build inspector (Phase 4).
 */
import type { Pattern } from '../../schemas/knowledge/pattern.schema.js';

// ─── 1. Hospital Management System ───────────────────────────────────────────

export const HOSPITAL_MANAGEMENT: Pattern = {
  id: 'pattern.healthcare.hospital-management',
  version: '1.0.0',
  status: 'active',
  createdAt: '2026-07-01T00:00:00+00:00',
  updatedAt: '2026-07-01T00:00:00+00:00',
  evidenceRefs: [],
  kind: 'Pattern',
  name: 'Hospital Management System',
  description: 'Full hospital ERP with patient management, appointments, wards, pharmacy, lab, billing, and staff modules',
  navigation: {
    style: 'sidebar',
    sticky: true,
    logo: true,
    items: [
      { label: 'Dashboard', href: '/' },
      { label: 'Patients', href: '/patients' },
      { label: 'Appointments', href: '/appointments' },
      { label: 'Doctors', href: '/doctors' },
      { label: 'Wards', href: '/wards' },
      { label: 'Pharmacy', href: '/pharmacy' },
      { label: 'Lab', href: '/lab' },
      { label: 'Billing', href: '/billing' },
      { label: 'Staff', href: '/staff' },
      { label: 'Reports', href: '/reports' },
    ],
  },
  pages: [
    { path: '/', name: 'Dashboard', type: 'dashboard', sections: ['stats-cards', 'activity-feed', 'charts', 'dashboard-widgets'],
      description: 'Admin overview: OPD count, bed occupancy, revenue, recent admissions' },
    { path: '/patients', name: 'Patients', type: 'listing', sections: ['filters', 'data-table'],
      description: 'Patient registry with search by name, ID, phone; filter by department' },
    { path: '/patients/:id', name: 'Patient Detail', type: 'detail', sections: ['profile', 'data-table', 'activity-feed'],
      description: 'Patient history, prescriptions, appointments, lab results, billing' },
    { path: '/appointments', name: 'Appointments', type: 'listing', sections: ['filters', 'calendar', 'data-table'],
      description: 'Today and upcoming appointments; calendar and list views; status tracking' },
    { path: '/doctors', name: 'Doctors', type: 'listing', sections: ['filters', 'team-grid'],
      description: 'Doctor directory with specialization, availability, schedule' },
    { path: '/wards', name: 'Wards', type: 'listing', sections: ['stats-cards', 'data-table'],
      description: 'Ward and bed management: occupancy, patient assignments, discharge' },
    { path: '/prescriptions', name: 'Prescriptions', type: 'listing', sections: ['filters', 'data-table', 'prescription-form'],
      description: 'Patient prescriptions: issue, refill, track, and manage dosage history' },
    { path: '/pharmacy', name: 'Pharmacy', type: 'listing', sections: ['stats-cards', 'filters', 'data-table'],
      description: 'Medicine inventory, dispensing, low-stock alerts, reorder management' },
    { path: '/lab', name: 'Lab Reports', type: 'listing', sections: ['filters', 'data-table'],
      description: 'Lab test orders, results upload, report delivery to doctors/patients' },
    { path: '/billing', name: 'Billing', type: 'dashboard', sections: ['stats-cards', 'filters', 'data-table', 'charts'],
      description: 'Invoice generation from services+medicines+room; payment tracking; insurance claims' },
    { path: '/staff', name: 'Staff', type: 'listing', sections: ['filters', 'team-grid'],
      description: 'Staff directory: nurses, technicians, admin; shift assignments' },
    { path: '/reports', name: 'Reports', type: 'dashboard', sections: ['filters', 'charts', 'data-table'],
      description: 'Revenue reports, OPD/IPD stats, department performance, compliance exports' },
  ],
  components: ['PatientCard', 'AppointmentCalendar', 'BillingTable', 'MedicineInventory', 'LabResultViewer', 'WardMap', 'StaffCard'],
  relationships: [],
  workflows: [
    'Patient Registration → OPD → Prescription → Pharmacy → Billing',
    'Appointment Booking → Doctor Consultation → Lab Order → Results → Follow-up',
    'Emergency Admission → Ward Assignment → Discharge → Invoice',
    'Medicine Reorder → Purchase Order → Stock Receipt → Inventory Update',
  ],
  integrations: [
    { type: 'auth', name: 'NextAuth.js', config: { provider: 'credentials' }, required: true },
    { type: 'email', name: 'Resend', config: {}, required: false },
    { type: 'analytics', name: 'PostHog', config: {}, required: false },
  ],
  design: {
    profileRef: 'design-profile.healthcare-clean',
    restrictions: ['clean-medical-aesthetic', 'high-data-density', 'accessible-colors', 'sidebar-navigation'],
  },
  generationRules: [],
  compatibleIndustries: ['healthcare', 'hospital', 'medical-center', 'clinic-chain', 'multi-specialty', 'enterprise-software', 'patient', 'clinic', 'doctor', 'appointment'],
  compatibleBusinessModels: ['subscription', 'wholesale'],
  // Enterprise extensions
  roles: ['Administrator', 'Doctor', 'Nurse', 'Receptionist', 'Lab Technician', 'Pharmacist', 'Billing Officer', 'Department Head'],
  departments: ['OPD', 'IPD', 'Emergency', 'Laboratory', 'Pharmacy', 'Radiology', 'Surgery', 'ICU', 'Administration', 'Billing & Finance'],
  kpis: ['Daily OPD Count', 'Bed Occupancy Rate', 'Average Wait Time (min)', 'Revenue Per Department', 'Discharge Rate', 'Lab TAT (hours)', 'Prescription Fill Rate'],
  vocabulary: {
    Customer: 'Patient',
    User: 'Staff',
    Product: 'Medicine',
    Order: 'Prescription',
    Invoice: 'Bill',
    Category: 'Department',
    Listing: 'Ward',
  },
  businessRules: [
    'Patient registration requires: name, DOB, gender, contact number, emergency contact',
    'Appointments must link to a patient, a doctor, a department, date, and time slot',
    'Prescriptions must link to a patient, prescribing doctor, and list of medicines with dosage',
    'Lab orders require doctor authorization before sample collection',
    'Billing auto-aggregates consultation fees + medicines dispensed + room charges + lab tests',
    'Bed assignment requires ward, room, and bed number; max one active patient per bed',
    'Medicine stock triggers low-stock alert when quantity falls below reorder level',
    'Insurance claims require policy number, insurer name, and pre-authorization code',
  ],
};

// ─── 2. Generic Enterprise ERP ────────────────────────────────────────────────

export const ERP_SYSTEM: Pattern = {
  id: 'pattern.enterprise.erp-system',
  version: '1.0.0',
  status: 'active',
  createdAt: '2026-07-01T00:00:00+00:00',
  updatedAt: '2026-07-01T00:00:00+00:00',
  evidenceRefs: [],
  kind: 'Pattern',
  name: 'Enterprise Resource Planning (ERP)',
  description: 'Full-stack ERP with inventory, procurement, finance, HR, and reporting modules',
  navigation: {
    style: 'sidebar',
    sticky: true,
    logo: true,
    items: [
      { label: 'Dashboard', href: '/' },
      { label: 'Inventory', href: '/inventory' },
      { label: 'Procurement', href: '/procurement' },
      { label: 'Finance', href: '/finance' },
      { label: 'Human Resources', href: '/hr' },
      { label: 'CRM', href: '/crm' },
      { label: 'Reports', href: '/reports' },
      { label: 'Settings', href: '/settings' },
    ],
  },
  pages: [
    { path: '/', name: 'Dashboard', type: 'dashboard', sections: ['stats-cards', 'charts', 'activity-feed'],
      description: 'Executive summary: revenue, orders, inventory health, headcount, open POs' },
    { path: '/inventory', name: 'Inventory', type: 'listing', sections: ['stats-cards', 'filters', 'data-table'],
      description: 'Stock levels by item, warehouse, category; low-stock alerts; stock movements' },
    { path: '/procurement', name: 'Procurement', type: 'listing', sections: ['filters', 'data-table'],
      description: 'Purchase orders: create, approve, receive; vendor management; PO tracking' },
    { path: '/finance', name: 'Finance', type: 'dashboard', sections: ['stats-cards', 'charts', 'data-table'],
      description: 'P&L, balance sheet summary, accounts payable/receivable, expense tracking' },
    { path: '/hr', name: 'Human Resources', type: 'listing', sections: ['filters', 'team-grid', 'data-table'],
      description: 'Employee directory, departments, leave management, payroll summary' },
    { path: '/crm', name: 'CRM', type: 'listing', sections: ['filters', 'data-table'],
      description: 'Customer accounts, contacts, deal pipeline, activity log' },
    { path: '/reports', name: 'Reports', type: 'dashboard', sections: ['filters', 'charts', 'data-table'],
      description: 'Exportable reports: inventory, sales, finance, HR across all modules' },
    { path: '/settings', name: 'Settings', type: 'page', sections: ['profile', 'data-table'],
      description: 'Company settings, user roles, module configuration, integrations' },
  ],
  components: ['InventoryTable', 'PurchaseOrderForm', 'FinanceSummaryCard', 'EmployeeList', 'ReportBuilder', 'ApprovalWorkflow'],
  relationships: [],
  workflows: [
    'Purchase Requisition → PO Approval → Vendor PO → Goods Receipt → Inventory Update → Invoice Payment',
    'Sales Order → Inventory Check → Fulfillment → Shipping → Invoice → Payment',
    'Employee Onboarding → Payroll Setup → Department Assignment → Access Provisioning',
    'Expense Submission → Manager Approval → Finance Approval → Reimbursement',
  ],
  integrations: [
    { type: 'auth', name: 'NextAuth.js', config: { provider: 'credentials' }, required: true },
    { type: 'payment', name: 'Stripe', config: {}, required: false },
    { type: 'email', name: 'Resend', config: {}, required: true },
    { type: 'analytics', name: 'PostHog', config: {}, required: false },
  ],
  design: {
    profileRef: 'design-profile.enterprise-clean',
    restrictions: ['high-data-density', 'sidebar-navigation', 'professional-aesthetic'],
  },
  generationRules: [],
  compatibleIndustries: ['enterprise-software', 'manufacturing', 'logistics', 'wholesale', 'distribution', 'retail-chain', 'erp', 'resource planning', 'operations'],
  compatibleBusinessModels: ['subscription', 'wholesale'],
  roles: ['CEO / Executive', 'Department Manager', 'Finance Officer', 'HR Manager', 'Inventory Manager', 'Procurement Officer', 'Sales Manager', 'IT Administrator'],
  departments: ['Executive', 'Finance', 'Human Resources', 'Inventory & Warehouse', 'Procurement', 'Sales & CRM', 'Operations', 'IT'],
  kpis: ['Revenue (MTD)', 'Operating Expenses', 'Inventory Turnover', 'Open Purchase Orders', 'Headcount', 'Accounts Receivable (aged)', 'Order Fulfillment Rate'],
  vocabulary: {
    Customer: 'Account',
    User: 'Employee',
    Product: 'Item',
    Order: 'Purchase Order',
    Category: 'Department',
  },
  businessRules: [
    'Purchase orders above approval threshold require manager sign-off before sending to vendor',
    'Goods receipt must match PO quantity within tolerance; variance triggers reconciliation workflow',
    'Payroll run requires all attendance records closed for the period',
    'Inventory adjustment requires reason code and supervisor authorization',
    'Finance period close blocks new entries after cut-off date until reopened by Finance Officer',
    'New user accounts require department assignment and role before activation',
  ],
};

// ─── 3. HR Management System ─────────────────────────────────────────────────

export const HRM_SYSTEM: Pattern = {
  id: 'pattern.enterprise.hrm-system',
  version: '1.0.0',
  status: 'active',
  createdAt: '2026-07-01T00:00:00+00:00',
  updatedAt: '2026-07-01T00:00:00+00:00',
  evidenceRefs: [],
  kind: 'Pattern',
  name: 'Human Resource Management System (HRMS)',
  description: 'Complete HRMS with employee master, attendance, leave, payroll, recruitment, and performance management',
  navigation: {
    style: 'sidebar',
    sticky: true,
    logo: true,
    items: [
      { label: 'Dashboard', href: '/' },
      { label: 'Employees', href: '/employees' },
      { label: 'Attendance', href: '/attendance' },
      { label: 'Leave', href: '/leave' },
      { label: 'Payroll', href: '/payroll' },
      { label: 'Recruitment', href: '/recruitment' },
      { label: 'Performance', href: '/performance' },
      { label: 'Reports', href: '/reports' },
    ],
  },
  pages: [
    { path: '/', name: 'Dashboard', type: 'dashboard', sections: ['stats-cards', 'charts', 'activity-feed'],
      description: 'Headcount, attendance today, pending leave requests, open positions, upcoming reviews' },
    { path: '/employees', name: 'Employees', type: 'listing', sections: ['filters', 'team-grid', 'data-table'],
      description: 'Full employee directory: search by name, department, role, status; view/edit profiles' },
    { path: '/employees/:id', name: 'Employee Profile', type: 'detail', sections: ['profile', 'data-table', 'activity-feed'],
      description: 'Personal details, employment history, leave balance, payslips, performance records' },
    { path: '/attendance', name: 'Attendance', type: 'dashboard', sections: ['stats-cards', 'calendar', 'data-table'],
      description: 'Daily attendance log: present, absent, late, half-day; monthly view; bulk import' },
    { path: '/leave', name: 'Leave Management', type: 'listing', sections: ['stats-cards', 'filters', 'data-table'],
      description: 'Leave requests: apply, approve, reject; leave balance tracker; holiday calendar' },
    { path: '/payroll', name: 'Payroll', type: 'dashboard', sections: ['stats-cards', 'filters', 'data-table', 'charts'],
      description: 'Monthly payroll run: CTC breakdown, deductions, net pay; payslip generation and email' },
    { path: '/recruitment', name: 'Recruitment', type: 'listing', sections: ['filters', 'data-table'],
      description: 'Job openings, applicant tracking, interview scheduling, offer management' },
    { path: '/performance', name: 'Performance', type: 'listing', sections: ['filters', 'charts', 'data-table'],
      description: 'Review cycles, goal setting, ratings, 360-degree feedback, performance history' },
    { path: '/reports', name: 'Reports', type: 'dashboard', sections: ['filters', 'charts', 'data-table'],
      description: 'Headcount report, attrition, payroll summary, leave utilization, recruitment funnel' },
  ],
  components: ['EmployeeCard', 'AttendanceCalendar', 'LeaveRequestForm', 'PayslipViewer', 'RecruitmentKanban', 'PerformanceRatingForm'],
  relationships: [],
  workflows: [
    'Employee Onboarding → Profile Creation → Department Assignment → Payroll Setup → Access Provisioning',
    'Leave Application → Manager Approval → HR Approval → Calendar Update → Leave Balance Deduction',
    'Recruitment Pipeline → Job Posting → Applications → Screening → Interviews → Offer → Joining',
    'Payroll Run → Attendance Import → Deductions Calculation → Net Pay → Payslip Distribution',
    'Performance Review → Goal Setting → Mid-Year Check-in → Annual Review → Rating → Increment',
  ],
  integrations: [
    { type: 'auth', name: 'NextAuth.js', config: { provider: 'credentials' }, required: true },
    { type: 'email', name: 'Resend', config: {}, required: true },
    { type: 'analytics', name: 'PostHog', config: {}, required: false },
  ],
  design: {
    profileRef: 'design-profile.enterprise-clean',
    restrictions: ['professional-aesthetic', 'sidebar-navigation', 'high-data-density'],
  },
  generationRules: [],
  compatibleIndustries: ['enterprise-software', 'saas', 'manufacturing', 'healthcare', 'logistics', 'education', 'hrms', 'employee', 'payroll', 'leave', 'attendance', 'recruitment'],
  compatibleBusinessModels: ['subscription'],
  roles: ['HR Manager', 'HR Executive', 'Department Manager', 'Team Lead', 'Employee', 'Finance (Payroll)', 'Recruiter', 'System Administrator'],
  departments: ['Human Resources', 'Payroll & Finance', 'Recruitment', 'Learning & Development', 'Administration'],
  kpis: ['Total Headcount', 'Attrition Rate (%)', 'Attendance Rate (%)', 'Open Positions', 'Time to Hire (days)', 'Payroll Accuracy (%)', 'Leave Utilization (%)'],
  vocabulary: {
    Customer: 'Employee',
    User: 'HR Admin',
    Product: 'Position',
    Order: 'Leave Request',
    Category: 'Department',
    Listing: 'Employee Directory',
  },
  businessRules: [
    'Employee ID must be unique; auto-generated in format EMP-YYYY-NNNN',
    'Leave request requires leave type, from date, to date, and reason; cannot overlap with existing approved leave',
    'Leave approval requires immediate manager then HR sign-off for leaves longer than 3 days',
    'Payroll run is locked until all attendance for the period is finalized',
    'Annual leave balance resets on January 1st; carry-forward capped at 5 days',
    'Payslip must show CTC, gross salary, all deductions (PF, tax, etc.), and net take-home',
    'Terminated employees lose system access within 24 hours of termination date',
    'Performance reviews are mandatory bi-annually; overdue reviews trigger HR notification',
  ],
};

// ─── 4. School Management System / LMS ───────────────────────────────────────

export const SCHOOL_LMS: Pattern = {
  id: 'pattern.education.school-management',
  version: '1.0.0',
  status: 'active',
  createdAt: '2026-07-01T00:00:00+00:00',
  updatedAt: '2026-07-01T00:00:00+00:00',
  evidenceRefs: [],
  kind: 'Pattern',
  name: 'School Management System',
  description: 'Complete school administration with students, classes, teachers, attendance, exams, fees, and parent portal',
  navigation: {
    style: 'sidebar',
    sticky: true,
    logo: true,
    items: [
      { label: 'Dashboard', href: '/' },
      { label: 'Students', href: '/students' },
      { label: 'Classes', href: '/classes' },
      { label: 'Teachers', href: '/teachers' },
      { label: 'Attendance', href: '/attendance' },
      { label: 'Exams & Grades', href: '/exams' },
      { label: 'Fees', href: '/fees' },
      { label: 'Timetable', href: '/timetable' },
      { label: 'Reports', href: '/reports' },
    ],
  },
  pages: [
    { path: '/', name: 'Dashboard', type: 'dashboard', sections: ['stats-cards', 'activity-feed', 'charts'],
      description: 'Total students, attendance today, fee collection this month, upcoming exams' },
    { path: '/students', name: 'Students', type: 'listing', sections: ['filters', 'data-table'],
      description: 'Student registry: search by name, class, roll number; admission management' },
    { path: '/students/:id', name: 'Student Profile', type: 'detail', sections: ['profile', 'data-table', 'activity-feed'],
      description: 'Student details, attendance history, exam results, fee payment history, parent contact' },
    { path: '/classes', name: 'Classes', type: 'listing', sections: ['filters', 'data-table'],
      description: 'Class sections: class teacher assignment, student list, subject list, timetable link' },
    { path: '/teachers', name: 'Teachers', type: 'listing', sections: ['filters', 'team-grid'],
      description: 'Teacher directory: subjects taught, class assignments, timetable, contact' },
    { path: '/attendance', name: 'Attendance', type: 'dashboard', sections: ['calendar', 'data-table', 'filters'],
      description: 'Daily attendance marking by class; student-wise monthly attendance report; SMS alerts for absences' },
    { path: '/exams', name: 'Exams & Grades', type: 'listing', sections: ['filters', 'data-table', 'charts'],
      description: 'Exam schedule, mark entry, result calculation, grade card generation, ranking' },
    { path: '/fees', name: 'Fee Management', type: 'dashboard', sections: ['stats-cards', 'filters', 'data-table'],
      description: 'Fee structure setup, student fee records, payment collection, defaulter list, receipts' },
    { path: '/timetable', name: 'Timetable', type: 'listing', sections: ['calendar', 'filters'],
      description: 'Weekly timetable by class; teacher-wise timetable; period and break management' },
    { path: '/reports', name: 'Reports', type: 'dashboard', sections: ['filters', 'charts', 'data-table'],
      description: 'Attendance report, result analysis, fee collection, class performance comparison' },
  ],
  components: ['StudentCard', 'AttendanceGrid', 'ExamResultTable', 'FeeReceipt', 'Timetable', 'ClassCard', 'TeacherCard'],
  relationships: [],
  workflows: [
    'Student Admission → Profile Creation → Class Assignment → Fee Structure → Parent Account',
    'Daily Attendance → Teacher Marks → Absence Alert → Monthly Summary',
    'Exam Schedule → Mark Entry → Result Calculation → Grade Cards → Report Cards',
    'Fee Due → Reminder SMS/Email → Payment Collection → Receipt → Update Balance',
  ],
  integrations: [
    { type: 'auth', name: 'NextAuth.js', config: { provider: 'credentials' }, required: true },
    { type: 'email', name: 'Resend', config: {}, required: true },
    { type: 'analytics', name: 'PostHog', config: {}, required: false },
  ],
  design: {
    profileRef: 'design-profile.education-friendly',
    restrictions: ['clear-typography', 'accessible-colors', 'sidebar-navigation'],
  },
  generationRules: [],
  compatibleIndustries: ['education', 'school', 'college', 'university', 'training-institute', 'coaching-center', 'enterprise-software', 'elearning'],
  compatibleBusinessModels: ['subscription'],
  roles: ['Principal / Administrator', 'Class Teacher', 'Subject Teacher', 'Accountant', 'Admissions Officer', 'Parent', 'Student'],
  departments: ['Administration', 'Academic', 'Finance & Fees', 'Examinations', 'Admissions', 'Library', 'Sports'],
  kpis: ['Total Enrollment', 'Daily Attendance Rate (%)', 'Pass Percentage (%)', 'Fee Collection Rate (%)', 'Average Grade Score', 'Defaulter Count'],
  vocabulary: {
    Customer: 'Student',
    User: 'Teacher',
    Product: 'Course',
    Order: 'Admission',
    Category: 'Class',
    Invoice: 'Fee Receipt',
  },
  businessRules: [
    'Student roll number is unique within a class-section; auto-assigned on admission',
    'Attendance can only be marked for the current day by the class teacher',
    'Exam marks cannot exceed the maximum marks defined for that exam',
    'Fee payment generates an auto-numbered receipt; partial payments are tracked',
    'Result is "Pass" only if student meets minimum pass percentage in all subjects',
    'Timetable cannot assign the same teacher to two classes at the same period',
    'Parent account is linked to student and has read-only access to attendance, grades, and fees',
  ],
};

// ─── 5. Enterprise CRM ───────────────────────────────────────────────────────

export const CRM_ENTERPRISE: Pattern = {
  id: 'pattern.enterprise.crm',
  version: '1.0.0',
  status: 'active',
  createdAt: '2026-07-01T00:00:00+00:00',
  updatedAt: '2026-07-01T00:00:00+00:00',
  evidenceRefs: [],
  kind: 'Pattern',
  name: 'Enterprise CRM',
  description: 'Full-featured CRM with lead management, pipeline, accounts, contacts, tasks, emails, and sales reporting',
  navigation: {
    style: 'sidebar',
    sticky: true,
    logo: true,
    items: [
      { label: 'Dashboard', href: '/' },
      { label: 'Leads', href: '/leads' },
      { label: 'Pipeline', href: '/pipeline' },
      { label: 'Accounts', href: '/accounts' },
      { label: 'Contacts', href: '/contacts' },
      { label: 'Tasks', href: '/tasks' },
      { label: 'Reports', href: '/reports' },
      { label: 'Settings', href: '/settings' },
    ],
  },
  pages: [
    { path: '/', name: 'Dashboard', type: 'dashboard', sections: ['stats-cards', 'charts', 'activity-feed'],
      description: 'Sales summary: new leads, pipeline value, deals closed, revenue forecast, activity feed' },
    { path: '/leads', name: 'Leads', type: 'listing', sections: ['filters', 'data-table'],
      description: 'Lead list: source, status, assigned to, last activity; bulk import; convert to deal' },
    { path: '/pipeline', name: 'Pipeline', type: 'dashboard', sections: ['filters', 'data-table', 'charts'],
      description: 'Deal pipeline by stage: Prospecting → Qualification → Proposal → Negotiation → Closed Won/Lost' },
    { path: '/accounts', name: 'Accounts', type: 'listing', sections: ['filters', 'data-table'],
      description: 'Company accounts: name, industry, ARR, contacts, deals, activity timeline' },
    { path: '/accounts/:id', name: 'Account Detail', type: 'detail', sections: ['profile', 'data-table', 'activity-feed'],
      description: 'Account 360: contacts, open deals, call logs, emails, notes, documents, tasks' },
    { path: '/contacts', name: 'Contacts', type: 'listing', sections: ['filters', 'data-table'],
      description: 'Contact directory: linked to accounts; communication history; role and title' },
    { path: '/tasks', name: 'Tasks', type: 'listing', sections: ['filters', 'data-table', 'activity-feed'],
      description: 'Tasks and activities: follow-up calls, demos, proposals; due date; owner; linked deal' },
    { path: '/reports', name: 'Reports', type: 'dashboard', sections: ['filters', 'charts', 'data-table'],
      description: 'Sales funnel, conversion rates, revenue by rep, win/loss analysis, forecast accuracy' },
    { path: '/settings', name: 'Settings', type: 'page', sections: ['profile', 'data-table'],
      description: 'Pipeline stages, lead sources, custom fields, team management, integrations' },
  ],
  components: ['LeadCard', 'PipelineKanban', 'AccountTimeline', 'ContactCard', 'TaskList', 'DealForm', 'ActivityFeed'],
  relationships: [],
  workflows: [
    'Lead Capture (web/import) → Qualification → Demo Scheduled → Proposal Sent → Negotiation → Closed',
    'Lead → Convert to Account + Contact + Deal → Assign to Rep',
    'Task Created → Reminder → Complete → Log Activity → Update Deal Stage',
    'Deal Won → Invoice Generated → Revenue Recognized → Account Update',
  ],
  integrations: [
    { type: 'auth', name: 'NextAuth.js', config: { provider: 'credentials' }, required: true },
    { type: 'email', name: 'Resend', config: {}, required: true },
    { type: 'analytics', name: 'PostHog', config: {}, required: false },
  ],
  design: {
    profileRef: 'design-profile.saas-modern',
    restrictions: ['professional-aesthetic', 'sidebar-navigation', 'data-dense-views'],
  },
  generationRules: [],
  compatibleIndustries: ['enterprise-software', 'saas', 'agency', 'consulting', 'real-estate', 'logistics', 'manufacturing', 'crm', 'sales', 'lead', 'pipeline', 'accounts'],
  compatibleBusinessModels: ['subscription', 'direct-sales'],
  roles: ['Sales Manager', 'Account Executive', 'Sales Development Rep (SDR)', 'Business Development Manager', 'Customer Success Manager', 'CRM Administrator'],
  departments: ['Sales', 'Business Development', 'Customer Success', 'Marketing', 'Revenue Operations'],
  kpis: ['New Leads (week)', 'Pipeline Value ($)', 'Deals Closed (MTD)', 'Win Rate (%)', 'Average Deal Size ($)', 'Sales Cycle Length (days)', 'Revenue Forecast'],
  vocabulary: {
    Customer: 'Account',
    User: 'Sales Rep',
    Product: 'Deal',
    Order: 'Proposal',
    Category: 'Lead Source',
    Subscription: 'Deal Stage',
  },
  businessRules: [
    'Lead must have name and email; phone and company are recommended',
    'Lead conversion creates an Account, a Contact, and a Deal simultaneously',
    'Deal stage progression is sequential; skipping stages requires manager override',
    'Closed Won deals automatically generate an invoice draft',
    'Closed Lost deals require a loss reason before the stage can be set',
    'Tasks with past due dates turn red and notify the assigned rep daily',
    'Revenue is recognized in the month the deal is marked Closed Won',
  ],
};

// ─── 6. Logistics & Fleet Management ─────────────────────────────────────────

export const LOGISTICS_PLATFORM: Pattern = {
  id: 'pattern.logistics.platform',
  version: '1.0.0',
  status: 'active',
  createdAt: '2026-07-01T00:00:00+00:00',
  updatedAt: '2026-07-01T00:00:00+00:00',
  evidenceRefs: [],
  kind: 'Pattern',
  name: 'Logistics & Fleet Management Platform',
  description: 'End-to-end logistics with shipment management, driver tracking, route optimization, warehouse, and POD',
  navigation: {
    style: 'sidebar',
    sticky: true,
    logo: true,
    items: [
      { label: 'Dashboard', href: '/' },
      { label: 'Shipments', href: '/shipments' },
      { label: 'Drivers', href: '/drivers' },
      { label: 'Routes', href: '/routes' },
      { label: 'Warehouses', href: '/warehouses' },
      { label: 'Live Tracking', href: '/tracking' },
      { label: 'Reports', href: '/reports' },
    ],
  },
  pages: [
    { path: '/', name: 'Dashboard', type: 'dashboard', sections: ['stats-cards', 'charts', 'activity-feed'],
      description: 'Active shipments, in-transit count, delayed alerts, today\'s deliveries, fleet status' },
    { path: '/shipments', name: 'Shipments', type: 'listing', sections: ['filters', 'data-table'],
      description: 'All shipments: status (pending/in-transit/delivered/failed), customer, origin, destination, ETA' },
    { path: '/shipments/:id', name: 'Shipment Detail', type: 'detail', sections: ['profile', 'activity-feed', 'data-table'],
      description: 'Full shipment timeline, assigned driver, route, package details, POD, customer communications' },
    { path: '/drivers', name: 'Drivers', type: 'listing', sections: ['filters', 'team-grid'],
      description: 'Driver directory: license, vehicle, current status, trip history, performance score' },
    { path: '/routes', name: 'Routes', type: 'listing', sections: ['filters', 'data-table', 'charts'],
      description: 'Route definitions, shipments per route, on-time rate, distance and duration analytics' },
    { path: '/warehouses', name: 'Warehouses', type: 'listing', sections: ['stats-cards', 'data-table'],
      description: 'Warehouse locations, capacity, current utilization, inbound/outbound volumes' },
    { path: '/inventory', name: 'Inventory', type: 'dashboard', sections: ['filters', 'data-table', 'charts'],
      description: 'Stock levels across warehouses, low-stock alerts, inventory adjustments, bin transfers' },
    { path: '/receiving', name: 'Receiving', type: 'listing', sections: ['filters', 'data-table', 'receiving-form'],
      description: 'Inbound shipments: receive, inspect, log against purchase orders, and stage for putaway' },
    { path: '/putaway', name: 'Putaway', type: 'listing', sections: ['filters', 'data-table', 'location-assignment'],
      description: 'Putaway tasks: assign storage locations, update inventory, track completion' },
    { path: '/picking', name: 'Picking', type: 'listing', sections: ['filters', 'data-table', 'pick-list'],
      description: 'Pick lists: wave planning, picker assignment, scan confirmation, exception handling' },
    { path: '/shipping', name: 'Shipping', type: 'listing', sections: ['filters', 'data-table', 'shipping-form'],
      description: 'Outbound shipments: pack, label, carrier assignment, manifest generation' },
    { path: '/tracking', name: 'Live Tracking', type: 'dashboard', sections: ['stats-cards', 'activity-feed', 'data-table'],
      description: 'Real-time shipment status feed; delayed shipments highlight; ETA updates' },
    { path: '/reports', name: 'Reports', type: 'dashboard', sections: ['filters', 'charts', 'data-table'],
      description: 'Delivery performance, on-time rate, driver performance, route efficiency, cost per shipment' },
  ],
  components: ['ShipmentCard', 'DriverCard', 'RouteMap', 'TrackingTimeline', 'WarehouseCapacityBar', 'DeliveryStatusBadge'],
  relationships: [],
  workflows: [
    'Shipment Created → Driver Assigned → Route Planned → Pickup → In Transit → Delivery → POD → Completed',
    'Customer Portal: Track Shipment → View ETA → Receive Delivery Notification → Rate Experience',
    'Failed Delivery → Exception Logged → Rescheduled → Retry → Second Attempt → Return if Failed',
    'Driver: Accept Trip → Navigate Route → Mark Packages Delivered → Upload POD Photo → Trip Completed',
  ],
  integrations: [
    { type: 'auth', name: 'NextAuth.js', config: { provider: 'credentials' }, required: true },
    { type: 'maps', name: 'Mapbox', config: {}, required: false },
    { type: 'email', name: 'Resend', config: {}, required: false },
    { type: 'analytics', name: 'PostHog', config: {}, required: false },
  ],
  design: {
    profileRef: 'design-profile.logistics-reliable',
    restrictions: ['clear-status-indicators', 'sidebar-navigation', 'professional-aesthetic'],
  },
  generationRules: [],
  compatibleIndustries: ['logistics', 'shipping', 'courier', 'freight', 'last-mile', 'fleet-management', 'supply-chain', 'enterprise-software', 'warehouse', 'inventory', 'fleet', 'shipment', 'dispatch'],
  compatibleBusinessModels: ['subscription', 'wholesale'],
  roles: ['Operations Manager', 'Dispatcher', 'Driver', 'Warehouse Manager', 'Customer Service', 'Finance Officer', 'System Administrator'],
  departments: ['Operations', 'Fleet & Drivers', 'Warehouse', 'Customer Service', 'Finance & Billing'],
  kpis: ['Active Shipments', 'On-Time Delivery Rate (%)', 'Average Delivery Time (hours)', 'Failed Deliveries (%)', 'Fleet Utilization (%)', 'Cost Per Shipment ($)', 'POD Capture Rate (%)'],
  vocabulary: {
    Customer: 'Client',
    User: 'Driver',
    Product: 'Shipment',
    Order: 'Trip',
    Category: 'Route',
    Invoice: 'Freight Bill',
  },
  businessRules: [
    'Shipment ID auto-generated as SHP-YYYYMMDD-NNNN; unique across the system',
    'Driver can only be assigned to one active trip at a time',
    'POD (Proof of Delivery) requires either signature capture or photo upload',
    'Shipment status transitions are sequential: Created → Assigned → Picked Up → In Transit → Delivered / Failed',
    'Failed delivery must have a failure reason and triggers automatic rescheduling workflow',
    'ETA is recalculated on each status update; customer is notified if ETA changes by more than 2 hours',
    'Warehouse receives inbound only during defined operating hours',
  ],
};

// ─── 7. Manufacturing ERP ────────────────────────────────────────────────────

export const MANUFACTURING_ERP: Pattern = {
  id: 'pattern.manufacturing.erp',
  version: '1.0.0',
  status: 'active',
  createdAt: '2026-07-01T00:00:00+00:00',
  updatedAt: '2026-07-01T00:00:00+00:00',
  evidenceRefs: [],
  kind: 'Pattern',
  name: 'Manufacturing ERP',
  description: 'Production-focused ERP with work orders, BOM, production scheduling, quality control, machine management, and raw material inventory',
  navigation: {
    style: 'sidebar',
    sticky: true,
    logo: true,
    items: [
      { label: 'Dashboard', href: '/' },
      { label: 'Work Orders', href: '/work-orders' },
      { label: 'Production', href: '/production' },
      { label: 'Inventory', href: '/inventory' },
      { label: 'Quality Control', href: '/quality' },
      { label: 'Machines', href: '/machines' },
      { label: 'Reports', href: '/reports' },
    ],
  },
  pages: [
    { path: '/', name: 'Dashboard', type: 'dashboard', sections: ['stats-cards', 'charts', 'activity-feed'],
      description: 'Production today: active work orders, output vs target, machine uptime, quality pass rate, material alerts' },
    { path: '/work-orders', name: 'Work Orders', type: 'listing', sections: ['filters', 'data-table'],
      description: 'Work orders: product, quantity, start date, due date, status, assigned production line' },
    { path: '/work-orders/:id', name: 'Work Order Detail', type: 'detail', sections: ['profile', 'data-table', 'activity-feed'],
      description: 'BOM list, operations sequence, material consumption, labour hours, quality checks, output recorded' },
    { path: '/production', name: 'Production', type: 'dashboard', sections: ['stats-cards', 'filters', 'data-table', 'charts'],
      description: 'Daily production log: line-wise output, shift performance, downtime log, efficiency rate' },
    { path: '/inventory', name: 'Raw Materials', type: 'listing', sections: ['stats-cards', 'filters', 'data-table'],
      description: 'Raw material stock by item, unit, location; low-stock alerts; consumption history; reorder management' },
    { path: '/quality', name: 'Quality Control', type: 'listing', sections: ['filters', 'data-table', 'charts'],
      description: 'QC inspection results per work order; pass/fail/rework/reject; defect category analysis; trend charts' },
    { path: '/machines', name: 'Machines', type: 'listing', sections: ['data-table', 'activity-feed'],
      description: 'Machine registry: ID, type, location, status; maintenance schedule; downtime log; utilization' },
    { path: '/reports', name: 'Reports', type: 'dashboard', sections: ['filters', 'charts', 'data-table'],
      description: 'Production vs plan, quality defect rate, machine OEE, material consumption vs BOM, labour cost' },
    { path: '/projects', name: 'Projects', type: 'listing', sections: ['filters', 'data-table', 'charts'],
      description: 'Construction projects: timeline, budget, resources, milestones, site assignments' },
    { path: '/projects/:id', name: 'Project Detail', type: 'detail', sections: ['profile', 'data-table', 'activity-feed', 'charts'],
      description: 'Project dashboard: phases, budget tracking, resource allocation, site logs, contractor status' },
    { path: '/contractors', name: 'Contractors', type: 'listing', sections: ['filters', 'team-grid'],
      description: 'Contractor directory: trade, license, insurance, assigned projects, performance rating' },
    { path: '/materials', name: 'Materials', type: 'listing', sections: ['filters', 'data-table'],
      description: 'Construction materials: purchase orders, stock on site, delivery schedules, quality checks' },
    { path: '/sites', name: 'Job Sites', type: 'listing', sections: ['filters', 'data-table', 'charts'],
      description: 'Active job sites: location, status, crew assigned, progress %, safety incidents' },
  ],
  components: ['WorkOrderTable', 'BOMViewer', 'ProductionLineStatus', 'QCInspectionForm', 'MachineCard', 'MaterialConsumptionChart', 'ProjectCard', 'ContractorCard', 'SiteMap'],
  relationships: [],
  workflows: [
    'Sales Order → Production Plan → Work Order Created → Material Issue → Production Run → QC Inspection → Finished Goods Stock → Dispatch',
    'Machine Breakdown → Downtime Log → Maintenance Request → Repair → Uptime Restored → Production Resumed',
    'Raw Material Low Stock → Reorder Alert → Purchase Requisition → PO Raised → Material Receipt → Stock Updated',
    'QC Fail → Rework Order → Production Re-run → QC Re-inspect → Pass/Scrap Decision',
  ],
  integrations: [
    { type: 'auth', name: 'NextAuth.js', config: { provider: 'credentials' }, required: true },
    { type: 'email', name: 'Resend', config: {}, required: true },
    { type: 'analytics', name: 'PostHog', config: {}, required: false },
  ],
  design: {
    profileRef: 'design-profile.enterprise-clean',
    restrictions: ['high-data-density', 'sidebar-navigation', 'clear-status-indicators'],
  },
  generationRules: [],
  compatibleIndustries: ['manufacturing', 'production', 'fabrication', 'assembly', 'food-manufacturing', 'pharma-manufacturing', 'automotive-manufacturing', 'enterprise-software', 'construction'],
  compatibleBusinessModels: ['wholesale', 'subscription'],
  roles: ['Plant Manager', 'Production Supervisor', 'Machine Operator', 'Quality Inspector', 'Inventory Controller', 'Maintenance Engineer', 'Procurement Officer'],
  departments: ['Production', 'Quality Control', 'Inventory & Stores', 'Maintenance', 'Procurement', 'Dispatch', 'Planning'],
  kpis: ['Work Orders Completed (today)', 'Production Efficiency (%)', 'Machine OEE (%)', 'Quality Pass Rate (%)', 'Material Wastage (%)', 'On-Time Production (%)', 'Active Downtime (hours)'],
  vocabulary: {
    Customer: 'Client',
    User: 'Operator',
    Product: 'Finished Good',
    Order: 'Work Order',
    Category: 'Product Line',
    Invoice: 'Delivery Challan',
    Item: 'Raw Material',
  },
  businessRules: [
    'Work order quantity must not exceed available raw material stock (BOM-based calculation)',
    'QC inspection is mandatory before finished goods are moved to stock',
    'Machine downtime must be logged with a reason code within 15 minutes of stoppage',
    'Material issue to production requires work order reference; no ad-hoc issues',
    'Rework orders are limited to 2 cycles; third failure triggers scrap decision workflow',
    'BOM must be version-controlled; changes require production planning approval before use in live orders',
    'Shift production log must be closed before the next shift opens',
  ],
};
