import type { Pattern } from '../../schemas/knowledge/pattern.schema.js';

export const RESTAURANT_BOOKING: Pattern = {
  id: 'pattern.restaurant.booking',
  version: '1.3.0',
  status: 'active',
  createdAt: '2025-01-01T00:00:00+00:00',
  updatedAt: '2025-01-01T00:00:00+00:00',
  evidenceRefs: [],
  kind: 'Pattern',
  name: 'Restaurant Booking',
  description: 'Restaurant site with menu, reservations, gallery, and reviews',
  navigation: { items: [{ label: 'Home', href: '/' }, { label: 'Menu', href: '/menu' }, { label: 'Reservations', href: '/reservations' }, { label: 'About', href: '/about' }, { label: 'Contact', href: '/contact' }], style: 'horizontal', sticky: true, logo: true },
  pages: [
    { path: '/', name: 'Home', type: 'home', sections: ['hero', 'featured-dishes', 'gallery', 'testimonials', 'cta'] },
    { path: '/menu', name: 'Menu', type: 'listing', sections: ['menu-categories', 'menu-grid', 'specials'] },
    { path: '/reservations', name: 'Reservations', type: 'auth', sections: ['booking-form', 'availability-calendar', 'map'] },
    { path: '/about', name: 'About', type: 'page', sections: ['story', 'chef', 'gallery', 'team'] },
    { path: '/orders', name: 'Orders', type: 'listing', sections: ['filters', 'data-table', 'order-status'] },
    { path: '/staff', name: 'Staff', type: 'listing', sections: ['team-grid', 'shift-schedule', 'role-list'] },
    { path: '/contact', name: 'Contact', type: 'page', sections: ['contact-form', 'map', 'hours'] },
  ],
  components: ['MenuCard', 'BookingForm', 'GalleryGrid', 'ReviewCard', 'StaffCard', 'OrderList'],
  relationships: [],
  workflows: ['Make Reservation', 'Order Online', 'Leave Review', 'Manage Staff'],
  integrations: [{ type: 'booking', name: 'Cal.com', config: {}, required: true }, { type: 'analytics', name: 'PostHog', config: {}, required: false }],
  design: { restrictions: ['food-photography-required', 'menu-pdf-available'] },
  generationRules: [],
  compatibleIndustries: ['restaurant', 'food', 'cafe', 'bakery', 'bar', 'catering', 'coffee-shop', 'pizzeria', 'sushi', 'steakhouse', 'vegan'],
  compatibleBusinessModels: ['direct-sales', 'marketplace'],
};

export const FITNESS_GYM: Pattern = {
  id: 'pattern.fitness.gym',
  version: '1.3.0',
  status: 'active',
  createdAt: '2025-01-01T00:00:00+00:00',
  updatedAt: '2025-01-01T00:00:00+00:00',
  evidenceRefs: [],
  kind: 'Pattern',
  name: 'Fitness & Gym',
  description: 'Gym/fitness site with classes, trainers, memberships, and booking',
  navigation: { items: [{ label: 'Home', href: '/' }, { label: 'Classes', href: '/classes' }, { label: 'Trainers', href: '/trainers' }, { label: 'Membership', href: '/membership' }, { label: 'Contact', href: '/contact' }], style: 'horizontal', sticky: true, logo: true },
  pages: [
    { path: '/', name: 'Home', type: 'home', sections: ['hero', 'features', 'class-schedule', 'testimonials', 'cta'] },
    { path: '/classes', name: 'Classes', type: 'listing', sections: ['class-grid', 'filter', 'booking'] },
    { path: '/trainers', name: 'Trainers', type: 'listing', sections: ['trainer-grid', 'trainer-detail'] },
    { path: '/membership', name: 'Membership', type: 'page', sections: ['pricing-table', 'benefits', 'faq'] },
    { path: '/contact', name: 'Contact', type: 'page', sections: ['contact-form', 'map', 'hours'] },
  ],
  components: ['ClassCard', 'TrainerCard', 'PricingTable', 'BookingWidget', 'CountdownTimer'],
  relationships: [],
  workflows: ['Book Class', 'Purchase Membership', 'Cancel Membership'],
  integrations: [{ type: 'payment', name: 'Stripe', config: {}, required: true }, { type: 'booking', name: 'Cal.com', config: {}, required: false }],
  design: { restrictions: ['bold-imagery', 'high-contrast'] },
  generationRules: [],
  compatibleIndustries: ['fitness', 'gym', 'yoga', 'pilates', 'crossfit', 'personal-training', 'wellness', 'sports', 'martial-arts', 'dance'],
  compatibleBusinessModels: ['subscription', 'direct-sales'],
};

export const EDUCATION_ELEARNING: Pattern = {
  id: 'pattern.education.elearning',
  version: '1.3.0',
  status: 'active',
  createdAt: '2025-01-01T00:00:00+00:00',
  updatedAt: '2025-01-01T00:00:00+00:00',
  evidenceRefs: [],
  kind: 'Pattern',
  name: 'Education & eLearning',
  description: 'Education platform with courses, lessons, quizzes, and progress tracking',
  navigation: { items: [{ label: 'Home', href: '/' }, { label: 'Courses', href: '/courses' }, { label: 'Dashboard', href: '/dashboard' }, { label: 'Pricing', href: '/pricing' }], style: 'horizontal', sticky: true, logo: true },
  pages: [
    { path: '/', name: 'Home', type: 'home', sections: ['hero', 'featured-courses', 'stats', 'testimonials', 'cta'] },
    { path: '/courses', name: 'Courses', type: 'listing', sections: ['course-grid', 'filters', 'search'] },
    { path: '/course/:id', name: 'Course Detail', type: 'detail', sections: ['course-info', 'curriculum', 'instructor', 'reviews', 'enroll-cta'] },
    { path: '/dashboard', name: 'Dashboard', type: 'dashboard', sections: ['enrolled-courses', 'progress', 'certificates'] },
    { path: '/students', name: 'Students', type: 'listing', sections: ['filters', 'data-table', 'progress-overview'] },
    { path: '/progress', name: 'Progress', type: 'dashboard', sections: ['charts', 'data-table', 'milestones'] },
    { path: '/assessments', name: 'Assessments', type: 'listing', sections: ['filters', 'data-table', 'grading'] },
    { path: '/reports', name: 'Reports', type: 'dashboard', sections: ['charts', 'data-table', 'exports'] },
    { path: '/pricing', name: 'Pricing', type: 'page', sections: ['pricing-table', 'features', 'faq'] },
  ],
  components: ['CourseCard', 'ProgressBar', 'VideoPlayer', 'QuizWidget', 'Certificate', 'StudentTable', 'ReportChart'],
  relationships: [],
  workflows: ['Enroll in Course', 'Complete Lesson', 'Earn Certificate', 'Track Progress', 'Generate Report'],
  integrations: [{ type: 'payment', name: 'Stripe', config: {}, required: true }, { type: 'video', name: 'Mux', config: {}, required: false }, { type: 'analytics', name: 'PostHog', config: {}, required: false }],
  design: { restrictions: ['accessible-colors', 'clear-typography'] },
  generationRules: [],
  compatibleIndustries: ['education', 'elearning', 'e-learning', 'online-course', 'tutoring', 'training', 'workshop', 'bootcamp', 'language-learning', 'kids-education', 'corporate-training'],
  compatibleBusinessModels: ['subscription', 'direct-sales', 'freemium'],
};

export const REAL_ESTATE_LISTING: Pattern = {
  id: 'pattern.real-estate.listing',
  version: '1.3.0',
  status: 'active',
  createdAt: '2025-01-01T00:00:00+00:00',
  updatedAt: '2025-01-01T00:00:00+00:00',
  evidenceRefs: [],
  kind: 'Pattern',
  name: 'Real Estate Listing',
  description: 'Property listing site with search, filters, virtual tours, and agent contact',
  navigation: { items: [{ label: 'Home', href: '/' }, { label: 'Buy', href: '/buy' }, { label: 'Rent', href: '/rent' }, { label: 'Agents', href: '/agents' }, { label: 'Contact', href: '/contact' }], style: 'horizontal', sticky: true, logo: true },
  pages: [
    { path: '/', name: 'Home', type: 'home', sections: ['hero-search', 'featured-listings', 'neighborhoods', 'testimonials', 'cta'] },
    { path: '/buy', name: 'Buy', type: 'listing', sections: ['property-grid', 'filters', 'map-view'] },
    { path: '/property/:id', name: 'Property Detail', type: 'detail', sections: ['photo-gallery', 'property-info', 'floor-plan', 'agent-card', 'similar-properties'] },
    { path: '/agents', name: 'Agents', type: 'listing', sections: ['agent-grid', 'agent-detail'] },
    { path: '/contact', name: 'Contact', type: 'page', sections: ['contact-form', 'map', 'office-info'] },
  ],
  components: ['PropertyCard', 'SearchBar', 'FilterSidebar', 'PhotoGallery', 'MapWidget', 'AgentCard'],
  relationships: [],
  workflows: ['Search Properties', 'Schedule Viewing', 'Contact Agent', 'Save Favorite'],
  integrations: [{ type: 'maps', name: 'Mapbox', config: {}, required: true }, { type: 'analytics', name: 'PostHog', config: {}, required: false }],
  design: { restrictions: ['hero-images-required', 'property-photos-mandatory'] },
  generationRules: [],
  compatibleIndustries: ['real-estate', 'property', 'housing', 'commercial-real-estate', 'vacation-rentals', 'property-management'],
  compatibleBusinessModels: ['direct-sales', 'marketplace'],
};

export const TRAVEL_AGENCY: Pattern = {
  id: 'pattern.travel.agency',
  version: '1.3.0',
  status: 'active',
  createdAt: '2025-01-01T00:00:00+00:00',
  updatedAt: '2025-01-01T00:00:00+00:00',
  evidenceRefs: [],
  kind: 'Pattern',
  name: 'Travel Agency',
  description: 'Travel booking site with destinations, packages, reviews, and itineraries',
  navigation: { items: [{ label: 'Home', href: '/' }, { label: 'Destinations', href: '/destinations' }, { label: 'Packages', href: '/packages' }, { label: 'About', href: '/about' }, { label: 'Contact', href: '/contact' }], style: 'horizontal', sticky: true, logo: true },
  pages: [
    { path: '/', name: 'Home', type: 'home', sections: ['hero', 'popular-destinations', 'deals', 'testimonials', 'cta'] },
    { path: '/destinations', name: 'Destinations', type: 'listing', sections: ['destination-grid', 'filters', 'search'] },
    { path: '/destination/:id', name: 'Destination Detail', type: 'detail', sections: ['photo-gallery', 'info', 'packages', 'reviews', 'map'] },
    { path: '/trips', name: 'Trips', type: 'listing', sections: ['filters', 'data-table', 'trip-status'] },
    { path: '/itineraries', name: 'Itineraries', type: 'listing', sections: ['filters', 'data-table', 'timeline'] },
    { path: '/bookings', name: 'Bookings', type: 'listing', sections: ['filters', 'data-table', 'calendar'] },
    { path: '/customers', name: 'Customers', type: 'listing', sections: ['filters', 'data-table'],
      description: 'Customer directory: travel history, preferences, contact info, loyalty status' },
    { path: '/packages', name: 'Packages', type: 'listing', sections: ['package-grid', 'filters', 'comparison'] },
    { path: '/contact', name: 'Contact', type: 'page', sections: ['contact-form', 'map', 'hours'] },
    { path: '/rooms', name: 'Rooms', type: 'listing', sections: ['filters', 'data-table'],
      description: 'Room inventory: types, rates, availability, amenities, housekeeping schedule' },
    { path: '/guests', name: 'Guests', type: 'listing', sections: ['filters', 'data-table'],
      description: 'Guest registry: check-in/out, preferences, stay history, special requests' },
    { path: '/housekeeping', name: 'Housekeeping', type: 'listing', sections: ['filters', 'data-table', 'schedule'],
      description: 'Housekeeping tasks: room assignment, status tracking, supply management' },
  ],
  components: ['DestinationCard', 'PackageCard', 'BookingWidget', 'PhotoGallery', 'MapWidget', 'ReviewCard', 'TripTable', 'RoomCard', 'GuestCard', 'HousekeepingTask'],
  relationships: [],
  workflows: ['Search Destinations', 'Book Package', 'Contact Agent', 'Leave Review', 'Manage Trip', 'Create Itinerary'],
  integrations: [{ type: 'payment', name: 'Stripe', config: {}, required: true }, { type: 'maps', name: 'Mapbox', config: {}, required: false }],
  design: { restrictions: ['hero-images-required', 'aspirational-photography'] },
  generationRules: [],
  compatibleIndustries: ['travel', 'tourism', 'vacation', 'adventure', 'luxury-travel', 'budget-travel', 'cruise', 'honeymoon', 'group-travel'],
  compatibleBusinessModels: ['direct-sales', 'marketplace'],
};

export const LEGAL_FIRM: Pattern = {
  id: 'pattern.legal.firm',
  version: '1.3.0',
  status: 'active',
  createdAt: '2025-01-01T00:00:00+00:00',
  updatedAt: '2025-01-01T00:00:00+00:00',
  evidenceRefs: [],
  kind: 'Pattern',
  name: 'Legal Firm',
  description: 'Law firm site with practice areas, attorneys, case results, and consultation booking',
  navigation: { items: [{ label: 'Home', href: '/' }, { label: 'Practice Areas', href: '/practice-areas' }, { label: 'Attorneys', href: '/attorneys' }, { label: 'Results', href: '/results' }, { label: 'Contact', href: '/contact' }], style: 'horizontal', sticky: true, logo: true },
  pages: [
    { path: '/', name: 'Home', type: 'home', sections: ['hero', 'practice-areas', 'attorneys-preview', 'case-results', 'testimonials', 'cta'] },
    { path: '/practice-areas', name: 'Practice Areas', type: 'listing', sections: ['area-grid', 'area-detail'] },
    { path: '/attorneys', name: 'Attorneys', type: 'listing', sections: ['attorney-grid', 'attorney-detail'] },
    { path: '/cases', name: 'Cases', type: 'listing', sections: ['filters', 'data-table', 'case-status'] },
    { path: '/clients', name: 'Clients', type: 'listing', sections: ['filters', 'data-table', 'client-detail'] },
    { path: '/documents', name: 'Documents', type: 'listing', sections: ['filters', 'data-table', 'document-viewer'] },
    { path: '/billing', name: 'Billing', type: 'dashboard', sections: ['stats-cards', 'data-table', 'charts'] },
    { path: '/calendar', name: 'Calendar', type: 'dashboard', sections: ['calendar', 'data-table', 'reminders'] },
    { path: '/results', name: 'Results', type: 'page', sections: ['case-studies', 'stats', 'testimonials'] },
    { path: '/contact', name: 'Contact', type: 'page', sections: ['contact-form', 'consultation-cta', 'office-info'] },
  ],
  components: ['PracticeAreaCard', 'AttorneyCard', 'CaseStudyCard', 'ConsultationForm', 'CaseTable', 'BillingChart', 'DocumentViewer'],
  relationships: [],
  workflows: ['Book Consultation', 'Submit Case', 'Contact Attorney', 'Manage Case', 'Track Billing'],
  integrations: [{ type: 'booking', name: 'Cal.com', config: {}, required: true }, { type: 'analytics', name: 'PostHog', config: {}, required: false }],
  design: { restrictions: ['professional-imagery', 'authoritative-tonality'] },
  generationRules: [],
  compatibleIndustries: ['legal', 'law', 'attorney', 'lawyer', 'litigation', 'corporate-law', 'family-law', 'criminal-defense', 'immigration', 'personal-injury'],
  compatibleBusinessModels: ['direct-sales'],
};

export const AGENCY_CREATIVE: Pattern = {
  id: 'pattern.agency.creative',
  version: '1.3.0',
  status: 'active',
  createdAt: '2025-01-01T00:00:00+00:00',
  updatedAt: '2025-01-01T00:00:00+00:00',
  evidenceRefs: [],
  kind: 'Pattern',
  name: 'Creative Agency',
  description: 'Digital/creative agency with portfolio, services, case studies, and team',
  navigation: { items: [{ label: 'Home', href: '/' }, { label: 'Work', href: '/work' }, { label: 'Services', href: '/services' }, { label: 'About', href: '/about' }, { label: 'Contact', href: '/contact' }], style: 'horizontal', sticky: true, logo: true },
  pages: [
    { path: '/', name: 'Home', type: 'home', sections: ['hero', 'featured-work', 'services', 'clients', 'testimonials', 'cta'] },
    { path: '/work', name: 'Work', type: 'listing', sections: ['portfolio-grid', 'filters', 'case-study-preview'] },
    { path: '/work/:id', name: 'Case Study', type: 'detail', sections: ['hero-image', 'project-info', 'results', 'gallery', 'next-project'] },
    { path: '/services', name: 'Services', type: 'page', sections: ['service-list', 'process', 'technologies'] },
    { path: '/about', name: 'About', type: 'page', sections: ['story', 'team', 'culture', 'clients'] },
    { path: '/contact', name: 'Contact', type: 'page', sections: ['contact-form', 'office-info', 'social-links'] },
  ],
  components: ['PortfolioCard', 'CaseStudyCard', 'ServiceCard', 'TeamCard', 'ContactForm'],
  relationships: [],
  workflows: ['Submit Inquiry', 'View Case Study', 'Download Portfolio'],
  integrations: [{ type: 'analytics', name: 'PostHog', config: {}, required: false }, { type: 'email', name: 'Resend', config: {}, required: false }],
  design: { restrictions: ['portfolio-images-required', 'creative-visuals'] },
  generationRules: [],
  compatibleIndustries: ['agency', 'creative', 'digital-agency', 'design-studio', 'marketing', 'advertising', 'branding', 'media', 'production', 'pr'],
  compatibleBusinessModels: ['direct-sales'],
};

export const MEDIA_PUBLISHING: Pattern = {
  id: 'pattern.media.publishing',
  version: '1.3.0',
  status: 'active',
  createdAt: '2025-01-01T00:00:00+00:00',
  updatedAt: '2025-01-01T00:00:00+00:00',
  evidenceRefs: [],
  kind: 'Pattern',
  name: 'Media & Publishing',
  description: 'News/media site with articles, categories, subscriptions, and newsletter',
  navigation: { items: [{ label: 'Home', href: '/' }, { label: 'Topics', href: '/topics' }, { label: 'Subscribe', href: '/subscribe' }, { label: 'About', href: '/about' }], style: 'horizontal', sticky: true, logo: true },
  pages: [
    { path: '/', name: 'Home', type: 'home', sections: ['hero-article', 'featured-articles', 'trending', 'newsletter-cta'] },
    { path: '/topics', name: 'Topics', type: 'listing', sections: ['topic-grid', 'article-list'] },
    { path: '/article/:slug', name: 'Article', type: 'detail', sections: ['article-header', 'article-body', 'related-articles', 'newsletter-cta'] },
    { path: '/subscribe', name: 'Subscribe', type: 'page', sections: ['pricing-table', 'benefits', 'faq'] },
    { path: '/about', name: 'About', type: 'page', sections: ['mission', 'team', 'contact'] },
  ],
  components: ['ArticleCard', 'TopicGrid', 'NewsletterForm', 'PricingTable', 'ShareButtons'],
  relationships: [],
  workflows: ['Subscribe to Newsletter', 'Read Article', 'Share Article'],
  integrations: [{ type: 'email', name: 'Resend', config: {}, required: true }, { type: 'analytics', name: 'PostHog', config: {}, required: false }],
  design: { restrictions: ['readable-typography', 'content-first-layout'] },
  generationRules: [],
  compatibleIndustries: ['media', 'publishing', 'news', 'blog', 'magazine', 'journalism', 'newsletter', 'content', 'editorial'],
  compatibleBusinessModels: ['subscription', 'direct-sales'],
};

export const NONPROFIT_CHARITY: Pattern = {
  id: 'pattern.nonprofit.charity',
  version: '1.3.0',
  status: 'active',
  createdAt: '2025-01-01T00:00:00+00:00',
  updatedAt: '2025-01-01T00:00:00+00:00',
  evidenceRefs: [],
  kind: 'Pattern',
  name: 'Nonprofit & Charity',
  description: 'Nonprofit site with donation, events, impact stats, and volunteer signup',
  navigation: { items: [{ label: 'Home', href: '/' }, { label: 'Impact', href: '/impact' }, { label: 'Events', href: '/events' }, { label: 'Donate', href: '/donate' }, { label: 'Contact', href: '/contact' }], style: 'horizontal', sticky: true, logo: true },
  pages: [
    { path: '/', name: 'Home', type: 'home', sections: ['hero', 'impact-stats', 'featured-programs', 'testimonials', 'donate-cta'] },
    { path: '/impact', name: 'Impact', type: 'page', sections: ['stats', 'stories', 'annual-report'] },
    { path: '/events', name: 'Events', type: 'listing', sections: ['event-grid', 'calendar', 'registration'] },
    { path: '/donations', name: 'Donations', type: 'listing', sections: ['filters', 'data-table', 'donation-stats'] },
    { path: '/campaigns', name: 'Campaigns', type: 'listing', sections: ['filters', 'data-table', 'campaign-progress'] },
    { path: '/volunteers', name: 'Volunteers', type: 'listing', sections: ['filters', 'data-table', 'schedule'] },
    { path: '/reports', name: 'Reports', type: 'dashboard', sections: ['charts', 'data-table', 'exports'] },
    { path: '/donate', name: 'Donate', type: 'page', sections: ['donation-form', 'impact-breakdown', 'recurring-options'] },
    { path: '/contact', name: 'Contact', type: 'page', sections: ['contact-form', 'volunteer-signup', 'office-info'] },
  ],
  components: ['DonationForm', 'ImpactCounter', 'EventCard', 'VolunteerForm', 'TestimonialCard', 'DonationTable', 'ReportChart'],
  relationships: [],
  workflows: ['Make Donation', 'Register for Event', 'Volunteer Signup', 'Track Campaign', 'Generate Report'],
  integrations: [{ type: 'payment', name: 'Stripe', config: {}, required: true }, { type: 'email', name: 'Resend', config: {}, required: false }],
  design: { restrictions: ['empathy-driven-imagery', 'accessible-colors'] },
  generationRules: [],
  compatibleIndustries: ['nonprofit', 'charity', 'ngo', 'foundation', 'social-cause', 'community', 'volunteer', 'fundraising'],
  compatibleBusinessModels: ['direct-sales'],
};

export const AUTOMOTIVE_DEALER: Pattern = {
  id: 'pattern.automotive.dealer',
  version: '1.3.0',
  status: 'active',
  createdAt: '2025-01-01T00:00:00+00:00',
  updatedAt: '2025-01-01T00:00:00+00:00',
  evidenceRefs: [],
  kind: 'Pattern',
  name: 'Automotive Dealer',
  description: 'Car dealership with inventory search, comparison, financing, and test drive booking',
  navigation: { items: [{ label: 'Home', href: '/' }, { label: 'Inventory', href: '/inventory' }, { label: 'Finance', href: '/finance' }, { label: 'Service', href: '/service' }, { label: 'Contact', href: '/contact' }], style: 'horizontal', sticky: true, logo: true },
  pages: [
    { path: '/', name: 'Home', type: 'home', sections: ['hero', 'featured-vehicles', 'brands', 'testimonials', 'cta'] },
    { path: '/inventory', name: 'Inventory', type: 'listing', sections: ['vehicle-grid', 'filters', 'comparison'] },
    { path: '/vehicle/:id', name: 'Vehicle Detail', type: 'detail', sections: ['photo-gallery', 'specs', 'pricing', 'financing', 'contact-dealer'] },
    { path: '/finance', name: 'Finance', type: 'page', sections: ['calculator', 'apply-form', 'faq'] },
    { path: '/service', name: 'Service', type: 'page', sections: ['service-menu', 'booking', 'hours'] },
    { path: '/contact', name: 'Contact', type: 'page', sections: ['contact-form', 'map', 'hours'] },
  ],
  components: ['VehicleCard', 'SearchBar', 'FilterSidebar', 'FinancingCalculator', 'ComparisonTable', 'ContactForm'],
  relationships: [],
  workflows: ['Search Vehicles', 'Book Test Drive', 'Apply for Financing', 'Schedule Service'],
  integrations: [{ type: 'analytics', name: 'PostHog', config: {}, required: false }, { type: 'booking', name: 'Cal.com', config: {}, required: false }],
  design: { restrictions: ['vehicle-images-required', 'specifications-visible'] },
  generationRules: [],
  compatibleIndustries: ['automotive', 'car-dealer', 'motorcycle', 'trucks', 'ev', 'used-cars', 'luxury-cars', 'fleet', 'rental'],
  compatibleBusinessModels: ['direct-sales'],
};

export const PET_SERVICES: Pattern = {
  id: 'pattern.pet.services',
  version: '1.3.0',
  status: 'active',
  createdAt: '2025-01-01T00:00:00+00:00',
  updatedAt: '2025-01-01T00:00:00+00:00',
  evidenceRefs: [],
  kind: 'Pattern',
  name: 'Pet Services',
  description: 'Pet care site with grooming, boarding, training, and booking',
  navigation: { items: [{ label: 'Home', href: '/' }, { label: 'Services', href: '/services' }, { label: 'Gallery', href: '/gallery' }, { label: 'Book', href: '/book' }, { label: 'Contact', href: '/contact' }], style: 'horizontal', sticky: true, logo: true },
  pages: [
    { path: '/', name: 'Home', type: 'home', sections: ['hero', 'services-overview', 'gallery', 'testimonials', 'cta'] },
    { path: '/services', name: 'Services', type: 'listing', sections: ['service-grid', 'pricing'] },
    { path: '/gallery', name: 'Gallery', type: 'page', sections: ['photo-grid', 'video'] },
    { path: '/book', name: 'Book', type: 'auth', sections: ['booking-form', 'service-select', 'calendar'] },
    { path: '/contact', name: 'Contact', type: 'page', sections: ['contact-form', 'map', 'hours'] },
  ],
  components: ['ServiceCard', 'BookingForm', 'PhotoGallery', 'TestimonialCard', 'PricingCard'],
  relationships: [],
  workflows: ['Book Service', 'Contact', 'Leave Review'],
  integrations: [{ type: 'booking', name: 'Cal.com', config: {}, required: true }, { type: 'analytics', name: 'PostHog', config: {}, required: false }],
  design: { restrictions: ['pet-photography-required', 'friendly-tonality'] },
  generationRules: [],
  compatibleIndustries: ['pet', 'pet-care', 'grooming', 'dog-walking', 'pet-boarding', 'veterinary', 'pet-training', 'pet-supplies'],
  compatibleBusinessModels: ['direct-sales'],
};

export const WEDDING_EVENTS: Pattern = {
  id: 'pattern.wedding.events',
  version: '1.3.0',
  status: 'active',
  createdAt: '2025-01-01T00:00:00+00:00',
  updatedAt: '2025-01-01T00:00:00+00:00',
  evidenceRefs: [],
  kind: 'Pattern',
  name: 'Wedding & Events',
  description: 'Wedding/event planning with portfolio, services, pricing, and inquiry form',
  navigation: { items: [{ label: 'Home', href: '/' }, { label: 'Portfolio', href: '/portfolio' }, { label: 'Services', href: '/services' }, { label: 'Pricing', href: '/pricing' }, { label: 'Contact', href: '/contact' }], style: 'horizontal', sticky: true, logo: true },
  pages: [
    { path: '/', name: 'Home', type: 'home', sections: ['hero', 'featured-events', 'services', 'testimonials', 'cta'] },
    { path: '/portfolio', name: 'Portfolio', type: 'listing', sections: ['portfolio-grid', 'filters', 'lightbox'] },
    { path: '/services', name: 'Services', type: 'page', sections: ['service-list', 'process', 'timeline'] },
    { path: '/pricing', name: 'Pricing', type: 'page', sections: ['pricing-table', 'packages', 'faq'] },
    { path: '/contact', name: 'Contact', type: 'page', sections: ['inquiry-form', 'calendar', 'availability'] },
    { path: '/tickets', name: 'Tickets', type: 'listing', sections: ['filters', 'data-table'],
      description: 'Event ticket inventory: types, pricing, availability, sales tracking' },
    { path: '/attendees', name: 'Attendees', type: 'listing', sections: ['filters', 'data-table'],
      description: 'Attendee registry: registration, check-in status, contact info, dietary/accessibility notes' },
    { path: '/schedule', name: 'Schedule', type: 'page', sections: ['calendar', 'data-table', 'timeline'],
      description: 'Event schedule: sessions, speakers, venues, timing, overlaps check' },
  ],
  components: ['PortfolioCard', 'ServiceCard', 'PricingTable', 'InquiryForm', 'TimelineWidget', 'TicketCard', 'AttendeeTable', 'CalendarView'],
  relationships: [],
  workflows: ['Submit Inquiry', 'Book Consultation', 'View Portfolio'],
  integrations: [{ type: 'booking', name: 'Cal.com', config: {}, required: true }, { type: 'email', name: 'Resend', config: {}, required: false }],
  design: { restrictions: ['elegant-imagery', 'romantic-tonality'] },
  generationRules: [],
  compatibleIndustries: ['event', 'wedding', 'event-planning', 'catering', 'photography', 'florist', 'venue', 'decor', 'event-management'],
  compatibleBusinessModels: ['direct-sales'],
};

export const DENTAL_CLINIC: Pattern = {
  id: 'pattern.dental.clinic',
  version: '1.3.0',
  status: 'active',
  createdAt: '2025-01-01T00:00:00+00:00',
  updatedAt: '2025-01-01T00:00:00+00:00',
  evidenceRefs: [],
  kind: 'Pattern',
  name: 'Dental Clinic',
  description: 'Dental practice with services, team, booking, and patient portal',
  navigation: { items: [{ label: 'Home', href: '/' }, { label: 'Services', href: '/services' }, { label: 'Team', href: '/team' }, { label: 'Book', href: '/book' }, { label: 'Contact', href: '/contact' }], style: 'horizontal', sticky: true, logo: true },
  pages: [
    { path: '/', name: 'Home', type: 'home', sections: ['hero', 'services-overview', 'team-preview', 'testimonials', 'cta'] },
    { path: '/services', name: 'Services', type: 'listing', sections: ['service-grid', 'pricing', 'insurance'] },
    { path: '/team', name: 'Team', type: 'listing', sections: ['team-grid', 'team-detail'] },
    { path: '/book', name: 'Book Appointment', type: 'auth', sections: ['booking-form', 'service-select', 'calendar'] },
    { path: '/contact', name: 'Contact', type: 'page', sections: ['contact-form', 'map', 'hours', 'emergency'] },
  ],
  components: ['ServiceCard', 'TeamCard', 'BookingForm', 'InsuranceBadge', 'EmergencyBanner'],
  relationships: [],
  workflows: ['Book Appointment', 'Contact', 'Leave Review'],
  integrations: [{ type: 'booking', name: 'Cal.com', config: {}, required: true }, { type: 'analytics', name: 'PostHog', config: {}, required: false }],
  design: { restrictions: ['clean-medical-aesthetic', 'trust-signals-required'] },
  generationRules: [],
  compatibleIndustries: ['dental', 'dentist', 'orthodontist', 'oral-surgery', 'cosmetic-dentistry', 'pediatric-dentistry'],
  compatibleBusinessModels: ['direct-sales'],
};

export const ARCHITECTURE_FIRM: Pattern = {
  id: 'pattern.architecture.firm',
  version: '1.3.0',
  status: 'active',
  createdAt: '2025-01-01T00:00:00+00:00',
  updatedAt: '2025-01-01T00:00:00+00:00',
  evidenceRefs: [],
  kind: 'Pattern',
  name: 'Architecture Firm',
  description: 'Architecture practice with projects, services, team, and inquiry',
  navigation: { items: [{ label: 'Home', href: '/' }, { label: 'Projects', href: '/projects' }, { label: 'Services', href: '/services' }, { label: 'About', href: '/about' }, { label: 'Contact', href: '/contact' }], style: 'horizontal', sticky: true, logo: true },
  pages: [
    { path: '/', name: 'Home', type: 'home', sections: ['hero', 'featured-projects', 'services', 'awards', 'cta'] },
    { path: '/projects', name: 'Projects', type: 'listing', sections: ['project-grid', 'filters', 'category-nav'] },
    { path: '/project/:id', name: 'Project Detail', type: 'detail', sections: ['photo-gallery', 'project-info', 'awards', 'next-project'] },
    { path: '/services', name: 'Services', type: 'page', sections: ['service-list', 'process', 'technologies'] },
    { path: '/about', name: 'About', type: 'page', sections: ['story', 'team', 'awards', 'publications'] },
    { path: '/contact', name: 'Contact', type: 'page', sections: ['contact-form', 'office-info', 'social-links'] },
  ],
  components: ['ProjectCard', 'ServiceCard', 'TeamCard', 'AwardCard', 'ContactForm'],
  relationships: [],
  workflows: ['Submit Inquiry', 'View Projects', 'Download Portfolio'],
  integrations: [{ type: 'email', name: 'Resend', config: {}, required: false }, { type: 'analytics', name: 'PostHog', config: {}, required: false }],
  design: { restrictions: ['portfolio-images-required', 'minimal-aesthetic'] },
  generationRules: [],
  compatibleIndustries: ['architecture', 'interior-design', 'landscape', 'urban-planning', 'construction', 'engineering'],
  compatibleBusinessModels: ['direct-sales'],
};

export const PHOTOGRAPHY_STUDIO: Pattern = {
  id: 'pattern.photography.studio',
  version: '1.3.0',
  status: 'active',
  createdAt: '2025-01-01T00:00:00+00:00',
  updatedAt: '2025-01-01T00:00:00+00:00',
  evidenceRefs: [],
  kind: 'Pattern',
  name: 'Photography Studio',
  description: 'Photographer portfolio with galleries, packages, booking, and blog',
  navigation: { items: [{ label: 'Home', href: '/' }, { label: 'Portfolio', href: '/portfolio' }, { label: 'Packages', href: '/packages' }, { label: 'Blog', href: '/blog' }, { label: 'Contact', href: '/contact' }], style: 'horizontal', sticky: true, logo: true },
  pages: [
    { path: '/', name: 'Home', type: 'home', sections: ['hero', 'featured-gallery', 'services', 'testimonials', 'cta'] },
    { path: '/portfolio', name: 'Portfolio', type: 'listing', sections: ['gallery-grid', 'lightbox', 'category-filter'] },
    { path: '/packages', name: 'Packages', type: 'page', sections: ['pricing-table', 'sample-gallery', 'faq'] },
    { path: '/blog', name: 'Blog', type: 'listing', sections: ['article-grid', 'categories'] },
    { path: '/contact', name: 'Contact', type: 'page', sections: ['inquiry-form', 'availability', 'social-links'] },
  ],
  components: ['GalleryGrid', 'Lightbox', 'PricingTable', 'InquiryForm', 'BlogCard'],
  relationships: [],
  workflows: ['Submit Inquiry', 'Book Session', 'View Gallery'],
  integrations: [{ type: 'email', name: 'Resend', config: {}, required: false }, { type: 'analytics', name: 'PostHog', config: {}, required: false }],
  design: { restrictions: ['high-quality-images', 'gallery-focused'] },
  generationRules: [],
  compatibleIndustries: ['photography', 'videography', 'studio', 'portrait', 'wedding-photography', 'commercial-photography', 'food-photography'],
  compatibleBusinessModels: ['direct-sales'],
};

export const CONSULTING_FIRM: Pattern = {
  id: 'pattern.consulting.firm',
  version: '1.3.0',
  status: 'active',
  createdAt: '2025-01-01T00:00:00+00:00',
  updatedAt: '2025-01-01T00:00:00+00:00',
  evidenceRefs: [],
  kind: 'Pattern',
  name: 'Consulting Firm',
  description: 'Management/IT consulting with services, case studies, team, and RFP',
  navigation: { items: [{ label: 'Home', href: '/' }, { label: 'Services', href: '/services' }, { label: 'Case Studies', href: '/case-studies' }, { label: 'Team', href: '/team' }, { label: 'Contact', href: '/contact' }], style: 'horizontal', sticky: true, logo: true },
  pages: [
    { path: '/', name: 'Home', type: 'home', sections: ['hero', 'services', 'featured-cases', 'clients', 'testimonials', 'cta'] },
    { path: '/services', name: 'Services', type: 'listing', sections: ['service-grid', 'service-detail', 'technologies'] },
    { path: '/case-studies', name: 'Case Studies', type: 'listing', sections: ['case-grid', 'filters', 'results'] },
    { path: '/team', name: 'Team', type: 'listing', sections: ['team-grid', 'expertise', 'bios'] },
    { path: '/contact', name: 'Contact', type: 'page', sections: ['contact-form', 'rfp-form', 'office-info'] },
    { path: '/policies', name: 'Policies', type: 'listing', sections: ['filters', 'data-table'],
      description: 'Insurance policy management: create, renew, modify, and track policy lifecycle' },
    { path: '/claims', name: 'Claims', type: 'listing', sections: ['filters', 'data-table', 'claims-form'],
      description: 'Claims processing: submit, review, approve/reject, payment tracking' },
    { path: '/customers', name: 'Customers', type: 'listing', sections: ['filters', 'data-table'],
      description: 'Customer directory with profiles, policy history, claims history, contact info' },
    { path: '/agents', name: 'Agents', type: 'listing', sections: ['filters', 'team-grid'],
      description: 'Agent directory: licenses, performance, commission, assigned customers' },
    { path: '/reports', name: 'Reports & Analytics', type: 'dashboard', sections: ['stats-cards', 'charts', 'data-table'],
      description: 'Underwriting reports, claims trends, customer acquisition, agent performance' },
    { path: '/accounts', name: 'Accounts', type: 'listing', sections: ['filters', 'data-table'],
      description: 'Bank accounts: checking, savings, fixed deposits, loan accounts' },
    { path: '/transfers', name: 'Transfers', type: 'listing', sections: ['filters', 'data-table', 'transfer-form'],
      description: 'Fund transfers: NEFT, RTGS, IMPS; scheduled, recurring transfers' },
    { path: '/statements', name: 'Statements', type: 'listing', sections: ['filters', 'data-table', 'charts'],
      description: 'Account statements: transaction history, downloadable PDF, date range filter' },
  ],
  components: ['ServiceCard', 'CaseStudyCard', 'TeamCard', 'ClientLogo', 'ContactForm', 'PolicyCard', 'ClaimCard', 'TransactionTable', 'AccountCard'],
  relationships: [],
  workflows: ['Submit RFP', 'Contact', 'Download Case Study'],
  integrations: [{ type: 'email', name: 'Resend', config: {}, required: false }, { type: 'analytics', name: 'PostHog', config: {}, required: false }],
  design: { restrictions: ['professional-imagery', 'data-driven-visuals'] },
  generationRules: [],
  compatibleIndustries: ['consulting', 'management', 'it-consulting', 'strategy', 'operations', 'hr-consulting', 'financial-advisory', 'digital-transformation', 'fintech', 'banking', 'insurance'],
  compatibleBusinessModels: ['direct-sales'],
};

export const SAAS_STARTUP: Pattern = {
  id: 'pattern.saas.startup',
  version: '1.3.0',
  status: 'active',
  createdAt: '2025-01-01T00:00:00+00:00',
  updatedAt: '2025-01-01T00:00:00+00:00',
  evidenceRefs: [],
  kind: 'Pattern',
  name: 'SaaS Startup',
  description: 'Startup landing with features, pricing, demo, and signup',
  navigation: { items: [{ label: 'Home', href: '/' }, { label: 'Features', href: '/features' }, { label: 'Pricing', href: '/pricing' }, { label: 'Docs', href: '/docs' }, { label: 'Login', href: '/login' }], style: 'horizontal', sticky: true, logo: true },
  pages: [
    { path: '/', name: 'Home', type: 'home', sections: ['hero', 'features', 'social-proof', 'pricing-preview', 'cta'] },
    { path: '/features', name: 'Features', type: 'page', sections: ['feature-list', 'screenshots', 'comparisons'] },
    { path: '/pricing', name: 'Pricing', type: 'page', sections: ['pricing-table', 'feature-comparison', 'faq'] },
    { path: '/docs', name: 'Docs', type: 'page', sections: ['search', 'sidebar', 'article'] },
    { path: '/login', name: 'Login', type: 'auth', sections: ['login-form', 'social-auth'] },
    { path: '/signup', name: 'Sign Up', type: 'auth', sections: ['signup-form', 'social-auth'] },
  ],
  components: ['FeatureCard', 'PricingTable', 'FAQ', 'LoginForm', 'SocialProof', 'DemoWidget'],
  relationships: [],
  workflows: ['Sign Up', 'Start Free Trial', 'Upgrade Plan'],
  integrations: [{ type: 'payment', name: 'Stripe', config: {}, required: true }, { type: 'auth', name: 'Clerk', config: {}, required: false }, { type: 'analytics', name: 'PostHog', config: {}, required: false }],
  design: { restrictions: ['modern-tech-aesthetic', 'feature-focused'] },
  generationRules: [],
  compatibleIndustries: ['saas', 'startup', 'developer-tools', 'productivity', 'ai', 'analytics', 'automation', 'api', 'no-code'],
  compatibleBusinessModels: ['subscription', 'freemium'],
};

export const ECOMMERCE_FASHION: Pattern = {
  id: 'pattern.ecommerce.fashion',
  version: '1.3.0',
  status: 'active',
  createdAt: '2025-01-01T00:00:00+00:00',
  updatedAt: '2025-01-01T00:00:00+00:00',
  evidenceRefs: [],
  kind: 'Pattern',
  name: 'E-Commerce Fashion',
  description: 'Fashion store with lookbook, size guide, wishlist, and social sharing',
  navigation: { items: [{ label: 'Home', href: '/' }, { label: 'Shop', href: '/shop' }, { label: 'Lookbook', href: '/lookbook' }, { label: 'About', href: '/about' }, { label: 'Contact', href: '/contact' }], style: 'horizontal', sticky: true, logo: true },
  pages: [
    { path: '/', name: 'Home', type: 'home', sections: ['hero', 'featured-collection', 'lookbook', 'testimonials', 'cta'] },
    { path: '/shop', name: 'Shop', type: 'listing', sections: ['product-grid', 'filters', 'sort-bar'] },
    { path: '/product/:id', name: 'Product Detail', type: 'detail', sections: ['product-gallery', 'size-guide', 'reviews', 'related-products'] },
    { path: '/lookbook', name: 'Lookbook', type: 'page', sections: ['gallery', 'shop-the-look'] },
    { path: '/about', name: 'About', type: 'page', sections: ['story', 'values', 'sustainability'] },
    { path: '/contact', name: 'Contact', type: 'page', sections: ['contact-form', 'faq', 'social-links'] },
  ],
  components: ['ProductCard', 'LookbookGallery', 'SizeGuide', 'WishlistButton', 'SocialShare'],
  relationships: [],
  workflows: ['Add to Cart', 'Save to Wishlist', 'Share Product'],
  integrations: [{ type: 'payment', name: 'Stripe', config: {}, required: true }, { type: 'email', name: 'Resend', config: {}, required: false }, { type: 'analytics', name: 'PostHog', config: {}, required: false }],
  design: { restrictions: ['lifestyle-photography', 'brand-storytelling'] },
  generationRules: [],
  compatibleIndustries: ['fashion', 'clothing', 'apparel', 'accessories', 'jewelry', 'footwear', 'streetwear', 'luxury-fashion', 'sustainable-fashion', 'vintage'],
  compatibleBusinessModels: ['direct-sales', 'marketplace', 'wholesale'],
};

export const ECOMMERCE_FOOD_DELIVERY: Pattern = {
  id: 'pattern.ecommerce.food-delivery',
  version: '1.3.0',
  status: 'active',
  createdAt: '2025-01-01T00:00:00+00:00',
  updatedAt: '2025-01-01T00:00:00+00:00',
  evidenceRefs: [],
  kind: 'Pattern',
  name: 'E-Commerce Food Delivery',
  description: 'Food delivery with menu, cart, delivery tracking, and reordering',
  navigation: { items: [{ label: 'Home', href: '/' }, { label: 'Menu', href: '/menu' }, { label: 'Cart', href: '/cart' }, { label: 'Track', href: '/track' }, { label: 'Account', href: '/account' }], style: 'horizontal', sticky: true, logo: true },
  pages: [
    { path: '/', name: 'Home', type: 'home', sections: ['hero', 'popular-items', 'categories', 'promotions', 'cta'] },
    { path: '/menu', name: 'Menu', type: 'listing', sections: ['menu-grid', 'category-nav', 'search'] },
    { path: '/cart', name: 'Cart', type: 'page', sections: ['cart-items', 'order-summary', 'promo-code'] },
    { path: '/checkout', name: 'Checkout', type: 'auth', sections: ['delivery-info', 'payment', 'order-review'] },
    { path: '/track', name: 'Track Order', type: 'page', sections: ['order-status', 'map', 'eta'] },
    { path: '/account', name: 'Account', type: 'dashboard', sections: ['order-history', 'addresses', 'favorites'] },
  ],
  components: ['MenuItemCard', 'CartDrawer', 'OrderTracker', 'CategoryNav', 'PromoBanner'],
  relationships: [],
  workflows: ['Add to Cart', 'Checkout', 'Track Order', 'Reorder'],
  integrations: [{ type: 'payment', name: 'Stripe', config: {}, required: true }, { type: 'maps', name: 'Mapbox', config: {}, required: false }, { type: 'analytics', name: 'PostHog', config: {}, required: false }],
  design: { restrictions: ['food-photography', 'mobile-first'] },
  generationRules: [],
  compatibleIndustries: ['food-delivery', 'restaurant-delivery', 'meal-kit', 'grocery', 'cloud-kitchen', 'bakery-delivery'],
  compatibleBusinessModels: ['direct-sales', 'marketplace', 'wholesale'],
};

export const ECOMMERCE_ELECTRONICS: Pattern = {
  id: 'pattern.ecommerce.electronics',
  version: '1.3.0',
  status: 'active',
  createdAt: '2025-01-01T00:00:00+00:00',
  updatedAt: '2025-01-01T00:00:00+00:00',
  evidenceRefs: [],
  kind: 'Pattern',
  name: 'E-Commerce Electronics',
  description: 'Electronics store with specs comparison, reviews, and tech support',
  navigation: { items: [{ label: 'Home', href: '/' }, { label: 'Shop', href: '/shop' }, { label: 'Deals', href: '/deals' }, { label: 'Support', href: '/support' }, { label: 'Cart', href: '/cart' }], style: 'horizontal', sticky: true, logo: true },
  pages: [
    { path: '/', name: 'Home', type: 'home', sections: ['hero', 'featured-products', 'deals', 'brands', 'cta'] },
    { path: '/shop', name: 'Shop', type: 'listing', sections: ['product-grid', 'filters', 'comparison'] },
    { path: '/product/:id', name: 'Product Detail', type: 'detail', sections: ['product-gallery', 'specs', 'reviews', 'related-products', 'warranty'] },
    { path: '/deals', name: 'Deals', type: 'listing', sections: ['deal-grid', 'countdown', 'flash-sale'] },
    { path: '/support', name: 'Support', type: 'page', sections: ['faq', 'contact-form', 'warranty-info'] },
    { path: '/cart', name: 'Cart', type: 'page', sections: ['cart-items', 'order-summary', 'recommendations'] },
  ],
  components: ['ProductCard', 'SpecsComparison', 'ReviewWidget', 'WarrantyBadge', 'DealBanner'],
  relationships: [],
  workflows: ['Add to Cart', 'Compare Products', 'Track Order', 'Submit Support Ticket'],
  integrations: [{ type: 'payment', name: 'Stripe', config: {}, required: true }, { type: 'email', name: 'Resend', config: {}, required: false }, { type: 'analytics', name: 'PostHog', config: {}, required: false }],
  design: { restrictions: ['product-images-required', 'specs-visible'] },
  generationRules: [],
  compatibleIndustries: ['electronics', 'tech', 'gadgets', 'computers', 'phones', 'audio', 'gaming', 'smart-home', 'appliances'],
  compatibleBusinessModels: ['direct-sales', 'marketplace', 'wholesale'],
};
