import type { IndustryTemplate } from '../builder.js';

export const INDUSTRY_TEMPLATES: IndustryTemplate[] = [
  {
    id: 'ecommerce',
    name: 'Ecommerce',
    description: 'Online store with product catalog, shopping cart, checkout, and order management',
    primitives: ['auth', 'data-crud', 'ui-presentation', 'payment', 'notification', 'commerce', 'inventory', 'customer-reviews', 'search'],
    vocabulary: {
      'buyer': 'customer',
      'listing': 'product',
      'cart': 'shopping bag',
    },
    requiredFeatures: ['product-catalog', 'shopping-cart', 'checkout', 'order-management'],
    optionalFeatures: ['wishlist', 'related-products', 'size-guide', 'gift-wrapping'],
  },
  {
    id: 'ecommerce-supplement',
    name: 'Supplement Marketplace',
    description: 'Indian supplement marketplace with multi-brand catalog, FSSAI certification, ingredient details, health category browsing',
    primitives: ['auth', 'data-crud', 'ui-presentation', 'payment', 'notification', 'commerce', 'inventory', 'search',
      'ecommerce-supplement', 'indian-payments', 'fssai-compliance', 'multi-vendor', 'customer-reviews'],
    vocabulary: {
      'seller': 'brand',
      'stock': 'in stock',
      'category': 'health goal',
      'product page': 'supplement detail',
    },
    requiredFeatures: ['supplement-catalog', 'brand-filtering', 'ingredient-list', 'fssai-certification', 'indian-payments', 'multi-vendor-cart'],
    optionalFeatures: ['dosage-guide', 'health-goal-browsing', 'customer-reviews', 'subscription-save', 'lab-report-viewer'],
  },
  {
    id: 'saas',
    name: 'SaaS Platform',
    description: 'Software as a service with subscription billing, user management, dashboard, and analytics',
    primitives: ['auth', 'data-crud', 'ui-presentation', 'payment', 'notification', 'analytics', 'subscriptions', 'crm'],
    vocabulary: {
      'user': 'account',
      'plan': 'tier',
      'sign up': 'get started',
    },
    requiredFeatures: ['user-dashboard', 'subscription-management', 'analytics', 'user-management'],
    optionalFeatures: ['team-management', 'api-keys', 'webhooks', 'single-sign-on'],
  },
  {
    id: 'healthcare',
    name: 'Healthcare',
    description: 'Medical practice with patient management, appointment scheduling, and telehealth',
    primitives: ['auth', 'data-crud', 'ui-presentation', 'notification', 'booking', 'scheduling', 'crm', 'compliance'],
    vocabulary: {
      'user': 'patient',
      'appointment': 'visit',
      'service': 'treatment',
    },
    requiredFeatures: ['patient-portal', 'appointment-booking', 'medical-records', 'provider-directory'],
    optionalFeatures: ['telehealth', 'prescription-management', 'lab-results', 'insurance-verification'],
  },
  {
    id: 'restaurant',
    name: 'Restaurant',
    description: 'Restaurant or food service with menu display, online ordering, reservations, and delivery',
    primitives: ['auth', 'data-crud', 'ui-presentation', 'payment', 'booking', 'gallery', 'contact-form'],
    vocabulary: {
      'product': 'dish',
      'order': 'dine-in order',
      'category': 'menu section',
    },
    requiredFeatures: ['menu-display', 'online-ordering', 'reservation-system', 'location-info'],
    optionalFeatures: ['delivery-tracking', 'loyalty-program', 'gift-cards', 'catering-form'],
  },
  {
    id: 'fitness',
    name: 'Fitness & Gym',
    description: 'Fitness center with class scheduling, membership management, and trainer profiles',
    primitives: ['auth', 'data-crud', 'ui-presentation', 'payment', 'booking', 'scheduling', 'subscriptions', 'notification'],
    vocabulary: {
      'user': 'member',
      'appointment': 'class',
      'service': 'workout',
    },
    requiredFeatures: ['class-schedule', 'member-portal', 'trainer-profiles', 'membership-plans'],
    optionalFeatures: ['workout-library', 'progress-tracking', 'nutrition-plans', 'check-in-system'],
  },
  {
    id: 'education',
    name: 'Education & E-Learning',
    description: 'Educational platform with course management, student enrollment, and learning paths',
    primitives: ['auth', 'data-crud', 'ui-presentation', 'payment', 'content', 'notification', 'search', 'subscriptions'],
    vocabulary: {
      'user': 'student',
      'product': 'course',
      'category': 'subject',
    },
    requiredFeatures: ['course-catalog', 'student-enrollment', 'lesson-player', 'learning-progress'],
    optionalFeatures: ['quiz-system', 'certificate-generation', 'discussion-forum', 'assignment-submission'],
  },
  {
    id: 'realestate',
    name: 'Real Estate',
    description: 'Real estate platform with property listings, agent profiles, and inquiry management',
    primitives: ['auth', 'data-crud', 'ui-presentation', 'gallery', 'contact-form', 'search', 'map', 'crm'],
    vocabulary: {
      'product': 'property',
      'seller': 'agent',
      'category': 'property type',
    },
    requiredFeatures: ['property-listing', 'property-search', 'agent-profiles', 'inquiry-form'],
    optionalFeatures: ['virtual-tour', 'mortgage-calculator', 'neighborhood-info', 'open-house-schedule'],
  },
  {
    id: 'legal',
    name: 'Legal Services',
    description: 'Law firm website with practice area showcase, attorney profiles, and consultation booking',
    primitives: ['auth', 'data-crud', 'ui-presentation', 'booking', 'contact-form', 'crm', 'content'],
    vocabulary: {
      'user': 'client',
      'service': 'practice area',
      'booking': 'consultation request',
    },
    requiredFeatures: ['practice-area-showcase', 'attorney-profiles', 'consultation-booking', 'resources-blog'],
    optionalFeatures: ['case-management-portal', 'document-library', 'testimonial-showcase', 'settlement-calculator'],
  },
  {
    id: 'agency',
    name: 'Creative Agency',
    description: 'Digital/creative agency with portfolio showcase, service offerings, and client proposal management',
    primitives: ['auth', 'data-crud', 'ui-presentation', 'gallery', 'contact-form', 'crm', 'content'],
    vocabulary: {
      'user': 'client',
      'portfolio': 'work',
      'service': 'offering',
    },
    requiredFeatures: ['portfolio-gallery', 'service-showcase', 'client-portal', 'contact-inquiry'],
    optionalFeatures: ['testimonial-slider', 'case-studies', 'blog', 'career-page'],
  },
  {
    id: 'nonprofit',
    name: 'Nonprofit & Charity',
    description: 'Nonprofit organization with donation processing, campaign management, and volunteer coordination',
    primitives: ['auth', 'data-crud', 'ui-presentation', 'payment', 'content', 'contact-form', 'gallery'],
    vocabulary: {
      'user': 'supporter',
      'product': 'campaign',
      'customer': 'donor',
    },
    requiredFeatures: ['donation-form', 'campaign-showcase', 'impact-stories', 'volunteer-signup'],
    optionalFeatures: ['recurring-donation', 'fundraising-tracker', 'newsletter', 'event-calendar'],
  },
  {
    id: 'media',
    name: 'Media & Publishing',
    description: 'Content publishing platform with articles, subscriptions, and multimedia content',
    primitives: ['auth', 'data-crud', 'ui-presentation', 'content', 'subscriptions', 'analytics', 'notification'],
    vocabulary: {
      'user': 'subscriber',
      'product': 'article',
      'category': 'section',
    },
    requiredFeatures: ['article-publishing', 'subscription-paywall', 'author-profiles', 'category-browsing'],
    optionalFeatures: ['newsletter', 'podcast-hosting', 'video-embed', 'comment-system'],
  },
  {
    id: 'travel',
    name: 'Travel & Hospitality',
    description: 'Travel platform with destination guides, booking engine, and itinerary management',
    primitives: ['auth', 'data-crud', 'ui-presentation', 'payment', 'booking', 'gallery', 'search', 'map', 'contact-form'],
    vocabulary: {
      'user': 'traveler',
      'product': 'package',
      'booking': 'reservation',
    },
    requiredFeatures: ['destination-listing', 'booking-engine', 'travel-guides', 'gallery'],
    optionalFeatures: ['itinerary-planner', 'review-system', 'currency-converter', 'travel-insurance'],
  },
  {
    id: 'luxury',
    name: 'Luxury Brand',
    description: 'High-end brand showcase with product collections, craftsmanship stories, and exclusive experiences',
    primitives: ['auth', 'data-crud', 'ui-presentation', 'gallery', 'commerce', 'contact-form'],
    vocabulary: {
      'user': 'patron',
      'product': 'creation',
      'category': 'collection',
    },
    requiredFeatures: ['collection-showcase', 'product-detail', 'craftsmanship-story', 'boutique-locator'],
    optionalFeatures: ['virtual-appointment', 'waitlist', 'bespoke-request', 'lookbook'],
  },
  {
    id: 'beauty',
    name: 'Beauty & Salon',
    description: 'Salon/spa with service booking, staff management, and product sales',
    primitives: ['auth', 'data-crud', 'ui-presentation', 'booking', 'gallery', 'scheduling', 'notification', 'payment'],
    vocabulary: {
      'user': 'client',
      'appointment': 'service booking',
      'staff': 'stylist',
    },
    requiredFeatures: ['service-menu', 'online-booking', 'staff-profiles', 'gallery'],
    optionalFeatures: ['product-shop', 'loyalty-program', 'gift-cards', 'before-after-gallery'],
  },
  {
    id: 'event',
    name: 'Event Management',
    description: 'Event platform with event listing, ticketing, attendee management, and venue booking',
    primitives: ['auth', 'data-crud', 'ui-presentation', 'payment', 'booking', 'gallery', 'contact-form', 'notification'],
    vocabulary: {
      'user': 'attendee',
      'product': 'event',
      'booking': 'ticket purchase',
    },
    requiredFeatures: ['event-listing', 'ticketing-system', 'speaker-profiles', 'schedule'],
    optionalFeatures: ['virtual-event', 'networking', 'sponsor-showcase', 'event-app'],
  },
  {
    id: 'portfolio',
    name: 'Portfolio / Personal Brand',
    description: 'Personal portfolio showcasing work, skills, and professional experience',
    primitives: ['auth', 'data-crud', 'ui-presentation', 'gallery', 'contact-form', 'content'],
    vocabulary: {
      'product': 'project',
      'service': 'skill',
      'testimonial': 'recommendation',
    },
    requiredFeatures: ['project-showcase', 'skill-display', 'contact-form', 'about-section'],
    optionalFeatures: ['resume-download', 'blog', 'testimonial-slider', 'dark-mode-toggle'],
  },
  {
    id: 'automotive',
    name: 'Automotive',
    description: 'Car dealership or auto service center with vehicle inventory and service scheduling',
    primitives: ['auth', 'data-crud', 'ui-presentation', 'gallery', 'inventory', 'booking', 'contact-form', 'search'],
    vocabulary: {
      'user': 'customer',
      'product': 'vehicle',
      'service': 'repair',
    },
    requiredFeatures: ['vehicle-inventory', 'vehicle-detail', 'service-booking', 'contact-location'],
    optionalFeatures: ['financing-calculator', 'trade-in-form', 'test-drive-booking', 'parts-shop'],
  },
  {
    id: 'enterprise-software',
    name: 'Enterprise Software',
    description: 'Enterprise business management system with modules, role-based access, and reporting',
    primitives: ['auth', 'data-crud', 'ui-presentation', 'analytics', 'crm', 'hr', 'workflow', 'reporting', 'compliance', 'integration'],
    vocabulary: {
      'user': 'employee',
      'customer': 'client',
      'dashboard': 'operations center',
    },
    requiredFeatures: ['role-based-dashboard', 'entity-management', 'reporting', 'user-administration'],
    optionalFeatures: ['module-manager', 'audit-log', 'approval-workflows', 'data-import-export'],
  },
  {
    id: 'logistics',
    name: 'Logistics & Supply Chain',
    description: 'Logistics platform with shipment tracking, fleet management, and route optimization',
    primitives: ['auth', 'data-crud', 'ui-presentation', 'analytics', 'inventory', 'scheduling', 'integration', 'workflow', 'map'],
    vocabulary: {
      'user': 'operator',
      'customer': 'shipper',
      'order': 'shipment',
    },
    requiredFeatures: ['shipment-tracking', 'fleet-management', 'route-optimization', 'operator-dashboard'],
    optionalFeatures: ['carrier-integration', 'warehouse-management', 'customer-portal', 'rate-calculator'],
  },
  {
    id: 'manufacturing',
    name: 'Manufacturing',
    description: 'Manufacturing execution system with production tracking, quality control, and BOM management',
    primitives: ['auth', 'data-crud', 'ui-presentation', 'analytics', 'inventory', 'scheduling', 'workflow', 'reporting', 'integration'],
    vocabulary: {
      'user': 'operator',
      'order': 'work order',
      'product': 'finished good',
    },
    requiredFeatures: ['production-tracking', 'quality-control', 'bom-management', 'operator-dashboard'],
    optionalFeatures: ['machine-monitoring', 'maintenance-scheduling', 'supplier-portal', 'compliance-audit'],
  },
  {
    id: 'fintech',
    name: 'Fintech',
    description: 'Financial services platform with transaction processing, account management, and compliance',
    primitives: ['auth', 'data-crud', 'ui-presentation', 'payment', 'analytics', 'crm', 'compliance', 'reporting'],
    vocabulary: {
      'user': 'account holder',
      'product': 'financial product',
      'order': 'transaction',
    },
    requiredFeatures: ['account-management', 'transaction-history', 'payment-processing', 'compliance-dashboard'],
    optionalFeatures: ['investment-portfolio', 'credit-scoring', 'insurance-quote', 'financial-advisor'],
  },
  {
    id: 'proptech',
    name: 'Property Technology',
    description: 'Property management platform with tenant management, maintenance tracking, and rent collection',
    primitives: ['auth', 'data-crud', 'ui-presentation', 'payment', 'crm', 'scheduling', 'notification', 'analytics'],
    vocabulary: {
      'user': 'tenant',
      'customer': 'property manager',
      'order': 'maintenance request',
    },
    requiredFeatures: ['tenant-portal', 'maintenance-tracking', 'rent-collection', 'property-dashboard'],
    optionalFeatures: ['lease-management', 'vendor-network', 'document-storage', 'accounting-integration'],
  },
];
