import type { PrimitiveCapability } from '../builder.js';

export const PRIMITIVES: PrimitiveCapability[] = [
  {
    id: 'auth',
    name: 'Authentication & Authorization',
    description: 'User login, registration, password reset, role-based access control, OAuth, session management',
    category: 'auth',
    industryAffinity: ['saas', 'healthcare', 'ecommerce', 'fintech', 'enterprise-software'],
  },
  {
    id: 'data-crud',
    name: 'CRUD Data Management',
    description: 'Create, read, update, delete operations for all business entities',
    category: 'data',
    industryAffinity: ['*'],
  },
  {
    id: 'ui-presentation',
    name: 'UI Presentation & Layout',
    description: 'Responsive layouts, navigation, theming, component library, page templates',
    category: 'ui',
    industryAffinity: ['*'],
  },
  {
    id: 'payment',
    name: 'Payment Processing',
    description: 'Stripe, Razorpay, UPI, COD, invoice generation, refund handling, transaction history',
    category: 'payment',
    industryAffinity: ['ecommerce', 'saas', 'fintech', 'hospitality', 'education'],
  },
  {
    id: 'notification',
    name: 'Email & Push Notifications',
    description: 'Transactional emails, order confirmations, appointment reminders, marketing campaigns',
    category: 'notification',
    industryAffinity: ['ecommerce', 'healthcare', 'fitness', 'education', 'saas'],
  },
  {
    id: 'integration',
    name: 'Third-Party Integrations',
    description: 'API connectors, webhooks, OAuth flows, data sync with external services',
    category: 'integration',
    industryAffinity: ['enterprise-software', 'saas', 'logistics', 'manufacturing'],
  },
  {
    id: 'compliance',
    name: 'Regulatory Compliance',
    description: 'GDPR consent, HIPAA safeguards, PCI DSS, data retention policies, audit logs',
    category: 'compliance',
    industryAffinity: ['healthcare', 'fintech', 'enterprise-software', 'ecommerce'],
  },
  {
    id: 'analytics',
    name: 'Analytics & Reporting',
    description: 'Dashboards, KPIs, charts, exports, scheduled reports, user behavior tracking',
    category: 'analytics',
    industryAffinity: ['saas', 'enterprise-software', 'fintech', 'ecommerce'],
  },
  {
    id: 'booking',
    name: 'Appointment Booking & Scheduling',
    description: 'Calendar integration, slot management, online booking, rescheduling, cancellations',
    category: 'data',
    industryAffinity: ['healthcare', 'fitness', 'beauty', 'legal', 'agency', 'travel'],
  },
  {
    id: 'commerce',
    name: 'Ecommerce & Shopping Cart',
    description: 'Product catalog, cart, checkout, tax calculation, shipping, inventory tracking',
    category: 'payment',
    industryAffinity: ['ecommerce', 'luxury', 'automotive'],
  },
  {
    id: 'content',
    name: 'Content Management',
    description: 'Blog, articles, rich text editing, media library, categories, tags, SEO metadata',
    category: 'data',
    industryAffinity: ['media', 'education', 'nonprofit', 'portfolio'],
  },
  {
    id: 'gallery',
    name: 'Media Gallery & Portfolio',
    description: 'Image grids, lightbox, video embedding, carousel, before/after comparison',
    category: 'ui',
    industryAffinity: ['luxury', 'portfolio', 'realestate', 'travel', 'beauty'],
  },
  {
    id: 'contact-form',
    name: 'Contact & Lead Capture',
    description: 'Contact forms, inquiry management, lead capture, CRM integration, auto-responder',
    category: 'data',
    industryAffinity: ['*'],
  },
  {
    id: 'search',
    name: 'Search & Filtering',
    description: 'Full-text search, faceted filters, autocomplete, advanced search, geolocation',
    category: 'data',
    industryAffinity: ['ecommerce', 'realestate', 'education', 'media'],
  },
  {
    id: 'map',
    name: 'Maps & Location',
    description: 'Interactive maps, geocoding, store locator, directions, service area display',
    category: 'ui',
    industryAffinity: ['travel', 'realestate', 'automotive', 'hospitality'],
  },
  {
    id: 'scheduling',
    name: 'Staff & Resource Scheduling',
    description: 'Shift planning, resource allocation, availability management, roster view',
    category: 'data',
    industryAffinity: ['healthcare', 'fitness', 'manufacturing', 'logistics'],
  },
  {
    id: 'inventory',
    name: 'Inventory & Stock Management',
    description: 'SKU tracking, stock levels, reorder points, warehouse management, barcode scanning',
    category: 'data',
    industryAffinity: ['ecommerce', 'manufacturing', 'logistics', 'automotive'],
  },
  {
    id: 'crm',
    name: 'Customer Relationship Management',
    description: 'Contact management, lead pipeline, deal tracking, communication history, tasks',
    category: 'data',
    industryAffinity: ['saas', 'agency', 'realestate', 'legal', 'enterprise-software'],
  },
  {
    id: 'hr',
    name: 'HR & People Management',
    description: 'Employee records, payroll, leave management, performance reviews, onboarding',
    category: 'data',
    industryAffinity: ['enterprise-software', 'manufacturing', 'logistics'],
  },
  {
    id: 'workflow',
    name: 'Workflow & Process Automation',
    description: 'Approval chains, task automation, state machines, document routing, business rules',
    category: 'integration',
    industryAffinity: ['enterprise-software', 'manufacturing', 'logistics'],
  },
  {
    id: 'reporting',
    name: 'Advanced Reporting & Compliance',
    description: 'Custom report builder, audit trails, compliance reports, data export, scheduled PDFs',
    category: 'analytics',
    industryAffinity: ['enterprise-software', 'fintech', 'manufacturing', 'healthcare'],
  },
  {
    id: 'subscriptions',
    name: 'Subscription & Billing Management',
    description: 'Recurring billing, plan management, tier upgrades, proration, dunning, invoices',
    category: 'payment',
    industryAffinity: ['saas', 'fitness', 'education', 'media'],
  },
  {
    id: 'ecommerce-supplement',
    name: 'Supplement Marketplace Features',
    description: 'Brand filtering, ingredient lists, FSSAI certification badges, health tags, multi-vendor cart, dosage guides',
    category: 'data',
    industryAffinity: ['ecommerce-supplement'],
  },
  {
    id: 'indian-payments',
    name: 'Indian Payment Gateway',
    description: 'UPI, Paytm, COD, Razorpay, NetBanking, Indian tax (GST) handling, invoice formats',
    category: 'payment',
    industryAffinity: ['ecommerce', 'ecommerce-supplement'],
  },
  {
    id: 'fssai-compliance',
    name: 'FSSAI Compliance',
    description: 'FSSAI license display, product certification badges, ingredient disclosure, health disclaimer',
    category: 'compliance',
    industryAffinity: ['ecommerce-supplement', 'ecommerce'],
  },
  {
    id: 'multi-vendor',
    name: 'Multi-Vendor / Marketplace',
    description: 'Vendor onboarding, brand isolation, seller dashboards, commission tracking, vendor payouts',
    category: 'data',
    industryAffinity: ['ecommerce', 'ecommerce-supplement'],
  },
  {
    id: 'customer-reviews',
    name: 'Customer Reviews & Ratings',
    description: 'Star ratings, review submission, photo reviews, verified purchase badges, moderation',
    category: 'ui',
    industryAffinity: ['ecommerce', 'ecommerce-supplement', 'automotive'],
  },
];
