// ─── Retry Engine ───────────────────────────────────────────────────────────
//
// Parses failures, generates fix suggestions, applies patches,
// and orchestrates retry loops with exponential backoff.
// ─────────────────────────────────────────────────────────────────────────────

import fs from 'node:fs';
import path from 'node:path';
import type {
  FailureInfo,
  FailureCategory,
  RuntimeRetryContext,
  FixSuggestion,
  FilePatch,
  ProcessSpec,
  ProcessResult,
} from './types.js';
import type { LogCapture } from './log-capture.js';
import { ProcessManager } from './process-manager.js';

// ─── Fix Generators ─────────────────────────────────────────────────────────

type FixGenerator = (failure: FailureInfo, projectRoot: string) => FixSuggestion | undefined;

const FIX_GENERATORS: Record<FailureCategory, FixGenerator> = {
  typescript: (failure, root) => {
    const msg = failure.message;
    if (msg.includes('Cannot find module')) {
      const moduleMatch = msg.match(/Cannot find module '(.+?)'/);
      if (moduleMatch) {
        return {
          description: `Install missing module: ${moduleMatch[1]}`,
          filePatches: [],
          autoGenerated: true,
          confidence: 0.9,
        };
      }
    }
    if (msg.includes('Cannot find name')) {
      const nameMatch = msg.match(/Cannot find name '(.+?)'/);
      if (nameMatch) {
        return {
          description: `Add missing import or declaration for '${nameMatch[1]}'`,
          filePatches: [],
          autoGenerated: true,
          confidence: 0.6,
        };
      }
    }
    return undefined;
  },

  eslint: (failure) => {
    const msg = failure.message;
    if (msg.includes('no-unused-vars')) {
      const varMatch = msg.match(/'(.+?)'/);
      if (varMatch && failure.files[0]) {
        return {
          description: `Remove unused variable '${varMatch[1]}'`,
          filePatches: [],
          autoGenerated: true,
          confidence: 0.7,
        };
      }
    }
    return undefined;
  },

  build: (failure) => {
    return {
      description: `Build failed: ${failure.message.slice(0, 100)}`,
      filePatches: [],
      autoGenerated: false,
      confidence: 0.3,
    };
  },

  dependency: (failure, root) => {
    const moduleMatch = failure.message.match(/Missing module: (.+)/);
    if (moduleMatch?.[1]) {
      const modName = moduleMatch[1].trim();
      return {
        description: `Install missing module: ${modName}`,
        filePatches: [],
        autoGenerated: true,
        confidence: 0.95,
      };
    }
    return undefined;
  },

  'port-conflict': () => {
    return {
      description: 'Port conflict detected — will use different port on retry',
      filePatches: [],
      autoGenerated: true,
      confidence: 1.0,
    };
  },

  memory: () => {
    return {
      description: 'Out of memory — increase Node.js heap size',
      filePatches: [],
      autoGenerated: true,
      confidence: 0.9,
    };
  },

  timeout: () => {
    return {
      description: 'Process timed out — may need longer timeout or optimization',
      filePatches: [],
      autoGenerated: false,
      confidence: 0.4,
    };
  },

  test: (failure) => {
    return {
      description: `Test failure: ${failure.message.slice(0, 100)}`,
      filePatches: [],
      autoGenerated: false,
      confidence: 0.3,
    };
  },

  runtime: () => {
    return {
      description: 'Runtime error detected',
      filePatches: [],
      autoGenerated: false,
      confidence: 0.2,
    };
  },

  unknown: () => {
    return {
      description: 'Unclassified error',
      filePatches: [],
      autoGenerated: false,
      confidence: 0.1,
    };
  },
};

// ─── Retry Engine ───────────────────────────────────────────────────────────

export interface RetryConfig {
  /** Max retry attempts */
  maxAttempts: number;
  /** Base delay between retries (ms) */
  baseDelayMs: number;
  /** Maximum delay between retries (ms) */
  maxDelayMs: number;
  /** Whether to apply auto-fixes */
  autoFix: boolean;
  /** Categories to retry */
  retryableCategories: FailureCategory[];
}

const DEFAULT_RETRY_CONFIG: RetryConfig = {
  maxAttempts: 3,
  baseDelayMs: 2000,
  maxDelayMs: 30000,
  autoFix: true,
  retryableCategories: ['typescript', 'eslint', 'build', 'dependency', 'port-conflict', 'memory', 'timeout'],
};

export class RetryEngine {
  private config: RetryConfig;
  private processManager: ProcessManager;
  private logCapture: LogCapture;
  private retryHistory: RuntimeRetryContext[] = [];

  constructor(
    processManager: ProcessManager,
    logCapture: LogCapture,
    config?: Partial<RetryConfig>,
  ) {
    this.config = { ...DEFAULT_RETRY_CONFIG, ...config };
    this.processManager = processManager;
    this.logCapture = logCapture;
  }

  /** Get retry history */
  getHistory(): RuntimeRetryContext[] {
    return [...this.retryHistory];
  }

  /** Reset history */
  reset(): void {
    this.retryHistory = [];
  }

  /**
   * Generate fix suggestion for a failure.
   */
  suggestFix(failure: FailureInfo, projectRoot: string): FixSuggestion | undefined {
    const generator = FIX_GENERATORS[failure.category];
    if (!generator) return undefined;
    return generator(failure, projectRoot);
  }

  /**
   * Apply file patches to the project.
   */
  applyPatches(patches: FilePatch[]): { applied: number; failed: number } {
    let applied = 0;
    let failed = 0;

    for (const patch of patches) {
      try {
        if (!fs.existsSync(patch.filePath)) {
          failed++;
          continue;
        }
        const current = fs.readFileSync(patch.filePath, 'utf-8');
        if (!current.includes(patch.oldContent)) {
          failed++;
          continue;
        }
        const updated = current.replace(patch.oldContent, patch.newContent);
        fs.writeFileSync(patch.filePath, updated, 'utf-8');
        applied++;
      } catch {
        failed++;
      }
    }

    return { applied, failed };
  }

  /**
   * Apply automatic fixes for a failure.
   */
  applyAutoFix(failure: FailureInfo, projectRoot: string): FixSuggestion | null {
    if (!this.config.autoFix) return null;

    const fix = this.suggestFix(failure, projectRoot);
    if (!fix || !fix.autoGenerated || fix.confidence < 0.7) return null;

    // Apply file patches if any
    if (fix.filePatches.length > 0) {
      const result = this.applyPatches(fix.filePatches);
      if (result.failed > 0) return null;
    }

    // For dependency issues, run install
    if (failure.category === 'dependency') {
      const moduleMatch = failure.message.match(/Missing module: (.+)/);
      if (moduleMatch?.[1]) {
        const modName = moduleMatch[1].trim();
        const pkgJsonPath = path.join(projectRoot, 'package.json');
        if (fs.existsSync(pkgJsonPath)) {
          try {
            const pkg = JSON.parse(fs.readFileSync(pkgJsonPath, 'utf-8'));
            pkg.dependencies = pkg.dependencies || {};
            pkg.devDependencies = pkg.devDependencies || {};
            pkg.dependencies[modName] = 'latest';
            fs.writeFileSync(pkgJsonPath, JSON.stringify(pkg, null, 2));
          } catch { /* noop */ }
        }
      }
    }

    return fix;
  }

  /**
   * Calculate retry delay with exponential backoff + jitter.
   */
  getRetryDelay(attempt: number): number {
    const delay = Math.min(
      this.config.baseDelayMs * Math.pow(2, attempt),
      this.config.maxDelayMs,
    );
    // Add jitter: ±25%
    const jitter = delay * 0.25 * (Math.random() * 2 - 1);
    return Math.round(delay + jitter);
  }

  /**
   * Check if a failure should be retried.
   */
  shouldRetry(failure: FailureInfo, attempt: number): boolean {
    if (attempt >= this.config.maxAttempts) return false;
    if (!failure.retryable) return false;
    return this.config.retryableCategories.includes(failure.category);
  }

  /**
   * Execute a command with automatic retry on failure.
   */
  async executeWithRetry(
    spec: ProcessSpec,
    projectRoot: string,
  ): Promise<{
    result: ProcessResult;
    retries: RuntimeRetryContext[];
    appliedFixes: FixSuggestion[];
  }> {
    let attempt = 0;
    const retries: RuntimeRetryContext[] = [];
    const appliedFixes: FixSuggestion[] = [];
    let lastResult: ProcessResult | undefined;

    while (attempt <= this.config.maxAttempts) {
      this.logCapture.reset();
      const result = await this.processManager.run(spec);
      lastResult = result;

      if (result.status === 'success') {
        return { result, retries, appliedFixes };
      }

      // Process logs and detect failures
      this.logCapture.processResult(result, spec.label ?? 'command');
      const failures = this.logCapture.getFailures();
      const primaryFailure = failures[0];

      if (!primaryFailure || !this.shouldRetry(primaryFailure, attempt)) {
        return { result, retries, appliedFixes };
      }

      // Record retry context
      const retryCtx: RuntimeRetryContext = {
        originalSpec: spec,
        failure: primaryFailure,
        attempt: attempt + 1,
        maxAttempts: this.config.maxAttempts,
        previousFixes: appliedFixes.map((f) => f.description),
      };
      retries.push(retryCtx);

      // Try to apply auto-fix
      const fix = this.applyAutoFix(primaryFailure, projectRoot);
      if (fix) {
        appliedFixes.push(fix);
      }

      // Wait before retry
      const delay = this.getRetryDelay(attempt);
      await new Promise((resolve) => setTimeout(resolve, delay));

      attempt++;
    }

    return {
      result: lastResult!,
      retries,
      appliedFixes,
    };
  }
}

export function createRetryEngine(
  processManager: ProcessManager,
  logCapture: LogCapture,
  config?: Partial<RetryConfig>,
): RetryEngine {
  return new RetryEngine(processManager, logCapture, config);
}
