// ─── Runtime Layer Types ────────────────────────────────────────────────────
//
// Types for the execution runtime: process management, log capture,
// failure detection, retry, preview, and visual regression.
// ─────────────────────────────────────────────────────────────────────────────

// ─── Process Management ─────────────────────────────────────────────────────

export interface ProcessSpec {
  /** Working directory */
  cwd: string;
  /** Command to run (e.g., 'npm', 'npx', 'node') */
  command: string;
  /** Arguments */
  args: string[];
  /** Environment variables (merged with process.env) */
  env?: Record<string, string> | undefined;
  /** Timeout in ms (0 = no timeout) */
  timeoutMs?: number | undefined;
  /** Max buffer size for stdout/stderr in bytes */
  maxBuffer?: number | undefined;
  /** Label for logging */
  label?: string | undefined;
}

export type ProcessStatus = 'pending' | 'running' | 'success' | 'failure' | 'timeout' | 'killed';

export interface ProcessResult {
  /** Exit code (null if killed) */
  exitCode: number | null;
  /** Process status */
  status: ProcessStatus;
  /** Captured stdout */
  stdout: string;
  /** Captured stderr */
  stderr: string;
  /** Combined output */
  combined: string;
  /** Duration in ms */
  durationMs: number;
  /** Whether process was killed due to timeout */
  timedOut: boolean;
  /** PID of the process */
  pid: number | undefined;
}

export interface DevServerHandle {
  /** Process PID */
  pid: number;
  /** Port the server is listening on */
  port: number;
  /** URL to access the server */
  url: string;
  /** Kill the server process */
  kill: () => Promise<void>;
  /** Check if server is still running */
  isRunning: () => boolean;
  /** Wait for server to be ready */
  ready: Promise<void>;
}

// ─── Log Capture ────────────────────────────────────────────────────────────

export type LogLevel = 'info' | 'warn' | 'error' | 'debug';

export interface LogEntry {
  /** Timestamp */
  timestamp: number;
  /** Log level */
  level: LogLevel;
  /** Log message */
  message: string;
  /** Source (e.g., 'stdout', 'stderr', 'build', 'test') */
  source: string;
  /** Raw line before parsing */
  raw: string;
}

export type FailureCategory =
  | 'typescript'        // TS compilation errors
  | 'eslint'            // Lint errors
  | 'build'             // Build failures
  | 'runtime'           // Runtime errors
  | 'test'              // Test failures
  | 'dependency'        // Missing/broken dependencies
  | 'port-conflict'     // Port already in use
  | 'memory'            // Out of memory
  | 'timeout'           // Process timeout
  | 'unknown';          // Unclassified

export interface FailureInfo {
  /** Unique failure ID */
  id: string;
  /** Category of failure */
  category: FailureCategory;
  /** Human-readable error message */
  message: string;
  /** File path(s) involved */
  files: string[];
  /** Line number(s) */
  lines: number[];
  /** Raw error output */
  rawOutput: string;
  /** Parsed error details */
  details: Record<string, unknown>;
  /** Suggested fix */
  suggestedFix: string | undefined;
  /** Whether this failure is retryable */
  retryable: boolean;
  /** Timestamp */
  timestamp: number;
}

// ─── Retry Engine ───────────────────────────────────────────────────────────

export interface RuntimeRetryContext {
  /** The original spec that failed */
  originalSpec: ProcessSpec;
  /** The failure that occurred */
  failure: FailureInfo;
  /** Number of attempts so far */
  attempt: number;
  /** Max attempts allowed */
  maxAttempts: number;
  /** Previous fix attempts */
  previousFixes: string[];
}

export interface FixSuggestion {
  /** Description of the fix */
  description: string;
  /** Files to modify */
  filePatches: FilePatch[];
  /** Whether this fix was auto-generated */
  autoGenerated: boolean;
  /** Confidence score 0-1 */
  confidence: number;
}

export interface FilePatch {
  /** File path */
  filePath: string;
  /** Old content to replace */
  oldContent: string;
  /** New content */
  newContent: string;
}

// ─── Preview Server ─────────────────────────────────────────────────────────

export interface PreviewConfig {
  /** Directory to serve */
  directory: string;
  /** Port (0 = auto-assign) */
  port?: number | undefined;
  /** Host to bind to */
  host?: string | undefined;
  /** Whether to use HTTPS */
  https?: boolean | undefined;
  /** Base path */
  basePath?: string | undefined;
}

export interface PreviewResult {
  /** URL where the app is accessible */
  url: string;
  /** Port in use */
  port: number;
  /** Whether server is ready */
  ready: boolean;
  /** Kill function */
  kill: () => Promise<void>;
}

// ─── Visual Regression ──────────────────────────────────────────────────────

export interface ScreenshotOptions {
  /** Viewport width */
  width?: number | undefined;
  /** Viewport height */
  height?: number | undefined;
  /** Full page screenshot */
  fullPage?: boolean | undefined;
  /** Wait for network idle */
  waitForNetworkIdle?: boolean | undefined;
  /** Custom wait time after load (ms) */
  waitAfterLoad?: number | undefined;
  /** Selectors to wait for */
  waitForSelectors?: string[] | undefined;
  /** Mask selectors (hide dynamic content) */
  maskSelectors?: string[] | undefined;
}

export interface ScreenshotResult {
  /** Screenshot file path */
  filePath: string;
  /** Viewport size */
  viewport: { width: number; height: number };
  /** Page title */
  title: string;
  /** Page URL */
  url: string;
  /** Console errors captured during render */
  consoleErrors: string[];
  /** Performance metrics */
  metrics: PageMetrics;
}

export interface PageMetrics {
  /** DOM content loaded (ms) */
  domContentLoaded: number;
  /** Load event (ms) */
  load: number;
  /** First contentful paint (ms) */
  fcp: number | undefined;
  /** Largest contentful paint (ms) */
  lcp: number | undefined;
  /** Total DOM nodes */
  domNodes: number;
  /** JS heap size (bytes) */
  jsHeapSize: number;
}

export interface VisualDiffResult {
  /** Whether images match within threshold */
  match: boolean;
  /** Mismatch percentage (0-100) */
  mismatchPercentage: number;
  /** Diff image file path */
  diffImagePath: string;
  /** Baseline image path */
  baselinePath: string;
  /** Current image path */
  currentPath: string;
  /** Diff pixel count */
  diffPixels: number;
  /** Total pixel count */
  totalPixels: number;
}

// ─── Runtime Engine Config ──────────────────────────────────────────────────

export interface RuntimeConfig {
  /** Project root directory */
  projectRoot: string;
  /** Package manager */
  packageManager?: 'npm' | 'yarn' | 'pnpm' | undefined;
  /** Dev server port */
  devPort?: number | undefined;
  /** Preview server port */
  previewPort?: number | undefined;
  /** Build command override */
  buildCommand?: string | undefined;
  /** Test command override */
  testCommand?: string | undefined;
  /** Install command override */
  installCommand?: string | undefined;
  /** Max retry attempts */
  maxRetries?: number | undefined;
  /** Screenshot viewport */
  screenshotViewport?: { width: number; height: number } | undefined;
  /** Visual diff threshold (0-1) */
  diffThreshold?: number | undefined;
  /** Timeout for operations (ms) */
  timeoutMs?: number | undefined;
  /** Whether to capture screenshots */
  captureScreenshots?: boolean | undefined;
  /** Whether to run visual regression */
  visualRegression?: boolean | undefined;
}

// ─── Cloudflared Tunnel ────────────────────────────────────────────────

export interface TunnelInfo {
  /** Public tunnel URL */
  url: string;
  /** Kill the tunnel process */
  kill: () => Promise<void>;
}

export interface RuntimeRunResult {
  /** Whether the entire run succeeded */
  success: boolean;
  /** Install result */
  install: ProcessResult | undefined;
  /** Build result */
  build: ProcessResult | undefined;
  /** Test result */
  test: ProcessResult | undefined;
  /** All captured logs */
  logs: LogEntry[];
  /** All detected failures */
  failures: FailureInfo[];
  /** Retry history */
  retries: RuntimeRetryContext[];
  /** Preview URL if available */
  previewUrl: string | undefined;
  /** Tunnel URL if cloudflared is available */
  tunnelUrl: string | undefined;
  /** Screenshots captured */
  screenshots: ScreenshotResult[];
  /** Visual diff results */
  visualDiffs: VisualDiffResult[];
  /** Total duration */
  durationMs: number;
}
